### ISSUE TITLE
add methods in documentation

### ISSUE THREAD

**Issue by Pofigizm** [mistic100/jQuery-QueryBuilder#100]
Hi, @mistic100!
It is good plugin for me. Thank you!

I think on [main page](http://mistic100.github.io/jQuery-QueryBuilder/) you need add descriptions of next  methods:

    $('#builder').queryBuilder('getSQL')
    $('#builder').queryBuilder('getMongo')

**Comment by mistic100** [comment]
http://mistic100.github.io/jQuery-QueryBuilder/plugins.html#sql-support
:-)

**Comment by Pofigizm** [comment]
Sorry, it is not clearly for me to find this methods on plugins page.
I found them in source code of demo page. ))
I think you can add comment about other methods to main page.

**Comment by mistic100** [comment]
I won't, the main page is long enough (and will be even more for 2.0.0)
