### ISSUE TITLE
Starting with no conditions

### ISSUE THREAD

**Issue by rhythmicdevil** [mistic100/jQuery-QueryBuilder#101]
I would like to be able to start the query builder, in some cases, with no conditions. I have tried not calling setRules at all, but the query builder always starts with one empty condition. I have tried calling setRules with an empty array, and an empty object but both of those cause an "incorrect data object passed" error. Is there a way to have the query builder start with no conditions?

Thanks
Steve

**Comment by rhythmicdevil** [comment]
This is the workaround I am currently using:

	              $(document).ready(function() {
	            	  var selectionFilters = ${selectionFilters};
	            	  var rules = ${currentRules};
	            	  
	            	  $('#queryBuilder').queryBuilder({
	            		  plugins: ['sortable', 'bt-tooltip-errors'],
	            		  filters: selectionFilters,
	            		  allow_empty: true
	            	  });

	            	  if(rules !== null){
	            	  	$('#queryBuilder').queryBuilder('setRules', rules);
	            	  } else {
						// Hack to clear the single empty condition if no rules are defined for this template
		            	$('#queryBuilder_rule_0 button').click()
		              }
	              });

**Comment by mistic100** [comment]
try

```js
$('#builder').queryBuilder({
  allow_empty: true,
  rules: {
    condition: 'AND',
    rules:[]
  }
})
```

**Comment by rhythmicdevil** [comment]
Perfect, thank you.
