### ISSUE TITLE
Big flaw in events systems

### ISSUE THREAD

**Issue by mistic100** [mistic100/jQuery-QueryBuilder#103]
With current system, no events can be called during initialization, that include full builder construction with `rules` parameter.

I need to either find a way to bind events before initialization and totally drop MicroEvents and use jQuery instead.

**Comment by abhijeetkdm** [comment]
hi,

Is this working now ? 
I don't see any event triggered at initialization. I need to access 'data' element from rule's filter at the time each rule creation at initialization. I tried to access it through events like 'afterUpdateRuleFilter', 
'afterCreateRuleFilters' at the time of initialization but it was not triggered.

Can you please suggest a best way to do it ?

**Comment by mistic100** [comment]
give some code please !

**Comment by abhijeetkdm** [comment]
$( document ).ready(function() {
    var builder_block =  $('#builder-basic');
 
   function applyRulePlugins(rule){
        applySelectPluginOnValue(rule);
        if (rule.filter && 'data' in rule.filter && rule.filter.data.selectable == 'true'){
            activateSelectableInputForRule(rule);
        }
    }
    builder_block.on('afterUpdateRuleFilter.queryBuilder', function(e, rule, error, value) {
           applyRulePlugins(rule);
    });

    builder_block.on('afterCreateRuleFilters.queryBuilder', function(e, rule, error, value) {
           applyRulePlugins(rule);
    });

});

'applySelectPluginOnValue' and 'activateSelectableInputForRule' methods basically applies some plugins on rule after update/creation (uses some attributes passed in data). This methods works any rule update/ rule creation after initialization but they are not called at the time of initialization (page reload).

**Comment by mistic100** [comment]
you can't apply anything to the value in the `*Filter*` events, because the input is not initialized yet
the cinematic is init/update filter select -> init/update operator select -> init value inputs

please open a a new issue with complete details and test case
you can start from https://jsfiddle.net/oaay73sw/ initiated with necessary dependencies
