### ISSUE TITLE
Drag and Drop Not Working in Version #2

### ISSUE THREAD

**Issue by jlegacy** [mistic100/jQuery-QueryBuilder#105]
Getting the following error when using drag and drop.  "Cannot read property '$el' of null"   Also happens in the demo.

**Comment by mistic100** [comment]
I don't have this error.
Which browser ?

**Comment by jlegacy** [comment]
Appreciate your response....Chrome is the browser I am using.

Thanks,
Joseph Legacy

**Comment by jlegacy** [comment]
Here is the block that is failing.  

  // Chrome glitch (helper invisible if hidden immediately)
                setTimeout(function () {
                    src.$el.hide();
                }, 0);

Thanks,
joseph

**Comment by jlegacy** [comment]
Line 3024

**Comment by mistic100** [comment]
seems that "dragend" is called immediately on Chrome, then setting src to null
and it's a known bug http://stackoverflow.com/questions/19639969/html5-dragend-event-firing-immediately

**Comment by mistic100** [comment]
Can you get the source from master branch, run `grunt` to build the dist files and tell me if it works for you ?

**Comment by jlegacy** [comment]
Working!

Thanks,
Joseph
