### ISSUE TITLE
Custom call to addRule method in version 2.0.0

### ISSUE THREAD

**Issue by smailliwnosaj** [mistic100/jQuery-QueryBuilder#106]
In version 1.4, I had been using the following line to inject custom rules to the queryBuilder().

    $("#xr-filter").queryBuilder("addRule", $(".rules-group-container"));

However, in version 2, that line was giving me an error.  I am able to get around the error by using the following in it's place:

    ("#xr-filter").queryBuilder("addRule", $("#xr-filter").data("queryBuilder").model.root);

I may not have been doing it right the first time.  I may not be doing it right, now, either.

Thanks,

I appreciate your time.

**Comment by mistic100** [comment]
This seems right to me. Good job in understanding how the internals now work :-)

I may suggest you cache the QueryBuilder instance (remember that $ element lookup is time consuming)

```js
var $builder = $("#xr-filter");
var builderModel = $builder.data('queryBuilder').model;
$builder.queryBuilder("addRule", builderModel.root);
```
