### ISSUE TITLE
Null option being added to Multi-Select when array is empty

### ISSUE THREAD

**Issue by smailliwnosaj** [mistic100/jQuery-QueryBuilder#107]
Thanks for this awesome tool.  I've been working with it for a little over 30 days and I love it.  

I've recently updated to version 2.0.  I have a very complex project and am using nearly all of your features.  I have been able to get away with not making any changes to your framework.  However, there is one thing I would like to change.  Depending on User settings in my application, my multi-select elements will often have no option items.  I show a message in the UI when this occurs.  However, the jQuery-QueryBuilder framework is adding a "null" option to the multi-select.  This "null" option causes some issues in my application.

In getRuleInput, I'd like to check if the value array is empty before adding option items to the multi-select box.  Here is the change I've made in my local copy of your framework:

    case 'select':
        h += '<select class="form-control" name="' + name + '"' + (filter.multiple ? ' multiple' : '') + '>';
        iterateOptions(filter.values, function (key, val) {
        if ( ! (key == null && val == null) ) {    // Added by JWilliams - 4/2015
            h += '<option value="' + key + '"> ' + val + '</option> ';
        }                                          // Added by JWilliams - 4/2015
    });
    h += '</select>';
    break;

I respect your product decisions and whether or not you want to include this change.

Thanks again,

Jason Williams

**Comment by mistic100** [comment]
if your dropdown have no element, `filter.values` should be a empty array (unlike checkboxes and radios, this is allowed by the framework)

I just tested with the example file at it works as expected
```js
  {
    id: 'category',
    type: 'integer',
    input: 'select',
    multiple: true, // or not
    values: []
  }
```

**Comment by smailliwnosaj** [comment]
Ah, crap.  My bad.  So sorry for wasting your time.  But, my array was looking like this: [null, null, null, null, null].  I had forgotten to 0 out the array length.  I stand corrected.

Thanks again,
