### ISSUE TITLE
Need possibility to load multiple language files

### ISSUE THREAD

**Issue by smehrbrodt** [mistic100/jQuery-QueryBuilder#112]
We have a multilingual app (with Angular) and so I need to load multiple languages at startup and switch on demand.

Including a language file should not override the default translation, but just register the strings and you should be able to switch the language after loading a translation.

**Comment by mistic100** [comment]
> Including a language file should not override the default translation

That's your point of view, any localised jQuery plugin I know (like datepickers) work exactly like this.

BTW the builder itself does not support dynamic change of the language, you will need to destroy it and init again.

The source language files are available in "src/i18n" you can use them for your specific usage (perhaps a wrapper  which use `getRules`, `destroy`, init again and `setRules` when you want to change language).

**Comment by mistic100** [comment]
> any localised jQuery plugin I know (like datepickers) work exactly like this.

that is totally false :-)

the problem of UI refreshing is still present though

**Comment by smehrbrodt** [comment]
> the problem of UI refreshing is still present though
Well I have no problem without a live translation update.
However, currently I cannot include more than one translation file at all in my app.

**Comment by mistic100** [comment]
It's a problem in a whole for me, if there is no live update there is no need to load multiple languages. And people who want this feature can directly use the source files like I said.

I'll update the language file load only if I find an elegant solution for live update.

**Comment by mistic100** [comment]
So I changed my mind: no live update.
 * Each language file will append content to $.fn.queryBuilder.regional
 * The right translated strings are loaded depending on `lang_code` option
 * `lang` option still exists to overload translation

The example file has been updated with a language picker

**Comment by smehrbrodt** [comment]
Thanks! Will test it soon!

**Comment by smehrbrodt** [comment]
Works great, thanks a lot!
