### ISSUE TITLE
event for value change

### ISSUE THREAD

**Issue by mszoernyi** [mistic100/jQuery-QueryBuilder#113]
Currently no event is triggered while or after a user changed a rule value. What's the best practice to add this? One way would be to register listeners on all inputs myself but not sure if this is the best approach here.

**Comment by mistic100** [comment]
There is none because there is no universal way to do it, especially when using plugins on rules input.

`valueSetter` and `valueParser` handle usage of plugins but there is no mechanism for a change event.

Do you have an idea for that ?

**Comment by mistic100** [comment]
goal : **implement two-way data binding for rule values**

DOM -> Model :
 * standard inputs are managed via standard events by QueryBuilder
 * customized inputs will use a public method to manually notify of a value change (internal use of `valueParser`, perhaps rename/alis in `valueGetter`)

Model -> DOM :
  * simply use `setValue` method already fully implemented (internal use of `valueSetter`)

In both case, trigger a `valueChanged.queryBuilder` event

**Comment by mszoernyi** [comment]
This sound good. Will try to read through the code and see how it works.

**Comment by mszoernyi** [comment]
+ Binding for group operator change

Changing the group condition (AND / OR) there is no event triggered. It might make sense to trigger and as well?!?

**Comment by mszoernyi** [comment]
Had to finish some tasks yesterday first. Gonna try to work on this later this day. Just wanna make sure, your idea is to handle all of this inside jquery-builder and trigger an event to communicate with the outside world right?

Did you start already on this topic?

**Comment by mistic100** [comment]
Yeah I started, and it's a pain in the a**
Mainly because `setRuleValue` trigger the DOM `change` to allow plugins to update themself, and then it leads to an infinite loop inside QueryBuilder.

But I'll make it ;-)

**Comment by mszoernyi** [comment]
Thanks! Do you have a donation link? We would like to donate because you saved us building it ourself :)

**Comment by mistic100** [comment]
I don't.
If you really insist you can contact me on my website and I'll give you my Paypal account.

**Comment by mistic100** [comment]
Added: `afterUpdateRuleValue.queryBuilder` event
Added: `filter.valueGetter` method
Added: `rule.value` property (binded to DOM)
Deprecated: `filter.valueParser` method
Removed: `beforeSetRuleValue.queryBuilder` and `afterSetRuleValue.queryBuilder` events

(group condition in a next commit)

**Comment by mszoernyi** [comment]
Thanks Damien! Added `afterUpdateRuleValue` + `afterUpdateGroupCondition` and works like a charm for default inputs. Gonna try selectize next which we might use as well.

When do you plan to release 2.1?

**Comment by mistic100** [comment]
I forgot to explain that you must trigger the `change` DOM event on the input if the value is changed programatically.
I know that selectize does not do it from scratch (the last time I tried), so you must hook `onChange` internal event to trigger the DOM event

**Comment by rsangiovanni** [comment]
I'm trying to update the field value programmatically, but the value of the `rule` is not updated.
is this possible?

**Comment by mistic100** [comment]
Well.... my anwser is just above, trigger the "change" event on the input

**Comment by rsangiovanni** [comment]
I did it 
` $(element).trigger('change');`
querybuilder intercept the event, but the value of rule filter is empty :(

**Comment by mistic100** [comment]
Open a new issue and provide a live example.

**Comment by rsangiovanni** [comment]
the problem is here 
```
QueryBuilder.prototype.getRuleValue = function(rule) {
...
value.push($value.find('[name=' + name + ']').val());
...
}
```
my widget has a different structure, so the value is always empty.
I need to figure out how to address this

**Comment by mistic100** [comment]
Then use "valueGetter" filter property, exactly for this kind of usage

**Comment by rsangiovanni** [comment]
👍

**Comment by eduardpaul** [comment]
Hi all, ¿is it possible to change value of filter in afterUpdateRuleValue? I'm trying to set value in the rule but it wont work.

`$(qb_OriginSelector).on('afterUpdateRuleValue.queryBuilder', function(e, rule, error, value){rule.value = rule.value.toLocaleUpperCase();});`

Any help is appreciated.

**Comment by mistic100** [comment]
Thus issue is closed, open another
