### ISSUE TITLE
SELECT & GROUP BYclause

### ISSUE THREAD

**Issue by AMilkov** [mistic100/jQuery-QueryBuilder#114]
Awesome job @mistic100 !

Do you have plans to add visual construction of `SELECT` or `GROUP BY` clauses of the query?

I imagine that the underling database schema is received via ajax call or provided as fixed JSON object.

**Comment by mistic100** [comment]
No I don't.
Plugins like http://johnny.github.io/jquery-sortable/#connected already exist

**Comment by KrishnaPG** [comment]
I was also interested in the GroupBy functionality and came across this issue. 

I am sorry - but do not understand your reference to the jquery-sortable. How to achieve groupby query clause with it? Are you suggesting some kind of mix & match of that plugin with this or something else you have in mind? Any pointers would be of great help.

**Comment by mistic100** [comment]
Use it to ask to user to select which fields to group by on (drag-and-drop between two boxes, available and activated fields), independently from QueryBuilder.

It's just a proposition.
It won't be in QueryBuilder.
