### ISSUE TITLE
Q: What is the best approach to modifying the rule layout?

### ISSUE THREAD

**Issue by bcajes** [mistic100/jQuery-QueryBuilder#115]
I would like to work on modifying the rule layout to function similarly to http://hirokiosame.github.io/VisualQuery/ .  At first glance, it looks like I will need to override the getRuleTemplate and replace it with something like Selectize that will hook into the Rule attributes.  Is this the right approach?  Any advice is appreciated.

**Comment by mistic100** [comment]
that's some impressive layout  !
yeah you will have to modify the template methods.

perhaps you can achieve the same behavior only overriding the templates and using the events system, without changing anything else, but I'll be difficult I guess

**Comment by timgws** [comment]
@bcajes off topic, but have you seen http://documentcloud.github.io/visualsearch/ ?

**Comment by Ruud-cb** [comment]
@bcajaes did you manage to get something done? Would love to see it :)

**Comment by bcajes** [comment]
@Ruud-cb yes, kind of, but it is a pretty hacked job, and too embarrassing to share ;) Also I did this a while ago, and I'm sure much has changed.  Basically, I did what was suggested above, and integrated the relevant code from visualsearch/visualquery into the templates.  I couldn't do it cleanly at the time, but maybe things are more modular at this point.
