### ISSUE TITLE
SQL SUM & GROUP BY clause

### ISSUE THREAD

**Issue by jeffrysteven** [mistic100/jQuery-QueryBuilder#117]
Hi, great job with QueryBuilder, many thanks for this tool.

is possible to do a SUM or GROUP BY in QueryBuilder?

**Comment by mistic100** [comment]
I would really appreciate you look at other issues before posting.
#114

**Comment by yaswant1122** [comment]
@mistic100  Any example or doc how i can use this SQL SUM & GROUP BY clause ... This exactly I need ... Thanks

**Comment by mistic100** [comment]
I guess you didn't read what is above. That doesn't exist

**Comment by yaswant1122** [comment]
ohh yes .. I realise later thanks for the response ...
