### ISSUE TITLE
Is there a Way to Restrict the sub-levels of the query builder?

### ISSUE THREAD

**Issue by Hilgo** [mistic100/jQuery-QueryBuilder#121]
I searched but haven't found a way to restrict sub-levels of the query builder (new group inside a group), For example, i would like to restrict to 3 or 4 levels. Is there a parameter that i am missing? 

Thanks, this is a great plugin. Sorry if i asked in the wrong place

**Comment by mistic100** [comment]
`allow_groups`
http://mistic100.github.io/jQuery-QueryBuilder/#usage
