### ISSUE TITLE
Populating dropdown with DB values

### ISSUE THREAD

**Issue by HuskyHound** [mistic100/jQuery-QueryBuilder#123]
Great job by the way :).

I was wondering if it's possible to populate dropdown values for a select input with values from a database?

If it is, do you happen to have an example please?

**Comment by mistic100** [comment]
You can do whatever you want, externally, make your AJAX request to get the values and use it to populate the `values` object|array.

Or use a plugin like Selectize which integrate all the needed operations.

Nothing more will be handled by QueryBuilder.
