### ISSUE TITLE
Adding Multiple plugins in one rule.

### ISSUE THREAD

**Issue by mkiitkgp** [mistic100/jQuery-QueryBuilder#126]
Can we add multiple plugin in one rule. Eg in one rule can i add datepicker as well as slider side by side without adding OR/AND ?

**Comment by mistic100** [comment]
As rules only contain only one field (or one set of linked fields, like checkboxes), the answer is no.

However you can tweak it by using "input" as a function to return a custom input template, "valueGetter" and "valueSetter" callbacks to handle it correctly and init your plugin manually ("afterCreateRuleInput" event for example).

**BUT** it will be still be considered as ONE value (returned by "valueGetter"), I don't think it make any sense
