### ISSUE TITLE
How to include dependencies?

### ISSUE THREAD

**Issue by Sedighzade** [mistic100/jQuery-QueryBuilder#127]
I'm  a windows users, so I cannot build the system. Also I cannot find bootstrap tooltip. I do have included 'bootstrap.min.css' butstill I get error.

**Comment by mistic100** [comment]
include bootstrap.min.js ?

**Comment by Sedighzade** [comment]
Hi,
I had trouble adding plugins. I end up fixing js errors by try and error. Please make a better documentation about how to include pre-requisites. Or add it all to the final examples

**Comment by mistic100** [comment]
I don't know what you need, [the doc](http://mistic100.github.io/jQuery-QueryBuilder/plugins.html#new-features) tells what is needed and [the example](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/examples/index.html) has a lot of stuff included.

Tell exactly what can be better and I'll add it.

Of course it requires a little knowledge of the Bootstrap and Bower ecosystem, I won't explain everything from scratch.

**Comment by Sedighzade** [comment]
Yes, this is true. I do not have knowledge of Bootstrap and Bower ecosystem, so I encountered a lot problems. I thought It would be as easy as reading links in the head of the 'index.html' file in examples folder and add all necessary files. But unfortunately I couldn't find files like 'bootstrap-tooltip.js', 'bootstrap-select.js', etc. in your dist folder. I just googled and add them to my code, in hope everything would go well. Now some plugins work well.
So I think I would better to add all necessary files in your final dist folder. This is of course my suggestion. It may help you.

**Comment by mistic100** [comment]
I don't agree. Today (well since a lot of time) trend is to use packages managers to ensure we have the right version of everything.

If you don't use a package manager then you have to download everything.

I won't explain how, why, etc.

Can we close ?

**Comment by Sedighzade** [comment]
Well, I think another way. Seems we do not agree on the matter.

Anyway, how can I ask you questions, rather than opening a ticket? What I have set-up is not exactly what I see by your example. Some minor problems I have. Can I send u an image of I see on my box?

BTW , thank you for your great job.

**Comment by mistic100** [comment]
I don't do any personal support, not time or patience for that.
