### ISSUE TITLE
bt-selectpicker plugin

### ISSUE THREAD

**Issue by source-transformer** [mistic100/jQuery-QueryBuilder#129]
![screen shot 2015-06-05 at 12 03 43 pm](https://cloud.githubusercontent.com/assets/6571230/8013066/07060080-0b7b-11e5-847e-e3fa9d498645.png)

When I use the following HTML and EJS/JSON:
<div id="builder-plugins"></div>

<script>

    $('#builder-plugins').queryBuilder({
        plugins: [
            'bt-selectpicker',
        ],

        filters: [{
            id: 'category',
            label: 'Category',
            type: 'integer',
            input: 'select',
            values: {
                1: 'Books',
                2: 'Movies',
                3: 'Music',
                4: 'Goodies'
            },
            color: 'primary',
            description: 'This filter uses Awesome Bootstrap Checkboxes',
            operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
        }
        }],

    });
</script>

There is a strange duplication of the filter and operator selects - that can be clicked - but has no options.  Further the values drop-down does not seem to be using the bt-selectpicker.  Also, what is the correct syntax to set the "live" option?  I was thinking it would be something like this:

plugins: {
            'bt-selectpicker': {liveSearch:true},
        }

**Comment by mistic100** [comment]
live example ?

**Comment by source-transformer** [comment]
Looks like the script I included/pasted was stripped:
    $('#builder-plugins').queryBuilder({
        plugins: [
            'bt-selectpicker',
        ],

        filters: [{
            id: 'category',
            label: 'Category',
            type: 'integer',
            input: 'select',
            values: {
                1: 'Books',
                2: 'Movies',
                3: 'Music',
                4: 'Goodies'
            },
            color: 'primary',
            description: 'This filter uses Awesome Bootstrap Checkboxes',
            operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
        }],
    });

**Comment by source-transformer** [comment]
Looks like there were two problems:
1. I wasn't including the css
2. the default plugin code doesn't map to the values portion of a select

Thanks!

**Comment by mistic100** [comment]
Sorry I read too quickly : yes bt-selectpicker internal plugin is only for operators and filters
You can of course activate it for the values with the filter level "plugin" and "plugin_config" attributes

**Comment by source-transformer** [comment]
Yeah I had experimented briefly with the plugin and plugin_config on the filter - but couldn't get that to work - it kept error'ing out with:
Uncaught TypeError: $inputs[filter.plugin] is not a function

here (in query-builder.js):
    if (filter.plugin) {
        $inputs[filter.plugin](filter.plugin_config || {});
    }

The only sample I could find was with the selectize - which seems similar to what I want (with bt select) - but it generates a transparent background - so it doesn't look quite right:

    plugin: 'selectize',
    plugin_config: {
      valueField: 'id',
      labelField: 'name',
      searchField: 'name',
      sortField: 'name',
      create: true,
      maxItems: 1,
      plugins: ['remove_button'],
      onInitialize: function() {
        var that = this;

        if (localStorage.demoData === undefined) {
          $.getJSON(baseurl + '/assets/demo-data.json', function(data) {
            localStorage.demoData = JSON.stringify(data);
            data.forEach(function(item) {
              that.addOption(item);
            });
          });
        }
        else {
          JSON.parse(localStorage.demoData).forEach(function(item) {
            that.addOption(item);
          });
        }
      }
    }

**Comment by mistic100** [comment]
plugin refers to the jQuery plugin, so 'selectpicker', not the QueryBuilder plugin ('bt-selectpicker')

it's just what the doc says:
> plugin: Name of a jQuery plugin to apply on the input.

**Comment by armin-abbasi** [comment]
First, thank you for writing this magnificent piece of work, it's really helpful
I have a problem using "onInitialize" callback , problem is when I use this callback on a field, after I use this field as rule and fill it with values, It does not display the saved rules after initialize. 

	      `{   id: 'tickets.ti_owner',
		    label: 'Ticket Generator Operator',
		    type: 'integer',
		    input: 'select',
		    multiple: true,
		    create:true,
		    plugin: 'selectize',
		    optgroup: 'ticket',
		    operators: ['in', 'not_in', 'is_null', 'is_not_null'],
		    plugin_config: {
		      valueField: 'id',
		      labelField: 'name',
		      searchField: 'name',
		      sortField: 'name',
                onInitialize: function() {
                    var that = this;

                    $.getJSON('loaddata.php?fields=operator', function(data) {
                        //console.log(data);
                        //localStorage.demoData = JSON.stringify(data);
                        data.forEach(function(item) {
                            item.id = item.op_userid;
                            item.name = item.op_name;
                            that.addOption(item);
                        });
                    });
                }
		    },
		    valueSetter: function(rule, value) {
			      rule.$el.find('.rule-value-container select')[0].selectize.setValue(value);
			}
                  }`

and this is loading the rules
`
$('#builder').queryBuilder('setRules', myData);
`

**Comment by mistic100** [comment]
Please read the doc. Callbacks have been removes since more than a year. Use events instead http://querybuilder.js.org/#events

**Comment by mistic100** [comment]
Please create a new issue with a jsfiddle.

**Comment by armin-abbasi** [comment]
My bad, there was no issue from QueryBuilder it was my api unicode compatibility! really sorry
