### ISSUE TITLE
Selecting a rule that populates the operator and the value throws a 'no value selected' error.

### ISSUE THREAD

**Issue by kristofer-escobar** [mistic100/jQuery-QueryBuilder#130]
When selecting a rule that populates the operator and the value and then calling 'getRules' throws an error that says that 'no value selected'. The value has already been populated when the rule was selected.

An example can be seen in the basic demo. (http://mistic100.github.io/jQuery-QueryBuilder/demo.html)
1) Hit reset to clear out the rules.
2) Select the 'Category' option
3) Click on the 'Get rules' button
4) The error 'no value selected' appears although the value is set to 'Books'.

**Comment by mistic100** [comment]
ok seen, there is a hole in the events chain which update the data model
thank you
