### ISSUE TITLE
Negate group or statement

### ISSUE THREAD

**Issue by bukowskiadam** [mistic100/jQuery-QueryBuilder#131]
Is there any simple way to introduce negation button? It would be nice if you could invert current logic.

Anyway it's a great tool - thanks for that!

**Comment by mistic100** [comment]
what do you mean ?

**Comment by bukowskiadam** [comment]
I'll post an example in SQL.

I have a query to get people in the age range 10-30 or older than 50.
`(age > 10 AND age < 30) OR age > 50`
Now I'd like to negate this statement so I'll write
`NOT ((age > 10 AND age < 30) OR age > 50)`
dead simple.
In query builder I have to reverse all operators an AND/ORs to make it
`(age <= 10 OR age >= 30) AND age <= 50`

**Comment by mistic100** [comment]
yeah could be done
we just need a mapping of "complementary" operators

**Comment by mistic100** [comment]
I added a new plugin named "invert".

When loaded (just loaded, not configured) it exposes a method conveniently named "invert".

When configured (in the "plugins" parameter) it adds an "Invert" button in each group header.

There also are options for recursion behaviour and rules buttons, see source code waiting for the doc to be updated.

**Comment by bukowskiadam** [comment]
Great! Many thanks! I'll build and test it on Monday. Also I'll update
polish translation then.

You've done more than expected. I was thinking that it would be great to
just have a switch for the inversion and just return that group is negative
during export, but it would be harder to read and it'll require to change
export plugins.
Again thanks for that change! I'll contact you on Monday.
 12 cze 2015 20:35 "Damien Sorel" <notifications@github.com> napisał(a):

**Comment by bukowskiadam** [comment]
I have created a pull request with one fix, but everything else looks great!
