### ISSUE TITLE
Not able to select multiple input for 'in' operator

### ISSUE THREAD

**Issue by abhijeetkdm** [mistic100/jQuery-QueryBuilder#134]
Not sure If I am doing right but my rule with operator 'in' / 'not in' not able to select multiple choices.
In my configuration 'multiple' attribute is true for 'in' / 'not in' operators.

**Comment by mistic100** [comment]
no code example, no help

**Comment by abhijeetkdm** [comment]
this is my operator configurations (leaving other types for brevity )
            operators: [
                   ......
                    {type: 'in',               nb_inputs: 1, multiple: true,  apply_to: ['string', 'number', 'datetime']},
                    {type: 'not_in',           nb_inputs: 1, multiple: true,  apply_to: ['string', 'number', 'datetime']},
                    .......
                ],

![screen shot](https://cloud.githubusercontent.com/assets/8029732/8214710/e27eb608-14df-11e5-81ed-46275b5954ce.png)

'Category' filter is defined as 
filters: [ {
            id: 'category',
            label: 'Category',
            type: 'integer',
            input: 'select',
            values: {
              1: 'Books',
              2: 'Movies',
              3: 'Music',
              4: 'Tools',
              5: 'Goodies',
              6: 'Clothes'
            },
            operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
          }]

Issue:  when I select 'in' as operator, I should be able to select multiple values but it is not letting me. 

(Hope this explains )

**Comment by mistic100** [comment]
that's not how it works
you don't have to modify the operators configuration (and this is the default config anyway)

`multiple` is an option of the filter http://mistic100.github.io/jQuery-QueryBuilder/#filters

**Comment by abhijeetkdm** [comment]
okay ! .. Great. It worked. Thank you for prompt response .

**Comment by mistic100** [comment]
good :)

**Comment by abhijeetkdm** [comment]
Ran into one more issue

Trying to change condition to show as dropdown instead of group buttons so I created my own group and rule templates ( its same as source template just condition template is changed )

    function getGroupConditions(this_obj, group_id, level){
        var h = '<select>';

        for (var i=0, l=this_obj.settings.conditions.length; i<l; i++) {
            var cond = this_obj.settings.conditions[i],
                label = this_obj.lang.conditions[cond] || cond;
            h+= '\
              <option name="'+ group_id +'_cond" value="'+ cond +'"> '+ label +'</option>' +'  \
            ';
        }
        return h + "</select>";
    }


    function getGroupTemplate(this_obj, group_id, level){
        return '\
            <dl id="'+ group_id +'" class="rules-group-container"> \
              <dt class="rules-group-header"> \
                <div class="btn-group pull-right group-actions"> \
                  <button type="button" class="btn btn-xs btn-success" data-add="rule"> \
                    <i class="' + this_obj.icons.add_rule + '"></i> '+ this_obj.lang.add_rule +' \
                  </button> \
                  '+ (this_obj.settings.allow_groups===-1 || this_obj.settings.allow_groups>=level ?
                    '<button type="button" class="btn btn-xs btn-success" data-add="group"> \
                      <i class="' + this_obj.icons.add_group + '"></i> '+ this_obj.lang.add_group +' \
                    </button>'
                  :'') +' \
                  '+ (level>1 ?
                    '<button type="button" class="btn btn-xs btn-danger" data-delete="group"> \
                      <i class="' + this_obj.icons.remove_group + '"></i> '+ this_obj.lang.delete_group +' \
                    </button>'
                  : '') +' \
                </div> \
                <div class="group-conditions"> \
                  '+ getGroupConditions(this_obj, group_id, level) +' \
                </div> \
                '+ (this_obj.settings.display_errors ?
                  '<div class="error-container"><i class="' + this_obj.icons.error + '"></i></div>'
                :'') +'\
              </dt> \
              <dd class=rules-group-body> \
                <ul class=rules-list></ul> \
              </dd> \
            </dl>'
    }


    function getRuleTemplate(this_obj, rule_id) {
        return '\
              <li id="'+ rule_id +'" class="rule-container"> \
              <div class="rule-header"> \
              <div class="btn-group pull-right rule-actions"> \
                <button type="button" class="btn btn-xs btn-danger" data-toggle="popover" title="Header" data-trigger="hover"  data-delete="rule"> \
                  <i class="' + this_obj.icons.remove_rule + '"></i> '+ this_obj.lang.delete_rule +' \
                </button> \
              </div> \
              </div> \
              '+ (this_obj.settings.display_errors ?
                '<div class="error-container"><i class="' + this_obj.icons.error + '"></i></div>'
              :'') +'\
              <div class="rule-filter-container"></div> \
              <div class="rule-operator-container"></div> \
              <div class="rule-value-container "></div> \
            </li>'
    } 


And using this functions in configuration 

        template: {
            group: function(group_id, level) {
                return getGroupTemplate(this, group_id, level);
            },
            rule: function(rule_id) {
                return getRuleTemplate(this, rule_id);
            }
        }



But it not updating condition (after changing value in dropdown )or invoking 'afterUpdateGroupCondition.queryBuilder' event. 

Any help would be appreciated.

Note:  It works if I change 'getGroupConditions' method to return button groups (similar to source template )

**Comment by mistic100** [comment]
that's why the `template` option is not documented.
particularly this is not template agnostic https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/core.js#L167-L172

**Comment by abhijeetkdm** [comment]
Sorry I am not very proficient in jQuery yet but what i don't understand is why changing to 'select' not triggering event 'change.querybuilder' ?

I tried to trigger it manually but got error 'Maximum call stack size exceed'

Is there any better way to change condition to dropdown. I see you suggesting button dropdown but i guess it does not show selected option on button

**Comment by abhijeetkdm** [comment]
Sorry to shoot with another question but I am currently confused with event triggering here.

I need to change one of the input to autocomplete (using django-selectable). But this does not trigger updateRuleValue function 

                case 'value':
                    that.updateRuleValue(node);
                    break;

is there any better way to trigger this events manually or any better solution ?

**Comment by abhijeetkdm** [comment]
Never mind. Got it working with some workarounds (Not very elegant ones )
