### ISSUE TITLE
Sortable flickering issue

### ISSUE THREAD

**Issue by derek831** [mistic100/jQuery-QueryBuilder#135]
Hi,

First of all, great plugin. However, I have found that when you have a nested group (3+ levels deep) and try to drag a rule to a parent's rule group. There is always this spot where the placeholder element would flicker between the parent and the child elements. Do you have any suggestions on how to fix this?

Many thanks.

**Comment by mistic100** [comment]
unless being pixel-perfect when placing elements (which is not possible) or add a lot of boiler-plate to the drag handler (which I don't want to), I don't have solution

if you remove padding to containers it will work but it will be ugly

**Comment by derek831** [comment]
I understand and thank you for your reply but do you know what it is that is causing the issue in the first place?

**Comment by mistic100** [comment]
As I said: padding.

Actually it's not padding but margin, as margins are not part of the element, the drag target is the parent element (group) when the cursor is between two rules, or at the top of of another group
