### ISSUE TITLE
Dynamic filters

### ISSUE THREAD

**Issue by phazei** [mistic100/jQuery-QueryBuilder#136]
Is it possible to add dynamic filters?

I'm creating a system where there are a number of pre-existing fixed filters as this builder does, but there are also many that will be dynamic; far far too many to create initially (hundreds to thousands)

For the dynamic options, an "add filter" would need to be selected, which would then popup an auto-complete type box allows them to search for a rule from the server, once selected, it would return the name/id of the rule, as well as the operators and values, and from those, the plugin would work as expected.

Once the plugin has been created, can I add an additional filter?  And is there a hook so when it runs "setRules", if it were a dynamically added rule that doesn't exist in the pre-existing filter list, I could have it grab that rule from the server so it can properly set the rule?

I believe that all should be able to be done with setFilter/getFilter hooks that are triggered for certain rules.

**Comment by mistic100** [comment]
you forgot the step where you refresh all select boxes to add the new filter.
but yes it should be possible

you can create a plugin to have access to all internals without boiler-plate
(I won't do it)

**Comment by mistic100** [comment]
I'm working on it

**Comment by mistic100** [comment]
A new plugin adds methods `setFilters`, `addFilter` & `removeFilter`.
