### ISSUE TITLE
Needs another Select Input

### ISSUE THREAD

**Issue by abhishekchitransh** [mistic100/jQuery-QueryBuilder#138]
Hello Damien,

My app uses 4 inputs, first one is Category, second one is Sub Category, third is Operator and 4th is Value. Attached the screenshot.

Could you please let me know how can i add one more select input and what are are the other changes i would need to make.

Thanks in advance.

![image](https://cloud.githubusercontent.com/assets/4608620/8375336/e9cba9d4-1c19-11e5-9903-4312d1df21d3.png)

**Comment by mistic100** [comment]
There is no "how to", you will have to understand how the data model, the templates and the events work and do the necessary changes.

If I had to do it myself I'll say I need at least 5 hours to make such drastic change working, so I won't do it :)

**Comment by mistic100** [comment]
oy you could just merge your two drop down using optgroups
