### ISSUE TITLE
Delete rules and groups from the outside

### ISSUE THREAD

**Issue by JanMalte** [mistic100/jQuery-QueryBuilder#139]
This is more a question, than a real issue.

I couldn't found a way to delete a rule or group of rules by JavaScript. How can I delete rules using jQuery before calling ```getRules()``` to avoid submitting invalid rules by trying to clean some common usage mistakes (like empty rule value fields)?

**Comment by mistic100** [comment]
You will need to access the builder data storage, it's available at
```js
$('#builder')[0].queryBuilder.model.root // model might be null, don't forget to test it
```

This is an instance of a **Group** (see http://mistic100.github.io/jQuery-QueryBuilder/#inside_the_box)

you can iterate the group with

```js
group.each(true, function(rule) {

}, function(group) {

});
```

there are two callbacks, one for rules and one for subgroup (you might use a self-calling recursive function to traverse the whole tree). The first `true` parameter is to ask a reverse lookup order, which is required if you are going to delete items.

When you have a **Rule** or a **Group** you can access it's data (cf doc) and call `drop` to delete it.

**Comment by JanMalte** [comment]
Thank you very much.
