### ISSUE TITLE
build sql from json

### ISSUE THREAD

**Issue by waitcon** [mistic100/jQuery-QueryBuilder#14]
hi mistic100,

great code !!!
is there a chance to add functionality in order to get valid sql where clause out of json string?

**Comment by gadelat** [comment]
If you got here like me - searching for parsing output of this library in PHP, I made fork of [timgws/QueryBuilderParser](https://github.com/timgws/QueryBuilderParser) for Doctrine, located at [gadelat/QueryBuilderParser](https://github.com/gadelat/QueryBuilderParser)

**Comment by hassanalisalem** [comment]
Hi there, I didn't know that there is a query builder for this :D.
so I created one 😄 
it works with laravel model and relation. so you don't need to redefine relation again.

also, it hides your table structure. please take a look at it.

[https://github.com/hassanalisalem/querybuilder](queryBuilder)

**Comment by mistic100** [comment]
But there already was a parser for Laravel http://querybuilder.js.org/#backends

**Comment by hassanalisalem** [comment]
@mistic100 
yes, I know, but the problem that you need to redo the relations and rethink them,
that what happened to me, I forgot what are my relations were.
so I created it, it uses the laravel relations ( the relations inside the Model itself)
