### ISSUE TITLE
valueSetter: a better way

### ISSUE THREAD

**Issue by philstrong** [mistic100/jQuery-QueryBuilder#140]
I have some rules that have a value different than the display aka
0: None
1: Positive
2: Negative

where 0,1,2 are what goes in the query but the words are displayed to the user.

When I getRules and then later setRules it remembers the value aka 0,1,2 which is totally fine.

So for the user I want for them to see None, Positive, Negative (made up strings btw ;P)

So I'm using valueSetter but it strikes me as something that isn't a good idea; notably because it relies on dom and has me triggering change events.

Is there a better way?

**Comment by mistic100** [comment]
are you using checkbox/radio/select ?
if so please read the doc about `values` http://mistic100.github.io/jQuery-QueryBuilder/#filters

**Comment by philstrong** [comment]
I knew there had to be a cleaner way.  Thanks

**Comment by philstrong** [comment]
What about for strings that are altered e.g. ip -> hex
user input: 192.168.1.1 -> C0A80101

how would you recommend when setRule w/ C0A80101 comes in to convert it back to human readable.  Is there a better hook than valueSetter?

**Comment by mistic100** [comment]
non that's exactly the purpose of valueSetter and valueGetter
