### ISSUE TITLE
error validating empty BETWEEN rule

### ISSUE THREAD

**Issue by MatthiasHild** [mistic100/jQuery-QueryBuilder#144]
Dear Damien,

I am getting to know version 2.2.0 of your wonderful plugin. I came across a bug in the validation logic for BETWEEN rules. The problem occurs when a user creates a BETWEEN rule and QueryBuilder.validate is invoked before the user has chosen any low-high values. 

The error occurs in the Basic example on the demo page http://mistic100.github.io/jQuery-QueryBuilder/demo.html:

__Uncaught TypeError: Cannot read property '0' of undefined__

The error is raised on line 1351 of the unminimized standalone file.

Here are the steps:

* Add a new rule to outermost group.
* Select Price
* Select Between
* Click "Get Rules"

The problem is in a missing check for value === undefined at the beginning of QueryBuilder.validateValueInternal. This causes a problem when we hit the following check within this function:
...
 case 'number':
                        if (value[i] === undefined || isNaN(value[i])) {
                            result = ['number_nan'];
                            break;
                        }
...

Many thanks for your work on this.

Best wishes,

M.

**Comment by mistic100** [comment]
I cannot reproduce on master, beside the fact I can't see how it could have been fixed since 2.2.0
https://github.com/mistic100/jQuery-QueryBuilder/compare/2.2.0...master

can you try ? Just follow the buld instruction https://github.com/mistic100/jQuery-QueryBuilder#build and use the builder in examples directory
