### ISSUE TITLE
setRulesFromSQL does not set groups

### ISSUE THREAD

**Issue by unosbm65** [mistic100/jQuery-QueryBuilder#145]
Hi
When I want to set the Query Builder, it doesn't populate Groups.  it shows all the rules without any groups 

consider this : 
$('#builder').queryBuilder('setRulesFromSQL','ProductTypeGroupId = "a string" AND (Username = "test" AND IsExtra = "yes")');

Could you please help me to come up with a solution or maybe i'm doing something wrong !!!?

**Comment by RonaldvanMeer** [comment]
this is not a bug.
since it only contains "AND" statements, querybuilder simplyfies the rule without groups.

**Comment by unosbm65** [comment]
You saved my day

Thanks
