### ISSUE TITLE
IE 11 compatibility mode.

### ISSUE THREAD

**Issue by maverickIndia** [mistic100/jQuery-QueryBuilder#146]
Very useful component. 

Is it not supported on IE 11 compatible mode ? Not able to see demo in IE-11 compatible mode.

Needs a help on this !

**Comment by mistic100** [comment]
No idea, I never use IE, neither my clients, especially not in compatibility mode (which we don't exactly know what it does).

My answer is the same for IE8, you can submit a PR but I won't work on it.
