### ISSUE TITLE
a combined query

### ISSUE THREAD

**Issue by unosbm65** [mistic100/jQuery-QueryBuilder#147]
Hi
I cannot make a query such as below . I do not know if I miss something or it is the nature of your control. 
but I make a wild guess maybe it is a bug
Username = "test" AND IsExtra = "yes" OR ('ProductTypeGroupId = "a string" )

**Comment by mistic100** [comment]
Hi

Imagine `a AND b OR c`
It's strictly the same as `(a AND b) OR c`
So set the main group condition to OR, it will contain rule c and another group with condition AND and rules a AND b 

You must understand that a condition applies between items inside the group.

**Comment by mistic100** [comment]
It works like this because end-users gently do not know that AND is evaluated prior OR.

**Comment by unosbm65** [comment]
I got it.
thanks a lot
