### ISSUE TITLE
Default placeholder for values

### ISSUE THREAD

**Issue by asleepatdesk** [mistic100/jQuery-QueryBuilder#149]
Nice tool.

Is it possible to have a placeholder for the Values drop down much like the 'select_placeholder' option for the filters?  It appears that the builder doesn't see a value until the index on the drop down is changed.  This is reproducible in the sql demo. Select 'Category' in the filter and you'll see that 'Books' defaults as the value. Click 'SQL' button and the 'No value selected' message shows. 

![image](https://cloud.githubusercontent.com/assets/13457966/8857812/dd98874e-3128-11e5-8d2c-589524fc593e.png)

Thanks!

**Comment by mistic100** [comment]
Actually this error is already solved.

But yes it's a good idea

**Comment by mistic100** [comment]
#130
