### ISSUE TITLE
$http.get call not updating the form group

### ISSUE THREAD

**Issue by sprakashg** [mistic100/jQuery-QueryBuilder#150]
I have set the response from $http.get call 
  $('#builder').queryBuilder('setRules', response["data"]["actions"]);
It works fine if we have form rule, but not for form group inside form rule.
in console I get  "Missing rule field id " error

**Comment by mistic100** [comment]
Please read the contribution guidelines, if you don't post example, I don't help.

And I can affirm it's not related to angular, your only problem is that your config object is invalid.

**Comment by sprakashg** [comment]
Yes it not related to angular. 
I followed the example from this link http://jsfiddle.net/graphitekom/ap9gxo4L/
If I add group under rule, it doesnt update the page with values. here is the 
{
  "condition": "AND",
  "rules": [
    {
      "id": "core_ID",
      "field": "core_ID",
      "type": "integer",
      "input": "text",
      "operator": "in",
      "value": "1240"
    },
    {
      "id": "core_ID",
      "field": "core_ID",
      "type": "integer",
      "input": "text",
      "operator": "equal",
      "value": "1"
    }
  ]
}

**Comment by mistic100** [comment]
Well.... http://jsfiddle.net/ap9gxo4L/14/

**Comment by mistic100** [comment]
Well... http://jsfiddle.net/ap9gxo4L/15/
I just pasted your rules in "setRules"

**Comment by sprakashg** [comment]
Yes, thank you..am looking into it.
Can I use two query builder div in one page.
example 
  $('#builder').queryBuilder({
    sortable: true,
    filters: [{
      id: 'core_ID',
      type: 'integer',
      operators: ['equal', 'not_equal', 'in', 'not_in']
     }, {
      id: 'store_id',
      label: 'Store ID',
      type: 'string',
      operators: ['equal', 'not_equal', 'in', 'not_in']
    }]
  })

  $('#builder1').queryBuilder({
    sortable: true,
    filters: [{
      id: 'core_ID1',
      type: 'integer',
      operators: ['equal', 'not_equal', 'in', 'not_in']
     }, {
      id: 'store_id',
      label: 'Store ID',
      type: 'string',
      operators: ['equal', 'not_equal', 'in', 'not_in']
    }]
  });

                  <div id="builder"></div>
                      <div id="builder1"></div>

but its not working, getting a message as " Missing filters list"

**Comment by mistic100** [comment]
of course you can, there are 4 builders on this page http://mistic100.github.io/jQuery-QueryBuilder/demo.html

I can't tell you why yours is not working

ps: `sortable` does not exist anymore, it's a plugin now http://mistic100.github.io/jQuery-QueryBuilder/plugins.html#sortable

and please use Markdown syntax for code (triple tick)

**Comment by sprakashg** [comment]
cool. But If I add a form-group under form-rules, I get this error 
 Missing rule field id

**Comment by mistic100** [comment]
look, you show me a code that IS working.
what must I do now ? begging for an example each time ?

yes I'm harsh, I'm tired of people who just say "it's not working"
