### ISSUE TITLE
selectize plugin failing

### ISSUE THREAD

**Issue by jsdev** [mistic100/jQuery-QueryBuilder#151]
Might be just a matter of not loading the latest selectize plugin as the demo found here used to work great! just a week ago or so.

you can see the issue checking out selectize in the widgets section
http://mistic100.github.io/jQuery-QueryBuilder/demo.html

**Comment by mistic100** [comment]
Working for me

**Comment by jsdev** [comment]
I stand corrected its my machine I just tried from another device
