### ISSUE TITLE
Change button style

### ISSUE THREAD

**Issue by karlr42** [mistic100/jQuery-QueryBuilder#152]
I would like to change the default styling applied to buttons to remove the Bootstrap '-xs' classes- end goal is something like this : 

![captursddsdsdsde](https://cloud.githubusercontent.com/assets/839771/9182041/3682b3fe-3fa0-11e5-8986-4449732db299.PNG)

I did try using the template argument in my model, but looking at the default getGroupTemplate function it seemed to rely on a lot of internal data and wasn't sure how to proceed

**Comment by mistic100** [comment]
Actually the usage of internal data is not a problem because when the template function is called, it is binded to the builder, so `this` is is still valid
So you should be able to use the `template.group` and `template.rule` parameters (needs to unfold `getGroupConditions` of course)

I am considering relying a real (micro) template engine to allow a more flexible customization and finally document this

**Comment by karlr42** [comment]
Oh, okay, didn't realise that. I'll try it out and see how it goes, thanks.

**Comment by karlr42** [comment]
Ok, that worked, I can set the group and rule template, thanks : 

![selection_119](https://cloud.githubusercontent.com/assets/839771/9195232/22ffe044-4019-11e5-871b-4f967c46d7f7.png)

However, as you can see, there is another problem- to make the rule container the right size to hold the delete button(and get the style from my initial image), I need to change the style of the dropdown to remove btn-xs as well. You can see how I did it in my fork : https://github.com/karlr42/jQuery-QueryBuilder/blob/master/src/plugins/bt-selectpicker/plugin.js#L31

Any ideas on how I can do this, or should I wait for the template engine? Thanks again.

**Comment by karlr42** [comment]
Ah, actually, in producing a jsfiddle, I found some hints and realised the problem is with how we are using bt-select, so I fixed the issue by just doing this
```
model: {
  plugins:    {
   "bt-selectpicker" : {style : "btn-default"}
 },
...
```
Here's the fiddle, by the way : https://jsfiddle.net/18jad46z/1/

Thanks again for all the help, and the awesome project.

**Comment by mistic100** [comment]
added configurable templates using http://olado.github.io/doT engine
doc will come with 2.3.0

**Comment by karlr42** [comment]
The new templating stuff is very cool, thanks.

I've updated my application to 2.3.0 and am using the templates- here's an updated jsfiddle with my style - https://jsfiddle.net/xrryf1k0/2/ . Thanks again.
