### ISSUE TITLE
ways to deal with lots of fields?

### ISSUE THREAD

**Issue by cesar-devera-movile** [mistic100/jQuery-QueryBuilder#153]
I'm amazed by jQuery-QueryBuilder, and I'm planning to use it in a project, but I have anusability issue that I could not find addressed in the docs: what happens if I want to offer my user a lot of fields, let's say, 500 fields?

by fields I mean the left-most combo, that shows "Name, Category, In Stock, Price,..." in the first demo.

in my project, I want to offer dozens of fields, from different tables. I'm not worried too much about the query generation funcionality at the moment. but showing a huuuge combo with lots of options might be an usability issue.

I could suggest three approaches:

1. the possibility to add a separator item in the combos, that could allow group items, like this:

-- table 1 --
field 1
field 2
-- table 2 --
field x
field y
...

by -- table -- imagine any header, title, or free-text in a non-selectable item. 

2. the second possibility would be to offer the same chained-combos technique demonstrated in the Coordinates Widget, but now in the field selection. this way, a first combo would select a "table" and populate a second combo with its corresponding fields. I think this approach is better than the first one, but harder to develop.

3. a last approach would be to popup a modal that the user could design as he wanted (possibly ajax,  allowing him to show how many fields he wants with the best design for his problem), and then capture the return (or closing) of that modal, just to get the field name/type.

hope my suggestions help improving this awesome project.

regards :)

**Comment by mistic100** [comment]
Hello, and thank you.

1. is already possible with optgroups, check the doc

2. would be really difficult to implement in a customizable way

3. seems a pretty good solution and is already possible with some work
 - init your modal (Bootstrap ?) without openning it and keep a reference to it
 - listen to the `getRuleFilterSelect.queryBuilder.filter` event to add a button next to the selectbox (see how plugins work)
 - add a listener to the buttons and open the dialog with a reference to the active rule
```js
$('#builder .my-button').on('click', function() {
  var $rule = $(this).closest('.rule-container');
  dialog_target = $rule.data('queryBuilderModel');
  dialog.open();
});
```
 - set the rule filter when you close the dialog
```js
dialog.on(what ever you want, function() {
  dialog_target.filter = $('#builder').queryBuilder('getFilterById', filter_id);
  dialog.modal('hide');
});
```

4. other solution: adapt bt-selectpicker plugin to use Selectize

**Comment by ganeshsb** [comment]
@mistic100: I like your 4th solution in which you mention to use the Jquery Selectize.  Can you please share a sample code snippet that implements the same. Thanks.

**Comment by mistic100** [comment]
Not really... it's not that complicated, just use selectize instead of selectpicker
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/plugins/bt-selectpicker/plugin.js

**Comment by ganeshsb** [comment]
I did change the plugin name  from 'bt-selectpicker' to 'selectize' but its not working. Can you please let me know If I need to make any additional changes -- I have attached my code snippet for your reference.  Thanks.
[sample.txt](https://github.com/mistic100/jQuery-QueryBuilder/files/32574/sample.txt)

**Comment by mistic100** [comment]
You know programming is not black magic right ? When I said **adapt** I meant "clone the plugin, understand how it work, modify the code and recompile the lib" not just "change the name and hope it will work by itself".

I just have not time currently to do it myself or provide full support.
