### ISSUE TITLE
setRules does not work with filter_readonly etc.

### ISSUE THREAD

**Issue by bqffen** [mistic100/jQuery-QueryBuilder#154]
When setting either
filter_readonly: true,
operator_readonly: true,
value_readonly: true,

from .queryBuilder('setRules', '...') nothing happens.

If setting the default value in the sourcecode, the result is as expected.

**Comment by mistic100** [comment]
The embedded example with filter_readonly just works.

So provide an example

**Comment by bqffen** [comment]
Did not work due to a typo.
