### ISSUE TITLE
bt-selectpicker does not work when applied to a rule value

### ISSUE THREAD

**Issue by karlr42** [mistic100/jQuery-QueryBuilder#157]
When you try to apply the plugin to a rule, the actual dropdown menu does not appear when you click on it. See in this example: https://jsfiddle.net/evvez2uc/

This issue was I think noticed before, in https://github.com/mistic100/jQuery-QueryBuilder/issues/129#issuecomment-109442278 . 

I tried to fix this myself, I thought it would be as simple as https://github.com/karlr42/jQuery-QueryBuilder/commit/0bb643fcea4aebdba035cc64393e179ce84e99a1 , but it doesn't seem to have any effect - see https://jsfiddle.net/qtcLoc39/1/ where I am using a gist of my locally created query-builder.standalone.js to test.

Any thoughts?

**Comment by karlr42** [comment]
Argh, just noticed my fork is using the wrong events, let me actually make my fix correct and then I'll test..

**Comment by mistic100** [comment]
add `container: 'body'`

FYI it works on the example file (applied to "continent" for instance), it's only a problem of what contains the builder

**Comment by mistic100** [comment]
don't know why it doesn't work with your fork
it's a bad idea to proceed this way anyway, your are lucky it does not mess the Name filter

**Comment by karlr42** [comment]
Ah, ok, great, that container fix should work for my application, so no need for the fork.

As a possible improvement, is it worth trying to make `container: 'body'` the default if no container is specified?

**Comment by mistic100** [comment]
like that ? https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/plugins/bt-selectpicker/plugin.js#L30

> it's the default value of the bt-selectpicker applied to filters and operators

**Comment by karlr42** [comment]
Fair enough. I suppose I'm just confused as to why the approach in my fork doesn't work then. Regardless, manually applying the container setting in plugin_config definitely works, so thanks for that.
