### ISSUE TITLE
how to populate data in dropdown through ajax ? how will i integrate ajax request with jquery query builder ?

### ISSUE THREAD

**Issue by ved54321** [mistic100/jQuery-QueryBuilder#159]
can u provide any example for getting data from ajax and populate select drop down from ajax data?

**Comment by mistic100** [comment]
This is not handled by QueryBuilder and will never be.

Do it yourself by injecting the options in the rule.
Or use a plugin for the selectboxes (Selectize, Select2, etc.)

**Comment by ved54321** [comment]
$('#builder-basic').on('afterInit.queryBuilder', function() {
 
  $.ajax({

      type: "GET",
      url: "/administrator/tribe_rules/show_tribe_role",
      style: "inherit",
      dataType: 'script',
   
      success: function(data) {
          question = JSON.parse(data)   
      }
    });
  });
i am  getting the json data like
 [
  {
    "id": 1854,
    "question_text": "Your staff ?"
  },
  {
    "id": 1855,
    "question_text": "Preferred city ?"
  },
  {
    "id": 1856,
    "question_text": "Tell us something about you."
  },
  {
    "id": 1857,
    "question_text": "Are you agree for terms  and conditions ?"
  },
  {
    "id": 1866,
    "question_text": "Are you interested in Volunteering?"
  },
  {
    "id": 1867,
    "question_text": "Subject of Interest?"
  },
  {
    "id": 1868,
    "question_text": "Which is birth place?"
  },
  {
    "id": 1869,
    "question_text": "I am registered student"
  },
  {
    "id": 2001,
    "question_text": "Are you currently already involved in the Students'  Union?"
  },
  {
    "id": 2244,
    "question_text": "How did you find out about CUSU volunteering?"
  },
  {
    "id": 2329,
    "question_text": "Please select your main campus of study."
  },
  {
    "id": 2361,
    "question_text": "Please State your Course of  Study."
  },
  {
    "id": 2363,
    "question_text": "Your favourite Vegetable"
  },
  {
    "id": 2478,
    "question_text": "Student  Number"
  },
  {
    "id": 2479,
    "question_text": "Course of study"
  },
  {
    "id": 2480,
    "question_text": "Which University /College do you attend?"
  },
  {
    "id": 2528,
    "question_text": "Did you attended any award ceremony?"
  },
  {
    "id": 2666,
    "question_text": "Please use this space to upload a personal statement"
  },
  {
    "id": 2963,
    "question_text": "Campus  Location"
  },
  {
    "id": 3018,
    "question_text": "ertret"
  },
  {
    "id": 3019,
    "question_text": "rtyrety"
  },
  {
    "id": 3020,
    "question_text": "Demo quesahkdsa"
  }
]


can i assign this json data to this filter

  filters: [{
    id: 'name',
    label: 'Name',
    type: 'string'
  }, {
    id: 'question',
    label: 'Question',
    type: 'integer',
    input: 'select',
    values: {
      1: 'option 1',
      2: 'optoin 2',
      3: 'Option 3',
      4: 'Option 4',
      5: 'Option 5',
      6: 'Option 6'
    },
    operators: ['equal', 'not_equal']
  }]

**Comment by mistic100** [comment]
Please use markdown syntax like I edited your message
----

Given you don't have any pre-filled rules.
Find your filter in `$('#builder-basic')[0].queryBuilder.filters` array and update the  `values` attribute in the filter.

The new values should be used when using the filter.

**Comment by ved54321** [comment]
https://jsfiddle.net/evvez2uc/ ,
How to populate question text in the first select drop down ?

**Comment by ved54321** [comment]
can i push into filter after ajax success ?

**Comment by DeveBj** [comment]
@mistic100 as you have said that we can use the select 2 plugin for query builder select boxes how can I use that any links will be helpful

**Comment by MateusFGoncalves** [comment]
Four formats are allowed for the values object.

Simple array of values, labels will be the values.
values: ['one', 'two', 'three']
Key-value object, keys are input values and values and labels.
values: {
  'one': 'Un',
  'two': 'Deux',
  'three': 'Trois'
}
Because the order of key-value objects is uncertain, you can also use an array of one-element objects.
values: [
  {'one': 'Un'},
  {'two': 'Deux'},
  {'three': 'Trois'}
]
The expanded format allows to define optgroups.
values: [
  { value: 'one', label: 'Un', optgroup: 'Group 1' },
  { value: 'two', label: 'Deux', optgroup: 'Group 2' },
  { value: 'three', label: 'Trois' } // no group
]

**Comment by MateusFGoncalves** [comment]
It depends how you are getting this JSON. Then you can go there.

**Comment by MateusFGoncalves** [comment]
If you get through PHP, open a script tag and get this inside a global variable, for example: top.myValues ​​= <? Php json_encode ($ myValues)?> And then use your global variable in queryBuilder, using the available formats, example : values: top.myValues
