### ISSUE TITLE
missing filter 1 id on add rule ?

### ISSUE THREAD

**Issue by ved54321** [mistic100/jQuery-QueryBuilder#160]
$('#builder-basic').queryBuilder('addFilter', { 

              filters: [{
              id: 'name',
              label: 'Name',
              type: 'string'
            }]

         });

what i am doing wrong here?

**Comment by mistic100** [comment]
```js
$('#builder-basic').queryBuilder('addFilter', [{
          id: 'name',
          label: 'Name',
          type: 'string'
});
```

**Comment by ved54321** [comment]
thanks ..
