### ISSUE TITLE
Edit types on the Query Builder object

### ISSUE THREAD

**Issue by nathan-rogers** [mistic100/jQuery-QueryBuilder#163]
QueryBuilder.types is a JSON object that contains 'datetime' as a property(line 156). Our operators are bound to our filters based on the TYPE of the FILTER. 

This is all well and good, but our client wants to have a separate set of operators, dynamic and static, so that means I need a new TYPE so I can apply the OPERATORS to the FILTER by 'datetimerange' TYPE. 

I cannot find the types object in the developer tools to know where the QueryBuilder.Types object lives, nor where or how to extend it. I can convert datetimerange to datetime again on our backend, but in order to render the dynamic dates correctly, your plugin applies changes by type, so therefor I need a new type to play with. Ideas?

**Comment by nathan-rogers** [comment]
for example:
addDateRange.operators.push({
            type: 'today',
            nb_inputs: 0,
            multiple: false,
            apply_to: ['datetimerange']
        });addDateRange.operators.push({
            type: 'last week',
            nb_inputs: 0,
            multiple: false,
            apply_to: ['datetimerange']
        });


QueryBuilder.types = {
    'string': 'string',
    'integer': 'number',
    'double': 'number',
    'date': 'datetime',
    'time': 'datetime',
    'datetime': 'datetime',
//how can I push this from the .extend method, when "this" doesn't contain the types object? Or does it contain it somewhere I just can't find it?
    'datetimerange': 'datetimerange',
    'boolean': 'boolean'
};

**Comment by mistic100** [comment]
You can't do this. Many data handling relies on these types, the library does not know what is a "datetimerange".

You will have to change the way you choose which operators to use.

**Comment by velykov** [comment]
How can I add custom operators for date type, I want add today, yesterday, this_week, etc.

**Comment by velykov** [comment]
And may be some-one know, how to add a link like 'today', 'yesterday' inside dom element with date type?

**Comment by mistic100** [comment]
As always, THE DOC http://querybuilder.js.org/#operators

Your second question doesn't make any sense to me

**Comment by velykov** [comment]
I'm sorry, the doc I found, but second question is how can I access to div (DOM) element of date type via jquery, I want add custom links, which will be set rule like date = today, yesterday, etc.

**Comment by velykov** [comment]
How can I get access to some rule dom container?

**Comment by velykov** [comment]
I try different variants, but what I found, first I can't catch anyway that user choose a date type in rule-filter-container's select, how can I catch this event?

**Comment by velykov** [comment]
found http://querybuilder.js.org/dev/events.html, in table with 'afterAddRule' i think must be a 'afterAddRule.queryBuilder'

**Comment by mistic100** [comment]
Please open a new issue with COMPLETE explanation and example if you still need help.
