### ISSUE TITLE
Using setRules to repopulate stored configuration doesn't work with selectize-handled elements

### ISSUE THREAD

**Issue by jpstacey** [mistic100/jQuery-QueryBuilder#164]
We're saving and then re-loading rules with getRules / setRules and we can't seem to get values to populate, where the selectize plugin is in charge of loading/saving lists of values dynamically over AJAX. 

The rule type (e.g. "Country" or "MP Party") is being repopulated on setRules, as is the operator (e.g. "in" or "not in"). We just don't see any selected values repopulating.

One thing I did notice from Chrome debugging is that `model.value` is just not being set to `item.value` here:

https://github.com/mistic100/jQuery-QueryBuilder/blob/3016e72b85fa5cf7d5d72c8328ccf3778c02ad29/src/public.js#L248

I'm not a Javascript expert, but is there some clever getter/setter thing happening that's validating each option and rejecting it as not in the (not yet fetched via AJAX) list?

**Comment by mistic100** [comment]
Use `valueSetter` filter function when using external plugins.

**Comment by jpstacey** [comment]
Smashing, thanks: that seems to be working great. Our `valueSetter` contains code a bit like this, in case anyone else has the same issue:

```javascript
var $input = $value.find('[name='+ name +']');
// Add options for each of the incoming values.
$.each(value[i], function(j, el) {
    $input[0].selectize.addOption({'id': el, 'name': el});
});
// Set the value to be the array of incoming values.
$input[0].selectize.setValue(value[i]);
// Fire the change event.
$input.trigger('change');
```

It's sort of like a customized version on one of the `switch()` cases in `getRuleValue()`.

Thanks again for the quick response.
