### ISSUE TITLE
How to give confirmation prompt on click of delete rule or group ?

### ISSUE THREAD

**Issue by ved54321** [mistic100/jQuery-QueryBuilder#165]
how to provide confirmation to user before he is removing the rule or group

**Comment by mistic100** [comment]
Use `beforeDeleteGroup` and `beforeDeleteRule` events http://mistic100.github.io/jQuery-QueryBuilder/dev/events.html

```js
$('#builder').on('beforeDeleteRule.queryBuilder beforeDeleteGroup.queryBuilder', function(e) {
  if (!confirmation('Are you sure ?')) {
    e.preventDefault();
  }
});
```

**Comment by ved54321** [comment]
thanks :+1:

**Comment by moyarich** [comment]
looks like there is an error in the code it should be:

`$('#builder').on('beforeDeleteRule.queryBuilder beforeDeleteGroup.queryBuilder',
  function(e) {
    if (!confirm('Are you sure ?')) {
      e.preventDefault();
    }
  });`

**Comment by moyarich** [comment]
looks like there is an error in the code, **confirmation** should be change to **confirm**  it should be:
```javascript
$('#builder').on('beforeDeleteRule.queryBuilder beforeDeleteGroup.queryBuilder',
  function(e) {
    if (!confirm('Are you sure ?')) {
      e.preventDefault();
    }
  });
`

**Comment by mistic100** [comment]
indeed
