### ISSUE TITLE
[Feature Request] Default filter names

### ISSUE THREAD

**Issue by mwoynarski** [mistic100/jQuery-QueryBuilder#166]
I'm using this library to build a CSV to MySQL mapping system, and it would be a huge boon if it were possible to define a default filter name, so that every time a new filter is added to a query, it could be given a value by default.

I don't currently see any functionality for this, so I'm now looking at accomplishing it through event handlers.

**Comment by mistic100** [comment]
Don't understand what you mean.
You use "filter name" and "a value by default" to designate the same thing ?

there is a `default_value` filter option http://mistic100.github.io/jQuery-QueryBuilder/#filters

**Comment by mwoynarski** [comment]
You're right, I used "Filter" and "value" interchangeably up there, let me try to clarify:

When you initialize a query builder, you define a list of filters:

>filters: [{
    id: 'name',
    label: 'Name',
    type: 'string'
  }, {
    id: 'address',
    label: 'Address',
    type: 'string'
  },

And when you click Add Rule, you select which filter you want to apply from the dropdown. By default, "------" is selected;  What I'm hoping to achieve is setting a default filter so that when I click New Rule, "Name" could automatically be selected by default.

**Comment by mistic100** [comment]
```js
$('#builder').on('afterCreateRuleFilters.queryBuilder', function(e, rule) {
  rule.filter = $('#builder').queryBuilder('getFilterById', 'name');
});
```

not tested, might have side effects if you use `setRules` somewhere ?

**Comment by mwoynarski** [comment]
That was *exactly* what I needed; you probably just saved me an hour of bumbling to figure out how to accomplish that.  Thanks a ton!

**Comment by mistic100** [comment]
[add "default_filter" option](https://github.com/mistic100/jQuery-QueryBuilder/commit/31f6a2ddd26eb5dd08cf91b6b1704a49ccec91dc)
