### ISSUE TITLE
Link to another column

### ISSUE THREAD

**Issue by groseb** [mistic100/jQuery-QueryBuilder#167]
Is there a way to generate something like 
WHERE table1.columnA = tableX.columnN ?
So not having a static value but a link to another column, chosen using a select where only columns with the same type would be shown for exemple.

I couldn't find any issue or discussion about that feature.

**Comment by mistic100** [comment]
filtering by type is way too limited

for selectbox you can simply build yourself a utility which will provide the right items to the `values` option of a `select` filter

for the SQL generation, you need to modify [this line](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/plugins/sql-support/plugin.js#L275) depending on a particular critera (don't know which one)

of course your requirement is not compatible with prepared statements, without a lot of reworking in the SQL generator

**Comment by groseb** [comment]
I'm not using the SQL generation at all actually, the back-end of my app takes care of that part, I just use the UI.
I talked about the type because I'd like to keep the consistency of the filters' operators (ex: col1 (int) > col2 (string) is a nonsense)

If you didn't think about that feature I'll try to develop something to make it work !
Thank you anyway

**Comment by mistic100** [comment]
I meant that someone would like to use only a subset of the compatible filters.
