### ISSUE TITLE
Update query builder filters 

### ISSUE THREAD

**Issue by angelinacc** [mistic100/jQuery-QueryBuilder#168]
Is it possible to update filters after already done so? How can I go about doing that?

If not, is it possible to remove query builder (not same as reset) from element so that I can set a new filter to it? 

Reason being is that my query builder filters are dependent on another value that will be selected by a user.

**Comment by mistic100** [comment]
Doc, doc, doc

Update filters : http://querybuilder.js.org/plugins.html#change-filters  
Destroy: http://querybuilder.js.org/index.html#methods

**Comment by angelinacc** [comment]
My apology but this is perfect. Thanks so much.

**Comment by giapfpt** [comment]
####ghk

**Comment by 77vetter1** [comment]
I have a MVC site and am using queryBuilder to display rows and then in the rows displayed there is an Edit button where the user can Edit that specific row, which takes them to a new page. Once they are done editing the row and click save they are brought back to the queryBuilder page. 

How do I repopulate the queryBuilder object with the users previous filters. I tried using the jqueryQueryBuilder.queryBuilder('setFilters', true, {} )  but it gives me the following error:
jQuery.Deferred exception: e.forEach is not a function TypeError: e.forEach is not a function
    at c.checkFilters 

I have retained the filterRules as a json object and pass it to the edit page and back to the queryBuilder page and it all valid JSON so not sure what I am missing?

**Comment by mistic100** [comment]
Use "setRules" not "setFilters"

And please to not dig 4 years old closed issues.

**Comment by 77vetter1** [comment]
Thanks so much it works perfectly!!!

Bob Van Roekel, MSIS
Senior Programmer/Analyst, Application Engineering Center of Excellence
Syneos Health
Mobile  +1 605 215 1997
robert.vanroekel@syneoshealth.com<mailto:robert.vanroekel@syneoshealth.com>
