### ISSUE TITLE
How can we use Querybuilder methods without attaching to DOM?

### ISSUE THREAD

**Issue by metanav** [mistic100/jQuery-QueryBuilder#169]
I want to convert SQL to Querybuilder Json rules without any UI. Is there any way to initialise it with options without attaching to DOM?

**Comment by mistic100** [comment]
you could probably use detached DOM element

```js
var $element = $('<div>');
$('<div>').queryBuilder();
```

The API is not conceived to be used in a static way at all, because of config used in the whole instance.

---

Another possible solution (not tested):

```js
var builder = new $.fn.queryBuilder.constructor($({}), options);

builder.someMethod(); // not via .queryBuilder()
```

This directly apply the QueryBuilder constructor with a dummy jQuery container.

**Comment by metanav** [comment]
@mistic100 , thanks for your timely help!  Both solutions worked. Actually, I was trying to use it in 3-ways, in the first scenario user interacts with the UI (in an AngularJS ui-bootstrap modal) to build query and return back in SQL. Another scenario is user can write SQL directly and the UI should render it and 3rd one is user can write SQL without interacting with UI and get back the rules. Although, integration with AngularJS was not difficult but l would like to see an AngularJS port of this awesome library, some day.

**Comment by mistic100** [comment]
#141
