### ISSUE TITLE
Destroying and recreating builder with sorting plugin creates extra droppable zone

### ISSUE THREAD

**Issue by Hilgo** [mistic100/jQuery-QueryBuilder#170]
Hi, i have been using this plugin in a way that the user can select a table to generate the filters in the query builder. To do it, I use the method ```$('#builder').queryBuilder('destroy');``` and then, recreate the builder with different options. This works really well, but i found  this behaviour when using the sort plugin. Everytime that the builder is destroyed and then recreated and the user drags a rule or a group rule, there's an extra droppable zone. It doesn't impact on the rules or anything.

I could recreate this in the demo page of the plugin. Here's an screenshot:
![captura de tela 10](https://cloud.githubusercontent.com/assets/7366331/9939411/70b56ce8-5d40-11e5-8c8e-8b39e421677e.png)

What i did was just destroy it and recreate with the same options defined in the page. 
Just for the record: I tested in Chrome, in Windows 8.1
Anyway, great plugin!

**Comment by mistic100** [comment]
Thank you.
BTW you can use http://querybuilder.js.org/plugins.html#change-filters
