### ISSUE TITLE
No event triggered when setting rules 

### ISSUE THREAD

**Issue by moux2003** [mistic100/jQuery-QueryBuilder#171]
I have a problem when setting the builder state on document ready using setRules method . I have nothing triggered when the inputs are created in their previous state (I use it on a form page).  Is it a real issue or does it work as expected ?

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/CONTRIBUTING.md

**Comment by moux2003** [comment]
I initialized the plugin this way:
```javascript
$('#builder').queryBuilder({
    filters: ... (filters definition), 
    operators: [{type: 'table', nb_inputs: 2, multiple: false, apply_to: ['string']}],
    allow_groups: 1,
    rules: ... (json with rules empty when reaching page the first time)
});

$('#builder').on('afterCreateRuleInput.queryBuilder', function(e, rule) {
    if('table' === rule.operator.type && rule.filter.data) {
        // Doing some work with rule.filter.data on the page
    }
});
```

Thing is when the field *rules* is not empty the filters and rules selected are initialized correctly but the event 'afterCreateRuleInput.queryBuilder' is not triggered nor any other event

**Comment by mistic100** [comment]
Because the listeners are added after init.

Either add the listeners before init the plugin, or use the classic "setRules" method after adding the listeners.

**Comment by moux2003** [comment]
Ok great, thanks for the help.
