### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by metanav** [mistic100/jQuery-QueryBuilder#172]
I am not seeing any specific class of error in catch block. It would be really useful to throw error of specific custom type, like ParseError, OperatorMissingError, UndefinedFIlterError etc.
```
try {
 // do something
} catch(err) {
    console.log(err.name);
    // always prints 'Error'
}
```
Also, is there any way to override error messages?

**Comment by mistic100** [comment]
IMHO you must never get this errors in production, it shows a bad configuration while developing.
Thus I think `err.message` is enough

**Comment by metanav** [comment]
My application uses a search box where user can enter SQL (where clause) manually, so I needed to show validation message if user mistype some filter names. Anyways I think for now I would  show something generic if validation fails. Does $.error provide message overriding?

**Comment by mistic100** [comment]
https://api.jquery.com/jQuery.error

---

Ok I see, you talk about user input in the SQL plugin
