### ISSUE TITLE
values after setting new rules

### ISSUE THREAD

**Issue by yavuzpeksen** [mistic100/jQuery-QueryBuilder#177]
I receive list of values from database after a filter is selected by user so I add a rule to the querybuilder by applying 'setRules' method with other existing rules. But after this, all rule values previously selected by user are lost and the first values of the corresponding lists are displayed. How can I prevent this happening? or Am I doing something wrong by setting rules? Any help is appreciated.  

Update: Additionally, I use "setRules" inside afterCreateRuleInput.queryBuilder changer function.

**Comment by yavuzpeksen** [comment]
Additionally, I use "setRules" inside afterCreateRuleInput.queryBuilder changer function.

**Comment by mistic100** [comment]
Can you be explicit on want you want to do ?
As the docs says `setRules` sets ALL the rules, after clearing up everything, it's obviously not what you want to do.

**Comment by yavuzpeksen** [comment]
Ok, I want to list all values dynamically when user selects the filter label. I can do this but after pressing add rule and then selecting a filter, values which have been selected by user in previous rules are reset and I loose their values.

I can post some parts of my code if you want.

**Comment by mistic100** [comment]
> I want to list all select box values dynamically

Which select boxes ?

Of course I want code, it's written on CONTRIBUTING.md

**Comment by yavuzpeksen** [comment]
$('#builder-basic').on('afterCreateRuleInput.queryBuilder', function(e, rule) {
	
	  var found = false;
	  
  for(var a=0; a<ruleList.length; a++){
	  if(rule.id == ruleList[a]){
		found = true;
		  
		if(rule.__.filter.field == filterList[a]){
		//Buraya giriyorsa rule'da value degistirildi..
			for(var i=0; i<jsonList.length; i++){
				if(filterList[a] == jsonList[i].id){
					if(e.value){
						curValues[a] = jsonList[i].values[e.value];						
						tmpRules[a].value = jsonList[i].values[e.value];
					}
					break;
					
				}
			}
			
		}else{
			var index = 0;
			filterList[a] = rule.__.filter.field;
			//Buraya giriyorsa filter'da id degistirildi. Sorgu gonderip listedeki degerleri alacagiz. Var olan degeri 0 yapacagiz..
			for(var i=0; i<jsonList.length; i++){
			  if(rule.__.filter.field == jsonList[i].id){
				  
				  //jsonList'in hangi index'inde oldugunu bulduk. Ona ait filter'daki degerleri degistirecegiz.
				  
				  jsonList[i].input = 'select';
				  $.ajax({
					  url:"query-builder/getColumnValues.jsp",
					  cache:false,
					  async:false,
					  type:"GET",
					  crossDomain:false,
					  data:{
						  Table:tableName,
						  Column:rule.__.filter.field
						  },
					  dataType:"text",
					  success:function(t){
						//$('#sqlQuery').val(t.trim());
						var result = JSON.parse(t.trim());
						
						flag = true;
						for(var j=0; j<result.List.length; j++){							  
						  jsonList[i].values[j] = result.List[j].value;
						}
						//jsonList[i].values = result;
					  },
					  error:function(){}});
			  
				  index = i;
				  break;
			  }	  
			}
			var newRule = {
				id: jsonList[index].id,
				operator: 'equal',
				value: jsonList[index].values[0]
			  };
			curValues[a] = jsonList[index].values[0];
			tmpRules[a] = newRule;
			  
			var rules_basic = {
			  condition: 'AND',
			  rules: tmpRules
			};
			$('#builder-basic').queryBuilder('setFilters', true,jsonList);
			$('#builder-basic').queryBuilder('setRules', rules_basic);
			
		}

	  }
  }
  if(found != true){
	ruleList.push(rule.id);
	filterList.push(rule.__.filter.field);
	var flag = false;
	var index = 0;
	for(var i=0; i<jsonList.length; i++){
	  if(rule.__.filter.field == jsonList[i].id){
		  
		  //jsonList'in hangi index'inde oldugunu bulduk. Ona ait filter'daki degerleri degistirecegiz.
		  
		  jsonList[i].input = 'select';
		  $.ajax({
			  url:"query-builder/getColumnValues.jsp",
			  cache:false,
			  async:false,
			  type:"GET",
			  crossDomain:false,
			  data:{
				  Table:tableName,
				  Column:rule.__.filter.field
				  },
			  dataType:"text",
			  success:function(t){
				//$('#sqlQuery').val(t.trim());
				var result = JSON.parse(t.trim());
				
				flag = true;
				for(var j=0; j<result.List.length; j++){							  
				  jsonList[i].values[j] = result.List[j].value;
				}
				//jsonList[i].values = result;
			  },
			  error:function(){}});
	  
		  index = i;
		  break;
	  }
	  
	}

	var newRule = {
		id: jsonList[index].id,
		operator: 'equal',
		value: jsonList[index].values[0]
	  };
	  curValues.push(jsonList[index].values[0]);
	tmpRules.push(newRule);
	  
	var rules_basic = {
	  condition: 'AND',
	  rules: tmpRules
	};
	$('#builder-basic').queryBuilder('setFilters', true,jsonList);
	$('#builder-basic').queryBuilder('setRules', rules_basic); //Bu kisim ayni yeri 2 kere tetiklemesine sebep oluyor..
	
  
  }
	
});

**Comment by yavuzpeksen** [comment]
ruleList is the array of existing rules, filterList is the array of selected filters


```javascript
$('#builder-basic').on('afterCreateRuleInput.queryBuilder', function(e, rule) {
	
  var found = false;
	  
  for(var a=0; a<ruleList.length; a++){
	  if(rule.id == ruleList[a]){
		found = true;
		  
		//TODO

	  }
  }
  if(found != true){
	ruleList.push(rule.id);
	var flag = false;
	var index = 0;
	for(var i=0; i<filterList.length; i++){
	  if(rule.__.filter.field == filterList[i].id){
		  
		  //filterList'in hangi index'inde oldugunu bulduk. Ona ait filter'daki degerleri degistirecegiz.
		  
		  filterList[i].input = 'select';
		  $.ajax({
			  url:"query-builder/getColumnValues.jsp",
			  cache:false,
			  async:false,
			  type:"GET",
			  crossDomain:false,
			  data:{
				  Table:tableName,
				  Column:rule.__.filter.field
				  },
			  dataType:"text",
			  success:function(t){
				//$('#sqlQuery').val(t.trim());
				var result = JSON.parse(t.trim());
				
				flag = true;
				for(var j=0; j<result.List.length; j++){							  
				  filterList[i].values[j] = result.List[j].value;
				}
				//filterList[i].values = result;
			  },
			  error:function(){}});
	  
		  index = i;
		  break;
	  }
	  
	}

	var newRule = {
		id: filterList[index].id,
		operator: 'equal',
		value: filterList[index].values[0]
	  };
	allRules.push(newRule);
	  
	var rules_basic = {
	  condition: 'AND',
	  rules: allRules
	};
	$('#builder-basic').queryBuilder('setFilters', true,filterList);
	$('#builder-basic').queryBuilder('setRules', rules_basic); //Bu kisim ayni yeri 2 kere tetiklemesine sebep oluyor..
	
  
  }
	
});
```
