### ISSUE TITLE
Add filer.listen option

### ISSUE THREAD

**Issue by mistic100** [mistic100/jQuery-QueryBuilder#178]
When using external plugins on values is often appear that they don't fire the standard "change" event on the input, thus QueryBuilder model is not updated and validation fails.

Current solution is to manually bridge events see #176

A nicer solution would be to tell QueryBuilder to listen to "change" and a configurable list of events.
For Bootstrap DateTimePicker it would be `listen: 'dp.change'`

**Comment by itajackass** [comment]
Hi, I tried you suggest for datetimepicker, but no luck:

{
		id: 'DataScadenza',
		label: 'Scadenza',
		type: 'datetime',
		listen: 'dp.change',  <------------------- added
		validation: {
		  format: 'DD/MM/YYYY'
		},
		plugin: 'datetimepicker',
		plugin_config: {
		  format: 'DD/MM/YYYY',
		  locale: "it"
		}
	  }
