### ISSUE TITLE
Read-only rule-group condition "AND"/ "OR" ?

### ISSUE THREAD

**Issue by sujith3g** [mistic100/jQuery-QueryBuilder#180]
I'm using this lib in one of my tool, and I want to add a read-only condition to the query-builder using `setRule()`, I have used the `readonly : true` for enforcing that condition/rule. 

Now I want that read-only rule/condition to be always `AND`ed with other rules/conditions created by user. So Do we have an option to make the rule condition ( `condition : "AND"`) read-only ?,  and the user won't be able to change it from `AND` to `OR`.

**Comment by mistic100** [comment]
There isn't. I will added it.

Currently you can still hide the condition buttons in CSS and/or force the condition afterwards
