### ISSUE TITLE
limit number of rules

### ISSUE THREAD

**Issue by recanti** [mistic100/jQuery-QueryBuilder#181]
Is there a way to limit the number of rules that a person can add to the queryBuilder? I see that there's an option to disable groups which gets rid of the "add group" button, but is there a similar option for rules?

**Comment by mistic100** [comment]
There is not.
You can use the `beforeAddRule.queryBuilder` and `beforeDeleteRule.queryBuilder` events to track how many rules has been added and use `e.preventDefault()` when needed.
http://querybuilder.js.org/dev/events.html

**Comment by recanti** [comment]
Thanks for getting back to me so quickly! It sounds like this method would leave the "add rule" button but prevent its behavior. I'd rather get rid of the button entirely so as not to confuse the User. Do you think it might be better to make a template without the button?

**Comment by mistic100** [comment]
Once a group is created, it's template is not rebuilded anymore, so you won't be able to toggle the "add rule" button.

Using the events you can toggle a CSS class on the builder and add :
```css
.builder-with-ten-rule [data-add=rule] {
  display:none;
}
```

**Comment by recanti** [comment]
That could work. Thanks for all your help!

**Comment by amirgee007** [comment]
> There is not.
> You can use the `beforeAddRule.queryBuilder` and `afterDeleteRule.queryBuilder` events to track how many rules has been added and use `e.preventDefault()` when needed.
> http://querybuilder.js.org/dev/events.html#triggers

Both working on add/delete rule but the add button works for the group but delete not.

whenever any group deleted the delete method not triggered...!
