### ISSUE TITLE
Create builder from query

### ISSUE THREAD

**Issue by karolispx** [mistic100/jQuery-QueryBuilder#186]
Hi!

Is there a way to reverse the functionality and have the ability to provide this plugin with a query and have it build the model for you (with correct groups etc), instead of the other way around.

How complicated would it be to incorporate such functionality? 

Thanks!

**Comment by mistic100** [comment]
Hi

could you please read the doc ?

from custom JSON format : `setRules` http://querybuilder.js.org/#methods  
from SQL : `setRulesFromSQL` http://querybuilder.js.org/plugins.html#sql-support  
from MongoDB : `setRulesFromMongo` http://querybuilder.js.org/plugins.html#mongodb-support
