### ISSUE TITLE
How to use ajax for get values?

### ISSUE THREAD

**Issue by velykov** [mistic100/jQuery-QueryBuilder#188]
How can I use a ajax to get values?

I use angular and code like this:
$scope.types= [];

    SomeService.getTypes().then(function(resp) {
        var obj = null;
        _.each(resp.data, function(e, i) {
            obj = {};
            obj[e.id] = e.typeName;
            $scope.types.push(obj);
        });
    });

    $scope.filters = [
        {
            id: 'TYPE_ID',
            label: 'Some label',
            type: 'string',
            input: 'select',
            values: $scope.types, // here is empty array, because ajax is incomplete here
            multiple: true
        },
        ...// many many many filters
    ];
    $scope.loadFilter = function() {
        $FILTER.queryBuilder({
            filters: $scope.filters
        });
    };

I don't want to put loadFilter into ajax readyFunction, because I got many filters, like this (types).

**Comment by velykov** [comment]
I found answer, for anybody, who need an example, use:
    $FILTER.queryBuilder('getFilterById', 'your_filter_id').values = $scope.types;

**Comment by mistic100** [comment]
yep, that's the solution

beware that if a rule is already using the filter, it will not be refreshed, no immediate solution

**Comment by velykov** [comment]
I think some-thing like datasource have must have a place to be in box, is't it?

**Comment by mistic100** [comment]
I don't understand what you mean.

QueryBuilder is build to be extendable but will not include support of async data.

That's what I use Selectize for selectboxes with ajax values.

**Comment by velykov** [comment]
I mean that some-thing like this:

  ....,
  dataSource: {
    url: 'http://get-values-url',
    method: 'get', //optional default get
    idField: 'someObjectFieldId', //optional if we need use values like {'id':'value'}
    valueField: 'someObjectFieldValueField' //optional if we need use values like {'id':'value'}
  }
So if use put only url dataSource will work like a array getter, like ['a', 'b', ..., 'd']

**Comment by nenya1840** [comment]
Is there a way to refresh the rule that is already using the filter?

**Comment by velykov** [comment]
You can try to do $filter.queryBuilder('reset');
