### ISSUE TITLE
Selectize problem when settting a rule

### ISSUE THREAD

**Issue by esatemre** [mistic100/jQuery-QueryBuilder#189]
Selectize dropdown is not filled when i am using setRules function to choose default filter.
I think multichoose selectize is not supported by QueryBuilder.
But i am not sure it is an issue or i missed some configs.

Selectize Dropdown Config:
```
plugin_config: {
valueField: 'id',
labelField: 'label',
searchField: 'label',
sortField: 'label',
create: true,
maxItems: 10,
plugins: ['remove_button'],
onInitialize: function() {
var that = this;
data.forEach(function(item) { that.addOption(item); });
}
}

var rules_plugins = {
            condition: "AND",
            rules: [
              {
                  id: "Key",
                  field: "Key",
                  type: "string",
                  input: "text",
                  operator: "in",
                  value: "Key1,Key2,Key3"
              }
            ]
        };
$('#queryBuilder').queryBuilder('setRules', rules_plugins);
```

**Comment by mistic100** [comment]
That something explained in the source of the Widgets example http://querybuilder.js.org/assets/demo-widgets.js
You need to define `valueSetter` to properly wire the plugin with the builder

**Comment by esatemre** [comment]
Exactly, Thanks.
I just need to fire addItem function for multi-choice selectize 

My valueSetter is like this :

                            valueSetter: function (rule, value) {
                                if (rule.operator.nb_inputs > 0) {
                                    var val = value.split(',');
                                    var select = rule.$el.find('.rule-value-container [name$=_0]').selectize()[0].selectize;
                                    val.forEach(function (item) {
                                        select.addItem(item);
                                    });
                                }
                            }
