### ISSUE TITLE
Jquery UI autocomplete

### ISSUE THREAD

**Issue by smm130130** [mistic100/jQuery-QueryBuilder#190]
Can we have Jquery UI autocomplete instead of dropdown for selecting coulmn name?

**Comment by mistic100** [comment]
You can try to adapt the Bootstrap Selectpicker plugin which replace the classic dropdowns by Bootstrap ones
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/plugins/bt-selectpicker/plugin.js

If I may, you should drop jQuery UI and switch to more serious and modern UI components.

**Comment by sunilmunavalli** [comment]
There are some 250 column name, which comes from Ajax request. I do not want wish to display all in drop down. I want to filter column names when user types just like Jquery UI autocomplete. Is that possible?

**Comment by mistic100** [comment]
exactly what I said up there, adapt the plugin to use autocomplete

**Comment by sunilmunavalli** [comment]
QueryBuilder.define('select-autocomplete', function(options) {
    if (!$.fn.Selectize || !$.fn.Selectize.Constructor) {
        Utils.error('Selectize is required to use "select-autocomplete" plugin.');
    }

    // init selectpicker
    this.on('afterCreateRuleFilters', function(e, rule) {
        rule.$el.find(Selectors.rule_filter).removeClass('form-control').Selectize(options);
    });
}, {
    container: 'body',
    style: 'btn-inverse btn-xs',
    width: 'auto',
    showIcon: false
});


I have added all required dependency. I Still get the error 'Selectize is required to use "select-autocomplete" plugin'.
 Can you please help.?

**Comment by mistic100** [comment]
How would I know ? seriously ?
You don't even tell what plugin you use

Because if it's https://brianreavis.github.io/selectize.js/ then it's `selectize`, not `Selectize`

**Comment by smm130130** [comment]
Yes i am using https://brianreavis.github.io/selectize.js/ plugin. Sorry i did not mention. Now i have changed it to selectize. Is there any other steps to follow because i still the same error.
