### ISSUE TITLE
Syntax error, unrecognized expression: <select class="form-control"...

### ISSUE THREAD

**Issue by rameshgorantla** [mistic100/jQuery-QueryBuilder#191]
I'm getting ' Syntax error, unrecognized expression: <select class="form-control" ' error while using the plugin. I'm using jQuery1.9.1 and angular 1.x

**Comment by mistic100** [comment]
Example ?

**Comment by rameshgorantla** [comment]
i'm getting the error while loading the page itself.
While creating the DOM its throwing the error, but when i used jQuery 1.10.0 its working properlyi'm getting the error while loading the page itself.
While creating the DOM its throwing the error, but when i used jQuery 1.10.0 its working properly

**Comment by mistic100** [comment]
If you don't provide an example I can't help you, I do not have enough time to set it up myself.

**Comment by rameshgorantla** [comment]
I fixed that issue. The issue is because of the jQuery qhich i'm using, I have upgraded the jQuery and its working now.
