### ISSUE TITLE
Custom input (Question)

### ISSUE THREAD

**Issue by rhythmicdevil** [mistic100/jQuery-QueryBuilder#193]
Hi,
I was hoping you could direct me to the best way create a custom input for the Query Builder. I have a case where I need to have 4 text inputs for a particular filter. 

Currently on the server I generate a JSON object that represents the filters. I embed it in the page and load it into the queryBuilder. It looks something like this:
```javascript
[
    {
        "id": "ontT1Port",
        "label": "ONT T1 Port",
        "type": "string",
        "input": "text",
        "operators": [
            "equal",
            "not_equal",
            "begins_with",
            "contains",
            "not_contains"
        ]
    },
    {
        "id": "wireCenterNode",
        "label": "Wire Center Node",
        "type": "string",
        "input": "t1endpoint",
        "operators": [
            "equal",
            "not_equal",
            "begins_with",
            "contains",
            "not_contains"
        ]
    },
    {
        "id": "remoteNode",
        "label": "Remote Node",
        "type": "string",
        "input": "t1endpoint",
        "operators": [
            "equal",
            "not_equal",
            "begins_with",
            "contains",
            "not_contains"
        ]
    }
]
```

My initial thought on how to create the custom input set was to pre-process the list of filters. When I find one with an input of "t1endpoint" I can use the function(Rule, InputName) to create the input set.  That does not exactly do it though I think its really designed to create 1 input, not 4.

Is there a better for me to handle this?

Thanks

**Comment by rhythmicdevil** [comment]
It looks as templates would provide this, am I right?

**Comment by mistic100** [comment]
Yes you must set the `input` filter option as a function.
See the `coords` filter in http://querybuilder.js.org/assets/demo-widgets.js
