### ISSUE TITLE
Preserve rule value after change filter

### ISSUE THREAD

**Issue by havran** [mistic100/jQuery-QueryBuilder#194]
It is possible preserve value of rule after change filter? Or store them on filter change and then restore if filter set to same filter type? 

For example i have:

```
Filter (field name): title 
Operator: or
Value: quick brown fox
```
and i want preserve after filter change

```
Filter (field name): content 
Operator: or
Value: quick brown fox
```

Thanks for great tool. I use QB as builder for complex queries for Elasticsearch.

**Comment by mistic100** [comment]
This could get really complex when dealing whith filters which do not have the same type.

You can build a dictionnary of values by listening to change events on inputs and re-inject the value with the `afterCreateRuleInput.queryBuilder` builder event.

**Comment by havran** [comment]
Thank you. For now i only need deal with six filters with same type (string) then this work great (coffee script).

``` cofeescript
  previous_value = ''

  # Preset filter to 'post_both' after add new rule.
  #
  $(target).on('afterCreateRuleFilters.queryBuilder', (e, rule) ->
    # Store rule value from previous filter setting.
    rule.$el.find('.rule-filter-container select').on('change', (e) ->
      previous_value = rule.$el.find('.rule-value-container input.form-control').val()
    )

    $("##{rule.id} .rule-filter-container select").val('post_both_cs').trigger 'change'
  )

  # Restore value after filter change.
  #
  $(target).on('afterCreateRuleInput.queryBuilder', (e, rule) ->
    rule.$el.find('.rule-value-container input.form-control').val(previous_value)
  )
```
