### ISSUE TITLE
How to listen for any change?

### ISSUE THREAD

**Issue by liranviper** [mistic100/jQuery-QueryBuilder#195]
Hello,

I would like to listen for any kind of change which affects the output of the "getRules" method.

for example, when a rule is deleted, a value in existing rule is changed, condition in existing rule is changed, etc.

is there such option?
as far as i can see, i can onlu register for each change-type specifically (for example, when rule is deleted).

thanks

**Comment by mistic100** [comment]
Hi

do you known that `$.on` can listen to multiple events at once ? http://api.jquery.com/on/

```js
$(...).on('event1 event2 event3', ....);
```

**Comment by liranviper** [comment]
Hi, I didn't know that. thank you.
does it mean that i must do:
$(element).on('afterDeleteGroup.queryBuilder, afterAddRule, afterDeleteRule.queryBuilder, afterUpdateRuleValue.queryBuilder, afterUpdateRuleOperator.queryBuilder, afterUpdateGroupCondition.queryBuilder', function () { .. })

or is there an easier way?
if there is not, i would appreciate it if you can make sure i didn't miss any event

**Comment by mistic100** [comment]
No comma between events names (read the doc).

You are missing `afterUpdateRuleFilter.queryBuilder` and the `queryBuilder` namespace to `afterAddRule` (type in the doc)

**Comment by liranviper** [comment]
Thank you.
It would be nice if in the futrue you can add a general purpose event for any change, i'm sure it will be helpful not just for me.
btw,
I'm working on an Angular-Directive version of your plugin. i'll share it if you are interested when its done.

**Comment by mistic100** [comment]
#141

**Comment by liranviper** [comment]
are you sure about the quiryBuilder namespace to afterAddRule ? in the doc it looks like it does not have any namespace (http://querybuilder.js.org/dev/events.html)

**Comment by mistic100** [comment]
> **(typo in the doc)**
has the namespace is everywhere you can guess it's missing here
