### ISSUE TITLE
Slider Plugin with Between Operator

### ISSUE THREAD

**Issue by kashif461** [mistic100/jQuery-QueryBuilder#196]
Slider plugin in http://querybuilder.js.org/demo.html Widgets section is not working for between operator. When clicked on getRule it is displaying "Not a number" error.

Please let me know how I can make work  the slider with between operator.

**Comment by mistic100** [comment]
The problem is how I implemented the `valueGetter` and `valueSetter`
https://github.com/mistic100/jQuery-QueryBuilder/blob/gh-pages/assets/demo-widgets.js#L64-L69
it does not work when there are multiple inputs

I can't fix it right now
