### ISSUE TITLE
MongoDB Aggregation Plugin?

### ISSUE THREAD

**Issue by tahpot** [mistic100/jQuery-QueryBuilder#197]
Are there any plans to build a MongoDB aggregation plugin?

**Comment by mistic100** [comment]
Are there any plans you do a real feature request with details ?

**Comment by tahpot** [comment]
Sorry, missed your reply.

The MongoDB plugin is great for mongo filters, eg:

```
{
  "$and": [
    {
      "name": "dave"
    }
  ]
}
```

However, it would be great if there was a plugin that supported [mongo aggregations](https://docs.mongodb.org/manual/aggregation/).

For example, the query builder interface would generate the following mongo aggregation:

```
[
   { $group: { _id: "$gender", totalPeople: { $count: "$_id" } } },
   { $match: { totalPeople: { $gte: 10 } } }
]
```

This is similar to the following SQL:
```
SELECT gender, COUNT(_id) AS totalPeople
FROM people
GROUP BY gender
HAVING totalPeople >= 10
```

**Comment by mistic100** [comment]
My answer is the same as #114
This will not be part of QueryBuilder (at least for a loooong time)
Good luck
