### ISSUE TITLE
After reset query builder

### ISSUE THREAD

**Issue by monice** [mistic100/jQuery-QueryBuilder#198]
http://mistic100.github.io/jQuery-QueryBuilder/demo.html#Plugins
if I reset this builder,cannot select  name of this filters anymore. 
it 's over my head, when I exec reset,this all will empty and enable rule's selected.Even rule that set unique is true.
please help me! thankyou.

**Comment by mistic100** [comment]
Can you be more explicit ? I don't understand

**Comment by monice** [comment]
I mean when I click the"Reset" button in this Plugin,there is only "Category","in Stock" and "Price" in the drop-down list.I can't choose "Name" anymore.Is it because clicking "Reset" means turning everything back to what it's like in the very begining?

**Comment by monice** [comment]
I mean when I click the"Reset" button in the third picture,there is only "Category","in Stock" and "Price"  left in the drop-down list.I can't choose "Name" anymore.Is it because clicking "Reset" means turning everything back to what it's like in the very begining?

**Comment by mistic100** [comment]
I guess it's a bug with the Unique Filters plugin, but I can't reproduce it, after clicking "Reset", the filter "Name" is actually unlocked.

**Comment by monice** [comment]
So you mean if the Unique Filters plugin works normally without nothing wrong,I shoud be able to choose "Name" after clicking "Reset"?By the way,you said "reproduce",so you also invented the Unique Filters plugin?If this bug cann't be fixed,is there any another solution I can find to deal with this problem?Thank you again~

**Comment by mistic100** [comment]
If I can't reproduce how could I tell you how to fix it ? => I can't.

I don't have time to develop anything so I can't tell you when I will be able to investigate.

**Comment by monice** [comment]
I've solved the problem with adding "this.on('afterReset',this.updateDisabledFilters)" to update those filters that have been set disabled and in the "Reset" case all filters wil be set to "disabled=false".Thanks you anyway though you are too busy to have time.

**Comment by monice** [comment]
I've solved the problem with adding "this.on('afterReset',this.updateDisabledFilters)" to update those filters that have been set disabled and in the "Reset" case all filters wil be set to "disabled=false".Thanks you anyway though you are too busy to have time reading this reply.

**Comment by monice** [comment]
I've solved the problem with adding "this.on('afterReset',this.updateDisabledFilters)" to update those filters that have been set disabled and in the "Reset" case all filters wil be set to "disabled=false".Thanks you anyway though you may be too busy to have time reading this reply.
