### ISSUE TITLE
IE11 does not implement startsWith

### ISSUE THREAD

**Issue by scottelgie** [mistic100/jQuery-QueryBuilder#199]
IE11 throws an error here:

        if (!data.sql.toUpperCase().startsWith('SELECT')) {
            data.sql = 'SELECT * FROM table WHERE ' + data.sql;
        }

This can be fixed with adding this method to the String prototype.

if (!String.prototype.startsWith) {
    String.prototype.startsWith = function (searchString, position) {
        position = position || 0;
        return this.indexOf(searchString, position) === position;
    };
}

**Comment by mistic100** [comment]
As said here #3 I won't add any shims to QueryBuilder.
But I will update to use indexOf instead.

(please use markdown syntax for code blocs where creating issues)
