### ISSUE TITLE
Get all values from rules

### ISSUE THREAD

**Issue by metanav** [mistic100/jQuery-QueryBuilder#200]
How can we get all "value" key values  from the rule? One way I can think of to write a plugin to iterate all rule object to collect values. Just want to know if there is already some function available to get it?

**Comment by mistic100** [comment]
Can you be more explicit ?

**Comment by metanav** [comment]
I want to get all values as an array ["10.25", "2", "1"] from the "value" key of the rules below:
```
{
  "condition": "AND",
  "rules": [
    {
      "id": "price",
      "field": "price",
      "type": "double",
      "input": "text",
      "operator": "less",
      "value": "10.25"
    },
    {
      "condition": "OR",
      "rules": [
        {
          "id": "category",
          "field": "category",
          "type": "integer",
          "input": "select",
          "operator": "equal",
          "value": "2"
        },
        {
          "id": "category",
          "field": "category",
          "type": "integer",
          "input": "select",
          "operator": "equal",
          "value": "1"
        }
      ]
    }
  ]
}
```

**Comment by mistic100** [comment]
Ok, there is no such feature, because it doesn't make sense for QueryBuilder itself.
The `getRules` method was designed to provide a way for developers to easily transform the builder data into anything they need, so it's what you will have to do : recursively explore the rules object to extract values.

You don't necessary need a plugin for that.

**Comment by metanav** [comment]
Yes, I also think that recursion will do that. Thanks for your time.

**Comment by godofblack** [comment]
Hi @metanav 
May i get your recursive function or How it works ? becoz, this structure is difficult to fetch the values

Thanks in advance
