### ISSUE TITLE
WHERE IN (NOT)

### ISSUE THREAD

**Issue by michalpenka** [mistic100/jQuery-QueryBuilder#201]
Is it possible to build a query with WHERE IN/NOT IN clause?

**Comment by mistic100** [comment]
Did you look at the doc and the example ? There are "in" and "not in" operators for all data types but booleans.

**Comment by michalpenka** [comment]
Apologies, I mean in combination with inner select. Or any way to simulate intersect/except...

Thanks

**Comment by mistic100** [comment]
See #173
won't do

**Comment by michalpenka** [comment]
ok, thanks!
