### ISSUE TITLE
Getting "Uncaught ReferenceError: QueryBuilder is not defined" in console

### ISSUE THREAD

**Issue by dyetube** [mistic100/jQuery-QueryBuilder#202]
Querybuilder is working without problems so far but I keep getting this eror in the console.  Here's the JS files I am referencing: doT.js, doU.js, jQuery.extendext.min.js, query-builder.min.js, sqp_parser.js, browser.js, defaults.js, template.js.  Anyone know why I am getting this error?

**Comment by mistic100** [comment]
why are you referencing defaults.js and template.js ? 
These are source files, you don't need them.
The doc says to include the ONE minified file. period.

**Comment by dyetube** [comment]
Should I just include the querybuilder.standalone.min.js?  Does this include everything including the plugins?

**Comment by mistic100** [comment]
Isn't it what the docs says ?

Note : it does not contains SQL Parser, and browser.js is not from QueryBuilder

**Comment by dyetube** [comment]
I saw what standalone does and I already have doT.js and extendetx.js downloaded so I'll go that route.  Not getting an error with the defaults.js or template.js but removed the references to them anyway.  only with the sql-support plugin (plugin.js) do I get the error.  But don't I have to include that one in order to have the sql support?

**Comment by dyetube** [comment]
Ok.  So just needed to include the query-builder.min.js, doT.js and jQuery.extendext.min.js.  Nothing else and everything works and the error goes away.  Thanks!
