### ISSUE TITLE
Validation step 0.01 gives validation error on correct value 0.07

### ISSUE THREAD

**Issue by Mette1982** [mistic100/jQuery-QueryBuilder#204]
The validation code in the plugin gives an error if the validation step is set to 0.01 and the value entered by the user is 0.07.

The code below gives the incorrect validation error. 0.07/0.01 = 7.000000000000001 instead of 7.

```js
if (validation.step !== undefined && validation.step !== 'any') {
   var v = value[i]/validation.step;
   if (parseInt(v) != v) {
      result = ['number_wrong_step', validation.step];
      break;
    }
  }
  break;
}
```

**Comment by mistic100** [comment]
You can try yourself in any javascript console, 0.07/0.01 will gives 7.000000000000001
I don't really know what can be done, it would be a non-sense to truncate the result
Common fix for this is to use Number.toPrecision, but it's not suitable as the purpose of this code it to exactly test the division.

**Comment by mistic100** [comment]
The fact is the current code is not working at all.
Try
```js
for (var i=0; i<1; i+=0.01)
  console.log(i/0.01);
```
very few values are correct

I guess we can do
```js
var v = (value[i]/validation.step).toFixed(12);
```
it truncates just before the last few incorrect decimals

**Comment by Mette1982** [comment]
Hi,

Thx for the fast reply!
It's idd a javascript issue... If the division would be done correctly everything would be fine.
Not that I like it, but my fix would be the same.

**Comment by mistic100** [comment]
not specifically JS, just any language using double float precision

**Comment by Mette1982** [comment]
Idd ;-)

Is it possible to create another version with the fix?

**Comment by mistic100** [comment]
What does idd means ?

Not yet, I have several things to finish.

**Comment by Mette1982** [comment]
Idd means Indeed :-)
Thx for the good help!
