### ISSUE TITLE
Readonly State not parsed with .getRules()

### ISSUE THREAD

**Issue by lars-str** [mistic100/jQuery-QueryBuilder#205]
Hey,
I added to multiple rules the readonly state. But when I click on the getRules Button, there is no readonly state in that JSON object.

**Comment by mistic100** [comment]
TODO : export `flags` in addition to `data`https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/public.js#L164

**Comment by lars-str** [comment]
Thank you very much for you fast answer!
