### ISSUE TITLE
Any thoughts to publishing this to npm

### ISSUE THREAD

**Issue by mofftarkin** [mistic100/jQuery-QueryBuilder#206]

**Comment by mistic100** [comment]
Why ? It's a front-end library only, bower is fine.

**Comment by mofftarkin** [comment]
Not all of your users use bower, (case in point: me). You already have the package.json so it should be as simple as saying "npm publish". 

I appreciate it!

**Comment by mistic100** [comment]
Oh no it shouldn't be so simple. What about dependencies ? jQuery.extendext and doT.js are not on npm.

Also you can still provide the URL of the repository as npm dependency.

**Comment by mofftarkin** [comment]
dot.js is there but not jQuery.extendext. Nevermind then. 
Thanks for looking into it.
