### ISSUE TITLE
How to deal with nested filters

### ISSUE THREAD

**Issue by allenkiwi** [mistic100/jQuery-QueryBuilder#207]
I have my user case as we need to add filter as nested object, how could we do it with this querybuilder?

Give an example as:

ObjectA --|
                | object B ----|
                                     |   object C --- "C1"
                                                       --- "C2"
                                                       --- "C3"

Where in the filters array we need to pass a Json formatted string to have nested object, how could we get it to work with QueryBuilder? Could anyone please give an example?

Regards,

**Comment by mistic100** [comment]
=> optgroup http://querybuilder.js.org/#filters

**Comment by drleewarden** [comment]
hi  mistic100,
I am helping Allen with the problem but in this case it works for the first dropdown, is there a way to make the values option in the second drop down extend to have nested objects?

**Comment by allenkiwi** [comment]
I tried your suggested way to set up filters however I can only set up optgroup with 1 level down, 

  {id: 'A'},
  {id: 'B'},
  {id: 'C1', optgroup: 'C'},
  {id: 'D1', optgroup: 'C1'},
  {id: 'D2', optgroup: 'C1'},
  {id: 'D3', optgroup: 'C1'},
  {id: 'C2', optgroup: 'C'},
  {id: 'C3', optgroup: 'C'},

I expect to see D1, D2, D3 under C1 and C1 under C from the tree style display, How could I get it to work?

Regards,

**Comment by mistic100** [comment]
HTML spec does not allow nested optgroups, neither QueryBuilder.

The same mechanism could be done for the operator selectors, will think about it.
