### ISSUE TITLE
Long & float support

### ISSUE THREAD

**Issue by lengoyvaerts** [mistic100/jQuery-QueryBuilder#208]
As types in Elastic can also be long & float, I was wondering if it's possible to implement them.

**Comment by mistic100** [comment]
There is no ints and floats in JS, only longs (integer in QueryBuilder) and doubles.
It's your task to make aliases if needed.

**Comment by mistic100** [comment]
Well actually JS only has `Number`. QueryBuilder only has `integer` and `double` because it represent different behavior, aliases, if needed, will be done outside the builder.

**Comment by lengoyvaerts** [comment]
If I were to overwrite QueryBuilder.types, how would I do this? I've read the plugins section but I can't seem to find a way to get it done.

**Comment by mistic100** [comment]
```js
$.fn.queryBuilder.constructor.types.long = 'number';
$.fn.queryBuilder.constructor.types.float= 'number';
```

But you will be REQUIRED to define a custom validation callback because these types are not handled here https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/data.js#L118
