### ISSUE TITLE
Dynamic filters and rules

### ISSUE THREAD

**Issue by stanep** [mistic100/jQuery-QueryBuilder#210]
Hi, thanks for all hard work, one question I have, 
is it possible to build filters dynamically from the code (exp User will click somewhere on the page and 
I would like to add that item to be a filter) there is setRules but I don't see setFilters or (addFilter) method

**Comment by mistic100** [comment]
http://querybuilder.js.org/plugins.html#change-filters

**Comment by stanep** [comment]
thx

**Comment by mistic100** [comment]
Can you close ?
