### ISSUE TITLE
Run querybuilder with no filters selected

### ISSUE THREAD

**Issue by dyetube** [mistic100/jQuery-QueryBuilder#212]
I tried adding the allow_empty: true; and display_errors: false;  but for some reason when I press the go button nothing happens except the builder doesn't display an error, but it should give me thealert to let me know it's work and what the params are (in this case nothing).  Am I missing something?

**Comment by mistic100** [comment]
Your are missing an (live) example of your code. I am not god I can't know what you are doing.

**Comment by dyetube** [comment]
I got it figured out.  Sorry for the confusion.
