### ISSUE TITLE
filter condition in no split val

### ISSUE THREAD

**Issue by nOcTIlIoN** [mistic100/jQuery-QueryBuilder#217]
Hi Guys, 
Why when i set the filter "IN" its doesn't split automatically the value in the input box ? 
What is the "char separator" to divide the value ? 
Thanks a lot

**Comment by mistic100** [comment]
Hi

You must use `valueSetter` and `valueGetter` to transform the input value into an array, and inversement

**Comment by nOcTIlIoN** [comment]
Exactly as i throught...well thanks a lot :) bye

**Comment by mistic100** [comment]
Version 2.4.0 added `value_separator` option.

```js
$('#builder').queryBuilder({
  filters: [
    {
      id: 'name',
      type: 'string',
      value_separator: ','
    }
  ]
});
```
