### ISSUE TITLE
What is the syntax for setting default values for a BETWEEN statement

### ISSUE THREAD

**Issue by dyetube** [mistic100/jQuery-QueryBuilder#218]
I'm setting Default rules on page load like you do in the Import/Export demo when (someone clicks the "Set Rules From Sql" button): var sql_import_export = 'name LIKE "%Johnny%" AND (category = 2 OR in_stock = 1)';.  What is the syntax for applying a BETWEEN statement?

**Comment by mistic100** [comment]
it's SQL...

so `field BETWEEN val1 AND val2`

**Comment by dyetube** [comment]
Doesn't work for me:

var sql_import_export = 'number BETWEEN 12 AND 2550';

$('#builder-import_export').queryBuilder({
            display_errors: false,
            allow_empty: true,
            plugins: ['bt-tooltip-errors'],

            filters: [{
                id: 'number',
                label: 'SSN #',
                type: 'integer',
                operators: ['between']
            }]
        });

$('#builder-import_export').queryBuilder('setRulesFromSQL', sql_import_export);

This doesn't work.

**Comment by dyetube** [comment]
am I just missing something?

**Comment by mistic100** [comment]
I'm pretty sure you didn't read the doc about the requirements for SQL parsing
http://querybuilder.js.org/plugins.html#sql-support

**Comment by dyetube** [comment]
I was actually missing the <script src="sql-parser/browser/sql-parser.js"></script> file.  I thought I had included it but didn't.  Works like a charm now thanks!

**Comment by mistic100** [comment]
If I may: you just had to open the dev console a read the error saying "SQLParser is required to parse SQL queries. Get it here https://github.com/mistic100/sql-parser"

**Comment by dyetube** [comment]
What was weird was I was using: 'name LIKE "%Johnny%" AND (category = 2 OR in_stock = 1)'; to first test and was doing so without the sql parser script and it was working.  The only sql command I couldn't use was BETWEEN so never thought I was getting errors hence why I never pulled up the console.

**Comment by mistic100** [comment]
Can't tell you
