### ISSUE TITLE
elastic search option

### ISSUE THREAD

**Issue by Kallin** [mistic100/jQuery-QueryBuilder#22]
I noticed the support to export rules as SQL has recently been added. In a project of mine, I convert rules to ElasticSearch filters which maps extremely well. Would there be interest in having this included here?

**Comment by mistic100** [comment]
My policy is now to restrict integrated export/import plugins to mainstream ones, which mean (for now) only SQL and MongoDB.

You are free to publish a separated plugin and I'll be happy to reference it in the documentation.
