### ISSUE TITLE
Problem Custom Input

### ISSUE THREAD

**Issue by vahidallahvakily** [mistic100/jQuery-QueryBuilder#220]
Hi, thank you for wonderful querybuilder
I want to add a custom element for money Control , How can i do this?
I appreciate it if you provide me with an example

**Comment by mistic100** [comment]
Look at the source code of the Widgets demo http://querybuilder.js.org/demo.html#widgets for the "coord" filter

**Comment by vahidallahvakily** [comment]
Thank you very much,
I got it right by adding my custom plugin for jquery.
I wonder if it is possible to embed sorting Description for fields for example
Adding ASC/ Desc in addition to Filters to QueryBuilder?

**Comment by mistic100** [comment]
Almost everything is possible with builder plugins http://querybuilder.js.org/dev/plugins.html
You can create one that adds a new dropdown and alter the result of `getRules` method.

**Comment by vahidallahvakily** [comment]
Nice , if I got your idea correctly, I should add a field to json getRules for example sort:asc/desc

**Comment by mistic100** [comment]
There is much more than that ! You will have to alter the HTML of the builder, add event handlers, etc.

**Comment by vahidallahvakily** [comment]
Thank you very much, I'll try it,
I appreciate your help.

**Comment by Inbarasan16** [comment]
how can i add 4 field for example 

a not-equal b then c  

how can build this

**Comment by nayeemg** [comment]
Devexpress <dvx:ASPxQueryBuilder > controler is not loading in .ascx. Is it possible? if yes how, please provide me solution.
