### ISSUE TITLE
Operators equal and not_equal appear when multiple set to true

### ISSUE THREAD

**Issue by groseb** [mistic100/jQuery-QueryBuilder#224]
Operators equal and not_equal are defined in the source code as : 
```js
equal:            {type: 'equal',            nb_inputs: 1, multiple: false, apply_to: ['string', 'number', 'datetime', 'boolean']},
not_equal:        {type: 'not_equal',        nb_inputs: 1, multiple: false, apply_to: ['string', 'number', 'datetime', 'boolean']},
```

`multiple` being set to `false`, I guess this should not happen : 
![image](https://cloud.githubusercontent.com/assets/5783476/12319651/0356a2b8-baa4-11e5-8c3b-1ae7b5325659.png)

It produces an error when initializing the builder with the saved filter : 
![image](https://cloud.githubusercontent.com/assets/5783476/12319769/d7eeba06-baa4-11e5-9186-dccc2ebbf24b.png)

##### How to reproduce : 
On http://querybuilder.js.org/demo.html using the Basic example, open a developer console and type :
```js
var q = document.getElementById('builder-basic');
q.queryBuilder.filters[1].multiple = true;
```
Click the "Set rules" button and here it is.

**Comment by mistic100** [comment]
It's totally fine to display the operator, as the user can still select one item, if he selects more there is real functional error ("Operator equal cannot accept multiple values").

I tried what you say and I do not reproduce...

**Comment by groseb** [comment]
I did not understand the operator's multiple attribute that way.
I might be saving the result as an array when the filter is set with `multiple: true` even if only one value is selected.
I'll look into it, thanks for the quick answer.

**Comment by groseb** [comment]
Yes I was, just added a little check as I'm processing the data before saving it on an MySQL server and it's ok now
```php
if(is_array($rule['value'])) {
    if(count($rule['value']) == 1) {
        $value = $rule['value'][0];
    } else {
        $value = json_encode($rule['value']);
    }
} else {
    $value = $rule['value'];
}
```

Thank you again
