### ISSUE TITLE
Support for new query language

### ISSUE THREAD

**Issue by raunak** [mistic100/jQuery-QueryBuilder#225]
Is there a way to add support for additional query language, like ElasticSearch for example? In addition, how can I extend to additional operators in addition to AND/OR, like NOT.

For example, a user would select the AND group in the UI, and input the relevant fields, and the output would be a ElasticSearch query like AND(clause1, clause2, clause3, etc).

**Comment by mistic100** [comment]
1. Yes you can develop your own plugin, check this repo for Loopback for example https://github.com/fabien/jQuery-QueryBuilder-Loopback (not my code)

2. Read the doc http://querybuilder.js.org/#usage => conditions

**Comment by mistic100** [comment]
I forgot to update the doc but I got notified 3 months ago of an existing ES plugin https://github.com/piotch/jQuery-QueryBuilder-Elasticsearch

I suggest you check with the author for improvements if needed.
