### ISSUE TITLE
Adding additional UI elements to rules

### ISSUE THREAD

**Issue by Lastik** [mistic100/jQuery-QueryBuilder#226]
Hello.

How could I extend QueryBuilder with additional UI elements (e.g. via plugins).
I need to add combobox with aggregation function before rule and combobox with units selection after rule.

E.g. <b>avg</b> bandwidth >= 10 <b>mb</b>

selected aggregation function and units should be in object returned by queryBuilder('getRules') also.

Thanks!

**Comment by mistic100** [comment]
Hi

Did you read http://querybuilder.js.org/dev/plugins.html already ?

**Comment by Lastik** [comment]
In order to extend model with aggregationFunction (avg/min/max) i had to override
QueryBuilder.constructor.prototype.setRules
("model.filter = that.getFilterById(item.id);
 model.operator = that.getOperatorByType(item.operator);
 model.flags = that.parseRuleFlags(item);
 <b>model.aggregationFunction = item.aggregationFunction;</b>")

 and
QueryBuilder.constructor.prototype.getRules
("var rule = {
                    <b>aggregationFunction: model.aggregationFunction</b>,
                    id: model.filter.id,
                    field: model.filter.field,
                    type: model.filter.type,
                    input: model.filter.input,
                    operator: model.operator.type,
                    value: value
                };")

This caused code duplicate (I had to copy code of these methods and add my modification).

Is there any other way to add new fields to rule?

**Comment by mistic100** [comment]
(Editted your message with correct Markdown syntax)

Can't you use the `data` rule attribute ? It was designed for this kind of app specific data.

**Comment by Lastik** [comment]
Thx, data attribute covered my requirements.

**Comment by dynamicscrmbiz** [comment]
@Lastik I am planning to add a bunch of aggregate functions as well. Possible to share your prototype?

**Comment by Lastik** [comment]
@dynamicscrmbiz Yes, ofc.

But it is tightly bound to angular stuff and some business logic. Maybe this code could be somehow useful to you.

`QueryBuilder.define(‘[here goes plugin name]', function(options) {

    this.on('afterAddRule.queryBuilder', function(e, rule){
        var queryBuilderElt = e.builder.$el;

        var ruleElt = rule.$el;
	//next goes some manipulations with rule and ruleElt.
        //Also, we should save ref to html elements added to rule hierarchy to rule (for afterUdate… handler).
    });

    this.on('afterUpdateRuleValue.queryBuilder', function(e, rule){
	//next goes some manipulations with added html elements on rule update.
    });
}, [here goes default options]);
Also, afterUpdateRuleFilter method could be useful (e.g. if you want units list to depend from the applied filter (e.g. money have one list of acceptable units, speed other).
To enable custom plugins, you should modify your code for query builder creation.
queryBuilderElt.queryBuilder({
    plugins: {
        ‘[plugin name]': [plugin options]
    }, …}

The entire code of angular directive using this plugin is below. It contains no NDA secrets or rocket science, so I guess I can send it to you freely.
(function() {

    var QueryBuilder = $.fn.queryBuilder;

    QueryBuilder.regional['ru'] = $.extend(QueryBuilder.regional['ru'], {
        "add_rule": "",
        "add_group": "",
        "delete_rule": "",
        "delete_group": "",
        "conditions": {
            "AND": "и",
            "OR": "или"
        }
    });

    QueryBuilder.define('aggregation-func', function(options) {

        var firstAggrFunction = options.aggrFunctions.length > 0 ? options.aggrFunctions[0]: undefined;

        var defaultAggrFunction = firstAggrFunction;

        this.on('afterAddRule.queryBuilder', function(e, rule){
            var queryBuilderElt = e.builder.$el;

            var ruleElt = rule.$el;

            var aggrFuncSelectContainer = $('<div class="aggregation-function-container"></div>');

            var aggrFuncSelect = $('<select class="form-control"></select>');

            aggrFuncSelectContainer.append(aggrFuncSelect);

            for(var i = 0; i < options.aggrFunctions.length; i++) {
                var aggrFunc = options.aggrFunctions[i];
                aggrFuncSelect.append('<option value="' + aggrFunc + '">' + aggrFunc + '</option>');
            }

            ruleElt.find(".error-container").after(aggrFuncSelectContainer);

            rule.aggrFuncSelect = aggrFuncSelect;

            var getRuleAggrFunc = function(rule) {
                if (rule.data && rule.data.aggregationFunction) {
                    return rule.data.aggregationFunction;
                }
                else {
                    return null;
                }
            };

            var ruleAggrFunc = getRuleAggrFunc(rule);

            if(ruleAggrFunc == null){
                ruleAggrFunc = defaultAggrFunction;
            }

            var onAggrFuncSelectedViaSelectElt = function(selectedAggrFunc) {
                if (!rule.data) {
                    rule.data = {};
                }
                rule.data.aggregationFunction = selectedAggrFunc;
                queryBuilderElt.trigger("afterUpdateRuleAggregationFunction");
            };

            aggrFuncSelect.val(ruleAggrFunc);

            aggrFuncSelect.on('change', function (e) {
                onAggrFuncSelectedViaSelectElt(this.value);
            });

            onAggrFuncSelectedViaSelectElt(ruleAggrFunc);
        });

        this.on('afterUpdateRuleValue.queryBuilder', function(e, rule){
            var aggrFuncSelect = rule.aggrFuncSelect;
            var selectedAggregationFunction = aggrFuncSelect.val();
            var ruleAggregationFunction = rule.data ? rule.data.aggregationFunction: undefined;

            if (selectedAggregationFunction != ruleAggregationFunction) {
                aggrFuncSelect.val(ruleAggregationFunction);
            }
        });
    }, {
        aggrFunctions: []
    });

    QueryBuilder.define('units-for-filters', function(options) {

        this.on('afterUpdateRuleFilter.queryBuilder', function(e, rule){

            var oldUnitsSelect = rule.unitsSelect;

            if(oldUnitsSelect) {
                oldUnitsSelect.remove();
            }

            var queryBuilderElt = e.builder.$el;

            var ruleElt = rule.$el;

            var ruleFilter = rule.filter;

            var unitsForRuleFilterOptions = options.unitsForFiltersOptions[ruleFilter.id];

            var initialUnits = unitsForRuleFilterOptions.initialUnits;
            var acceptableUnitsList = unitsForRuleFilterOptions.acceptableUnitsList;

            var getRuleUnits = function(rule) {
                if (rule.data && rule.data.units) {
                    return rule.data.units;
                }
                else {
                    return null;
                }
            };

            var ruleUnits = getRuleUnits(rule);

            if(ruleUnits == null || $.inArray(ruleUnits, acceptableUnitsList) < 0) {
                ruleUnits = initialUnits;
            }

            var onUnitsSelected = function(selectedUnits) {
                if (!rule.data) {
                    rule.data = {};
                }
                rule.data.units = selectedUnits;
                queryBuilderElt.trigger("afterUpdateRuleUnits");
            };

            var acceptableUnitsListContainsSingleDimensionlessUnitsWithNoSymbol =
                acceptableUnitsList.length == 1 && acceptableUnitsList[0] == "";
            
            if(!acceptableUnitsListContainsSingleDimensionlessUnitsWithNoSymbol) {

                var unitsSelectContainer = $('<div class="units-container"></div>');

                var unitsSelect = $('<select class="form-control"></select>');

                unitsSelectContainer.append(unitsSelect);

                for (var i = 0; i < acceptableUnitsList.length; i++) {
                    var units = acceptableUnitsList[i];
                    unitsSelect.append('<option value="' + units + '">' + units + '</option>');
                }

                ruleElt.find(".rule-value-container").after(unitsSelectContainer);

                rule.unitsSelect = unitsSelect;

                unitsSelect.val(ruleUnits);

                unitsSelect.on('change', function (e) {
                    onUnitsSelected(this.value);
                });
            }

            onUnitsSelected(ruleUnits);
        });

        this.on('afterUpdateRuleValue.queryBuilder', function(e, rule){
            var unitsSelect = rule.unitsSelect;
            if(unitsSelect) {
                var selectedUnits = unitsSelect.val();
                var ruleUnits = rule.data ? rule.data.units : undefined;

                if (selectedUnits != ruleUnits) {
                    unitsSelect.val(ruleUnits);
                }
            }
        });
    }, {
        unitsForFiltersOptions: {}
    });

    angular.module(’[secret]').directive("[secret]", function (objectHelper, safeApply) {
        return {
            restrict: 'E',
            replace: true,
            require: 'ngModel',
            templateUrl: ‘[secret]',
            scope: {
                metrics: "=",
                aggregationFunctions: "="
            },
            controller: function($scope) {
                $scope.forms = {};
            },
            link: function (scope, element, attrs, ngModelCtrl) {

                scope.queryBuilderCreated = false;
                scope.queryBuilderRulesInternalUpdateInProcess = false;

                var stopWatchMetrics = scope.$watch('metrics', function(metrics) {
                    if (metrics != undefined) {
                        scope.createQueryBuilder(metrics);
                        stopWatchMetrics();
                    }
                });

                scope.buildFilters = function(metrics) {
                    return _.map(metrics, function (metric) {
                        return {
                            id: metric.id,
                            label: metric.name,
                            units: metric.units,
                            input: "text",
                            type: "double"
                        };
                    });
                };

                var queryBuilderElt = element.find(".builder");
                scope.queryBuilderElt = queryBuilderElt;

                scope.createQueryBuilder = function(metrics) {

                    var metricsById = _.fromPairs(_.map(metrics, function(metric) {
                        return [metric.id, metric]
                    }));

                    queryBuilderElt.queryBuilder({
                        plugins: {
                            'aggregation-func': {"aggrFunctions": scope.aggregationFunctions},
                            'units-for-filters': {"unitsForFiltersOptions": metricsById}
                        },
                        filters: scope.buildFilters(metrics),
                        operators: [
                            {type: '=', nb_inputs: 1, multiple: false, apply_to: ['number', 'boolean']},
                            {type: '≠', nb_inputs: 1, multiple: false, apply_to: ['number', 'boolean']},
                            {type: '<', nb_inputs: 1, multiple: false, apply_to: ['number']},
                            {type: '≤', nb_inputs: 1, multiple: false, apply_to: ['number']},
                            {type: '>', nb_inputs: 1, multiple: false, apply_to: ['number']},
                            {type: '≥', nb_inputs: 1, multiple: false, apply_to: ['number']}
                        ],
                        icons: {
                            add_group: 'fa fa-plus-circle',
                            add_rule: 'fa fa-plus',
                            remove_group: 'fa fa-close',
                            remove_rule: 'fa fa-close',
                            error: 'fa fa-warning'
                        }
                    });

                    queryBuilderElt.on(
                        'afterAddGroup.queryBuilder afterDeleteGroup.queryBuilder ' +
                        'afterAddRule.queryBuilder afterDeleteRule.queryBuilder ' +
                        'afterUpdateRuleValue.queryBuilder afterUpdateRuleFilter.queryBuilder afterUpdateRuleOperator.queryBuilder ' +
                        'afterUpdateGroupCondition.queryBuilder ' +
                        'afterUpdateRuleAggregationFunction.queryBuilder ' +
                        'afterUpdateRuleUnits.queryBuilder', function () {
                            safeApply(scope, function () {
                                if (!scope.queryBuilderRulesInternalUpdateInProcess) {

                                    ngModelCtrl.$setDirty();

                                    var changedRules = scope.convertQueryBuilderRulesToConditionRules(scope.queryBuilderElt.queryBuilder('getRules'));

                                    if (!objectHelper.deepEquals(changedRules, scope.rules)) {
                                        if (changedRules && changedRules.rules) {
                                            scope.rules = changedRules;

                                            ngModelCtrl.$setViewValue(scope.rules);
                                        }
                                    }

                                    ngModelCtrl.$setValidity("rules", queryBuilderElt.queryBuilder('validate'));
                                }
                            });
                        });

                    if(scope.rules){
                        scope.updateQueryBuilderRules(scope.rules);
                    }

                    scope.queryBuilderCreated = true;
                };

                scope.updateQueryBuilderRules = function(rules) {
                    scope.queryBuilderRulesInternalUpdateInProcess = true;
                    scope.queryBuilderElt.queryBuilder('setRules', scope.convertConditionRulesToQueryBuilderRules(rules));
                    scope.queryBuilderRulesInternalUpdateInProcess = false;
                };

                ngModelCtrl.$render = function () {

                    scope.rules = ngModelCtrl.$viewValue;

                    if(scope.queryBuilderCreated) {
                        scope.updateQueryBuilderRules(scope.rules);
                    }
                };

                scope.convertConditionRulesToQueryBuilderRules = function(conditionRules) {
                    if(!$.isArray(conditionRules) && conditionRules.condition){
                        return {
                            rules: scope.convertConditionRulesToQueryBuilderRules(conditionRules.rules),
                            condition: conditionRules.condition
                        }
                    }
                    else {
                        return _.map(conditionRules, function (conditionRule) {
                            if (conditionRule.rules) {
                                return {
                                    rules: scope.convertConditionRulesToQueryBuilderRules(conditionRule.rules),
                                    condition: conditionRule.condition
                                }
                            }
                            else {
                                return {
                                    id: conditionRule.metricId,
                                    operator: conditionRule.operator,
                                    value: conditionRule.value.amount,
                                    data: {
                                        aggregationFunction: conditionRule.aggregationFunction,
                                        units: conditionRule.value.units
                                    }
                                }
                            }
                        });
                    }
                };

                scope.convertQueryBuilderRulesToConditionRules = function(queryBuilderRules) {
                    if(!$.isArray(queryBuilderRules) && queryBuilderRules.condition){
                        return {
                            rules: scope.convertQueryBuilderRulesToConditionRules(queryBuilderRules.rules),
                            condition: queryBuilderRules.condition
                        }
                    }
                    else {
                        return _.map(queryBuilderRules, function (queryBuilderRule) {
                            if (queryBuilderRule.condition) {
                                return {
                                    rules: scope.convertQueryBuilderRulesToConditionRules(queryBuilderRule.rules),
                                    condition: queryBuilderRule.condition
                                }
                            }
                            else {
                                return {
                                    aggregationFunction: queryBuilderRule.data ? queryBuilderRule.data.aggregationFunction : undefined,
                                    metricId: queryBuilderRule.id,
                                    operator: queryBuilderRule.operator,
                                    value: {
                                        amount: parseFloat(queryBuilderRule.value),
                                        units: queryBuilderRule.data ? queryBuilderRule.data.units: undefined
                                    }
                                }
                            }
                        });
                    }
                };
            }
        }
    });
})();
`
