### ISSUE TITLE
Backtick problem with table name/field name combination

### ISSUE THREAD

**Issue by chassteel** [mistic100/jQuery-QueryBuilder#227]
I'm using the setRulesFromSQL method to load a query which contains a table name as well as a field name in the select statement:

    SELECT parent.lastname, child.lastname FROM parent JOIN child ON...

I'm getting the error: 

    Undefined filter "`parent.lastname`"

The backticks are not in my original query and are obviously being inserted incorrectly.  If I include backticks in my query (\`parent\`.\`lastname\`) the result is the same.

I looked at the function throwing the error, getFilterById, and added the following modification:
 
    QueryBuilder.prototype.getFilterById = function(id) {
        if (id == '-1') {
            return null;
        }

        var search = (typeof id.values != 'undefined') ? id.values[0]+'.'+id.values[1] : id; // <--- new line

        for (var i=0, l=this.filters.length; i<l; i++) {
            //db(this.filters[i].id);
            if (this.filters[i].id == search) { // <--- replace id with search
                return this.filters[i];
            }
        }

        Utils.error('Undefined filter "{0}"', id);
    };

The query then loaded fine.  I may have missed something, but I was wondering if this is the correct approach to the problem.

**Comment by mistic100** [comment]
Do you use the last version (yesterday) ? This should have been fixed here #203

**Comment by chassteel** [comment]
Nope.  I should have mentioned I was using 2.3.0 last week, and I should have checked for an update this morning.  2.3.1 works perfectly.

Thank you and I'm sorry to have troubled you.

**Comment by mistic100** [comment]
No problem :)
