### ISSUE TITLE
Unable to retrieve rules when rule element IDs include colons

### ISSUE THREAD

**Issue by ryansmith4** [mistic100/jQuery-QueryBuilder#228]
I'm trying to use QueryBuilder in a JSF application.  By default JSF prepends the container(s) elements to child elements using colons, which jQuery interprets as a selector.  

```HTML
<div id="MyForm:RuleTabs:builder" class="query-builder form-inline">
	<dl id="MyForm:RuleTabs:builder_group_0" class="rules-group-container">
		<dt class="rules-group-header">
			...
			<div class="btn-group group-conditions">
				...
				<dd class="rules-group-body">
					<ul class="rules-list">
						<li id="MyForm:RuleTabs:builder_rule_0" class="rule-container">
							...
							<div class="rule-value-container">
								<input class="form-control" type="text" name="MyForm:RuleTabs:builder_rule_0_value_0">
							</div>
						</li>
					</ul>
				</dd>
				...
			</div>
		</dt>
	</dl>
</div>
```

The inclusion of the colons in the element IDs prevents get/setRules from being able to retrieve/set rule values properly.   The affected code appears to be in query-builder.js, in the getRuleValue/setRuleValue function, where the values of the input controls are retrieved/applied using something similar to: ` $value.find('[name='+ name +']').val()`.  When name contains colons (or other reserved selector characters), the find will fail.

This issue could be avoided, if the get/set rules escaped the rule element ids before referencing the rule's input control.

**Comment by ryansmith4** [comment]
Out of curiosity, is there an anticipated release date for 2.3.2?  We're using bower to pull QueryBuilder down - since there isn't a release yet with this fix, I'd thought to pull via bower and and build locally as part of our build process, but according to everything I've read, it's a bower anti-pattern (see [http://stackoverflow.com/questions/17170500/how-make-bower-build-the-package](how-make-bower-build-the-package).  I'd create an interim build and commit to my fork, but I recall seeing a comment somewhere where you asked folks not to commit to the dist folder since that is reserved for official releases.  I suppose I could commit an interim dist on a branch on my fork that I have no intention of ever creating a pull request against, but I was wondering if you had any recommendations/suggestions concerning interim builds?

**Comment by mistic100** [comment]
My requirement for the dist directory is only for pull requests. You do what ever you want on your repo..

I prefer to have a few more changes before releasing.
