### ISSUE TITLE
Has anyone written a gem for this in Rails? 

### ISSUE THREAD

**Issue by markmcdonald51** [mistic100/jQuery-QueryBuilder#230]
This query builder is awesome. I want to use it with many different projects what contain many tables. 
I am curious, has anyone built a gem for this yet in Rails?

Nice work!
Mark

**Comment by mistic100** [comment]
Not has I know.
If anyone do it and notifies me, I'll reference it in the doc http://querybuilder.js.org/plugins.html#other-export

Sorry I close this, I don't want to pollute the list with tickets that are not bugs or feature requests.
