### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: <

### ISSUE THREAD

**Issue by carnivaltechnologies** [mistic100/jQuery-QueryBuilder#232]
Got this error while using with JQuery 1.9.1, Tried to implement with Drupal.

Uncaught Error: Syntax error, unrecognized expression: <select class="form-control" name="builder-basic_rule_0_filter">        <option value="-1">------</option>                <option value="name">Name</option>             <option value="category">Category</option>             <option value="in_stock">In stock</option>             <option value="price">Price</option>             <option value="id">Identifier</option>       </select>
!

Attached a Screenshot of the Error. 
[error_querybuilder](https://cloud.githubusercontent.com/assets/13253869/12450254/95114006-bfa8-11e5-946b-f2860e999192.png)

**Comment by mistic100** [comment]
Please create a plukr or jsfiddle showing the error.
The lib if available on jsdelivr CDN if needed

**Comment by carnivaltechnologies** [comment]
Created a JsFiddle
http://jsfiddle.net/r7Lc6ff5/1/

**Comment by carnivaltechnologies** [comment]
Just checked with Jquery 1.8, working now. But My Whole system uses 1.9.1 
In documentation it shows it require >=Jquery 1.9.1

**Comment by mistic100** [comment]
There is nothing I can do (or will do).
It's a behaviour change in 1.9 that was reverted in 1.10 https://bugs.jquery.com/ticket/13223
