### ISSUE TITLE
QueryBuilder widget throws d[e.plugin] is not a function error

### ISSUE THREAD

**Issue by raj-vel** [mistic100/jQuery-QueryBuilder#234]
Hello Team,

I am trying to implement QueryBuilder Widgets in my projects. I added plugins and filters for the Querybuilder. In the UI, when I click the textbox which is supposed to load datepicker or slider throws JS error at the console. Below is the error.
Error: Uncaught TypeError: d[e.plugin] is not a function [queryBuilder.js: 442]

Thanks

**Comment by mistic100** [comment]
Provide some code. https://github.com/mistic100/jQuery-QueryBuilder/blob/master/CONTRIBUTING.md

**Comment by raj-vel** [comment]
Hello Team,

I figured out the issue, I was not including the bootstrap JS using require which was throwing this error. I am good now. Thank You.

**Comment by mistic100** [comment]
Please close issues when it's done.

**Comment by rkrameshkumar71** [comment]
core.es5.js:1020 ERROR TypeError: jQuery(...).queryBuilder is not a function(…)defaultErrorLogger @ core.es5.js:1020webpackJsonp.../../../core/.es5.js.ErrorHandler.handleError @ core.es5.js:1080next @ core.es5.js:4503schedulerFn @ core.es5.js:3635webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:239webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:186webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:127webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:91webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56webpackJsonp.../../../core/.es5.js.EventEmitter.emit @ core.es5.js:3621(anonymous function) @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142webpackJsonp.../../../core/.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844onHandleError @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:396webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:195webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499invokeTask @ zone.js:1540globalZoneAwareCallback @ zone.js:1566

# **I am Getting this error if i am creating another angular program and there i am implementing then it is working fine but when i am implementing Jquery query builder in my project it will showing above error i think js files are conflicting but i don't no how to resolve this solution any on can help me.**

my angular.cli.json file code is below

{
"project": {
"version": "1.0.0-beta.28.3",
"name": "new-mis"
},
"apps": [{
"root": "src",
"outDir": "dist",
"assets": [
"assets",
"favicon.ico"
],
"index": "index.html",
"main": "main.ts",
"test": "test.ts",
"tsconfig": "tsconfig.json",
"prefix": "app",
"mobile": false,
"styles": [
"styles.css",
"../src/assets/styles/custom-bootstrap.less",
"../node_modules/fullcalendar/dist/fullcalendar.css",
"../node_modules/primeng/resources/themes/omega/theme.css",
"../node_modules/bootstrap-select/dist/css/bootstrap-select.css",
"../node_modules/ng2-daterangepicker/daterangepicker.component.css",
"../node_modules/primeng/resources/primeng.css",
"../node_modules/font-awesome/css/font-awesome.css",
"../bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css",
"../node_modules/nouislider/distribute/nouislider.min.css",
"../node_modules/jQuery-QueryBuilder/dist/css/query-builder.default.min.css"

],
"scripts": [
    "../node_modules/jquery/dist/jquery.js",
    "../node_modules/bootstrap/dist/js/bootstrap.js",
    "../node_modules/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js",
    "custom.js",
    "../node_modules/moment/moment.js",
    "../node_modules/chart.js/dist/Chart.js",
    "../node_modules/fullcalendar/dist/fullcalendar.js",
    // "../node_modules/material-design-lite/dist/material.js",
    "../node_modules/bootstrap-select/dist/js/bootstrap-select.js",
    "../node_modules/ng2-daterangepicker/lib/daterangepicker/daterangepicker.component.js",
    "../node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js",
    "../bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js",
    "../node_modules/nouislider/distribute/nouislider.js",
    "../node_modules/ng2-nouislider/src/nouislider.js"
],
"environmentSource": "environments/environment.ts",
"environments": {
    "source": "environments/environment.ts",
    "dev": "environments/environment.ts",
    "prod": "environments/environment.prod.ts"
}
}],
"addons": [],
"packages": [],
"e2e": {
"protractor": {
"config": "./protractor.conf.js"
}
},
"test": {
"karma": {
"config": "./karma.conf.js"
}
},
"defaults": {
"styleExt": "css",
"prefixInterfaces": false,
"inline": {
"style": false,
"template": false
},
"spec": {
"class": false,
"component": true,
"directive": true,
"module": false,
"pipe": true,
"service": true
}
}

**Comment by upendra-d** [comment]
@ raj-vel , What was the issue? because I am facing similar issue using datepicker

**Comment by MateusFGoncalves** [comment]
What was the issue?
