### ISSUE TITLE
Change Template Engine example

### ISSUE THREAD

**Issue by sabski** [mistic100/jQuery-QueryBuilder#235]
Hello i`m trying to change the template engine, but in the documentation there is no example can you help me out with a simple example ?

**Comment by mistic100** [comment]
Hi

first why do you want to change the engine ? doT.js is really easy to learn.

Example with lodash/underscore :
``` js
$('#builder').queryBuilder({
  templates: {
    group: _.template('HERE THE TEMPLATE STRING')
  }
});
```

PS: I will not provide support if you break your builder because of incorrect templating :-)

**Comment by sabski** [comment]
I want to change it so i can add angular code in the templates like ng-if. 
Thanks for the help. 
PS: I will try not to break the templates :)

**Comment by IMM0rtalis** [comment]
I came here to look for an example of changing the template. Can you add this to the doku? So others dont have to search for this like me.

Merci
