### ISSUE TITLE
Turning off and / or selector

### ISSUE THREAD

**Issue by ErikBrewster** [mistic100/jQuery-QueryBuilder#236]
I'm interested in using this to configure a homegrown (non sql) rules engine. My rules engine is completely flat -- a single level of OR related rules. Is there a way to disable the and / or rules to configure this system?

**Comment by mistic100** [comment]
Change [`conditions`](http://querybuilder.js.org/#options) options or just use CSS and set `allow_groups` to `false`

**Comment by ErikBrewster** [comment]
Works for me. For those trying to follow along later, I took the vary simplest sample code and changed this:
```
    filters: [{
      id: 'name',
      label: 'Name',
      type: 'string'
    }],
```
to this:

```
$('#builder').queryBuilder({
    filters: [{
      id: 'name',
      label: 'Name',
      type: 'string'
    }],
    conditions: ['OR'],
    allow_groups: false
  });
```
