### ISSUE TITLE
Unique filter issue

### ISSUE THREAD

**Issue by liorbashan** [mistic100/jQuery-QueryBuilder#237]
Unique filter doesn't seem to work.
been using it as described inside a filter:
filters: [
  {
    /* .... */
    unique: true // this filter can be used only once in the whole builder
  },

but the builder allows this filter to be re used.

**Comment by mistic100** [comment]
I reproduce on the demo, the behaviour is really eratic.

**Comment by mistic100** [comment]
I cannot reproduce with the example file, I don't know why it's not working in the demo site.
If you want further help, setup a live example.

**Comment by liorbashan** [comment]
Thanks for the replay,
Here is my example - http://codepen.io/liorbashan/pen/XXOweW

**Comment by mistic100** [comment]
You didn't add "unique-filter" to the plugins list.

So it's not the same problem I encounter on the demo.

**Comment by IMM0rtalis** [comment]
I'd like to reopen this:

my config:
```
display_empty_filter: false,
default_filter: 'channel',
conditions: ['AND', 'OR'],
plugins: [
    'unique-filter',
],
filters: [
   {
    id: 'channel',
    label: 'Channel',
    type: 'string',
    operators: ['contains'],
    unique: true,
   }
],
```
When I click "add" rule I have multiple "channel"-filters.

So I would say this is a bug :/

**Comment by mistic100** [comment]
you set "default_filter" = "channel" and say it must be unique ? this is not coherent and can not work
