### ISSUE TITLE
Load filters from rest.

### ISSUE THREAD

**Issue by sabski** [mistic100/jQuery-QueryBuilder#238]
Hello i\`m having trouble loading filters from a rest api. 
This is the error i get, but all filters have id.
`type":"error","message":"ConfigError: Missing filter 1 id"`
Also is there a way to dynamically change all filters and rules i tried what was written in page, but the builder would still show the old values instead of the new ones ?

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/CONTRIBUTING.md

**Comment by sabski** [comment]
Thanks got the message :+1:

**Comment by mistic100** [comment]
Understand me, I want to help, but I just can't if you do not provide more info.

**Comment by sabski** [comment]
I need to be able to change filters and rules with several different sets of them. I have the following rule example `{
          "id": "objectN",
          "field": "objectN",
          "type": "string",
          "input": "text",
          "operator": "contains",
          "value": "",
          "flags": {
            "filter_readonly": "true",
            "operator_readonly": "true",
            "condition_readonly": "true"
          }`
This is loaded properly but when i want to remove it and replace it with something like this `  {
          "id": "objectID",
          "field": "emf:externalID",
          "type": "string",
          "input": "text",
          "operator": "equal",
          "value": "",
          "flags": {
            "filter_readonly": "true",
            "operator_readonly": "true",
            "condition_readonly": "true"
          }` the builder does not react.
My code is like this.
`  switch (newValue) {
      case 'one' :
        builder.queryBuilder('setRules', this.testRulesSet());
        break;
      case 'two:
        builder.queryBuilder('setRules', this.testRules());
        break;
    }`

**Comment by mistic100** [comment]
You are mixing up filters and rules, it's absolutely not the same thing !
Here you are changing the filters, not the rules http://querybuilder.js.org/plugins.html#change-filters

**Comment by sabski** [comment]
Hmm yes they have me a little confused, how do i change the rules with new ones and remove the old ones ?

**Comment by mistic100** [comment]
Rules: setRules
Filtres: setFilters

Really, is in the doc, I know it's big but you must read it.

**Comment by sabski** [comment]
Yes sorry i just got lost in the docks.

**Comment by sabski** [comment]
Hmm when i try to switch between 2 different filter and rule sets the plugin, has disappeared completely.

**Comment by mistic100** [comment]
You will have to create a fiddle otherwise i can't help you.

**Comment by sabski** [comment]
I`m having trouble creating a fidle example.  Best i can do for now http://pastebin.com/C61YFvSM

**Comment by mistic100** [comment]
The "setFilters" method takes an array of filters, here you give a full config object, so obviously it does not work.

Need
```js
 $('#builder').queryBuilder('setFilters', true ,testFilterSet2().filters);
```
