### ISSUE TITLE
Unable to add new operator in filter for type : 'date'.

### ISSUE THREAD

**Issue by shrabanee** [mistic100/jQuery-QueryBuilder#239]
Hi,
 I am trying to add a new operator to filter of type : 'date'. But the code is making the drop down blank. Attaching the code I have tried . Refered http://querybuilder.js.org/index.html#operators

`
       var builder = $('#builder');

       builder.queryBuilder({
           sortable: true,
           filters:
           [
               {
                   id: '_id',
                   label: 'Org Id',
                   type: 'integer',
                   operators: ['equal', 'not_equal', 'in', 'not_in']
               }, 
               {
                   id : 'ca',
                   label : 'Created at',
                   type : 'date',
                   operators: [{ type: 'in', optgroup: 'basic' },
                       { type: 'not_equal', optgroup: 'basic' },
                       { type: 'equal', optgroup: 'basic' },
                       { type: 'new_opt', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['datetime'] }]
               }
           ]
       });
`

What is wrong I am doing? Can you please help.

**Comment by mistic100** [comment]
Hi

You mixed the global operators and the filter's operators (a reference to the global operators)
http://querybuilder.js.org/index.html#filters

it's only an array of operators types.

See the basic demo source http://querybuilder.js.org/demo.html

**Comment by shrabanee** [comment]
Ok. Understood.

So, is there any way to add a new operator to existing operators?

My requirement is to add a new operator (i.e. n days before) for type 'date' and use the option to form mongo query accordingly. Can I do this in any way?

**Comment by shrabanee** [comment]
I have tried like the code below:

` var builder = $('#builder');

       builder.queryBuilder({
           sortable: true,
           operators:
           [
               { type: 'in', optgroup: 'basic' },
               { type: 'not_equal', optgroup: 'basic' },
               { type: 'equal', optgroup: 'basic' },
               { type: 'string', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['datetime'] }
           ],
           filters:
           [
               {
                   id: '_id',
                   label: 'Org Id',
                   type: 'integer'
               }, {
                   id: 'ourl',
                   label: 'URL',
                   type: 'string'
               },
               {
                   id: 'ona',
                   label: 'Org Name',
                   type: 'string'
               },
               {
                   id : 'ca',
                   label : 'Created at',
                   type : 'date'
               }
           ]
       });`

Is it the correct way to use?

**Comment by mistic100** [comment]
Yes it's the correct way.

Again, check the doc http://querybuilder.js.org/plugins.html#mongodb-support, the part about Operators.

**Comment by shrabanee** [comment]
Okay. Thanks. 

I read the doc.
So I am using the code below

` $.fn.queryBuilder.defaults({
            getPastDate : function()
            {
                //Do stuff here to generate query
            }
       });`

Will this help to generate the query or I have to make changes in mongoOperators and mongoRuleOperators?

**Comment by mistic100** [comment]
What is getPastDate ? I think your are understanding what you are doing here...

What you need : 

```js
builder.queryBuilder({
  mongoOperators: {
    newOpt: function(v) {
      return something;
    }
  }
  /* other options */
});
```

**Comment by shrabanee** [comment]
Okay. Understood what I have to do. 
I thought I have to create a new function to generate the query, so named 'getPastDate'.
Thanks for the help.
