### ISSUE TITLE
Datetime field with bootstrap datepicker not working

### ISSUE THREAD

**Issue by farzanayusuf** [mistic100/jQuery-QueryBuilder#240]
There is a datetime field in mongo database, i tried querying the field from jquery builder mongo output, but it returns  nothing. So far i have seen that one needs to convert the string into ISODate for mongo.

Mongo expects the format:
 { '$and': [{'dt_est_school': {'$lte': ISODate('2016-02-17'), '$gte':  ISODate('1980-01-01') }} ]}

QueryBuilder produces 
{ '$and': [{'dt_est_school': {'$lte':'2016-02-17' , '$gte':  '1980-01-01' }} ]}

Have anyone worked it other way around, nothing seems to work for me, i tried converting string to new Date().toISOString() from javascript, but doesn't work

**Comment by mistic100** [comment]
As QueryBuilder produces JSON it cannot use the ISODate function.

You can try `D M dd 00:00:00 +0000 yyyy`  as Datepicker format.

But this is not something QueryBuilder can change.

**Comment by farzanayusuf** [comment]
By json you mean the mongodb supported json,right? As this output form doesn't work for mongodb, i was hoping someone might have a workaround about that. 

Anyway can you just point me to the function which convert the input to MongoDB queries. One more thing is there not any way where we can append the the output format to ISODate for datetime in jquery_builder.js to make it work for my purpose?

**Comment by mistic100** [comment]
No, I mean json valid for the navigator, because the builder works in the navigator.

Try to put a Mongo query in a is script on your navigator, it won't work, ISODate dies not exist.

**Comment by aryeharmon** [comment]
@mistic100 how how timestamp? can we use that instead of date?
