### ISSUE TITLE
How to set the "value" in "rule.$el", after selecting date time from custom calender

### ISSUE THREAD

**Issue by shrabanee** [mistic100/jQuery-QueryBuilder#242]
Hi, 

I have added a custom calendar to filter type "date". On clicking on the input field, calendar will come up. After selecting date, when I am trying to do $("#builder").queryBuilder('getMongo'), value is null in "rule.$el.value", so I am unable to generate the query. My code is as shown below:-

```html
<div id="builder"></div>
<div class="parse-mongo">Run</div>
``` 
```js
var builder = $("#builder");
$.fn.showCalender = function(options) 
 {
     //Code to show calendar
     return this;
 }; 
 
self.closeCalender = function()
{
     //Do stuff here to close calender and set the value in the input
}
 builder.queryBuilder({
     sortable: true
     filters:
     [       
         {
             id: 'ona',
             label: 'Org Name',
             type: 'string'
         },
         {
             id : 'ca',
             label : 'Created at',
             type : 'date' ,
            plugin : "showCalender"
         }
     ]
 });

$('.parse-mongo').on('click', function ()
{
   var resJson = builder.queryBuilder('getMongo');
});

```

How I can set the value I am getting from the calender to the "value" in "rule.$el"? 
I have tried some of the "changers", but could not make it work seems.

**Comment by mistic100** [comment]
That's exactly what I said at the bottom of my comment https://github.com/mistic100/jQuery-QueryBuilder/issues/241#issuecomment-185600432

Once the user closes the calendar and you updated the input value you must the trigger the standard DOM event "change". Otherwise QueryBuilder does not know an interraction happened.

**Comment by shrabanee** [comment]
Okay. May be I did not notice that. Will add the event.

**Comment by shrabanee** [comment]
That worked. Thanks.
