### ISSUE TITLE
How can I use 2 filter dropdowns and then dropdown for operators?

### ISSUE THREAD

**Issue by shrabanee** [mistic100/jQuery-QueryBuilder#246]
Hi,

   I am trying to create two filters dropdpown and then operators dropdown to generate query, as explained below. 
    My requirement is, from 1st filter dropdown, I will select one option. Then the second filter's values will be changed based on the first selection and then I can select some operator from dropdown provided and use it to generate query.

Db structure :- 

```
[{
_id: 1234,
oid: 6754,
event:
   {
         ena : "create",
         first_ca : some_date,
         last_ca : some_date
    },
   {
         ena : "login",
         first_ca : some_date,
         last_ca : some_date
    }
   {
         ena : "invite",
         first_ca : some_date,
         last_ca : some_date
    }
}]

example of query to get records:
{
     'event.ena' : 'invite',
     first_ca : { $gte : some_date, $lte : another_date }
}
```

 I want to show list of "event.ena" in first filter dropdown and second dropdown will have fields like "first_ca" and "last_ca". Then I want to select some operator provided for type "date" and use it.

Is there any way of doing this?

**Comment by mistic100** [comment]
No it's not possible, And I don't plan to make it possible.

There is the `optgroup` attribute of filters that can be used to group filters together.

**Comment by shrabanee** [comment]
Okay. Will try the optgroup attribute then.
