### ISSUE TITLE
.Net Filter Backend Compatible with jQuery-QueryBuilder

### ISSUE THREAD

**Issue by tghamm** [mistic100/jQuery-QueryBuilder#247]
Hi there,

We really appreciate all of the work done on jQuery-QueryBuilder, and we built a dynamic parser library in `C#` that compliments the jQuery-QueryBuilder platform (it implements a generic filter on a collection of objects based on the filter objects supplied by jQuery-QueryBuilder) and have released it along with a sample of it being used with this library.  Mostly we just wanted to make people aware, but we also thought perhaps mentioning it somewhere in the documentation might be appropriate, if helpful.

We're still expanding on documentation, but it's currently in use in a couple of production environments.

Here's the project: [https://github.com/castle-it/dynamic-linq-query-builder](https://github.com/castle-it/dynamic-linq-query-builder)

**Comment by mistic100** [comment]
Great, I'll add a note about it.

**Comment by tghamm** [comment]
Awesome, thanks!

**Comment by moyarich** [comment]
Do you have a screen shot of the application

**Comment by tghamm** [comment]
Sure, here's a screenshot of the sample application in our repository in-action.

![demo screenshot](https://cloud.githubusercontent.com/assets/5253107/14127395/6341e77e-f5e5-11e5-9576-c3cc7c4f035e.png)

**Comment by Yearmix** [comment]
Good issue, but how about translation of the query and etc. such as https://blogs.msdn.microsoft.com/mattwar/2007/07/31/linq-building-an-iqueryable-provider-part-ii/
means create full IQueryable provider
