### ISSUE TITLE
Is it possible to add a new field in rules (in the level of "value")?

### ISSUE THREAD

**Issue by shrabanee** [mistic100/jQuery-QueryBuilder#248]
Hi,

I want to add a new field (ex. dt) in the level of value, inside rules and update 'dt' value when "value" is being updated. I have tried using 'data', it is adding a new object in rules object but I am not getting any way to update this new field, for specific rule object.

I have tried using observable variable, but it is updating 'data' object  of all the rules, which is not giving me the data I want.

```
rules: {
field: "ca",
id: "ca",
input: "text",
operator: "in",
type: "date",
value: "10 Wed 12:00a",
dt : //here I want to store a proper date object, which can be used in query
}
```

I am using a custom calender. Once user selects date, I am calling 'this.trigger("change")'. Displayed date format is different from the format I want to create the query with. So I want to save the value I am getting from calender in dt fiield, which I can use for query formation.

How can I do this?

**Comment by mistic100** [comment]
Why are you using a custom calendar (with an "a") exactly ? Components like jquery Datepicker have two format paremeters : display and actual value, that could solve your problem.

Now for your question, you can ONLY use the `data` attribute, for example in your jQuery plugin definition, before `this.trigger("change")`  :

```js
var model = $('#builder').queryBuilder('getModel', this);

model.data = {
  realValue: 'something'
};
```

**Comment by shrabanee** [comment]
I am using custom calendar because, user can select time along with date.

Tried the solution you gave. Did not work, model is undefined.

```
$.fn.showCalender = function(options)
       {
           var instance = this;
           this.on("click", function(element)
           {
               if(showPlugin && $(element.target).attr("class") === "form-control" && $(element.target).attr("type") === "text" )
               {
                   require(['custompicker'],function(custompicker)
                   {
                       new custompicker($(element),new Date(), {hours:12, minutes:0, meridian:"AM", value : "12:00 AM"},{'startDate':new Date(0),'allowPastDate':true});
                       $(element).on('canSave', function(e,data)
                       {
                           if(data['picker']['dateObject'])
                           {
                               var dispDate = Utility.getDisplayDate(data['picker']['dateObject'], 1 , 1);
                               $(element.target).val(dispDate);

                               var model = $('#builder').queryBuilder('getModel', instance);

                               console.log(model);     // model is undefined here

                               model.data = {
                                   dateObj :  data['picker']['dateObject']
                               };

                               instance.trigger('change');
                           }
                       });
                   });
               }
           });
```

Is there anything wrong I am doing?

**Comment by mistic100** [comment]
http://xdsoft.net/jqplugins/datetimepicker (my point being: do not waste time redevelopping what already exists)

Without being able to debug i can't help sorry.

**Comment by shrabanee** [comment]
Okay.

Can you tell me what 'this' suppose to be? 
```
var model = $('#builder').queryBuilder('getModel', this);
```
So that I can sent the proper value.

**Comment by mistic100** [comment]
https://learn.jquery.com/plugins/basic-plugin-creation/

It's a jQuery object corresponding to the DOM element on which the plugin has been initialized.

I actually made a mistake, you need : 

```js
var ruleContainer = instance.closest('.rule-container');
var model = $('#builder').queryBuilder('getModel', ruleContainer);
```

The QueryBuilder model is attached to the main rule DIV, not the input

**Comment by shrabanee** [comment]
Thanks. 
That helped.

So we can add multiple fields to the "model.data" object in this way and use it, right?

**Comment by mistic100** [comment]
Yep

**Comment by shrabanee** [comment]
Okay. 
Thanks for the help.
