### ISSUE TITLE
Raw SQL output option fails for "is [not] {empty, null}"

### ISSUE THREAD

**Issue by jennformatics** [mistic100/jQuery-QueryBuilder#25]
Hi. I've confirmed this behavior on the main demo site (demo-basic.html): the raw SQL output button doesn't seem to work for the empty and null options.

If you select "Name", then "equal", and type a string, then you can choose "JSON", "SQL (prepared statement)", or "SQL (raw)", and get the desired output.

However, if you choose "Name", then "is empty", only the first two options work. Clicking on "SQL (raw)" does nothing visible; if there is previous output showing, the output div doesn't change, and if there was no output showing, no output div appears.

The error in my JS console is "TypeError: a is null", from query-builder.min.js.  I wish I could help more, but I'm not a JS person (which is why I was hoping to get this great functionality from a drop-in library!).

I reproduced the problem in both Firefox and Chrome, in case it was browser-dependent in some weird way. Thanks, and let me know if I can provide any additional useful information.

**Comment by laratutodotcom** [comment]
[solved] - How do I get the query builder to output in raw as string - 9 -->https://laratuto.com/i-get-the-query-builder-to-output-in-raw-as-string/
