### ISSUE TITLE
Feature request for getSQL / Question

### ISSUE THREAD

**Issue by kristianoye** [mistic100/jQuery-QueryBuilder#252]
I am using QueryBuilder to generate statements for SQL + .NET SqlClient.  It would be nice if getSQL 'named' could take an optional argument to replace the ':' variable name prefix with '@'.  

e.g.  .queryBuilder('getSQL', 'named', undefined, undefined, '@')

I hacked it in for my purposes but would be a nice feature (for maintainability).

Completely unrelated question: filter's valueSetter function.  I've added a filter like:
```
                            {
                                id: 'Class',
                                field: 'Class',
                                label: 'Class',
                                type: 'string',
                                input: 'text',
                                operators: ['begins_with', 'not_begins_with', 'equal', 'not_equal', 'contains', 'not_contains'],
                                valueSetter: function (rule, value) {
                                    console.log('valueSetter');
                                    return value;
                                }
                            },
```
... but it never gets called.  I am trying to figure out how to convert the value entered into the control when getSQL is called so if a set operator like 'in' is used that the value returned is an array.  Is that possible?

**Comment by mistic100** [comment]
#142

for "Completely unrelated question"... open another ticket :-) with live example please because I never had the case where it does not work.

**Comment by kristianoye** [comment]
^ #142 sqlStatements customization = awesome sauce.  This is, by far, one of my favorite js libraries.

**Comment by kristianoye** [comment]
Btw, I found my other solution in another thread #43 Thanks!  valueParser was what I was looking for:

```
                                valueParser: function (rule, value) {
                                    return ['in','not_in'].indexOf(rule.operator.type) > -1 ?
                                        value.split(',').map(function(x){return x.trim();}) : value;
                                }

```
Thanks!

**Comment by mistic100** [comment]
`valueParser` is deprecated and will be removed (already removed from the doc)

I'll appreciate you setup an example

**Comment by mistic100** [comment]
I finally decided to make it configurable without rewriting the internal generator :

```js
.queryBuilder('getSQL', 'named(@)')

.queryBuilder('setRulesFromSQL', data, 'named(@)')
```

the char between parenthesis can be anything (only one char)

**Comment by kristianoye** [comment]
Woo!  That's cool.  I'll try and get back and post a fiddler to repro what I'm seeing (or not seeing) with valueSetter.  I am not even sure I fully understand it's purpose (was thinking it's functionally equivalent to valueParser).

**Comment by kristianoye** [comment]
I'll try valueGetter (just saw that comment)
