### ISSUE TITLE
How to use query builders, with dynamic filters, in different tabs within same view?

### ISSUE THREAD

**Issue by shrabanee** [mistic100/jQuery-QueryBuilder#253]
Hi,

I am trying to use the query builder inside some tabs. I have multiple tabs in my view. I want to create different querybuilders for each of them. The code I am using is as below:-

```html
<div data-bind="foreach: tabList">
    <div class="builder"></div>
    <br/>
    <label>
        Tab name <input class="tabName" type="text"/>
    </label>
    <div class="saveBtnAdmin parse-mongo" data-bind="click : $root.saveTab">Create new tab</div>
</div>
```

```js
this.tablist = ko.observableArray([{tna: 'abc'},{tna : 'mno'},{tna : 'pqr'}]);

 $('.builder').queryBuilder({
      filters: [
                {
                    id: 'url',
                    label: 'URL',
                    type: 'string'
                },
                {
                    id: 'nal',
                    label: 'Org Name',
                    type: 'string'
                },
                {
                    id: 'ca',
                    label: 'Created at',
                    type: 'date',
                    plugin: "showCalender"
                }
            ]
});

var objArr= [{
        id: 'event1',
        label: "Event1",
        type: 'date',
    },
    {
        id: 'event2',
        label: "Event2",
        type: 'date'
    },
    {
        id: 'event3',
        label: "Event3",
        type: 'integer'
    }];

$(".builder").queryBuilder('addFilter', objArr, 3);
```

Getting error in console as (Uncaught ConfigError: Missing filters list). It added the first three options (which is already there in 'filters' option) in filter drop down, but not the options I am trying to add to it later.

First time when "QueryBuilder.prototype.init" function is being called, this.filters is with length 3 (since I have given 3 filters initially), but when second time it is being called this.filters is coming with length 0.

Is it I need to call "$('.builder').queryBuilder" multiple times to do the configs again?

**Comment by mistic100** [comment]
Should I repeat that I can't help without a live example ?

You are showing a small part of your code, of a framework I absolutely don't know, what can I do ?

**Comment by shrabanee** [comment]
[Check error in console](http://jsfiddle.net/graphitekom/ap9gxo4L/)

Error is coming in console.

**Comment by shrabanee** [comment]
[check the link](http://jsfiddle.net/qnd71zde/)

Error is coming in console.

**Comment by mistic100** [comment]
You are using $('#builder') and then $('.builder') so of course it does not work.

And as I understand your are creating multiple builders, one for each tab, perhaps you should wait the tabs are builded before initializing the builders. This is always the same problematic when using jQuery plugins with frameworks like React/Angular etc.

Now I don't know Knockout, and I won't learn Knockout.

**Comment by shivendramca10** [comment]
Hi mistic100,
I also user query builder and my requirement is that I would like to bind filter value from database.
Please suggest me how is doing work. 

I get all values from database using ajax and store in array and array value assign in filter but this is not working. i have use local storage of browser 

Please suggest me 

Thanks...
