### ISSUE TITLE
Do you have any guidelines for SQL Database structure to save rules?

### ISSUE THREAD

**Issue by ultrasonicsoft** [mistic100/jQuery-QueryBuilder#256]
Hi There,

I am impressed by your plugin and using it. It's great. (I can star your repo only once, though tried to start it many times :) )

As part of my work, I was going to save the output of Query Builder to MS SQL Server. Before creating database structure, may I know do you have any specific guidelines/example best suited to save these rules in db?

I have found few examples like below:
http://stackoverflow.com/questions/1902951/what-is-an-appropriate-data-structure-and-database-schema-to-store-logic-rules

http://stackoverflow.com/questions/11407062/storing-business-logic-in-database

http://stackoverflow.com/questions/545603/storing-conditional-logic-expressions-rules-in-a-database

Thank you!

**Comment by mistic100** [comment]
I actually used the builder only once. I had two tables : one for groups and one for rules, with complex foreign keys. And then the same logic as in the SQL plugin (didn't exist at this time) to build the queries.

Or if you do not need to work with the rules set outside the builder, just store the output (JSON or SQL) in a text field.

**Comment by mistic100** [comment]
Further details :
 - everything was stored in ONE table (both groups and rules) in a relational table with cyclic foreign keys
 - I used Spring Data to build Java object from the database or from the JSON send by the client
 - I had some logic to build MongoDB criteria from the rules

(I don't have access to the code anymore I can't show you)

But again if you don't need to manipulate the filter outside the builder I would recommend to simply store the whole SQL query somewhere (given proper escaping of course).

**Comment by ultrasonicsoft** [comment]
Thank you very much @mistic100 for reply.

To explain my intended work is as below:
I am trying to create alerts. So user will create alert using builder. It will be saved in db. For example, user create rule that "If Field X <10 and Field Y >20 then DO something".
Once I saved rule to db (sql/mongo), there will be continuous input stream of data which should get validated against all rules saved in db. If rule matches, I need to show alert.

On this line, yes I have to work outside builder and need evaluate then against various incoming input.

I would be glad to hear your thoughts on such design.

Thanks!

**Comment by mistic100** [comment]
When I say "manipulate outside the builder" I mean modify, does not seem to be your case.

**Comment by schalla27** [comment]
Hi @ultrasonicsoft: Can you give me some code examples of how you saved these jquery query builder rules to SQL Server. I am doing the same thing

**Comment by ultrasonicsoft** [comment]
Hi schalla27,

I have to search it. I will send you once found.

**Comment by ahmadSibai** [comment]
@ultrasonicsoft Are you still searching? did you find anything that would help?
