### ISSUE TITLE
Support for postgres ilike operator

### ISSUE THREAD

**Issue by iyerushalmi** [mistic100/jQuery-QueryBuilder#257]
Is there any way to easily swap out the "like" operator with an "ilike" operator for postgres databases? I am looking to implement case insensitive searches

**Comment by mistic100** [comment]
```js
$(....).queryBuilder({
  .......,
  sqlOperators: {
        begins_with:      { op: 'ILIKE(?)' },
        not_begins_with:  { op: 'NOT ILIKE(?)' },
        contains:         { op: 'ILIKE(?)' },
        not_contains:     { op: 'NOT ILIKE(?)' },
        ends_with:        { op: 'ILIKE(?)' },
        not_ends_with:    { op: 'NOT ILIKE(?)' },
  }
});
```

**Comment by iyerushalmi** [comment]
Amazing , thank you! The only thing I am wondering now is how to build compatibility with the SQL Parser but I am guessing that may not be within the scope of this forum?

**Comment by mistic100** [comment]
You can propose changes https://github.com/mistic100/sql-parser
