### ISSUE TITLE
Chage rules and filtes 

### ISSUE THREAD

**Issue by sabski** [mistic100/jQuery-QueryBuilder#258]
I want to switch between several sets of rules and filters. This is the code i have i pass the builder reference, and the data contains the nesasery data it works for the first filter but for the second i get the following error : 

```
angular.js:13239 {"url":"http:","type":"error","message":"UndefinedFilterError: Undefined filter \"\"","stackTrace":[
"Object.Utils.error@http:///jspm_packages/github/mistic100/jQuery-QueryBuilder@2.3.1/dist/js/query-builder.js:2559:15",
"QueryBuilder.getFilterById@http:///jspm_packages/github/mistic100/jQuery-QueryBuilder@2.3.1/dist/js/query-builder.js:1608:11",
"{anonymous}()@http:///jspm_packages/github/mistic100/jQuery-QueryBuilder@2.3.1/dist/js/query-builder.js:1325:37",
"Array.forEach@native",
"add@http:///jspm_packages/github/mistic100/jQuery-QueryBuilder@2.3.1/dist/js/query-builder.js:1294:20",
"QueryBuilder.setRules@http:///jspm_packages/github/mistic100/jQuery-QueryBuilder@2.3.1/dist/js/query-builder.js:1335:6",
"$.fn.queryBuilder@http:///jspm_packages/github/mistic100/jQuery-QueryBuilder@2.3.1/dist/js/query-builder.js:2667:29",
"DefaultSearchTemplate.testSwitch@http:///search/utils/template/default-search-template.js:528:23",
"ExternalSearch.changeRulesAndTemplate@http:///external-search/external-search.js:126:27",
"{anonymous}()@http:///external-search/external-search.js:114:23"
],"cause":"","userId":"userId","browser":"Chrome 49","os":"","resolution":"1920 x 1080","mobile":false}
```

This is the code i am working on, any ideas ?

```js
    testSwitch(data, builder) {

    if (builder.queryBuilder('getRules') !== undefined){
       builder.queryBuilder('reset')
    }

    builder.queryBuilder('setFilters', data.template.filters);

    if (data.rules !== undefined){

       builder.queryBuilder('setRules', data.rules, true);
    }
  }
```

**Comment by mistic100** [comment]
Please use valid Markdown syntax for code blocks (I edited your message)
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

------

Without knowing what data you are working with I cannot help. Sorry but I will not answer if you don't setup a live demo of the problem.

**Comment by sabski** [comment]
Yup sorry, thanks for the edit. As for the live demo i tried to set it up but couldn't even get the builder up.

**Comment by sabski** [comment]
Found the problem there was a mismatch between the filters and the rules.

**Comment by IMM0rtalis** [comment]
Could it be that "setFilters"-method is not at the wiki/doku? Just looked for it and found it just here.

**Comment by mistic100** [comment]
It's in the "Plugins" page

**Comment by IMM0rtalis** [comment]
Ahh...
"This plugin does not require initialization through the plugins config." Thatswhy its working^
Found it here: [http://querybuilder.js.org/plugins.html#change-filters](http://querybuilder.js.org/plugins.html#change-filters)

Shouldn't this be a standard method?

**Comment by mistic100** [comment]
it's still a plugin that can be removed with a custom build
