### ISSUE TITLE
Is date widget included in the query builder ? 

### ISSUE THREAD

**Issue by sabski** [mistic100/jQuery-QueryBuilder#259]
I am trying to add a data widget to my builder. I changed it to #builder-widgets and set the filters and rules but i get the following error : 
`"TypeError: $inputs[filter.plugin] is not a function"`
Where  filter.plugin = datepicker ?

**Comment by mistic100** [comment]
No input plugin is included in Query Builder.
The doc explicitely says "Name of a **jQuery** plugin to apply on the input."
