### ISSUE TITLE
Query period of time (example: 24 hours)

### ISSUE THREAD

**Issue by JPedroM** [mistic100/jQuery-QueryBuilder#261]
I, sorry if I've missed the info on how to do this.

My goal is to query a mean or a sum value of an attribute in a period of time. For example, mean temperature on the last 24 hours. 

My doubt is how should I present the fields for the time period input along side the filter for the value.

Thanks,
JPedroM

**Comment by mistic100** [comment]
I don't understand what you want. Provide a real example of output (SQL or other).

**Comment by JPedroM** [comment]
I've found another way to do what I want. 

I want to add a group under a rule when a specific filter is selected. I've figured out how to detect the selected filter but haven't found how can I add the group under the rule. 

To add a group should I get the model and modify it?

**Comment by mistic100** [comment]
Something like (inside the "afterUpdateRuleFilter.queryBuilder" event handler)

```js
container.queryBuilder('addGroup', theRuleJustModified.parent);
```

**Comment by JPedroM** [comment]
Have I missed 'addGroup' method in the documentation?

What does container should be? ($('#builder'))?

Congratulations for your great work and great and fast support. :D

**Comment by mistic100** [comment]
It's not in the doc, because under the hood.

Yes that's it, but you really should store it once for all, DOM querying has an impact on performances.

**Comment by JPedroM** [comment]
It just worked!!

```javascript
builder.on('afterUpdateRuleValue.queryBuilder', function(e, rule, error, value) {
                if (rule.filter.id == 'rain_level') {
                    builder.queryBuilder('addGroup', rule.parent);

                }
});
```

Now I just need to limit the available filters and some other options for the group.

Thanks.

**Comment by JPedroM** [comment]
Isn't possible to define which filters should appear on the second level group. And also make this sencond group only AND or OR?

**Comment by mistic100** [comment]
Use "getRuleFilters.queryBuilder.filter" to modify which filters are accsessible to a rule.
And use CSS to disable groups conditions

**Comment by JPedroM** [comment]
```javascript
builder.on('getRuleFilters.queryBuilder.filter', function(e, rule) {
                console.log(e.value);

                var filters = [{
                    description: "Temperatura",
                    field:"Temperatura Instantânea",
                    id:"Temperatura Instantânea",
                    input:"text",
                    label:"Temperatura Instantânea",
                    operators: ['greater', 'less', 'less_or_equal', 'greater_or_equal', 'between', 'not_between'],
                }]

                e.value = filters;
                console.log(e.value);
            });
```

I'm doing this but I'm getting this eror: query-builder.standalone.js:2110 Uncaught TypeError: Cannot read property 'pt' of undefined

**Comment by mistic100** [comment]
The same filter normally used (not within the event) works ?

**Comment by JPedroM** [comment]
I added some details to the filter trying to solve the problem but this one works in "normal mode":

```javascript
{
                    id: 'Temperatura Instantânea',
                    type: 'integer',
                    unique: true,
                    operators: ['greater', 'less', 'less_or_equal', 'greater_or_equal', 'between', 'not_between'],
                    description: 'Temperatura'
                }
```

**Comment by mistic100** [comment]
Can you place a breakpoint on line 2110 and see what the value of "label" is ?

**Comment by JPedroM** [comment]
I've got undefined.

**Comment by mistic100** [comment]
No sorry, I actually never used it.
I'll investigate but next week.

**Comment by JPedroM** [comment]
Hi! Any news on the issue?

**Comment by mistic100** [comment]
The new filter needs to have `optgroup: null`
But anyway, this WILL NOT WORK.

The builder stores all available filters elsewhere and you cannot add a new filter at runtime.

`getRuleFilters.queryBuilder.filter` can only be used to remove or reorder filters, not adding new ones.

**Comment by simsim0z** [comment]
Can I add a variable instead fixed values for dates ?

I other words "related to the title of this post", I want to create a rule that will check todays date, and todays date - 10 days, and by todays date I mean a variable that will be replaced by the date of the date on which this resulted sql query will run, so if I run the query today it will substitute todays date with 3-april-2016, or if I will run this query after a week, it will give me 10-april-2016 

**Example sql query [oracle syntax]**
`select .... WHERE .... AND ITEM_DATE <= SYSDATE AND ITEM_DATE >= SYSDATE - 10`

**Comment by mistic100** [comment]
Use a "select" filter with the desired elements.

If you use the included sql generator it will of course surround values with quotes, which you will have to remove.

**Comment by simsim0z** [comment]
I'm not sure how to create a select filter, but I worked around this by adding another field, say `ITEM_DATE_RANGE`, and give it a type of int, and then later parse the script in my server side.

Thanks,
Awesome tool by the way

**Comment by mistic100** [comment]
I mean a filter with a select input http://querybuilder.js.org/#filters
