### ISSUE TITLE
Widget Selectize background dropdown transparent

### ISSUE THREAD

**Issue by centenario** [mistic100/jQuery-QueryBuilder#262]
Hi, i've mugrated jQuery-QueryBuilder and i got some strange behavior.
Most important for me is that in Selectize, dropdown show values but background is transparent so isn't easy to see values for selecting.

thanks in advance.

**Comment by mistic100** [comment]
Example ?

**Comment by centenario** [comment]
It happens the same from your site, (firefox 45.0.1)
![selectize_ff4501](https://cloud.githubusercontent.com/assets/5682766/13984337/ca411520-f0f5-11e5-8a5b-30fe1614b02d.png)

**Comment by mistic100** [comment]
temporary fix: 
```css
.query-builder .selectize-dropdown {
  height: auto;
}
```

The problem is that Selectize inherits CSS classes from the input, and the input has `form-control`, and Bootstrap sets an height of 34px for form controls.

**Comment by centenario** [comment]
Ok, that seems fix error.
Thanks for your support.

**Comment by mistic100** [comment]
Actually there is no problem if you use bootstrap version of selectize css. I don't see any clean way to handle this in QueryBuilder itself.

you can also set `copyClassesToDropdown: false` in Selectize config
https://github.com/selectize/selectize.js/blob/master/docs/usage.md#data_searching

**Comment by mistic100** [comment]
f61f14d7347386d9ddc56d85d23b381dc22c8745
