### ISSUE TITLE
Problems with DatePicker

### ISSUE THREAD

**Issue by centenario** [mistic100/jQuery-QueryBuilder#263]
Hi,
when i select a date from datepicke, in any format (fi DD/MM/YYYY: 22/03/2016) the value in the ouput is like this: 22/03/20162016 , i dunno but always add 2 times year value.
Any idea?

**Comment by mistic100** [comment]
What is your config ? Which datepicker ? (there are plenty)

Did you tried to put only two "Y" instead of four ? (Check the doc of your datepicker).

(Not related to QB though)

**Comment by centenario** [comment]
Hi, it happens the same from your site, (FF 45.0.1);
![selectize_ff4501](https://cloud.githubusercontent.com/assets/5682766/13984291/79162adc-f0f5-11e5-8239-82a92b49e676.png)

**Comment by centenario** [comment]
- Datepicker jquery ui
- Yes i've tried but it always return value with 8 numbers for yera (althought i have seen value from datepicker is right)
- config is minimal, like in your examp
thans in advance

**Comment by mistic100** [comment]
In my example I don't use jQuery UI, so show your config !
Or better : create a demo, how you guys want to get real help if there is notyhing to see ?

**Comment by centenario** [comment]
Yes, you're right.
Datepicker wasnt from jquery ui.
I have made an complete demo and it works, and then i have deployed to my web app and it works right now. 
thanks!

**Comment by mistic100** [comment]
Any idea of what the problem was ?

**Comment by centenario** [comment]
I got datepicker ui in my project, it was well configured, and it worked right (even dustom theme for jquery ui was appied, but something was going wrong when datepicker setted value into input.
Now with datepicker from example it wors rigth.
