### ISSUE TITLE
Request for Order Filter alphabetically by Label

### ISSUE THREAD

**Issue by centenario** [mistic100/jQuery-QueryBuilder#264]
Hi, 
my app is multi-language and the value for Label in filters change dinamically depende the language of user.
It could be a nice option, add capability for sorting filter dropdown by Label, something like this:
sorted: true
By the way i've got this little function for making this:

```
//Function that sort array by Label:
function SortByLabel(a, b) {
    var aLabel = a.label.toLowerCase();
    var bLabel = b.label.toLowerCase();
    return ((aLabel < bLabel) ? -1 : ((aLabel > bLabel) ? 1 : 0));
}
```
And then, after setting array of filters:

`filters.sort(SortByLabel);`

I hope that can be helpfull.
Thanks.

**Comment by mistic100** [comment]
`a.localCompare(b)` is way more safe than your function.

The problem is that labels are translated only when the template is rendered so the array of filters itself can't be sorted.

I suggest you do it yourself before passing the filters to the builder.

**Comment by mistic100** [comment]
I realized the QueryBuilder translation is not dynamic (in the example it is destroyed and reinitialized with the new lang).

So yes it would be possible to sort the filters at startup.
