### ISSUE TITLE
Raw Binding String parameter always empty

### ISSUE THREAD

**Issue by purell** [mistic100/jQuery-QueryBuilder#265]
Hi,

Maybe I'm doing something wrong but I'm unable to get a raw query properly work with parameter binding. 

```
knex
.table('Product')
.whereRaw("ProductName LIKE(:ProductName_1)", {ProductName_1 : '%foo%'})
.select('ID', 'ProductName')
.then(function (rows) {
    // rows is always an empty array
});
```

In the debug console : 
```
{ method: 'select',
  options: {},
  bindings: [],
  sql: 'select "ID", "ProductName" from "Product" where ProductName LIKE (:Prod
uctName_1)' }
```

As you can see, the bindings is EMPTY. Why ?

I've also tried with : 
```
.where( knex.raw("ProductName LIKE(:ProductName_1)", {ProductName_1 : '%foo%'}) )
```
But same problem.

If I use SQL equal operator it seem to work, but as soon as I use one of the following operators "LIKE, IN, NOT IN", knex discard my binding.

My configuration : 
 - knex 0.10.0
 - sqlite.
 - Node .0.12.0

**Comment by mistic100** [comment]
I guess you openned this issue in the wrong repo.

**Comment by purell** [comment]
Sorry :(, my fault.
