### ISSUE TITLE
Does querybuilder support custom field?

### ISSUE THREAD

**Issue by HolyOne** [mistic100/jQuery-QueryBuilder#267]
I have hundreds of fields in my database. Query builder is helpful in common fields but some records have extra fields.

Can I filter records by inputting field name and value?

**Comment by mistic100** [comment]
Please precise your need

**Comment by HolyOne** [comment]
I mean I can get mongodb query from jquery querybuilder. 
It would be great if I could write a custom query in a box (on the querybuilder interface)  and it combines it with the main query.

I mean there can be a selector "custom" and I can write a custom select query inside.

**Comment by mistic100** [comment]
There would be so many ways to make it working (or break it) it's too complicated.

If you really want it to be in the builder itself, I suggest you add a standard textarea filter, and postprocess the data to achieve want you want.
