### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by lammia07** [mistic100/jQuery-QueryBuilder#270]
Hi.
Is it somehow possible to replace the language files to a translate function?
Like: 
```js
$('#builder-basic').queryBuilder({
            lang: function(stringToTranslate, languageCode) {
                return translation;
            }
        });
```
LG

**Comment by mistic100** [comment]
Hello

as the translation is not dynamic (the language cannot be changed at runtime) and don't see the in interest of this.

You can build the lang object based on `$.fn.queryBuilder.regional.en`  before transmiting to the builder.

**Comment by lammia07** [comment]
Thank you for your quick response.
Okay. I will use the translation file.
