### ISSUE TITLE
Subquery with only one operation

### ISSUE THREAD

**Issue by DHoffm** [mistic100/jQuery-QueryBuilder#275]
Hey if a subtree has only one clause it is kind of confusing to still be able to toggle the parent AND/OR buttons. In fact they do nothing in that case.

![querybuilder-logic](https://cloud.githubusercontent.com/assets/167885/14461091/55d46634-00c1-11e6-89f0-e0048885f743.png)

The should be greyed out or in some way deactivated.

**Comment by jamesjara** [comment]
thanks

**Comment by DHoffm** [comment]
I suppose I was too quick about this behaviour. What If I want something like that:

![and_or](https://cloud.githubusercontent.com/assets/167885/15531524/0ad6cd82-225b-11e6-85f0-55b854c28155.png)

The condition inside the group can not be an OR.

**Comment by mistic100** [comment]
Well that's absolutely not what you said. Please open a new issue with more detals because it's still not clear want you want.

**Comment by DHoffm** [comment]
I suppose we don't need a new case.
Here are a few examples:

1. condition a + one group with condition b -> group AND/OR selection deactivated
result: a AND/OR b
2. condition a + conditon b + 1 group with condition c -> group AND/OR selection should be activated
result: (a AND/OR b) OR/AND c

**Comment by mistic100** [comment]
I insist : new issue.

BTW your second example is totally the inverse of how QueryBuilder works :
condition a + conditon b + 1 group with condition c -> group AND/OR selection should be activated
result: a AND/OR b AND/OR (c)
the order of parenthesis is critical, and this behavior is not going the change
