### ISSUE TITLE
How do the "in" and "not_in" operators work

### ISSUE THREAD

**Issue by DHoffm** [mistic100/jQuery-QueryBuilder#276]
Hi when I try the demos from here: http://querybuilder.js.org/demo.html the "in" and "not in" operators don't seem to work properly.
I suspected the query builder to accept a list in the following format: (1,2,3,4.5....) and so on.
I'm using the latest Chrome browser and the input field is numeric and the query builder validator won't allow a comma separated list.

**Comment by mistic100** [comment]
It works exactly as expected. I can not make the assumption that the user want to use a comma as delimiter.

The operators work natively with multiple select inputs. If you want to use a plain text field, implement "valueSetter" and "valueGetter" to split and join with a comma.

**Comment by DHoffm** [comment]
"The operators work natively with multiple select inputs."

This don't seem to be the case for the demos! I can only see a basic text input.

Do you have another demo for this "natively" behaviour?

**Comment by mistic100** [comment]
Well the demo is not configured for this particular case (and the input is configured for a filter not an operator).
There is the "Category" filter of the "Plugins" demo using checkboxes.

Or try it yourself.

**Comment by DHoffm** [comment]
Ok thanks for the clarification. Can you supply some code sample on how to alter the input element for specific operators. 

Also the datepicker plugin is not working for those operators. The datepicker isn't even opening.

**Comment by mistic100** [comment]
No idea, I never did it.

**Comment by DHoffm** [comment]
So these two operators only work out of the box only for multi select input fields or multiple checkboxes?

**Comment by mistic100** [comment]
That's it

**Comment by DHoffm** [comment]
Alternatively: Is it possible to deactivate certain operators for specific types?

**Comment by mistic100** [comment]
Not sure I understand.
"operators" at filter level https://github.com/mistic100/jQuery-QueryBuilder/blob/master/examples/index.html#L234

**Comment by DHoffm** [comment]
Kind of the opposite. I found the QueryBuilder.OPERATORS which supplies the list of default assignements.
What I want is to remove the "in", "not in", "null" "not null" portion.

**Comment by mistic100** [comment]
Then define the list of operators to all others, it's not that hard.

**Comment by DHoffm** [comment]
Seems a bit of an overhead for just removing one operator to redefine everything:

```javascript
switch (type) {  
 case 'date':
 case 'integer':
 case 'double':
   filter_settings.operators = ['equal','not_equal','less','less_or_equal','greater','greater_or_equal','between','not_between'];
   break;
 case 'string':
   filter_settings.operators = ['equal','not_equal','begins_with','not_begins_with','contains','not_contains','ends_with','not_ends_with','is_empty','is_not_empty'];
   break;
 case 'boolean':
   filter_settings.operators = ['equal','not_equal'];
   break;
}
```

**Comment by mistic100** [comment]
And it would be overhead for people wanting 2 or 3 operators if the setting was reversed. This won't change, there are more important things to work on.

**Comment by mistic100** [comment]
Version 2.4.0 added `value_separator` option.

```js
$('#builder').queryBuilder({
  filters: [
    {
      id: 'name',
      type: 'string',
      value_separator: ','
    }
  ]
});
```
