### ISSUE TITLE
queryBuilder('setRules', ...) on an instance with unique-filter unique: true constraint allows multiple

### ISSUE THREAD

**Issue by prashker** [mistic100/jQuery-QueryBuilder#277]
I'm not exactly sure where the discussion should go, but I figured this should be brought up to see what the expected result **should be**.

So, take an arbitrary filter (I'm going to explain with the 'price' filter from the Demo page), and add [unique: true](http://querybuilder.js.org/plugins.html#unique-filter) globally to the QueryBuilder instance.

Then call setRules with two instances of that rule. Example.

```
var rules_basic = {
    condition: 'AND',
    rules: [{
            id: 'price',
            operator: 'less',
            value: 10.25
        }, {
            id: 'price',
            operator: 'greater',
            value: 10.00
        }
    }
};

instance.queryBuilder('setRules', rules_basic);
```

So in this case, if **price** had unique: true, I could not create the ruleset above "normally" in the interface (as expected, Price would be greyed out the 2nd time I select it from the dropdown).

However, setRules allows this no problem.

There's a disconnect, as setRules bypasses the limitation of unique-filter. Whether that was a design decision or a bug, I don't know.

Personally, I used this to my advantage earlier today when I needed to hack in a specific query for an odd request I received. However going forward it would be good to know how QueryBuilder devs considers this issue.

v2.3.2

**Comment by mistic100** [comment]
Hello
For me the behaviour is acceptable (I don't know either if it's correct either). I actually didn't consider this case, as you might see if you read the plugin code, it's only a visual change (the item is disabled) but the internal methods are not blocked.

It would actually be a bit tricky to block it as the rule is updated through multiple events (beforeAddRule, afterChangeFilter, afterChangeOperator, etc).

**Comment by prashker** [comment]
Admittedly I hadn't looked at the code prior to posting the issue but looking now it's clear that it's slightly more difficult than initially anticipated.

If we were to treat this as an inconsistency, then presumably the fix would be to ensure that subsequent instances of a duplicated filter item throws a validation error. So you'd technically still be able to setRules, but would not be able to getRules from it. With update-filter you'd be unable to normally add a 2nd filter, but should it happen, then a normal.

I think a validation error should be easier than an outright block right? The former seems just more logic is necessary for update-filter.

Still, not sure where I stand on this issue :smile:

**Comment by mistic100** [comment]
You are right, a validation check is easier to implement,.
But I'm not sure it's the right thing to do, i mean, it lets the programmer thinks it will work but it won't.

**Comment by prashker** [comment]
Fair enough, that's a good point...

At the end of the day, given the nature of JavaScript, from a malicious point of view, people could remove the unique constraint and do whatever they want (I had to do such a thing because our server side does not validate some conditions that are set as **unique: true** on the client side.)

So if the idea is to give the programmer the priority, then I'm in agreeance with you.

**Comment by mistic100** [comment]
I guess you mean if the user access the builder object (it's always possible as it's attached to the DOM) he could manually call `setRules`.

The fact is even if the library made this check, a really motivated "hacker" could overwrite QueryBuilder prototype to remove the check.

If this condition is important, the server **MUST** validate it anyway :-)
