### ISSUE TITLE
I can´t create custom operators 

### ISSUE THREAD

**Issue by Davimor** [mistic100/jQuery-QueryBuilder#278]
Hello,

Firstly thanks you very much for this plugin. I am trying to create some custom operands following this guide (http://mistic100.github.io/jQuery-QueryBuilder/#advanced) but when i pass de operators property field as an array of objects instead of strings, query builder doesn´t display any operator or error to try fixing it.

I have this example code:

```
var field = {
                id: 'name',
                label: 'Name',
                type: 'string',
				operators: [
				    { type: 'equal', optgroup: 'basic' },
				    { type: 'geo', optgroup: 'custom', nb_inputs: 3, multiple: false, apply_to: ['string'] }
				]
            };

 $('#builder-basic').queryBuilder({
                filters: [field],
            });
```

And the result is:
![image](https://cloud.githubusercontent.com/assets/12715270/14814520/ed86590c-0ba6-11e6-8618-7434705cedb0.png)

Thanks you again and sorry for the inconvenience and my english.

**Comment by mistic100** [comment]
So I guess you figured out.

For other people : new operators can only be crated through teh global "operators" parameter. "operators" at filter level is ONLY to define a sub-set of global operators.

**Comment by Davimor** [comment]
Yes, thanks very much for your work!

**Comment by SarahTrees** [comment]
For those who like me, want to add a simple custom operator, my fiddle.
https://jsfiddle.net/89byg4wh/12/

**Comment by kevalbhatt** [comment]
@SarahTrees  why to override default option. QueryBuilder allows custom operators options as well.

**Example:**

```
this.ui.builder.queryBuilder({
    plugins: ['bt-tooltip-errors'],
    filters: filters,
    select_placeholder: '--Select Attribute--',
    allow_empty: true,
    conditions: ['AND'],
    allow_groups: false,
    operators: [
        { type: '=', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['number', 'string'] },
        { type: '!=', optgroup: 'custom', nb_inputs: 2, multiple: false, apply_to: ['number', 'string'] },
        { type: '>', optgroup: 'custom', nb_inputs: 3, multiple: false, apply_to: ['number', 'string'] },
        { type: '<', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['number', 'string'] },
        { type: '>=', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['number', 'string'] },
        { type: '<=', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['number', 'string'] },
        { type: 'contains', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['string'] },
        { type: 'begins_with', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['string'] },
        { type: 'ends with', optgroup: 'custom', nb_inputs: 1, multiple: false, apply_to: ['string'] }
    ],
    lang: {
        add_rule: 'Add filter',
        add_group: 'Add filter group',
        begins_with: 'begins_with'
    },
    rules: rules_widgets
});
```

**Comment by mistic100** [comment]
She does this because she wants to keep all default operators and a new ones, it's simplier than re-defining everything. And perfectly valid (this does not modify the defaults)
