### ISSUE TITLE
Plugin similar to invert

### ISSUE THREAD

**Issue by DHoffm** [mistic100/jQuery-QueryBuilder#280]
Hi I'm using the standalone version and would like to use a custom plugin similar to the invert plugin I copied the invert plugin and changed the naming and added the missing references (Group, Rule etc).

I setup a demo:
https://plnkr.co/edit/GFVoVx9d3vc1p2MYZM23?p=preview

Some problems I came across:
1. So far I don't know how to load the Node prototype
2. Not sure if I included the various other prototypes correctly like Group, Rule, Model etc.
3. the demo runs into an infinite loop

Do you have any advice what needs to be changed to get the demo running.

**Comment by mistic100** [comment]
1. instead of testing against "Node", test against "Group" AND "Rule"

2. this is useless `var Model = c.prototype.getModel`. getModel is in the prototype, so call-it from the builder : `self.getModel($group)`

3. I don't have time for this

If you want further help explain what you want from scratch, without ygly copy-paste

**Comment by DHoffm** [comment]
Thanks for your hints. Essentially I want to enable or disable a select list with this button on the group level which is used to specify the filters available for this group and sub groups.

**Comment by DHoffm** [comment]
The infinite loop i ran into is caused by 1.

Just for clarification. What is this part used for and when is it called:

```
 if (!(node instanceof Node)) {
            console.log(node)
            if (!this.model.root) return;
            options = node;
            node = this.model.root;
        }
```
The console.log is never fired.

**Comment by mistic100** [comment]
If the developer calls the `invert` method externally (it's a public method) without parameter (or only the options hashmap), it applies the invertion to the root group.

Of course in your case Node is not defined and the recursion always falls here.

Either you remove this test or you replace it by `!(node instanceof Group) && !(node instanceof Rule)`.
