### ISSUE TITLE
How to do date validation: Need help

### ISSUE THREAD

**Issue by Lidiak** [mistic100/jQuery-QueryBuilder#281]
I have tried to do date validation following the example in (https://github.com/mistic100/jQuery-QueryBuilder/blob/master/examples/index.html) but it is not still successful. So I need help. Here is how I wrote it this way but it doesn't work

{
    id: 'rate',
    label: 'Rate',
    type: 'date',
    validation: {
      min: 12-1995  //I though this the format for a valid MomentJS string format
    },

**Comment by mistic100** [comment]
Hi

first of all, date validation REQUIRES Moment.js to be loaded.

Now about your code, what do you think "12-1995" will do ? Answer : "-1983" because you wrote it as numbers.

The docs says about "validation.min"
> For date, time, datetime: minimum value, respecting format

Which involves you must provide a format.

Like
```
{
id: 'rate',
label: 'Rate',
type: 'date',
validation: {
  format: 'DD-MM-YYYY'
  min: '01-12-1995'
},

**Comment by Lidiak** [comment]
Thanks for the quick reply but can I use the format just for a month and year as I did since I dont see that format in the Moment.js string format

**Comment by mistic100** [comment]
Off course, it's just an example

**Comment by Lidiak** [comment]
Thank you very much. I wrote it this way and it worked

{
id: "rate",
label: "Rate",
type: "date",
 "validation":{
	  "format": "YYYYMM",
	     "min": "190001",
	     "max": "200001"
	}
},

**Comment by Lidiak** [comment]
I have more question, I added validation for string as regular expression, so I need help. Here it is how I did it?
{
  "label": "Zip Code",
  "id": "15328",
  "type": "string",
  "operators": "[''in'']",
  "validation":{
	  "format": "/^[0-9]{5}$/"
	}
}

2) How to specify today's date in the validation, is it possible in Moment.js?

**Comment by mistic100** [comment]
1. `"/^[0-9]{5}$/"` makes no sense, either you declare your regex as a regex object : `/^[0-9]{5}$/` (no quotes) or your declare your regex as a string : `"^[0-9]{5}$" (no slashes)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

2. as simple as `"min": moment().format('YYYYMM')`

**Comment by Lidiak** [comment]
Hi, 

Thanks for your reply. Neither of them are working. I did this for today's date. I want the max to be today's date and min 190001
{
id: "rate",
label: "Rate",
type: "date",
 "validation":{
	  "format": "YYYYMM",
            "min": "190001",
            "max": "moment().format()"
       }
}

**Comment by mistic100** [comment]
I never used quotes around `moment().format('YYYYMM')`

excuse me but I'm not here to teach you JavaScript. Closed.
