### ISSUE TITLE
sql-parser doesn't parse column names with '(' brackets

### ISSUE THREAD

**Issue by mkaushik10** [mistic100/jQuery-QueryBuilder#286]
Hi,
I am trying to use the query-builder for my project. I have database table with columns like 'Result(1/0)'. When I pass this to query-builder as query, it is not able to parse it and gives error.
I tried  `'[Result(1/0)] = 0'` and `Result(1/0) = 0`. 
Can you please suggest how to add this in the lexer to support this.
Thanks.

**Comment by mistic100** [comment]
Sorry I absolutely do not have the knowledge for this kind of change in the lexer.
By the way this issue should have been opened in the repository of sql-parser, my fork or original.
