### ISSUE TITLE
Error when try to SetRules

### ISSUE THREAD

**Issue by centenario** [mistic100/jQuery-QueryBuilder#289]
Hi, im getting this error message:

`Error: NOTHING CONSUMED: Stopped at - '#[2]# = '01/06/2016' AND #[12]'` 

when i trying to set rules from SQL like this:

`$('#builder').queryBuilder('setRulesFromSQL', "#[2]# = '01/06/2016' AND #[12]# > 0");`

#[2]# is the ID from a filter that is gonna be "decoded" in stored Procedure.

Thanks in advance

**Comment by mistic100** [comment]
The SQL parser is rather limited and does not support this kind of exotic syntax, fields must be textual only.

If you have the knowledge in lexers (and time) you can submit a change to
https://github.com/mistic100/sql-parser and/or https://github.com/forward/sql-parser
which might help #286 too.
