### ISSUE TITLE
Supporting Pagination when using "selectize.js" DropDown with QueryBuilder

### ISSUE THREAD

**Issue by smark111** [mistic100/jQuery-QueryBuilder#290]
Hello,

Thanks for the good plugin. Have a question question. We are using the selectize.js plugin together with QueryBuilder plugin.

The issue, we have several items to load, and trying to load all items in list is taking long time to load. So we are tying to see how we can support pagination for selecting list of items that are used in Query.

Following is how we envision the plugin extension needs to be work,

1. Next to Drop Down shown using "selectize.js", show "Select Items" hyperlink, clicking on which will show Bootstrap Modal, with "JQuery Datatable" with support for pagination
2. User selects list of items to be added from the Datatable and clicks OK, closing Modal Dialog.
3. Drop Down (Multi Select) using "selectize.js" shows list of all selected Items. User can remove items if required using selectize.js remove item button.
4. User can again click "Select Items" link next to the same Drop Down, and add more items to the Drop down.
5. On clicking "Get Rules", ID's for all Selected Items are added to response JSON

Can you please provide guidance on how to implement this Plugin for usage with Query Builder.

Thanks

**Comment by mistic100** [comment]
I really don't know how I could help you... what kind of help are you expecting exactly ?
All I would be able to tell is already in the doc http://querybuilder.js.org/dev/plugins.html and http://querybuilder.js.org/dev/events.html

**Comment by mistic100** [comment]
BTW as I understand your need, it's absolutely not related to QueryBuilder, you just want a selectize with pagination. QueryBuilder does not care about where and how the data come from.

select2 has a built-in paginator http://embed.plnkr.co/db8SXs/preview

**Comment by smark111** [comment]
Thanks for the quick reply. The pagination provided by Select2 is good. We use Select2 at several places on other pages also. 

Wanted to check if the "QueryBuilder" plugin supports Select2, or if not if there any plans to support Select2 in future. 

Thanks

**Comment by mistic100** [comment]
As the doc says, the bigger supports every jQuery plugin applicable to an input.

**Comment by smark111** [comment]
Thanks. Will try with Select2. Thanks again for your help.
