### ISSUE TITLE
How to append multiple values to rule model

### ISSUE THREAD

**Issue by ShinkarevDV** [mistic100/jQuery-QueryBuilder#291]
How to append multiple values to rule model without inputs? I need to append values from another component, invoked from rule when filter is selected. I my case rule not sets value, rule only invokes some component who must set value.

**Comment by mistic100** [comment]
What you said makes no sense at all without knowing what you are trying to achieve

**Comment by ShinkarevDV** [comment]
I describe the working principle:
I have some filter. If i select that filter, in rule must appears 'in' operator and some link. Click on link opens modal window where i can select multiple values.

**Comment by mistic100** [comment]
Much better.

In the definition of the filter :
- define a custom `input` as a function that returns the HTML string of your link and the necessary bootstrap for your popup (see the source code of the `coord` example http://querybuilder.js.org/assets/demo-widgets.js)
    - once you close the popup, store the data somewhere (for example in the element "data") and trigger the "change" event on the link (needed to inform the builder the value changed)
- define `valueGetter` and `valueSetter`  to set the value between the builder model and your custom storage

Quick untested example :
```js
{
  id: 'field',
  name: 'It opens a popup',
  type: 'integer',
  input: function(rule, name) {
    // click on link via delegation
    var $container = rule.$el.find('.rule-value-container');
    
    $container.on('click', 'a', function(e) {
      e.preventDefault();
      var $a = $(this);

      // get previous value
      var value = $a.data('value');

      // open the popup
      // once finished do this :
        $a.data('value', yourValue);
        $a.trigger('change');
    });
    
    return '<a href="#">Select value</a>';
  },
  valueGetter: function(rule) {
    return rule.$el.find('.rule-value-container a').data('value');
  },
  valueSetter: function(rule, value) {
    rule.$el.find('.rule-value-container a').data('value', value);
  }
}
```

**Comment by ShinkarevDV** [comment]
Thanks for quick help. You saved my day.
