### ISSUE TITLE
Multiple Entities support

### ISSUE THREAD

**Issue by boopathi-rs** [mistic100/jQuery-QueryBuilder#293]
Hi,

I have got my database tables associated using JPA in the backend. I would like to use querybuilder.js to create where clause involving multiple tables. I understand that this plugin supports creating where clause for one table only. Please correct me if I am wrong. 

Thanks
B

**Comment by mistic100** [comment]
Hi

you are wrong :-)

nothing prevents you to set the filters field to something like `users.email`, `operations.type` etc.

**Comment by boopathi-rs** [comment]
That's brilliant. Thank you!

**Comment by mistic100** [comment]
Can you close ?
