### ISSUE TITLE
Groups are not restored from SQL

### ISSUE THREAD

**Issue by DHoffm** [mistic100/jQuery-QueryBuilder#294]
Hi I came across a problem when a group has only a sub group but no rule.

![group_sql](https://cloud.githubusercontent.com/assets/167885/15544499/3ac336aa-2299-11e6-98c7-e7377ab2ccc7.png)

The generated sql from $('#builder').queryBuilder('getSQL', false, true) for that is the following: 

`( category = 2 ) `

If try to recreate the builder via set setRulesFromSQL the outer group is stripped.

This might be an issue with the sql-parser.

**Comment by mistic100** [comment]
I don't see it as an issue it's perfectly remove empty and invisible groups. And as you said this the behaviour of the parser, which, as said many times, I don't have the knowledge to update.
