### ISSUE TITLE
Unable to load rule with sql query having NOT BETWEEN 

### ISSUE THREAD

**Issue by ultrasonicsoft** [mistic100/jQuery-QueryBuilder#296]
Hi,

I'have referred sql-parser and when I import simple sql rule like below, query builder is loading rule perfectly.
Sql Rule:  Temperature > 5

Builder output:
![image](https://cloud.githubusercontent.com/assets/4145169/15597942/eba7b860-23f2-11e6-91b4-7f97a2137514.png)

But when I set complex rule with Between and Not between, it's saving to db correctlike like below:

but when I'm trying to load rule in builder, it's unable to.
Sql rule: Temperature NOT BETWEEN 1 AND 2

Builder output:
![image](https://cloud.githubusercontent.com/assets/4145169/15597949/f7af0ec4-23f2-11e6-84e6-faa05a4f4319.png)

![image](https://cloud.githubusercontent.com/assets/4145169/15597936/d49dcf10-23f2-11e6-978e-3af6eab345ba.png)

I debugged in console, and I see error is thrown in file query-builder.standalone.js line number 4215.   var parsed = SQLParser.parse(data.sql);

Could you please give me some hint how to fix this?

Thanks!

**Comment by mistic100** [comment]
Update sql-parser (my fork, not the iriginal)

**Comment by mistic100** [comment]
@ultrasonicsoft  feedback ?

**Comment by ultrasonicsoft** [comment]
Sorry for delayed response. 

Will give try. That requirement has been put on hold for this iteration.

 Thank you!

**Comment by mistic100** [comment]
Reopen this issue if you work in it.
