### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by rhythmicdevil** [mistic100/jQuery-QueryBuilder#297]
I'd like the option to have one or more criteria be required and immutable. For instance I want to populate the query builder with "fieldA = 1234" and that cannot be changed.

**Comment by mistic100** [comment]
`setRules` with flags http://querybuilder.js.org/#methods

**Comment by mistic100** [comment]
```js
$(...).queryBuilder('setRules', [{
  "id": "price",
  "value": 10.5,
  "readonly": true
}]);
```

**Comment by rhythmicdevil** [comment]
Thank you.
