### ISSUE TITLE
[Question] Web Jars

### ISSUE THREAD

**Issue by rhythmicdevil** [mistic100/jQuery-QueryBuilder#298]
Hi,
do you maintain or have anything to do with the [Web Jar for Query Builder]( http://www.webjars.org/)? It appears to break on the dependency for extendext. 

Failed to collect dependencies at org.webjars.bower:jQuery-QueryBuilder:jar:2.3.2 -> org.webjars.bower:jquery-extendext:jar:[0.1.1,0.2): No versions available for org.webjars.bower:jquery-extendext:jar

**Comment by mistic100** [comment]
Hello,

absolutely not.

I added "jquery-extendext" (pretty simple) but it won't work anyway because QueryBuilder requires doT#master that can't be deployed on WebJars

**Comment by rhythmicdevil** [comment]
Ok cool, thanks for the update. I am posting my Maven config here so that anyone who does need to it work can save some time. 

```
		<dependency>
			<groupId>org.webjars.bower</groupId>
			<artifactId>jQuery-QueryBuilder</artifactId>
			<version>2.3.2</version>
			<exclusions>
				<exclusion>
					<groupId>org.webjars.bower</groupId>
					<artifactId>jquery-extendext</artifactId>
				</exclusion>
				<exclusion>
					<artifactId>doT</artifactId>
					<groupId>org.webjars.bower</groupId>
				</exclusion>
				<exclusion>
					<artifactId>jquery</artifactId>
					<groupId>org.webjars.bower</groupId>
				</exclusion>
				<exclusion>
					<artifactId>bootstrap</artifactId>
					<groupId>org.webjars.bower</groupId>
				</exclusion>
			</exclusions>
		</dependency>
```
