### ISSUE TITLE
Data Issue with Coordinates filter widget

### ISSUE THREAD

**Issue by randyabbey** [mistic100/jQuery-QueryBuilder#299]
It seems you cannot add multiple filters using the "Coordinates" custom input definitions. If I add multiple filters from an out side data source the second select box always uses the data from the last filter. I have tried many routes around this with no success. Is there a way to get around this?

**Comment by mistic100** [comment]
Show some code !

**Comment by randyabbey** [comment]
working on a demo now. it will be up shortly. thanks.

**Comment by randyabbey** [comment]
I add a demo on jsfiddle. https://jsfiddle.net/randyabbey/m0g1fswf/ IT is using dummy data that will not make a lot of sense for rules, but it will show the issue that I am having. Thanks.

**Comment by mistic100** [comment]
aren't you missing a "set rules" button ?

**Comment by mistic100** [comment]
but if I understood your problem, it's in no way related to QueryBuilder, you just fall in one of the main JavaScript mistakes.

Let's try to explain it :
You register an event handler in a loop (the "change" event on "[name='+name+'_1]").
One of the loop variables is "qdata" which is NOT scoped to the inside of the loop (this is only possible with ECMA2015 "let" keyword).
As a result, every event handlers use the last value of "qdata".

To solve this, you need  to add a closure around the event handler.
See http://stackoverflow.com/questions/6487366/how-to-generate-event-handlers-with-loop-in-javascript

**Comment by randyabbey** [comment]
thanks. that did the trick. glad it was a silly oversight. FYI. great query builder. best UI I have seen and lots of great functionality
