### ISSUE TITLE
IE 8/9 support

### ISSUE THREAD

**Issue by tedliang** [mistic100/jQuery-QueryBuilder#3]
Great project! Exactly what we are after. Thanks for sharing. Any particular reason not supporting IE 8 or 9?

**Comment by abeverley** [comment]
Great - has support now been added for IE8? Sorry for not doing it myself. Thanks.

**Comment by mistic100** [comment]
no, if nobody do it it will never be supported
IE8 is too old, move on

ps: I am working (professionally) with big industries with old computer infrastructure and everyone uses at least IE9

**Comment by abeverley** [comment]
Like I say, I'm happy to do it, and I have it working (ish) on a local copy. Obviously I'd rather merge it upstream though.

Of course, no developer (including me) wants to support IE8. But unfortunately it is widespread in the public sector in the UK, and that's who I work with.  Awful, I know, but hopefully there will be progress soon. The main government department I work with only got rid of IE6 last year.

**Comment by abeverley** [comment]
Any chance of leaving this open please? I'll aim to send the PR this month. Thanks.

**Comment by mistic100** [comment]
will you ? after I rewrote 60% of the code last week ?

**Comment by abeverley** [comment]
I didn't realise that you'd rewritten the code, but yes, I'll certainly attempt to get it working. Thanks.

**Comment by ALenfant** [comment]
Any news on the PR?
I love jQuery-QueryBuilder but v2 doesn't work on ie8

**Comment by abeverley** [comment]
Really sorry. I said March and now it is May... I'll have a look at the weekend.

**Comment by maverickIndia** [comment]
Nice component. I liked it and serves majority of the use cases.

@abeverley 
Anything on IE8 which I can use as of now, have to make this component used in our project ... Needs support on IE8. Any help ?

**Comment by abeverley** [comment]
Okay, I've started looking at this. It seems that most problems can be worked around with the use of shims, but the stumbling block I have come across is `defineProperty`, which can't be provided by a shim as it's half-implement by IE8 (see "may fail" in https://github.com/es-shims/es5-shim).

I'm trying various things to work around this, but in the meantime does anyone have any suggestions?

**Comment by abeverley** [comment]
The diff at the link below shows a way of making this work with IE8. As per the comment above, the main issue is that `defineProperty` is not fully implemented in IE8 (it can only be used on a DOM object). The only way I can see to fix this is to create a separate setter function and access the properties directly (or also create a getter function).

It's not fully tested, but /seems/ to work okay.

If you let me know any comments you have, then I can work on it accordingly. There are also CSS issues, which I can look at in due course.

It requires the es5 shims.

https://github.com/abeverley/jQuery-QueryBuilder/commit/0c735b3748a04e09738e4b84c15451b90c8f240e

Andy

**Comment by mistic100** [comment]
- you'd better work on the "src" files as explained in CONTRIBUTING.md file
 - why the `Node.getParent` ? it's not coherent with everything else.
 - if you don't rely anymore on the `__` internal object, just remove it
 - there is a big test suite, use it

**Comment by mistic100** [comment]
Anyway my point of view is still http://zurb.com/article/1265/ie8-is-going-the-way-of-the-dodo-so-why-s
I'm ok to improve the doc for IE9, but not the sacrifice code lisibility and syntax sugar for IE8

**Comment by abeverley** [comment]
Thanks for the quick reply.

Sorry, I should have been clearer: this wasn't meant to be a proper patch, hence the hacky presentation. It was more of a "would you be prepared to merge something like this?".

If you don't want to incorporate changes like this (as your second comment suggests), then I'll completely understand. I am the last person that wants to support IE8. Unfortunately when you're a small supplier to a multi-billion dollar organisation, you don't get a choice (if I don't support it, then they'll just use another supplier who does). I don't think any organisation needs convincing they need to move away from IE8, but these things don't happen overnight (it continues to amaze me how slow change management is in most large organisations).

Anyway, I can keep this as a separate repository for others that also need IE8 support, or I can do a proper PR if you're prepared to make such changes. Just let me know.

Thanks,

Andy

**Comment by sukima** [comment]
If IE8 is a wanted feature (temporary) then it should be based on a branch and not part of the main upstream. An `ie8-support` branch. It should also have a disclaimer in that branches README and a `console.log()` deprecation warning at time of instantiation.

I think IE8 is finally at the point where most people no longer have to look back. Support is an edge case and not something the core team should continue to develop on.

**Comment by mistic100** [comment]
I am ok for a dedicated branch

**Comment by maverickIndia** [comment]
Hi 

I am able to have a fully working version of this component in IE-8. Along with all JS functions which was not supported on IE-8 and all CSS-3 and html5 fixes. Will place a demo link shortly with IE-8. All the plugins also works fin in IE-8.

I had put a pull request. once it works well try to get it into the main stream. 

Once again thanks for the well thought, feature rich component !!!

**Comment by GrgDmr** [comment]
Hi @maverickIndia 

you could share your version with us ? I would use this library in IE8 browser.

Thanks
