### ISSUE TITLE
Issue in adding new operator

### ISSUE THREAD

**Issue by nidhin038** [mistic100/jQuery-QueryBuilder#300]
I need to add new operator "is_contained_in" in the operator drop down. I have added it in the library like this 
```
is_contained_in: {
            type: "is_contained_in",
            nb_inputs: 0,
            multiple: !1,
            apply_to: ["string"]
        }
```

But when I select this option in the dropdown, the corresponding input field disappears.  a style display none gets added to the div .rule-value-container

**Comment by mistic100** [comment]
Why do you set nb_inputs to 0 ?

**Comment by mistic100** [comment]
Hello ?
