### ISSUE TITLE
has_operator_oprgroup - Typo?

### ISSUE THREAD

**Issue by prashker** [mistic100/jQuery-QueryBuilder#304]
[See L16 in core.js](https://github.com/mistic100/jQuery-QueryBuilder/blob/11259a944c4143e46c883ca684524f9ad7c5d09f/src/core.js#L16)

Other references in the core refer to has_operator_op**t**group. Due to the flow of the code, I don't think this actually results in a bug, just an unnecessary variable.

**Comment by mistic100** [comment]
yes it's a typo, will be fixed.
