### ISSUE TITLE
Does Query builder support GUID?

### ISSUE THREAD

**Issue by raj-vel** [mistic100/jQuery-QueryBuilder#305]
Hello Team,
I want to add one of the type as GUID in query builder, but it doesn't support it. So i am using string. Is there any way to achieve Query builder to support GUID?

**Comment by mistic100** [comment]
Hi, there is no "team".

What do you mean by "support GUID" ?

**Comment by raj-vel** [comment]
The various data types supported by QueryBuilder is string, integer, boolean, double, date. And i see for these data types, in build validation is also done by default. I want to use the data type "GUID" inside query builder. Does query builder support/allow GUID data type?

**Comment by mistic100** [comment]
That does not answer the question. What do you expect of this support ? in what it differs from a string ?
Anyway GUID is not a time in Javascript, I really don't see what you want.

**Comment by raj-vel** [comment]
In my project, i want the textbox in query builder to allow "GUID" which i can achieve by using input as text and type as string. Later based on type i want to validate or take some action. But in this case, GUID is treated as string so i couldn't differentiate based on type which is GUID and which is string. So i am asking you if query builder supports GUID as one of the data type like string, it would be great. Or please let me know if there are any work around.

**Comment by mistic100** [comment]
Ok got it, you want to check if the input is an valid GUID. Just use `validation.format` [cf doc](http://querybuilder.js.org/#validation) with a regex (first result on stackoverflow)

```js
/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
```

**Comment by mistic100** [comment]
Or use `validation.callback` with an external validation tool, still on the first stackoverflow result : http://stackoverflow.com/a/25171486/1207670

**Comment by raj-vel** [comment]
If i do this, i could validate GUID input. What if I want to take some action later based on the input type?
For example, i added string datatype instead of GUID. Later i GetRules, on that the type will be String. There I may not identify GUID fields because all will be string.

**Comment by mistic100** [comment]
It's your data model, you should know which field is a GUID and which is not. Anyway I cannot help you more here, as I said, "guid" in Javascript is not a thing (actually I none of the languages I know).
