### ISSUE TITLE
Unable to add custom operator

### ISSUE THREAD

**Issue by power-power** [mistic100/jQuery-QueryBuilder#306]
I am attempting to add a custom operator. For the sake of simplicity, I used the one provided in your sample code:

`{`
`    id: 'test',`
`    label: 'Test',`
`	type: 'string',`
`	operators: [`
`	  { type: 'equal', optgroup: 'basic' },`
`	  { type: 'not_equal', optgroup: 'basic' },`
`	  { type: 'geo', optgroup: 'custom', nb_inputs: 3, multiple: false, apply_to: ['string'] }`
`	]`
` }`

However, that yields an `query-builder.js:2602 Uncaught ConfigError: Filter operators must be global operators types (string)` error

**Comment by mistic100** [comment]
And did you try to understand what this error means reading the doc ?

see #278

**Comment by power-power** [comment]
Ah.. I see what you mean now. For those who may be confused as I was, custom operators are  defined one level above filters, not within.

Appreciated!
