### ISSUE TITLE
Generate JS file for the QueryBuilder

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#307]
Hi all, 

I know this question is not related to any issues with QueryBuilder but wanted to see if someone did something similar or had any ideas as I'm not an expert with JS.
We are designing DB to have the model for Filters and Groups including type, operators, etc. The idea is - when the Application starts up we are going to read from DB and generate all objects (for filters and groups) to be set later on the QueryBuilder. I started with a simple JSP page that uses Jquery to call Java Servlet and get objects iterate through it and generate JavaScript array object for the filters and optgorups. However since that's all "static" and does not change between releases I was thinking if the Java code can somehow generate JavaScrips file or JSON file that can easily be used later in the JSP to get a reference to the JS arrays (instead of doing that logic in the Jquery every time the JSP renders). 

Thanks,
Nick

**Comment by mistic100** [comment]
Hello
sorry but this a not forum

you could ask your question on stackoverflow (by making it more specific and agnostic of QueryBuilder) or any other general forum

**Comment by nikataus** [comment]
I understand. I was actually able to generate JS file on Application startup that should be used by the JSP on setting the QueryBuilder. 
Thanks.
