### ISSUE TITLE
jquery query builder validation not working

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#309]
Jquery query builder default validations are not working, this is my plunkr link http://jsfiddle.net/Balajivaishnav/ap9gxo4L/237/ for you reference, please help me in solving this issues

**Comment by mistic100** [comment]
You are using very old versions grabbed I don't know where (1.3.0-SNAPSHOT ??? this is totally outdated).

Please update your fiddle with the last version from jsdelivr https://www.jsdelivr.com/projects/jquery.query-builder
And fix your bad include of datepicker.
And there should not be any "link" or "script" in the HTML of a fiddle

**Comment by mistic100** [comment]
By the way, if you don't include MomentJS the date validation cannot work.

**Comment by DeveBj** [comment]
@mistic100 I have customized the query-builder.standalone.js for my need, but with out any modification to the query-builder.standalone.js the validation part is working correctly
here is the file link which I have customized [http://pastebin.com/CFVUG9BR](url)

**Comment by DeveBj** [comment]
have any solution for this

**Comment by mistic100** [comment]
Please fix your Markdown, this not how you create links, you reversed the url and the legend, or just paste the link without any markdown.

**Comment by mistic100** [comment]
What are you expecting ? you want me to read the 2000 lines of code and try to understand what you changed ? no way.

**Comment by DeveBj** [comment]
ohh buddy hold on, will tell you my modifications

**Comment by DeveBj** [comment]
http://pastebin.com/sxTbisYz this is my link

I have modified the operator added a new operator called date_equal, date_not_equal, date_less, date_less_equal, date_greater,date_greater_equal, I have added mod like #{0}# so that I will get my date output as (date ='#2016/06/14#'), now you got it

**Comment by mistic100** [comment]
You don't have to fork the lib to create new operators http://querybuilder.js.org/#operators
And don't really see the point of creating new operators just for dates.

Now for your problem of validation : you NEED MomentJS otherwise no validation can be performed on dates.

**Comment by DeveBj** [comment]
in my local machine am having moment.js, actually no validation is working incluisive of string and integer also

**Comment by mistic100** [comment]
then fix your fiddle, I can't help you there

**Comment by mistic100** [comment]
Would you please share with others what was the problem ?
