### ISSUE TITLE
Uncaught TypeError: Cannot set property 'queryBuilder' of undefined

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#311]
Am including query builder in angular 2 but while placing the local script tag am getting this error can any body tell me whats is wrong   

getting Uncaught TypeError: Cannot set property 'queryBuilder' of undefined

**Comment by mistic100** [comment]
Didn't you forget to include jquery before querybuilder ?

**Comment by DeveBj** [comment]
yeah am doing it, actually am loading the html file from typescript

this is my type script code

```
import {Component} from 'angular2/core';
import {
    FORM_DIRECTIVES, FormBuilder, ControlGroup, ControlArray, Validators, NgForm, Control,
    AbstractControl
} from 'angular2/common';

@Component({
	selector: 'my-app',
	templateUrl:'app/template_rule.html',
	directives: [FORM_DIRECTIVES],
})
export class AppComponent {
  userForm: ControlGroup;
  constructor(private fb: FormBuilder) {
   this.userForm = fb.group({
      rules_list:  new ControlArray([])
    });
    this.rules_list();
 }
 
 rules_list(){
   this.userForm.controls['rules_list'].push(this.fb.group({
        select_state: this.fb.control("",Validators.compose([Validators.required])),
        rules: this.fb.control("", Validators.required),
        pass_state: this.fb.control("", Validators.required),
        fail_state: this.fb.control("", Validators.required)
    }));
 }

 removeAdress(ctrl) {
   let addressBookList = (<Array>(<ControlGroup>this.userForm.controls['rules_list']).controls);
   for(var i = 0; i < addressBookList.length; i++) {
        console.log("each rules", ctrl);
        if(addressBookList[i] == ctrl) {
            console.log("rules to remove", addressBookList[i]);
            addressBookList.splice(i, 1);
            (<ControlGroup>this.userForm.controls['rules_list']).updateValueAndValidity();
            break;
        }
    }
 }
 
 submitRules() {
   console.log(this.userForm.value)
 }

 isRequired(select_state: string): boolean {
      if (Object.keys(this._validationMessages).includes(select_state)) {
        return Object.keys(this._validationMessages[select_state]).includes('required');}
      return false;
  }
}
```

**Comment by mistic100** [comment]
So I will answer exactly the same thing as before : **submit a complete live demo.**

And I don't see anything call to queryBuilder here so I don't' know why you show it.

**Comment by DeveBj** [comment]
hey here is the [link](http://plnkr.co/edit/d38iwjLhJzTjM5t46zD7?p=preview) for complete live demo 

in this there will be a button in top left corner click that it will keep on adding a set of fields, in that set of fields there will be a text box if you click that text box a modal will pop up, in that only am rendering the query builder, the buttons will be showing but the core functionality part is not showing in that modal pop up, the query builder script is in app/template_rule.html file and the necessary libraries are included in index.html file, hope you understood it if have any doubt please ping me

**Comment by mistic100** [comment]
I don't see any error, the builder is just not initializing. So as I don't know Angular 2 you probably will have to figure it by yourself.

And you failed your CSS imports by the way.

**Comment by DeveBj** [comment]
not initializing means still I don't get you, and can you say what css I have left in adding it

**Comment by mistic100** [comment]
I mean nothing is happening, the #builder div is still empty, so I guess some part of your directive is not working but **I don't know Angular 2** I don't have time to dig in there to fond your error.

Just open your console, you will see four 404 errors on CSS

**Comment by DeveBj** [comment]
okay

**Comment by DeveBj** [comment]
Solved this issue by loading the script file dynamically in angular 2

below are the code to load dynamically

load_script(){
var head=document.getElementByTagName('head')[0];
var script=document.createElement('script');
script.type='text/javascript';
script.src='js file url'
head.appendChild(script);
}
