### ISSUE TITLE
How to use query builders, with dynamic filters

### ISSUE THREAD

**Issue by shivendramca10** [mistic100/jQuery-QueryBuilder#312]
Hi 
I also user query builder and my requirement is that I would like to bind filter value from database.
Please suggest me how is doing work.

I get all values from database using ajax and store in array and array value assign in filter but this is not working. i have use local storage of browser

Please suggest me

error: Uncaught ConfigError: Missing filter 0 id

Thanks...

**Comment by mistic100** [comment]
Do I really need to ask for a demo ? again ?

**Comment by shivendramca10** [comment]
yes mistic100 
I have need your suggestion. 
Please tell me.

**Comment by mistic100** [comment]
What ?? I am asking you to post your code ! You can't request hero if you don't show what you do.

**Comment by shivendramca10** [comment]
i have declare a array 
var filtersArray = [];
var vformat = "";
var pformat = "";
var todayBtn = "";
var todayHighlight = "";
var autoclose = "";
var f = "";
var v = "";
var p = "";
var sPath = 'AjaxMethods.aspx/';
$.ajax({
    type: "POST",

    url: sPath + "Getvalues",
    contentType: "application/json; charset=utf-8",

    dataType: "json",
    crossDomain: true,
    success: function (r) {
        debugger
        for (var i = 0; i < r.d.length; i++) {
           
            var id = r.d[i].id;
            var label = r.d[i].label;
            var type1 = r.d[i].type;
            var plugin = r.d[i].plugin;
            //f = "{id: '" + id + "', label: '" + label + "', type: '" + type1 + "', plugin: '" + plugin;
           
            if (r.d[i].AlertValidationId != "" && r.d[i].AlertValidationId != null) {
                var alertValidationId = r.d[i].AlertValidationId;
               debugger
              // validation(alertValidationId);
                $.ajax({
                    type: "POST",
                    url: sPath + "GetValidationbyid",
                    data: '{avid: ' + alertValidationId + '}',
                    contentType: "application/json; charset=utf-8",

                    dataType: "json",
                    crossDomain: true,                    
                    success: function (data) {
                        //alert(JSON.stringify(a.d));
                        for (var j = 0; j < data.d.length; j++) {
                            alert(data.d[j].format);
                            vformat = data.d[j].format;
                            //v = "validation:{format: '" + vformat + "'}";
                        }
                    },
                    error: function (xhr, status, error) {
                        var err = eval("(" + xhr.responseText + ")");
                        alert(err.Message);
                    }
                });
               
            }
            if (r.d[i].PluginConfigId != "" && r.d[i].PluginConfigId != null) {

                var pcId = r.d[i].PluginConfigId;
                debugger
               // PluginConfig(pcId);
                $.ajax({
                    type: "POST",

                    url: sPath + "PluginConfigbyid",
                    data: '{pcId: ' + pcId + '}',
                    contentType: "application/json; charset=utf-8",

                    dataType: "json",
                    crossDomain: true,
                    success: function (r1) {
                        for (var k = 0; k < r1.d.length; k++) {
                            pformat = r1.d[k].format;
                            todayBtn = r1.d[k].todayBtn;
                            todayHighlight = r1.d[k].todayHighlight;
                            autoclose = r1.d[k].autoclose;
                          
                        }

                    },
                    error: function (xhr, status, error) {
                        var err = eval("(" + xhr.responseText + ")");
                        alert(err.Message);
                    }
                });
               
            }
            
            f = "{id: '" + id + "', label: '" + label + "', type: '" + type1 + "', plugin: '" + plugin;
            v = "validation:{format: '" + vformat + "'}";
            p = "plugin_config: { format: '" + pformat + "', todayBtn: '" + todayBtn + "', todayHighlight: '" + todayHighlight + "', autoclose: '" + autoclose + "'}}";
            filtersArray.push(f);
            filtersArray.push(v);
            filtersArray.push(p);   
        }

      
    },
    error: function (r) {

    },
    failure: function (r) {

    }
});




$('#builder-widgets').queryBuilder({
    plugins: {
        'bt-tooltip-errors': { delay: 100 },
        'sortable': null
    },
    filters: [filtersArray],
    rules: rules_widgets
});




i have push all value in filtersArray  


Please suggest me

**Comment by shivendramca10** [comment]
basically my requirement is that I want to fill filter value from database 
as give filters bellow .
filters: [
                {
                    id: 'url',
                    label: 'URL',
                    type: 'string'
                },
                {
                    id: 'nal',
                    label: 'Org Name',
                    type: 'string'
                },
                {
                    id: 'ca',
                    label: 'Created at',
                    type: 'date',
                    plugin: "showCalender"
                }
            ]

**Comment by mistic100** [comment]
$.ajax is asynchronous, hence your code it totally wrong. I suggest you to read some tutorials about ajax and async JS.

I won't take time to correct your code sorry.

**Comment by mistic100** [comment]
And why are you using POST ? You are fetching data not posting data.
Also I strongly advise against doing ajax requests in a loop, this is very unefficient, your server should serve all the data in one request.

**Comment by nikataus** [comment]
Hi shivendramca10,

I'm doing exactly the same thing. I have a DB model of all filters and generate all configurations dynamically. What I do is when my App starts  I retrieve data from DB and generate JavaScript file that I simply use in the JSP. Since all users share the same configuration I found this to be working just fine. If I need to provide any customization per user I can use Ajax to additionally provide more configuration. If you generate static configuration there is no need to call AJax every time the page loads (it is doing the same thing for every user).

**Comment by shivendramca10** [comment]
Hi Nikataus
can you give me idea that how you generate JavaScript file.
I am using ASP.NET and  I retrieve data from BD and generate a array and store in local storage on browser. and try to some other way but not get solution so please suggest me.

Thanks..

**Comment by shivendramca10** [comment]
Hi mistic100 
one more things I store a array in Local Storage of browser. I want to use local storage data as a filters value 
**I have store array like  :** {id: 'starttime', label: 'Start Time', type: 'datetime', plugin: 'datetimepicker},{id: 'endtime', label: 'End Time', type: 'datetime', plugin: 'datetimepicker},{id: 'startLat', label: 'Start Latitude', type: 'string', plugin: '}
**we get local storage value** 
like var lsv =  [localStorage.demoData];

$('#builder-widgets').queryBuilder({
    plugins: {
        'bt-tooltip-errors': { delay: 100 },
        'sortable': null
    },
    filters: [localStorage.demoData],  //  i want to pass array value 
    rules: rules_widgets
});


Please suggest 

Thanks...

**Comment by shivendramca10** [comment]
Hi 
I have got **Uncaught ConfigError: Missing filter 0 id** in console when bind dynamic array in filters.

Please give me some ideas why show this error in console.

**Comment by nikataus** [comment]
> Hi Nikataus
can you give me idea that how you generate JavaScript file.

Hi again, 

Simply use classes to write to a file like:
 String path = paramServletContext.getRealPath("/builder");
 FileOutputStream fos = new FileOutputStream(path + "/querybuilderdata.js");

Then I generate the JS array structure for filters and groups based in the documentation or something like:

public static String toQueryBuilderString() {
        
        StringBuffer rez = new StringBuffer();
        rez.append("[");
        for (Iterator<QueryBuilderParameter> iterator = parameters.iterator(); iterator.hasNext();) {
            QueryBuilderParameter parameter = iterator.next();
            rez.append("{");
            rez.append("id:" + "'" + parameter.getId() + "'");
            rez.append(", ");
            rez.append(getDataType( parameter.getType()));
            rez.append(", ");
            rez.append(getInputControlType( parameter.getInput()));
            rez.append(", ");
            rez.append("label:" + "'" + parameter.getLabel() + "'");
            rez.append(", ");
            rez.append("optgroup:" + "'" + "group" + parameter.getGroupId() + "'");
            rez.append(", ");
            rez.append("operators: [");
            rez.append(getCollectionAsString(parameter.getOperators()));
            rez.append("]");
            rez.append(", ");
            rez.append("values: {");
            rez.append(getMapAsString(parameter.getValues()));
            rez.append("}");
            
            rez.append("}");
            if(iterator.hasNext())
                rez.append(", ");
        }
        
        rez.append("]");
        
        return rez.toString();
    }

**Comment by shivendramca10** [comment]
Thanks nikataus for your help
before I try to using ajax and value store in local storage in browser. but Now I have got solution using c#
Vary Very Thanks Nikataus..

**Comment by Bhavesh751** [comment]
@shivendramca10 

hi, 

can you please provide ideas on how you got the solution using C# ? 
actually i am trying to do the same thing, to bind filters dynamically from the Database in angular ? 

may be i can get some idea.
