### ISSUE TITLE
Linked datasets

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#313]
I'm using filters like States and Counties where intuitively when the user selects given state the county dropdown to be filtered. I found the coordinates example in the demo but that is not exactly what I need. I still need to have 2 separate filters that are linked together. Any suggestions for the easiest implementation? I would prefer to have some kind of configuration with mapping for State/County.
Thanks,

**Comment by mistic100** [comment]
Hello.
If you use the events system (like onRuleValueChanged.queryBuilder) you can alter the other filter.

**Comment by nikataus** [comment]
Hi, thanks for your quick response! Do you have a working example to help me figure it out faster? I understand your point. I want to see how you will reference the child drop down by name or id...? so when the user changes State filter you have to set new values in the County drop down.

**Comment by mistic100** [comment]
No I don't. The plugin itself only uses jquery.find.

**Comment by mistic100** [comment]
And you have access to $("#builder").queryBuilder[0].model.root

**Comment by nikataus** [comment]
yes, I initialize the builder like below - and have access to it if that's what you are asking? 

$('#builder-basic').queryBuilder({
			
			plugins: ['bt-tooltip-errors',
			          'filter-description',
			          'sortable',
			          'unique-filter'],
			  
			  
			  filters: filters,
			  
			  optgroups: optGroups,
			  
			
            
            
			  allow_groups: 2,
			  
			  lang: {
				  ....
				  }
				}
		});

**Comment by mistic100** [comment]
No it's not a question : I tell you you can access the current list of groups and rules in `("#builder").queryBuilder[0].model.root`

**Comment by nikataus** [comment]
Got it. If the Rule for County has not been created (say user add rule for State, but County rule is not yet created) do i still have reference to that object and change values property dynamically?

**Comment by nikataus** [comment]
So right now I generate filter for County like the one below: 
I assume I can set the values attribute of that filter when the user selects a State..

{id:'9', type:'string', input:'select', label:'County', optgroup:'group1', operators: ['in','not_in'], values: {'01059':"Franklin", '01057':"Fayette", ................}

**Comment by nikataus** [comment]
Hi again, I need to get some clarifications to make sure we are on the same page. 
Scenario 1: User adds State rule and selects a state. At this time I can update values of the County filter.
Scenario 2; User adds State rule, then adds County rule. User selects a state - how to reference County Rule obj to update its values?
The name of the generated rule for County is something like builder_rule_0_value_0
