### ISSUE TITLE
printing the select box values in sql rules

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#314]
Hello I need to print the select box values in SQL rules when it is generated

I have altered the contains operator, which will print iscontains instead of %LIKE%

For ex

employeename conatins hello will give you employeename iscontains('hello') 

Now I need to change this as iscontains('hello', employeename) is this ispossible if so plkease help me to solve this

**Comment by mistic100** [comment]
No it's not possible, unless you modify how https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/plugins/sql-support/plugin.js works (use functions instead of placeholder and transmit the field name when colling the function and also change line 270)

**Comment by mistic100** [comment]
I suggest you create your own SQL generator plugin which suits your requirements.

**Comment by DeveBj** [comment]
how can I get the values of left side select box do u have any idea

**Comment by mistic100** [comment]
I don't understand

**Comment by DeveBj** [comment]
actually I can access the value in the first select box using rule.field, I need to get the operator value in getSQL functions

**Comment by DeveBj** [comment]
finally achieved it thanks for your reply
