### ISSUE TITLE
I need to add select box for number instead of input type number

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#315]
Hello, 

Am trying to add select box for number data type instead of `<input type ='number'>` and in that select box I need to pass the options from query script as we do add the options for filter, is this possible please give some idea

**Comment by mistic100** [comment]
> pass the options from query script as we do add the options for filter
this sentence makes no sense at all

**Comment by DeveBj** [comment]
Actually am asking for the number data type to be selectable option instead of manual entering of values, am not asking the filter options

**Comment by DeveBj** [comment]
@mistic100 did you got it what ma saying

**Comment by mistic100** [comment]
http://querybuilder.js.org/#filters

```
id: 'myFilter',
type: 'number',
input: 'select',
values: [1, 2, 3, 4, 5]
```

**Comment by DeveBj** [comment]
@mistic100 thanks having one more doubt, I need a label in front of the date field or date operator

<label> date </label> <input type='text' >

**Comment by mistic100** [comment]
http://querybuilder.js.org/dev/events.html#changers

```js
$('#builder').on('getRuleInput.queryBuilder.filter', function(e, rule) {
  if (rule.filter.id == 'myFilter') {
    e.value = '<label>date</label> ' + e.value;
  }
});
```

**Comment by DeveBj** [comment]
@mistic100  thanks a lot it works
