### ISSUE TITLE
unknown identifier handling

### ISSUE THREAD

**Issue by cwmichi** [mistic100/jQuery-QueryBuilder#317]
Hello together,

is there any way to display the values for the query builder in case of getting the error message ("unknown identifier") in the console of the browser?

**Comment by mistic100** [comment]
I don't know what you talking about...

**Comment by cwmichi** [comment]
Sorry I mean "Undefined filter" which is thrown in 

/**
 * Returns a particular filter by its id
 * @param filterId {string}
 * @return {object|null}
 */
QueryBuilder.prototype.getFilterById = function(id) {
    if (id == '-1') {
        return null;
    }

    for (var i=0, l=this.filters.length; i<l; i++) {
        if (this.filters[i].id == id) {
            return this.filters[i];
        }
    }

    Utils.error('Undefined filter "{0}"', id);
};


But I just look at first to.. http://querybuilder.js.org/dev/events.html
Maybe you can close it

**Comment by mistic100** [comment]
Okay I see which error you are talking about but what do you want to do in that case ?

**Comment by cwmichi** [comment]
Displaying the query builder with an empty filters list. Currently it´s not possible to display the builder. 
In this case I want to select a new filter from the combo, e.g. the filter / identifier is not available anymore

**Comment by mistic100** [comment]
Leaving the filter empty involves discarding the operator and the value. Which means you'd better clean the rules list befaore calling "setRules" and then call "addRule" where needed.

The only possible evolution I see is to allow to add empty rules with "setRules", for example :

```js
.queryBuilder('setRules', [
  {
    id: 'name',
    operator: 'equal',
    value: 'cwmichi'
  },
  {
    empty: true
  }
]);
```

This would add a complete rule and an empty rule.

My point is it's up to the developper to ensure the data are coherent and acknowledged, I don't want any "silent fail".

**Comment by cwmichi** [comment]
Thank you very much! I will try this for me
