### ISSUE TITLE
Refresh query builder for each dynamically added fileds

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#318]
Hello,

I have created a form which will dynamically add and remove fields when the user clicks add button it adds a couple of fields to the form (2 text box and 3 combo boxes) and there is also a remove button to remove the field group, I have integrated the jquery query builder with that form in while adding the fields there will be 2 text boxes in that from one text box I have made the query builder to appear in an modal by on click of that text box in that I have a button called rule while on click of that button the rule will be generated and copied to that particular text boxes, my problem is that if I add any number of fields and I generate the rules for that particular text box still it updating to the first text box only not in others, is there any solution to resolve this problem

**Comment by mistic100** [comment]
Sorry I won't answer until you rephrase your issue. Do you realize you wrote ONE sentence of 7 lines? it's not understable.

**Comment by DeveBj** [comment]
Sorry, actually am inserting a textbox field while clicking on a add button, if the user click the text box a bootstrap modal will popup with query builder, after the rule filter is set if user clicks the submit button it will generate a SQL query,

The problem

If the user adds more than text boxes means if they click the text box modal is poping up with the already setted  rule filters for first text box, when I generate a new rule filter it gets updated to the first text box only not the clicked one

Now you got it

**Comment by mistic100** [comment]
Well I guess you just mixed your variables somehow, excuse me but that does not seems to be related with QueryBuilder, it's not my problem to handle what you do with your data.

But for sur I can tell you that if the builder is a singleton (you reuse it for each text box) you must reset it each time.
The cleaner way is to call `$('#builder').queryBuilder('destroy');` and start over. There are also the "setFilters", "setRules" and "clear" methods that can be useful.

**Comment by DeveBj** [comment]
@mistic100 refer this [link](https://plnkr.co/edit/SXPjiAHaIIp2FYSw95jj?p=preview) for the demo, 

in this demo there will a plus button on the top left corner if you click that a couple of fields will be added  in that there will be text box of border warning color, if you click that you will get a modal popup in that query builder appears, set some filters and click rule the sql query will be generated and it will be pasted on that text box, now add another field and check it please, need your help to resolve this error

**Comment by mistic100** [comment]
I don't have time to dig in your code and find your error.

As I said, you certainly must call "clear" on the builder when opening the popup, and you are certainly more aware of your application to know why the binding is incorrect.
