### ISSUE TITLE
need to add another attribute in filter

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#319]
Hello 

Am trying to add a new attribute in the filter like this

   ```
     filters: [{
                  id: 'salary',
                  label: 'Salary',
                  type: 'integer',
                  flag : 3
              }]
```
the flag is a new attribute, is that is a possible one

**Comment by mistic100** [comment]
Use `data`  property to store your custom attributes http://querybuilder.js.org/#filters

**Comment by DeveBj** [comment]
@mistic100 am having one more doubt, is this possible to find all the rule type which is integer and there corresponding value which is greater do you have any idea on this

**Comment by mistic100** [comment]
Just do it yourself with a recursive loop.

Acces the root group with `$('#builder')[0].queryBuilder.model.root` and use the `each`  method http://querybuilder.js.org/#inside_the_box

Example usage in the core https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/core.js#L726-L742

**Comment by DeveBj** [comment]
@mistic100  still I don't get you do you have any links other than you provided before

**Comment by DeveBj** [comment]
this was my code and i did not get what I needed is this code is correct

```
  if (rule.type == 'integer') {
                    var filterz = $('$builder').queryBuilder('getRules');
                    $.each(filterz, function (key, value) {
                        console.log("keyzz " + key + " valuezz " + value);
                    });
```

**Comment by mistic100** [comment]
I said a **recursive** loop.

```js
var output = $('$builder').queryBuilder('getRules');

var rulesOverThree = [];

// self executing function
(function loop(rules) {

  rules.forEach(function(ruleOrGroup) {
    // this item is a group: recurse
    if ('rules' in ruleOrGroup) {
      loop(ruleOrGroup.rules);
    }
    // this item is a rule
    else if (ruleOrGroup.field == 'myIntegerField' && ruleOrGroup.value > 3) {
      rulesOverThree.push(ruleOrGroup);
    }
  });

}(output.rules)); // apply to the root rules
```

**Comment by DeveBj** [comment]
@mistic100 your code gives me **Uncaught TypeError: Cannot read property 'forEach' of undefined**

**Comment by mistic100** [comment]
I can test right now, open your debugger and figure it out by yourself.
