### ISSUE TITLE
afterUpdateRuleValue only triggers if pressing enter or blurring the field

### ISSUE THREAD

**Issue by Cremz** [mistic100/jQuery-QueryBuilder#320]
I am trying to trigger queryBuilder('getRules') each type a user types inside a value field (for example a String rule that has contains. I want to get instant results based on the filters defined, but i am noticing that afterUpdateRuleValue is only triggered if i click out of the field or press enter.

If i attach an event (keypress) on the input field and try to do .queryBuilder('validate') i get only false (assuming the field starts off empty). So even if i do attach a custom event for typing in the field, i can't get the queryBuilder to be valid so i can extract the rules.

Any help would be greatly appreciated

**Comment by mistic100** [comment]
Sorry this won't change. Is a too expansive process to trigger it xxxx times by second.
