### ISSUE TITLE
Top level group configuration

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#321]
I have preset allow_groups: 1. However I wanted to check if I can configure top level group to be used only as AND (disable or remove OR). This should only apply to the top level group and not the nested groups.

Thanks,

**Comment by mistic100** [comment]
Actually already possible with `setRules`

Current version requires a base rule :

```js
$('#builder').queryBuilder('setRules', {
  condition: 'AND',
  flags: {
    condition_readonly: true // this is the important line
  },
  rules: [{
    id: 'name',
    value: 'Mistic'
  }]
});
```

But in the next version, since https://github.com/mistic100/jQuery-QueryBuilder/commit/ecab56f633459ba2b670a0e46f52b69bb0254ce2 you will be able to do 

```js
$('#builder').queryBuilder('setRules', {
  condition: 'AND',
  flags: {
    condition_readonly: true
  },
  rules: []
});
```
