### ISSUE TITLE
Missing field and/or value SQL-Parser Error while setting the rule in Jquery QueryBuilder

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#322]
Hello 

Am trying to set rules to the jquery query builder while click of a button below is my code but am getting 

> Missing field and/or value SQL-Parser Error  in query-builder.standalone.js

 ```
  $('#editBtn').click(function () {
        $('#builder').queryBuilder('setRulesFromSQL', 'employeeid = "11" and employeename != "" and doj >= "23/7/2016" and  iscontains("657657",salary) and (employeename = "" and salary != "6757")');
    });

please help me to resolve this issue
```

**Comment by DeveBj** [comment]
@mistic100  can you help me in this

**Comment by mistic100** [comment]
Why did you close ?

The problem is that the SQL parser does not understand functions, so "iscontains" is not valid, only the LIKE syntax is valid.

Use `salary LIKE "%654654%"` instead
