### ISSUE TITLE
Need to add one more select box and validate optional

### ISSUE THREAD

**Issue by DeveBj** [mistic100/jQuery-QueryBuilder#323]
Hello

Am having 2 select box and one text box for number type, I need one more select box in the and also need to validate if the value is selected on that new select box or entered in text box if either of the one is correct the error message must not occur, is this possible to achieve this

**Comment by DeveBj** [comment]
@mistic100  can you help me in this

**Comment by mistic100** [comment]
Why did you close ?

I'm afraid I don't understand you need, make it clearer
