### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by Cremz** [mistic100/jQuery-QueryBuilder#326]
I assume it should be possible to use negative values for fields that are integer or float. but it doesn't validate my rule.
What am i missing? Couldn't find anything in the documentation about how to enable negative values.

**Comment by mistic100** [comment]
Did you read the rules ? Setup an example.

**Comment by mistic100** [comment]
Please answer or I close

**Comment by Cremz** [comment]
http://querybuilder.js.org/demo.html - just type in any negative value in your demos, for example for price. the field type is integer but it doesn't allow negative values.
We use filters like Profit, that can be negative, so we can't do things like Profit > -10 for example..

**Comment by mistic100** [comment]
It does not allow negative values because it was configured for that http://querybuilder.js.org/index.html#validation

Juste look at the code of the demo http://querybuilder.js.org/assets/demo-basic.js
