### ISSUE TITLE
Do not display operator select for only one operator

### ISSUE THREAD

**Issue by drasha** [mistic100/jQuery-QueryBuilder#327]
Hi,

is there a way to not include an operator select with only one operator and have custom HTML or just text instead? For example, in case of radio buttons I am always using `equal` and the select is distracting and superfluous. 

I was able to go around this problem by altering `QueryBuilder.prototype.createRuleOperators` and checking for `operators.length`, but that seems to me a bit hackish.

Any idea how to do it better?

Thanks,
Martin

**Comment by mistic100** [comment]
You don't have to alter anything, use the `getRuleOperatorSelect.queryBuilder.filter` [event (doc)](http://querybuilder.js.org/dev/events.html#changers)

-----

I will change the default display when the dropdown has only one item
