### ISSUE TITLE
Operator WIth a Single Rule

### ISSUE THREAD

**Issue by aroramayur** [mistic100/jQuery-QueryBuilder#328]
{
  "condition": "AND",
  "rules": [
    {
      "id": "category",
      "field": "category",
      "type": "integer",
      "input": "select",
      "operator": "equal",
      "value": "1"
    }
  ]
}

If there is just one rule, why have an operator at all. The  last selected operator is one used even if there is just one rule

**Comment by aroramayur** [comment]
I meant condition actually , sorry! Why do we have one in case there is a single rule ( no groups , no nesting).

**Comment by mistic100** [comment]
the main container IS a group itself, so it needs a condition.
but if you want to initialize the builder with a single rule you can skip it.

```js
$('#builder').queryBuilder('setRules', [
{
"id": "category",
"field": "category",
"type": "integer",
"input": "select",
"operator": "equal",
"value": "1"
}
]);
```

and it will take the `default_condition` option
