### ISSUE TITLE
Addrule not a function

### ISSUE THREAD

**Issue by jschaufele** [mistic100/jQuery-QueryBuilder#333]
I can get qb to load and read in options but I get an "Addrule" not a function error when I try and change the query,  using the stand alone version. I am willing to pay someone to tell me what I am doing wrong.

Please let me know if you might know what I need to do

Thanks

**Comment by mistic100** [comment]
I don't have to pay anything -_- just provide en complete example of what you do (like asked in the issue guidelines !!)

**Comment by jschaufele** [comment]
So i have load the stand alone version
use you basic example 

it renders great but when i try and add a rule you see the error below
included is the code i use 
 you help is greatly appreciated 

	<div id="builder-basic" >
	</div>
	<div class="btn-group">
		<button class="btn btn-warning reset" data-target="basic">Reset</button>
		<button class="btn btn-success set-json" data-target="basic">Set rules
		</button><button class="btn btn-primary parse-json" data-target="basic">
		Get rules</button></div>


    </div>

<script>
var rules_basic = {
  condition: 'AND',
  rules: [{
    id: 'price',
    operator: 'less',
    value: 10.25
  }, {
    condition: 'OR',
    rules: [{
      id: 'category',
      operator: 'equal',
      value: 2
    }, {
      id: 'category',
      operator: 'equal',
      value: 1
    }]
  }]
};
$(document).ready(function(){ 
$('#builder-basic').queryBuilder({
  plugins: ['bt-tooltip-errors'],
  
  filters: [{
    id: 'name',
    label: 'Name',
    type: 'string'
  }, {
    id: 'category',
    label: 'Category',
    type: 'integer',
    input: 'select',
    values: {
      1: 'Books',
      2: 'Movies',
      3: 'Music',
      4: 'Tools',
      5: 'Goodies',
      6: 'Clothes'
    },
    operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
  }, {
    id: 'in_stock',
    label: 'In stock',
    type: 'integer',
    input: 'radio',
    values: {
      1: 'Yes',
      0: 'No'
    },
    operators: ['equal']
  }, {
    id: 'price',
    label: 'Price',
    type: 'double',
    validation: {
      min: 0,
      step: 0.01
    }
  }, {
    id: 'id',
    label: 'Identifier',
    type: 'string',
    placeholder: '____-____-____',
    operators: ['equal', 'not_equal'],
    validation: {
      format: /^.{4}-.{4}-.{4}$/
    }
  }],

  rules: rules_basic
});

$('#btn-reset').on('click', function() {
  $('#builder-basic').queryBuilder('reset');
});

$('#btn-set').on('click', function() {
  $('#builder-basic').queryBuilder('setRules', rules_basic);
});

$('#btn-get').on('click', function() {
  var result = $('#builder-basic').queryBuilder('getRules');
  
  if (!$.isEmptyObject(result)) {
    alert(JSON.stringify(result, null, 2));
  }
});
});
</script>


<img width="781" alt="error" src="https://cloud.githubusercontent.com/assets/20531447/17435889/0206cef6-5ad1-11e6-8951-a7a9ab89d09c.PNG">

<img width="552" alt="render" src="https://cloud.githubusercontent.com/assets/20531447/17435869/c5250d9a-5ad0-11e6-84f5-2755a221ce26.PNG">

**Comment by mistic100** [comment]
please load the unminified file

**Comment by jschaufele** [comment]
Here you go these are the screen shots and line numbers , assume this is what you are looking for

Thanks for your quick response !

<img width="238" alt="error2" src="https://cloud.githubusercontent.com/assets/20531447/17436447/4aebc4b6-5ad4-11e6-841e-f112f4339d05.PNG">
<img width="245" alt="errror3" src="https://cloud.githubusercontent.com/assets/20531447/17436446/4aebb2be-5ad4-11e6-8878-e5814afbba00.PNG">

**Comment by mistic100** [comment]
Sorry you will have to setup an online example. I don't reproduce with the latest build.

**Comment by jschaufele** [comment]
There is a version conflict w/ my versions of BS , JQ etc - I pulled down your full demo and pulled in your scripts and things worked - 

Thanks for your reply looking forward to using your plugin

Thanks
