### ISSUE TITLE
Working with relative dates

### ISSUE THREAD

**Issue by netonme** [mistic100/jQuery-QueryBuilder#334]
Is it possible to work with relative dates? I Try to get a SQL output like 

`field > DATE_SUB(NOW(), INTERVAL 14 DAY)`

my idea was...

``` js
var filter = {
    "id": "field", 
    "field": "field", 
    "type": "string", 
    "operators":[ "equal", "not_equal", "less_or_equal", "greater_or_equal", "between"], 
    "data": {
        "mode": "rel"
        },
    "valueGetter": function (rule) {
        return 'DATE_SUB(NOW(), INTERVAL ' + rule.$el.find('.rule-value-container input').val() + ' DAY)';
        }
    }
```

but then the output is quoted like this 

`field > 'DATE_SUB(NOW(), INTERVAL 14 DAY)'`

and if i use "type": "integer", the output is complete empty. It there any solutions to get this up?

Thanks

**Comment by mistic100** [comment]
Please use valid syntax for your code blocks,I edited your message with triple `

-----

Your approach is the right one but the SQL generator was never designed for that.

What do you think about a new filter method `getSQL` which will be responsible to generate the SQL of this filter ?

Something like (will change to accommodate complex operators) :
```js
getSQL: function(field, operator, value, rule) {
  return field + operator + 'DATE_SUB(NOW(), INTERVAL ' + value + ' DAY)';
}
```

**Comment by netonme** [comment]
Sounds great! But like something you have to implement? Or is this something i can do with the current version? in my case, the reverse operation, is not needed. But of course, it make sense to have it. 

My Idea was something like ```SQLMethod: "DATE_SUB(NOW(), INTERVAL %s DAY)"``` but your solution is more flexible.

**Comment by mistic100** [comment]
The big problem is that forward/sql-parser does not support this kind of "advanced" syntax, so the `setRulesFromSQL`  could not work

**Comment by mistic100** [comment]
It is done, it requires the latest version of mistic100/sql-parser (1.1.0).

There are not getters/setters but is totally based on events I added in a recent feature.
You can see how it works in the unit test here https://github.com/mistic100/jQuery-QueryBuilder/blob/c72d36774c0d5f4aeb2ffd82667c65e1dc3cb29a/tests/plugins.sql-support.module.js#L194-L270 it's a bit complicated for parsing because it requires to inspect the AST.
