### ISSUE TITLE
unique + display_empty_filter: false => not working

### ISSUE THREAD

**Issue by IMM0rtalis** [mistic100/jQuery-QueryBuilder#335]
my config:
```
display_empty_filter: false,
conditions: ['AND', 'OR'],
plugins: [
    'unique-filter',
],
filters: [
   {
    id: 'channel',
    label: 'Channel',
    type: 'string',
    operators: ['contains'],
    unique: true,
   }
],
```
When I click "add rule" I have multiple "channel"-filters.
![selection_001](https://cloud.githubusercontent.com/assets/1506919/17479849/46d5a86c-5d75-11e6-9f6d-0a51c6ffc0bd.png)

So I would say this is a bug :/

PS: could not write you a pm --> great plugin so far! thx a lot!

**Comment by IMM0rtalis** [comment]
Progress: It seems that "display_empty_filter: false," makes this problem. With "display_empty_filter: true," it's working

**Comment by mistic100** [comment]
This patch will try to use the first available filter when adding a new rule.

If every filter is used and error is thrown and the rule is unusable. This is the best I can do for now. Ideally the "add rule" button will be disabled if no more filter is available.
