### ISSUE TITLE
how to check if queryBuilder is assigned to element?

### ISSUE THREAD

**Issue by IMM0rtalis** [mistic100/jQuery-QueryBuilder#336]
Heyho,

I google'd for an common way to check if the queryBuilder was assigned to an element but did not find a solution. 

Is there a way to check if my element xyz has an initialized queryBuilder-Object on it?

Best,
Florian

**Comment by IMM0rtalis** [comment]
Answered myself:

`if((typeof jQuery('#IdOfQueryBuilderElement').data('queryBuilder') !== 'undefined')) {}`

**Comment by mistic100** [comment]
why using typeof ?

```js
if (jQuery('#IdOfQueryBuilderElement').data('queryBuilder') !== undefined) {}
```

or just

```js
if (jQuery('#IdOfQueryBuilderElement').data('queryBuilder')) {}
```
