### ISSUE TITLE
templating: first/last element as variable

### ISSUE THREAD

**Issue by IMM0rtalis** [mistic100/jQuery-QueryBuilder#337]
Heyho,

I came across a small problem while templating.
When I want to show sth. different for the first and/or last element I have nearly no choice to do it dynamically. 

[Template](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/template.js#L1)

If I want to get the first group I have to use sth like 
`{{? it.group_id === "IDOFELEMENT_group_0" }}First{{?}}`

This is just a feature-request, but could you provide sth like
- first
- last
- index
?

Best,
Florian

**Comment by mistic100** [comment]
The id is unpredictable, "0" is not necessarly the first one.

first/last/index relative to what ? globally or in its parent (when there are groups in groups), I don't like this approach

Can't you simply use CSS ? you always add the HTML and hide or not with ":last-child" and ":first-child".

**Comment by IMM0rtalis** [comment]
Isn't there sth like a foreach-loop for displaying the elements? insie this loop i meant the first/last/index. With just css it's a bit ugly in my opinion. 

Can you show me the location at the code so maybe I can think of a better solution?
I also have to keep in mind that one plugin makes the rules movable by javascript.

If something else is added, the tags could be manipulated with javascript. But yeah, I see a point here. It's more tricky than I though. So maybe I need a javascript-hack for my needs :/

Best,
Florian

**Comment by mistic100** [comment]
No there is no loop, each HTML block is builded and inserted on demand without refreshing everything.

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/core.js#L288-L311

**Comment by IMM0rtalis** [comment]
Hm. OK, you're right. With this structure it's really a mess to implement sth like this. 

You can close this ticket, I have to find another solution.

thx
