### ISSUE TITLE
Add 'afterSetRules' trigger

### ISSUE THREAD

**Issue by psilent** [mistic100/jQuery-QueryBuilder#338]
After calling .setRules(), a number of triggers are fired for all of the various changed items (afterAddGroup, afterAddRule, etc.). In my UI, I have all triggers for such changes wired to enable a save button when something is changed. I would like to ignore change notifications until .setRules() has completed and a trigger at the end of that process would be very helpful. Thanks.

**Comment by mistic100** [comment]
`setRules`is synchronous, you don't need an event to know it's done.

**Comment by psilent** [comment]
Sorry, I should have mentioned that I'm using the query builder from a Vaadin application which makes things asynchronous where I'm making calls and handling triggers.

**Comment by psilent** [comment]
As I think further on it, perhaps I can handle this with some more code in the wrapper. I'll take another look at it. Thanks.

**Comment by mistic100** [comment]
Whatever framework you put around it, there must somewhere where you call the method synchronously, so put your code here.

I won't add this event, it does not make sense in the architecture of the plugin.
