### ISSUE TITLE
How to restrict QueryBuilder for constructing rules in CNF?

### ISSUE THREAD

**Issue by sitingren** [mistic100/jQuery-QueryBuilder#339]
I am trying to use QueryBuilder for constructing rules in CNF ([conjunctive normal form](https://en.wikipedia.org/wiki/Conjunctive_normal_form)).
CNF rules are only one level deep and enforce that any inner query group is joined by OR, and any outer query group is joined by AND.

I can set the number of allowed nested groups by using `allow_groups: 1`. However, I cannot find a way to set something like

```
available inner group conditions = 	['OR']
available outer group conditions = 	['AND']
```

Do I need to modify query-builder.standalone.js file? and how?
Any help is appreciated!

**Comment by mistic100** [comment]
First of all you never modify files in "dist", you modify "src" and you rebuild.

----

I suggest you use `getGroupTemplate.queryBuilder.filter` [changer](http://querybuilder.js.org/dev/events.html#changers) to modify the HTML depending on the `level` variable, and the `afterAddGroup.queryBuilder` event to ensure the condition is correct (still depending on the level).

**Comment by sitingren** [comment]
@mistic100 Thank you for your help. I'm able to construct rules in CNF.

Now the thing is I want to use `.setRulesFromSQL(sql [, mode])` to set new rules from an SQL query, but I find that the new rules do not in CNF. Is it possible to use `.setRulesFromSQL(sql [, mode])` in CNF? Or I can only set new rules by `.setRules(rules)`?

**Comment by mistic100** [comment]
I don't understand... CNF is a concept, a set a formal rules you apply to your data.

`setRulesFromSQL` is "stupid" it translates exactly the SQL you enter.

**Comment by sitingren** [comment]
For example, I get ` ( person_name LIKE('%abc%') OR person_name LIKE('%def%') ) ` from the following rules
![screen shot 2016-08-10 at 2 40 40 pm](https://cloud.githubusercontent.com/assets/15162542/17566274/b494824e-5f08-11e6-822d-59fbdac6b4af.png)

But when I call `.setRulesFromSQL(sql [, mode])` with ` ( person_name LIKE('%abc%') OR person_name LIKE('%def%') ) `  I get the following interface
![screen shot 2016-08-10 at 2 46 52 pm](https://cloud.githubusercontent.com/assets/15162542/17566455/71e68ff4-5f09-11e6-983e-0d1b5f7d56b1.png)
Now the query changes to `person_name LIKE('%abc%') AND person_name LIKE('%def%')`

**Comment by mistic100** [comment]
Ok I see.
The problem is the SQL Parser which simplifies useless groups and outputs `person_name LIKE('%abc%') OR person_name LIKE('%def%')`
But because you blocked the root condition to AND it fails.

I see no solution

**Comment by sitingren** [comment]
@mistic100 Thank you, I'll set new rules by `.setRules(rules)`.
