### ISSUE TITLE
Check if no rules or empty builder

### ISSUE THREAD

**Issue by ldescamps** [mistic100/jQuery-QueryBuilder#340]
By default an empty rules is added to the builder. I want to check if there is one empty rules or no rules at all in the queryBuilder. Another linked question is : how to get the current number of rules ?
I need to disable a dropdown list if any input element (other than default empty rule) and enable the dd list if the queryBuilder is empty.
Thank you for your help ! 
This queryBuilder is very nice, congrats for your work!

**Comment by mistic100** [comment]
Call the `validate`  method, if it fails, either the builder is empty either there is an incomplete rule.

You cannot know the total number of rules, you have to recursively count items starting from `$('#builder')[0].queryBuilder.model.root`

Example of recursive loop https://github.com/mistic100/jQuery-QueryBuilder/issues/319#issuecomment-232599521
