### ISSUE TITLE
in and not in conditions multiple values

### ISSUE THREAD

**Issue by sivakumaralpha** [mistic100/jQuery-QueryBuilder#341]
how to enter multiple values for **_in_** and **_not in_** conditions, data type **_double_** and **_int_** it is not allowing comma separator.

**Comment by mistic100** [comment]
You can use :

 - a selectbox 
 - a "string" input with `valueGetter`  and `valueSetter` to split and join the values
 - a custom input (`input` as a function) to display multiple inputs

**Comment by sivakumaralpha** [comment]
OK. Thanks for the quick reply.i will check the custom input options.

**Comment by mistic100** [comment]
Version 2.4.0 added `value_separator` option.

```js
$('#builder').queryBuilder({
  filters: [
    {
      id: 'name',
      type: 'string',
      value_separator: ','
    }
  ]
});
```

**Comment by ismailarilik** [comment]
Hi.

Maybe dynamically added numeric fields may be used to allow users to enter multiple number values for IN and NOT IN subqueries... @mistic100 , what do you think about this suggestion?

Regards...
