### ISSUE TITLE
initial event for filter creation is not fired

### ISSUE THREAD

**Issue by IMM0rtalis** [mistic100/jQuery-QueryBuilder#342]
heyho,

i have an empty set of rules and 3 filters.

I want to modify the filter-select (with selectize) and the most logic way (for me) was over the events.

So I choosed "afterCreateRuleFilters". But this event is just fired after I ADD another rule, not for the first initial rule.

Did I do sth wrong or is it a bug?

Best, Florian

**Comment by mistic100** [comment]
You are wrong, the event is fired, but because the initialization of the builder is synchronous your listener does not exists yet.

So just register the events before calling the plugin.

**Comment by IMM0rtalis** [comment]
Ahh...  yes, you are absolutely right. I am used to define further things after the init. 

thx. And the for your fast reply!
