### ISSUE TITLE
Select RuleFilter programmatically

### ISSUE THREAD

**Issue by rsangiovanni** [mistic100/jQuery-QueryBuilder#343]
Hi, is it possible to select a RuleFilter programmatically?

I saw the code `QueryBuilder.prototype.setRuleValue = function(rule, value) ` but it takes as 
```
 @param rule {Rule}
 @param value {mixed}
 
```
How to create a Rule object?

thanks

**Comment by mistic100** [comment]
You don't create rule objects, you use existing ones.

The model is available at `$('#builder')[0].queryBuilder.model.root`.

See http://querybuilder.js.org/#inside_the_box and https://github.com/mistic100/jQuery-QueryBuilder/issues/319#issuecomment-232599521

once you found your rule :
```js
myRule.value = 12346;
```

every process is done automatically

**Comment by rsangiovanni** [comment]
Great thanks...
and how to change the value of RuleFilter? 
(I'm going to start a new branch for angular wrapping)

**Comment by mistic100** [comment]
What is "RuleFilter" ?? Do you mean the filter of the rule ? Look at the doc I linked, there is a "filter" property in the rule.

**Comment by rsangiovanni** [comment]
I tried this
```
var ruleToUpdate someFunctionIteratingOverRootModel();
var filter=$('#builder').queryBuilder('getFilterById','some-filter-id');
ruleToUpdate.filter=filter;
$('#builder').queryBuilder('updateRuleFilter',ruleToUpdate);
```

**Comment by mistic100** [comment]
I said "and that's all" on purpose. Which mean this line is completely useless 

```js
$('#builder').queryBuilder('updateRuleFilter',ruleToUpdate);
```

and you forgot a "=" on the first line

**Comment by rsangiovanni** [comment]
Yes! 
Thanks so much! 👍
