### ISSUE TITLE
custom input with type string -> javascript error when none selected "value[i] of null"

### ISSUE THREAD

**Issue by IMM0rtalis** [mistic100/jQuery-QueryBuilder#344]
Heyho,

I checked a lot and debugged the library and I came to the conclusion that the following must be a bug:
```
input: function(rule, input_name) {
    var filter = rule.filter;
    var h = ''

    h+= '<select class="" name="' + input_name + '"' + (filter.multiple ? ' multiple' : '') + '>';
    if (filter.placeholder) {
        h+= '<option value="' + filter.placeholder_value + '" disabled selected>' + filter.placeholder + '</option>';
    }
    jQuery.each(filter.values, function(key, val) {
        h+= '<option value="' + key + '">' + val + '</option> ';
    });
    h+= '</select>';

    return h;
},
```
I copied the select-tag from the core, at the html-side it's exact the same.
But when I select none of the mulitselect I get an javascript-error. reproducable with the demo's and multiselect an this input-function.

When I tried to get a workaround and added a custom validation for this I notices that the "rule" parameter for the validate-function was "undefined". 

Best,
Florian

**Comment by mistic100** [comment]
Create a live demo with the full config

**Comment by mistic100** [comment]
bump
