### ISSUE TITLE
How to add/delete/update a group or rule based on a specific event

### ISSUE THREAD

**Issue by happy2share** [mistic100/jQuery-QueryBuilder#345]
I am a newbie to this plugin and trying to add/delete/update a group or rule dynamically to the existing query builder group or rule based on an event (For eg: select box change).  
**Rule is duplicated several times on change event**. Scenario is I have 2 countries (of a select box of a rule) with different sub rule sets. So I am creating a group on change event with the First country sub rule set. When I am trying to switching to Second country it is adding to the existing sub rule set instead of replacing the existing one.
In achieving this I got two questions
1. How to refer an existing rule or group to perform these operations?
2. How to update the existing one with the new one or adding a new one after deleting the existing one?
Please suggest me the way to implement it and correct me If I am doing anything wrong.

**Comment by mistic100** [comment]
1. recursively find it in the model, get the model with `$builder.queryBuilder('getModel')`

2. if you found your existing rule you can directly update it https://github.com/mistic100/jQuery-QueryBuilder/issues/343#issuecomment-239238167

if you found a group and want to add a rule inside it : ` $builder.addRule(group)`
