### ISSUE TITLE
Top level Rule configuration 

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#346]
Hi,

I have preset a Rule like:

```js
var rules = {
			condition: 'AND',
			flags: {
				condition_readonly: true 
			},
			  rules: [{
				    id: '1',
				    operator: 'equal',
				    value: 'CA',
				    
				    flags: {
				        no_delete: true,
				        filter_readonly: true,
				        operator_readonly: true,
				        value_readonly: true
				      },
				  }]
			};
```

I want to have the top level Rule to allow only Add Group and remove Add Rule button. 
Please let me know if that is configurable.

Thanks,

**Comment by mistic100** [comment]
Will be possible (one day) with https://github.com/mistic100/jQuery-QueryBuilder/issues/301#issuecomment-224693246
