### ISSUE TITLE
Getting error message query-builder.js:3558 Uncaught TypeError

### ISSUE THREAD

**Issue by ezequias** [mistic100/jQuery-QueryBuilder#348]
Hi everyone

I am getting this error message when I try to load the example html:

query-builder.js:3558 Uncaught TypeError: Cannot read property 'push' of undefined

![bowererrors](https://cloud.githubusercontent.com/assets/539561/17890557/33b40f1e-690d-11e6-86d6-a4be59be85d1.jpg)

Does anyone have some idea of how to solve this problem?

Sincerely
Ezequias Rocha

**Comment by mistic100** [comment]
Thank you

**Comment by ezequias** [comment]
Your welcome @mistic100 I would like to ask you wicth jQuery version is the best one to work on current release (master or 1.4)?

**Comment by mistic100** [comment]
It doesn't matter.
