### ISSUE TITLE
Favicon error opening on Brackets

### ISSUE THREAD

**Issue by ezequias** [mistic100/jQuery-QueryBuilder#349]
Hi everyone

I am having a simple error when I load the index.html page from Brackets that makes the upper side of the page to be hidden.

See image below.
![errorbrackets](https://cloud.githubusercontent.com/assets/539561/17895668/350c42ac-6924-11e6-8072-35719428598b.jpg)

**Comment by mistic100** [comment]
It's not related to Brackets, web browsers always try to load a default favicon, and there is none in the example file.

Nothing is missing on the example page.

**Comment by mistic100** [comment]
And if you want to serve the example page, use `grunt serve`
