### ISSUE TITLE
Using with older version of jquery (1.8.3)

### ISSUE THREAD

**Issue by ksrb** [mistic100/jQuery-QueryBuilder#350]
I realize that the recommended version of jquery is 1.10.0+ but I've been successfully using this library with jquery 1.8.3 (it fails in 1.9.0/1 due to some [validation changes](https://bugs.jquery.com/ticket/11290)).

This is a bit of a stretch but other than the reason above I was wondering:

- If you remember why you designated the jquery version to 1.10.0+?
- If you're using any features that exists in 1.10.0 that don't exist in older version of jquery?
- Or is this a case of 1.10.0 was the newest jquery version at the time this library was developed?

**Comment by mistic100** [comment]
It's 1.10 because the whole 1.9 branch is broken and I consider 1.8 too old.
And beside the fact I forgot to update the bower.json file it's impossible de declare the dependency as "<1.9 & >=1.10"

**Comment by ksrb** [comment]
Thanks for the info I didn't know jquery 1.9 was broken. My situations is slightly unique in that I can't update the jquery version, even though I really want to...

**Comment by mistic100** [comment]
By "broken" I meant this nasty breaking change you linked in your first message. Just seeing the number of duplicates reports in the bug-tracker shows they f***ed-up.

**Comment by ksrb** [comment]
Lol yeah it was causing me grief as well.

**Comment by ksrb** [comment]
Anyways I edited my initial response.

> But what you said seems to imply that there isn't really any issue with using 1.8 beside it being too old, unless I'm twisting your words.

Any words on that?

**Comment by mistic100** [comment]
> Anyways I edited my initial response.
Don't. It does not send a new notification.

----

I don't know, I can run the unit tests against 1.8 if you want to be sure, but I won't (and can't) retrograde.

**Comment by ksrb** [comment]
Okay I'll give the unit test a shot when I get a chance, and yeah it wouldn't make sense to retrograde thanks!

**Comment by ksrb** [comment]
I tried running your test verbatim via:
```bash
git clone github.com/mistic100/jQuery-QueryBuilder
cd jQuery-QueryBuilder
npm install
npm run test
```

PhantomJS is reporting a bunch of errors:
```bash
ReferenceError: Can't find variable: $/Qunit/blanket
```

Is this expected or should I open another ticket?

**Comment by mistic100** [comment]
`bower install`

**Comment by ksrb** [comment]
Oh right 😓 .
I got 2/171 failures running without any modifications:
```bash
>> core - Empty builder
>> Message: Should return object with no rules
>> Actual: {}
>> Expected: {
>>   "condition": "AND",
>>   "rules": []
>> }
...
>> core - Empty builder
>> Message: Expected 3 assertions, but 4 were run
>> Actual: null
>> Expected: undefined
...
```

I'm sure you're aware but in package.json you can do:
```bash
"scripts" : {
  "install": "npm install && bower install"
}
"devDependencies": {
   "bower": "^1.7.9",
}
```

For those who run into a similar situation in the future the test ran mostly successfully with 1.8.3 with 4/164 failures, for some reason the number of test run is different. All the errors were around the bootstrap tooltip complaining it needs a newer version of jquery, probably much for the same reasons as mentioned above.
