### ISSUE TITLE
Dragging and dropping on touch devices

### ISSUE THREAD

**Issue by nmnb18** [mistic100/jQuery-QueryBuilder#352]
I am new to this plugin, and want to use it across all the touch devices like ipad, surface pro etc. All functionalities are working fine except drag and drop.

I checked a lot but unable to find anything relevant to this.

Please suggest me the way to implement this.

Regards,
Naman

**Comment by mistic100** [comment]
never tested but it should work

**Comment by nmnb18** [comment]
I have tested it on all the devices but it is not working, can you please suggest me the way to implement this for devices?

**Comment by mistic100** [comment]
I can't suggest anything, it's a bug...

**Comment by mistic100** [comment]
Problem is "dragstart", "dragend", etc events are not fired on touch devices.

I'll try re-implement the plugin through a device-agnostic library http://interactjs.io/
