### ISSUE TITLE
"Standalone" plugin

### ISSUE THREAD

**Issue by rsangiovanni** [mistic100/jQuery-QueryBuilder#354]
As i read from documentation is possible to create a standalone plugin.
I need to init it after QueryBuilder is loaded.

```
$.fn.queryBuilder.define('my_plugin', function (options) {
            console.log('init called')
            this.on('getRuleInput.filter', function (h, rule, name) {
               console.log('getRuleInput.filter'')
            });
        });
```
the result is 
```
TypeError: $inputs[filter.plugin] is not a function
```
It seems that the plugin is not initialized by `QueryBuilder.initPlugins()`

**Comment by mistic100** [comment]
When you define the "plugin" property of a filter, it refers to a jQuery plugin (like "selectize", or any bootstrap component), it has nothing to do with QueryBuilder plugins.

QueryBuilder plugins are global, and applied to the builder itself, filter plugins are applied the rule input (and I repeat, must be jQuery plugins).

**Comment by rsangiovanni** [comment]
the scenario:
* I want to implement a new widget: an input type text with any special behavior.
* I set the filter configuration as:  `filter.plugin = 'fancy-text';`
Is the plugin the right way to do?
The concept is the same as bt-checkbox, right?

**Comment by mistic100** [comment]
You can do it ever in jQuery plugin or QueryBuilder plugin.

In the last case it's the same thing as "bt-checkbox" but if you look carefully there is never `filter.plugin = 'bt-checkbox'`, because it's not a jQuery plugin.

But If you plan to apply your widget to only specific filters I advise you create a jQuery plugin.

**Comment by rsangiovanni** [comment]
ok got it, how to do as  QueryBuilder plugin?
thanks

**Comment by mistic100** [comment]
Read the doc http://querybuilder.js.org/dev/plugins.html
Look at what exists https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/plugins/bt-selectpicker/plugin.js

what more can I say ?

**Comment by rsangiovanni** [comment]
I've already read that.
the problem is I created a "Standalone" plugin with $.fn.queryBuilder syntax, but it doesn't work... 
```
$.fn.queryBuilder.define('my_plugin', function (options) {
            console.log('init NOT called!')
          ... 
          ///event registration
          ...
        });
```

**Comment by mistic100** [comment]
Ok you created a plugin, but you need to ENABLE it. Exactly like every other plugin.

```js
$('#builder').queryBuilder({*
  plugins: ['my_plugin'],
  ......
});
```

**Comment by rsangiovanni** [comment]
I missed this
```
config.plugins = {
                'my_plugin': null
            }
```

**Comment by rsangiovanni** [comment]
👍  thanks
