### ISSUE TITLE
Question On Custom Filter Types

### ISSUE THREAD

**Issue by robbert229** [mistic100/jQuery-QueryBuilder#355]
Why does jQuery-QueryBuilder error out when you specify a type that doesn't exist in javascript? IE I would like to create an operator that applies to type foo, and bar, and have filters of foo and bar. 

Right now I have commented out the following 3 lines and it appears to allow me to do what I want.
[Source](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/core.js#L101:L103)

        if (!filter.type) {
            filter.type = 'string';
        }
        /*else if (!QueryBuilder.types[filter.type]) {
            Utils.error('Config', 'Invalid type "{0}"', filter.type);
        }*/
        if (!filter.input) {
            filter.input = 'text';
        }

My 2 cents is that by removing it QueryBuilder can be a lot more flexible and powerful. 

BTW thanks for building such an awesome tool! It has save me dozens of hours to say the least.

**Comment by mistic100** [comment]
Because it is used by the validation system and other part of the lib to know what is going on. I think it's not totally crazy to limit to types actually supported by the language (JavaScript).

If you need special handling of some filters you can use the `data` attribute to store your "type".
