### ISSUE TITLE
MongoDB Export IN clause outputs single string value

### ISSUE THREAD

**Issue by humbao** [mistic100/jQuery-QueryBuilder#356]
The returned $In query value should be an [ 'arrary', 'of', ' values' ].

Import works.

Output is $in : [ "array, of, values" ]

**Comment by mistic100** [comment]
As far as I know it is the case. Can you provide an example where it sits not work ?

**Comment by mistic100** [comment]
Your problem is certainly https://github.com/mistic100/jQuery-QueryBuilder/issues/276

The plugin can't know it should split the string input on commas.

**Comment by mistic100** [comment]
Version 2.4.0 added `value_separator` option.

```js
$('#builder').queryBuilder({
  filters: [
    {
      id: 'name',
      type: 'string',
      value_separator: ','
    }
  ]
});
```
