### ISSUE TITLE
Input dropdown is sorted based on key

### ISSUE THREAD

**Issue by Malkoba** [mistic100/jQuery-QueryBuilder#357]
Hi mistic,

first of all, thank you very much for the awesome tool. Nicely done.

Now to the issue.
We have a country dropdown filter were we load all countries to the input control with the id of the country as the key of the dropdown. It seems that the dropdown is sorted based on the key, not the display value.

Our requirement is to show countries in a specific order, for which, we create the datasource at server side as per the requirement. But once bound to the dropdown, the custom order we set at server side is lost due to key based sorting. Is there anyway we can set the dropdowns to preserve an un-orderd list.

regards,
Malkoba.

**Comment by mistic100** [comment]
JavaScript objects DO NOT have an predefined order. Once your map is received by the web application, the order is lost.

That's why the `filter.value` property accept an array of objects to preserve the order. http://querybuilder.js.org/#filters Click on "more details" on the "values" line.

**Comment by Malkoba** [comment]
Thanks Mistic. Solved my issue from your inputs. I was sending a serialized IDictionary<object, object>. I changed that to IList<KeyValuePair<object, object>>.

Thanks you very much for the help
