### ISSUE TITLE
Converting JSON query -> ActiveRecord query

### ISSUE THREAD

**Issue by daunish-nova** [mistic100/jQuery-QueryBuilder#359]
I'm using this query builder in my front end and I really like how configurable it is!

Right now I have it set to send the JSON up to the RoR based server to parse and construct an ActiveRecord query to return results. This works but it's harder to do complex nesting of groups and stuff like that.

Has anyone built a gem which can parse the JSON and correctly build the active record query? Or even something that can convert it from JSON -> SQL server side so I can avoid an abstraction leak by generating it client side.

**Comment by nikataus** [comment]
Hi Daunish, 
We have implemented JSON to XML conversion. We use the XML as a parameter to call a Stored procedure to retrieve data. XML looks like:

<Query>
  <Group>
    <Guid>700e001e-760f-4cee-ad46-65889622ca3f</Guid>
    <Level>0</Level>
    <Condition>AND</Condition>
    <ParentGuid/>
    <Rule>
      <Guid>e8e4809b-c8ba-42cc-b661-4848bfdfc4ee</Guid>
      <Parameter>1</Parameter>
      <Operator>equal</Operator>
      <Arguments>
        <Argument>AL</Argument>
      </Arguments>
    </Rule>
  </Group>
</Query>

**Comment by nikataus** [comment]
Hi Daunish, 
We have implemented JSON to XML conversion. We use the XML as a parameter to call a Stored procedure to retrieve data. XML looks like:
------------------------------------------------------------------------------------------------------------
<Query>
  <Group>
    <Guid>700e001e-760f-4cee-ad46-65889622ca3f</Guid>
    <Level>0</Level>
    <Condition>AND</Condition>
    <ParentGuid/>
    <Rule>
      <Guid>e8e4809b-c8ba-42cc-b661-4848bfdfc4ee</Guid>
      <Parameter>1</Parameter>
      <Operator>equal</Operator>
      <Arguments>
        <Argument>AL</Argument>
      </Arguments>
    </Rule>
  </Group>
</Query>

**Comment by nikataus** [comment]
Hi Daunish, 

We implemented JSON to XML conversion. Then we pass XML as parameter for SQL Stored procedure to retrieve data.

**Comment by daunish-nova** [comment]
Interesting idea, thanks for the reply!

**Comment by mistic100** [comment]
I can't help you on this, and I can't keep every discution about integration in every environment.
