### ISSUE TITLE
SQL Plugin - properly using the IN statement

### ISSUE THREAD

**Issue by shawndibble** [mistic100/jQuery-QueryBuilder#360]
I am using the SQL plugin with the QueryBuilder and I can't figure how to utilize the IN statement. Specifically, how I can have multiple values. For example, lets say I would like to get any results that maybe in the following list: 117,118,126,131.

If I input that into the builder, the SQL plugin will return a result of Select * from TABLE where id in ('117,118,126,131'). Instead, I would like (117,118,126,131) OR ('117','118','126','131'). Maybe there is another way to perform a search with the IN condition, but I can't find any documentation specifically for performing this function and when I try to add in the single quotes, they are scrubbed ie: \'. 

What am I doing wrong?

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/issues/341
https://github.com/mistic100/jQuery-QueryBuilder/issues/217

**Comment by mistic100** [comment]
On second (or third) though, I'll add a separator option for the nest major version (no deadline)
