### ISSUE TITLE
validation error message

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [mistic100/jQuery-QueryBuilder#362]
is there any way to customize the validation error message through something like the [title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern)?

e.g.  when setting
```
validation: {
	format: /^[a-zA-Z]+$/
}
```
the tooltip shows `Invalid format (/^[a-zA-Z]+$/)` - this probably isn't the most descriptive error message for a user.

**Comment by mistic100** [comment]
without better solution (for now) :

```js
$('#builder').on('validationError.queryBuilder', function(e, node, error, value) {
  if (something) {
    error[0] = 'My error message';
  }
});
```

----

But this is not perfect (`error` should be immutable), so I will add a 'displayError.queryBuilder.filter' event called just after the default translation :

```js
$('#builder').on('displayError.queryBuilder.filter', function(e, node, error, value) {
  if (something) {
    e.value = 'My error message';
  }
});
```

and configurable messages at filter level:

```js
validation: {
  messages: {
    format: 'Message when the format is not validated',
    min: 'Message when the min boundary is passed',
    /* etc */
  }
}
```

**Comment by hycday** [comment]
I trying to hide any errors when no filter is applied using : 

```
$('#builder-import_export').on('validationError.queryBuilder', function(e, rule, error, value) {
  if (rule.filter.id == 'no_filter') { 
    e.preventDefault();
  }
});
```


but I get "Uncaught TypeError: Cannot read property 'id' of null"
Can you please provide an example ? 

Thank you so much !
