### ISSUE TITLE
improvements to visibility of selected condition

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [mistic100/jQuery-QueryBuilder#363]
Maybe it's just me, but I'm finding it hard to know whether the `AND` or `OR` condition is set for a particular group.  

I suppose I could custom CSS to overwrite the `btn-primary` class for the `label` and set the color through the `active` class, but perhaps a better way would be to exchange that button group for an [inline radio group](https://getbootstrap.com/css/#inline-checkboxes-and-radios)?

Anyway, I'm loving this project! <3

**Comment by mistic100** [comment]
I agree but this won't change until a new design is created, I try as most as possible ton only rely on Bootstrap components.
