### ISSUE TITLE
Need to change operators display value 

### ISSUE THREAD

**Issue by sandesilva** [mistic100/jQuery-QueryBuilder#364]
How can we change the casing of operator display values.

operators: ['equal', 'not_equal']
I need to display operator values "Equal, Not equal" instead of "equal, not equal".
Please help.

**Comment by mistic100** [comment]
Look at the doc for `lang`  http://querybuilder.js.org/#usage

```js
$('#builder').queryBuilder({
  lang: {
    "operators": {
      "equal": "Equal",
      "not_equal": "Not equal"
    }
  }
});
