### ISSUE TITLE
Query builder disappears when adding plugins

### ISSUE THREAD

**Issue by officiallysameer** [mistic100/jQuery-QueryBuilder#369]
Hi Damien,

First of all I would like to thank you for making this fantastic tool. It definitely saved me a lot of effort trying to write one for my project.

My question might be very trivial, so excuse me for this. I am basically a back-end Java developer and so my question might sound very silly. I have spent couple of days looking trying different possibilities before posting this question.

When I create the normal querybuilder without any plugins,it works fine, the moment i add any, i get a blank page.  I have included the js and css files mentioned, not sure if doing it correctly.

Am including the code. Appreciate any help.
So in the attached code, the moment i remove plugins, t works fine, but as soon as i add them, it fails.

[pluginsExample.txt](https://github.com/mistic100/jQuery-QueryBuilder/files/508365/pluginsExample.txt)

**Comment by mistic100** [comment]
1- the lib available on jsdelivr, donc use rawgit http://www.jsdelivr.com/projects/jquery.query-builder
2- if you use the standalone version, remove dot.js script

----

please setup this example online on jsfiddle or so

**Comment by mistic100** [comment]
and if you had open your web console you would see

> Bootstrap Popover is required for filter-description plugin

As explained here http://querybuilder.js.org/plugins.html#filter-description

**Comment by officiallysameer** [comment]
Thanks Damien for quick response,

It works now. Here it is https://jsfiddle.net/w6hjznhf/
i have seen, if you add a plugin and not the dependencies then it does not display anything.

Similarly, if you add a plugin that is not to be explicitly added, like 'change-filters' for example, the whole thing will stop working.

**Comment by mistic100** [comment]
Again: there are explicit errors in the console.

**Comment by officiallysameer** [comment]
That was the wrong link

**Comment by officiallysameer** [comment]
Here is the updated link

**Comment by officiallysameer** [comment]
https://jsfiddle.net/coks52ot/
