### ISSUE TITLE
TypeError: c[0] is undefined

### ISSUE THREAD

**Issue by karousn** [mistic100/jQuery-QueryBuilder#370]
I have try to integrate the builder by add this files list :
Js : 
- query-builder.standalone.min.js
- sql-parser.js

with QueryBuilder Config :
```js
var options = {
  allow_empty: true,
  //default_filter: 'name',
  sort_filters: true,
  filters: [
  {
    id: 'name',
    label: {
      en: 'Name',
      fr: 'Nom'
    },
    type: 'string',
    optgroup: 'core',
    default_value: 'Mistic',
    size: 30,
    unique: true
  }]
};
$('#builder').queryBuilder(options);
```

but i have this error on console firebug without any view result :
`TypeError: c[0] is undefined`

there is any other js library i must called ?

**Comment by mistic100** [comment]
Include the non-minified script, we can't debug anything here !!

**Comment by karousn** [comment]
using a non-minified script, i got another message error :
`TypeError: $el[0] is undefined` at line :  [this ](https://github.com/mistic100/jQuery-QueryBuilder/blob/master/dist/js/query-builder.standalone.js#L593)

**Comment by mistic100** [comment]
Create a jsfiddle with your code (as asked in the issues guidelines).

**Comment by karousn** [comment]
the problem that i should check the existence of the element #builder before call the init method also by using of Jquery version > 3. I find the way.
Thanks for fast response.

**Comment by mistic100** [comment]
Ok that's because I don't use standard plugin definition. Need a fix (display a real error)

**Comment by karousn** [comment]
i see that in the Project tab view [(here)](https://github.com/mistic100/jQuery-QueryBuilder/projects/1) of the library there is no element in the bug column. it is not automatically updated ?

**Comment by mistic100** [comment]
No  it's not, tell that to the github team :-)
