### ISSUE TITLE
How can I implement NOT for groups and rules?

### ISSUE THREAD

**Issue by thunderbless** [mistic100/jQuery-QueryBuilder#377]
I want to implement:
- NOT A and B 
- A and NOT B
where A and B can be rules or groups:
- A is "lang=es", B is "money > 10"
- A is (lang <> es and lang <>en), B is (money > 10 and money < 100)

**Comment by mistic100** [comment]
You can't.

Feel free to suggest a **usable and clear** interface for this need, I can't think of any.

**Comment by thunderbless** [comment]
- Add checkbox for a rule that negates the rule.
- Add checkbox for a group that negates the group

**Comment by mistic100** [comment]
What does "negate a group" means ?

Did you try the Invert plugin ?

**Comment by thunderbless** [comment]
Let's say we have a group: (lang = es and money=10). By negate I mean to put a NOT in front, resulting in NOT (lang = es and money=10).

**Comment by mistic100** [comment]
Of course it does ! It inverts all the relations, but it's strictly the same thing :
`a AND b` => Invert => `!a OR !b` which is the same thing as `NOT (a AND b)`

---

anyway I'll if I can implement it

The Invert plugin comes from this ticket https://github.com/mistic100/jQuery-QueryBuilder/issues/131
His request was similar to yours but he seemed happy with the plugin.

Hence the importance of being EXTREMELY precise when asking such evolution.

**Comment by thunderbless** [comment]
Yes, I need exactly this. I get as input an expression and I need to load it into the query builder. The user can then modify it and save it. So if I get input=NOT(A and B), I can't have as output=!A or !B (even if logically are the same).
If you could implement this, it would be great.
Adding a checkbox in front of a group/rule that will add a (NOT: true) to the object will do the job. 
Example for group: {condition: "AND", rules: Array[2], **not: true**}
Example for rule: {field:"@Domain", id:"@Domain", input:"text", operator:"equal", type:"string", value:"fgf", **not=true**}

**Comment by mistic100** [comment]
Almost done, just a little more work for Mongo parsing

**Comment by thunderbless** [comment]
Great, thank you :)

**Comment by aciurea** [comment]
Are the last changes that you've done for the NOT implementation released in the version 2.3.4?

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/releases 2.4.0

**Comment by aciurea** [comment]
Can you provide a simple example on how can be used? I mean, the configuration. In the released version there is no example. 
Thank you!

**Comment by mistic100** [comment]
It's a plugin like any other plugins http://querybuilder.js.org/plugins.html
It **IS** enabled in the example file https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/examples/index.html#L142
**AND** in the demo http://querybuilder.js.org/demo.html#plugins

**Comment by aciurea** [comment]
Very good example. Thank you for your work and for the information!
