### ISSUE TITLE
Context-sensitive operator labels

### ISSUE THREAD

**Issue by jimf** [mistic100/jQuery-QueryBuilder#378]
Hi! I'm trying to figure out if there's a way to have operator labels that are dynamic, based on the type of the field being operated on. For example, is there a way to have `greater` labeled as "greater than" for strings, but "after" for dates? I've combed through the docs and source, and it seems this currently isn't baked in per se, but might be achievable through custom operators and/or custom templates. Am I correct on that? If so, any interest in having this implemented as a feature?

**Comment by mistic100** [comment]
Hello,

You have the `getRuleOperatorSelect.queryBuilder.filter` than can be used to edit the labels just before injection in the DOM

```js
$('#builder').on('getRuleOperatorSelect.queryBuilder.filter', function(e, rule) {
  if (rule.filter.type === 'date') {
    var $h = $(e.value); // parse the HTML for easy manipulation

    $h.find('option').each(function() {
      // change the labels
    });

    e.value = $h.prop('outerHTML'); // return modified HTML
  }
});
```

**Comment by jimf** [comment]
Nice! I'm going to need to read up on all these events. Powerful stuff. Thanks for the pointer! 🍻
