### ISSUE TITLE
Inline QueryBuilder

### ISSUE THREAD

**Issue by chrispadfield** [mistic100/jQuery-QueryBuilder#380]
Hi, Slightly strange question for you/your project; but thought there was a chance you might be able to help.

Love this project; we built a QueryBuilder a long time ago - and it would have been so much better to use this. We are considering replacing what we have now with it. Thank you.

We have another part of our interface where we want to avoid using a big query builder but instead use a search bar with auto complete on field values. The focus off the search box is full text search but you can add additional criteria.

The aim is similiar to QueryBuilder but it's a very different UX for the user.

I'm just wondering if you have seen any libraries like this that could help.

![screen shot 2016-10-14 at 12 16 21](https://cloud.githubusercontent.com/assets/318422/19386213/d50d2762-920a-11e6-8f91-4dc7f6ba5cc9.png)

**Comment by mistic100** [comment]
Here #115

**Comment by chrispadfield** [comment]
@mistic100 thank you so much :)
