### ISSUE TITLE
i dont found some file

### ISSUE THREAD

**Issue by AlirezaMokhtari** [mistic100/jQuery-QueryBuilder#381]
hi
i gunna use this jquerybuilder in my app.
when i download this and open in browser some file *.js or *.css is undefined how can download all file?
tnx

**Comment by mistic100** [comment]
When you open what ? Which files are missing ?

**Comment by AlirezaMokhtari** [comment]
when i open example , some file is missing. like this picture.

![capture](https://cloud.githubusercontent.com/assets/22911621/19508051/daadc442-95e3-11e6-8a21-1d25d8d5aef5.PNG)

**Comment by mistic100** [comment]
What is the first sentence in your picture ?
You must also run bower install in the root directory.

**Comment by AlirezaMokhtari** [comment]
thank you
