### ISSUE TITLE
Parent child relationship through query builder

### ISSUE THREAD

**Issue by sandesilva** [mistic100/jQuery-QueryBuilder#382]
Hi,
Can we implement parent child relationship (ex: country and state) in the query builder?

**Comment by mistic100** [comment]
Please be more explicit.

**Comment by sandesilva** [comment]
We added country drop-down filter to query builder. Then we want to add state drop-down, It should be change according to the selected country value. Otherwise all state values should be display.

**Comment by mistic100** [comment]
So you want linked/nested filters. This has already been discussed and this won't be natively supported.

#207
#313 (I didn't answer because I just don't understand what he says)

**Comment by sandesilva** [comment]
Thanks for the information and also quick response.
