### ISSUE TITLE
Is there any internal data source for drop-down filters

### ISSUE THREAD

**Issue by sandesilva** [mistic100/jQuery-QueryBuilder#383]
Do you mange the internal data source for query builder drop-down filters? 
If the answer is yes, Can we access and modify the data source?

**Comment by mistic100** [comment]
Show what you do (**Issues guidelines**). I'm stupid I don't understand textual explanations

**Comment by mistic100** [comment]
And I don't receive notifications when you edit your message -_-

The initial config is cloned and stored in the `settings` internal property.

You can access it in direct **which is totally not recommended** `$('#builder')[0].queryBuilder.settings.filters`
or use the [Change filters plugin](http://querybuilder.js.org/plugins.html#change-filters)
