### ISSUE TITLE
How do you get (export to json) the final data out?

### ISSUE THREAD

**Issue by polomint82** [mistic100/jQuery-QueryBuilder#384]
I can see the import/export for SQL/Mongo, but how do you do a simple export to a json object including children?

**Comment by mistic100** [comment]
Read the doc and the examples ?
`getRules`

**Comment by polomint82** [comment]
Yes I did, but my impression was that getRules returns the rules versus the
data entered by the user?! Is that not the case. In your demo I only see
the conditions/rules output as json.

thanks,
Andrew

**Comment by mistic100** [comment]
It outputs the field+operator+value and the groups. That's the rules, and that's what the user entered.

Just take 5 minutes to read the json and compare it to the gui.

If it's not want you want be more explicit on your demand, good bye.

**Comment by polomint82** [comment]
Yep, my bad. It's an impressive little widget btw.

**Comment by mistic100** [comment]
Thank you
