### ISSUE TITLE
'data' from the 'rule' is retained even if the filter is changed to create a new rule

### ISSUE THREAD

**Issue by boopathi-rs** [mistic100/jQuery-QueryBuilder#386]
Please see my jfiddle - https://jsfiddle.net/boopathiramasamy/xuc5n4ar/19/
I have taken builder-basic demo from your site. Added 'data' ( data: { container: 'user', isCustomData: 'true' }) to the rule (id=price) in rules_basic variable and filter variable. 

 Now what I think can be a bug is, if I change the rule by selecting some other value from the dropdown then 'data' is retained for that rule as well. To reproduce, 

1. Click on 'Get Rules'
2. Notice 'data' is present for price rule.
3. Now change price to category
4. click on 'Get Rules'
5. Notice 'data' is present for category rule as well. Shouldn't data be dropped for category rule because there is no data for category in filter?

This issue does not happen if I delete the existing price rule and create a new rule for category. Can this be a bug? Or am I doing something wrong?

I think I can work around by not adding 'data' to the rules_basic for price rule. But I do not want to do this because I am displaying what was submitted earlier by the user.

**Comment by mistic100** [comment]
Good point.

Easy fix:

```js
$('#builder').on('afterUpdateRuleFilter.queryBuilder', function(e, rule) {
  if (rule.filter.id !== 'price') {
    delete rule.data;
  }
});
```

This could be done automatically.

**Comment by boopathi-rs** [comment]
Seems like it has not fixed the issue. Please see - https://jsfiddle.net/boopathiramasamy/xuc5n4ar/23/
I have removed this check as well - 'if (rule.filter.id !== 'price')' because I think it is unnecessary due to the fact that plugin is merging the data from the filter if found anyway. That means, I can delete data in the rule even for price.

**Comment by mistic100** [comment]
Replace ` delete rule.data`  by `rule.data = undefined`

Why ? The model use setters that are not affected by `delete`

**Comment by boopathi-rs** [comment]
Brilliant, that works. Thanks for your time and quick responses. I will apply the fix in my code.

As a plugin user, from my point of view, I think "rule.data = undefined" should be done whenever filter is changed within the plugin instead of doing it as an event in everyone's script. What do you think?
