### ISSUE TITLE
I need to generate some JSON based on restricted count of objects. Is that good idea to change this project for achieve this purpose?

### ISSUE THREAD

**Issue by neosven** [mistic100/jQuery-QueryBuilder#389]
I have some count of objects looking like this:
{
  node: someNode,
  val1: someVal,
  val2: [{node: someNode, val: someVal}, {..}],
}
I just think maybe I can add select element in the Group and generate my object by choising type of the node. My object will be represented by the Group. At the end of editing getRules() function will be generate JSON.

**Comment by mistic100** [comment]
What ère jbjects ? Thou can use the description odd the issue

**Comment by neosven** [comment]
Sorry, objects.

**Comment by mistic100** [comment]
Detail your question

**Comment by neosven** [comment]
The question is - Is that hard to modify that project for my purpose? Is that a big changing?

**Comment by mistic100** [comment]
You question makes no sense to me.
Reformulate it for normal human beings that doesn't know what you are working on.

**Comment by neosven** [comment]
I'm working on web application wich allow represent JSON through visual interface. User can use this interface to make the hierarchy of objects which he needs and generate JSON by clicking on the button. The objects is not random. There is restricted amount of them. So, user can just choise the required object and fill in the fields. The objects can be nested.

**Comment by mistic100** [comment]
Good for you.
And is still don't know what you want.

If you are not capable to clearly details what you have and what you need I can't help you, sorry.

You know, with code, examples, online demo, etc.

Enough time wasted.

**Comment by neosven** [comment]
No problem. Sorry for wasted your time.
