### ISSUE TITLE
setRules doesnt set value to select from database

### ISSUE THREAD

**Issue by centenario** [mistic100/jQuery-QueryBuilder#390]
Hi, in my project i have a search module where user can save the conditions selected from Querybuilder into a DB, i save info:
- SQL from `$('#builder').queryBuilder('getSQL', false);`
- Rules from `JSON.stringify($('#builder').queryBuilder('getRules'));`

When i show a particular search that is saved in DB i show Name of the search, date, text about search and rules for the search.
I show rules in Querybuilder.
It works fine but when rule is input = select, plugin is selectize and data for selecting comes from Ajax.

Just what i do when i retrieve all data for a search:
- Load all data in their inputs (sql and rules are loading in hiddenfields)
- when document is loaded i call js function for getting filters: there are some fields that are select and data come from AJAX)
- then `$('#builder').queryBuilder({
            plugins: ['bt-tooltip-errors'],
            sortable: true,
            filters: filter,
        });`
- Then `$(document).ajaxStop(function () {
    var rules_basic = jQuery.parseJSON($("#hfsqlrules").val());
    $('#builder').queryBuilder('reset');
    $('#builder').queryBuilder('setRules', rules_basic);
});`

It works OK, but rule for select with plugin selectize where there's not any selected value.

This is rule that i save in DB and load into a hiddenfield "hfsqlrules"
`<input id="hfsqlrules" name="RulesFormatted" type="hidden" value="{&quot;condition&quot;:&quot;AND&quot;,&quot;rules&quot;:[{&quot;id&quot;:&quot;DDDDDD&quot;,&quot;field&quot;:&quot;DDDDDD&quot;,&quot;type&quot;:&quot;integer&quot;,&quot;input&quot;:&quot;select&quot;,&quot;operator&quot;:&quot;equal&quot;,&quot;value&quot;:&quot;0&quot;},{&quot;id&quot;:&quot;EEEEEE&quot;,&quot;field&quot;:&quot;EEEEEE&quot;,&quot;type&quot;:&quot;integer&quot;,&quot;input&quot;:&quot;select&quot;,&quot;operator&quot;:&quot;equal&quot;,&quot;value&quot;:&quot;1&quot;},{&quot;id&quot;:&quot;LLLLLL&quot;,&quot;field&quot;:&quot;LLLLLL&quot;,&quot;type&quot;:&quot;integer&quot;,&quot;input&quot;:&quot;select&quot;,&quot;operator&quot;:&quot;in&quot;,&quot;value&quot;:[&quot;15&quot;,&quot;17&quot;]}]}" />`

Last rule is a select binded from ajax values and it works with plugin selectize.

I even try setrules through a botton click after all data is loaded but it happens the same, so i think is something about setting value in select with selectize plugin.

Thanks in advance.

**Comment by mistic100** [comment]
Please format your code with triple back quote, it's unreadable.

I couldn't help you if you don't setup a live example of your code, sorry.

**Comment by centenario** [comment]
Hi,
i have fixed my problem adding this line from examples:

`
          valueSetter: function (rule, value) {
              rule.$el.find('.rule-value-container select')[0].selectize.setValue(value);
          },`

thanks
