### ISSUE TITLE
Create a redraw method

### ISSUE THREAD

**Issue by pmcfernandes** [mistic100/jQuery-QueryBuilder#391]
Hi, is possible if you can implement a redraw method? This is very important for asp.net ajax webforms because after pagerequest, jquery controls is initialozed in document.ready lost state and need be called again, problem is already filters and rules is there but contol lost status of html.

**Comment by mistic100** [comment]
Sorry but I don't understand, what "redraw" means ? What "control lost status of html" means ? The build is bound to the DOM it generates, if you remove it externally the plugin won't be able to redraw anytning.

This plugin is architectured like any jQuery plugin, show me an example of another jQuery plugin that does what you want.

**Comment by pmcfernandes** [comment]
Sorry for my english. In asp.net all controls is generated in server side and when click on any button they send an event to server and execute there. Not problem is use normal asp.net code behind but when use ajax have a control called UpdatePanel and all code inside is send and received in html way. problem is when code is sent and receive all jquery plugins stop working because dom tree is regenerated and controls stop working. To put it working again we need recall jquery plugins again. 

Problem is with your control is already everything configured in filters and rules and can't get this data again just need a method to recall this all again and rebuild entire layout of control.

**Comment by mistic100** [comment]
Export the rules before refreshing your view our whatever you are doing, then call the destroy method and re-init the plugin completely.
I can't do anything else.
