### ISSUE TITLE
Minified version does not export QueryBuilder global

### ISSUE THREAD

**Issue by buffcode** [mistic100/jQuery-QueryBuilder#392]
The minified version from the 2.4.0 release (`query-builder.standalone.min.js`) is packed in a way, that the `QueryBuilder` global is no longer available.
Defining custom plugins won't work, as `QueryBuilder.define` does not exist anymore.

The library should export it's name to the window global (see https://developers.google.com/closure/compiler/docs/api-tutorial3#export)

**Comment by mistic100** [comment]
`QueryBuilder` was never exported globally, only added to jQuery namespace.

As said in the doc http://querybuilder.js.org/dev/plugins.html, external plugins must use `$.fn.queryBuilder`
