### ISSUE TITLE
Set Selectize options with ajax

### ISSUE THREAD

**Issue by konpa** [mistic100/jQuery-QueryBuilder#393]
I'm trying to implement this [Selectize Example](http://www.escaperoom.com/assets/escapeg/scripts/selectize/examples/github.html) with QueryBuilder.

Here is what I tried :

``` javascript
$('#builder').queryBuilder({
  
  filters: [{
    id: 'ProduitIngredients',
    label: 'Ingredients',
    type: 'string',
    plugin: 'selectize',
    plugin_config: {
      valueField: 'name',
      labelField: 'name',
      searchField: 'name',
      sortField: 'name',
      create: false,
      maxItems: 1,
      options: [],
      render: {
        option: function(item, escape) {
          return '<div>'+item.name+'</div>';
        }
      },
      load: function(query, callback) {
        var that = this;
        if (!query.length) return callback();
        $.ajax({
          url: 'http://localhost/ingredients/search?query=' + encodeURIComponent(query),
          type: 'GET',
          error: function() {
            callback();
          },
          success: function(res) {
            callback(res.slice(0, 10));
          }
        });
      }
    },
    valueSetter: function(rule, value) {
      rule.$el.find('.rule-value-container input')[0].selectize.setValue(value);
    },
    operators: ['contains', 'not_contains']
  }]
});
```

An example of my json : 

``` json
[{
 "id":"6587",
 "name":"asparine"
},{
 "id":"6488",
 "name":"aspagopsis arma"
}]
```

But the callback function does not seem to work. Options values are not updated. 

Any help on this would be much appreciated.

**Comment by mistic100** [comment]
Which callback ? `valueSetter` or Selectize's `callback` ?

If it's selectize one's, start by making the component working alone, outside QueryBuilder.
I can only provide support for QueryBuilder not other components

**Comment by konpa** [comment]
My bad, I did not try to test it outside of QueryBuilder. I just did it and I have the same problem so it's not coming from QueryBuilder. It seems to come from my API response. Anyway, thanks for the quick answer and sorry for the trouble.

**Comment by surajMetkar33** [comment]
@konpa 
Could u paste working code of this?
As u mentioned it was having some issue.
Thanks in advanced
