### ISSUE TITLE
Use events with setRules

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#394]
Hi,

I have 2 filters for States and Counties and implemented logic when the user adds County rule to build relation with State Rule and implement onchange event to populate the county list based on State selected... 
I used the Event system so when the County rule has been created I add my logic or something like:
$('#adhocBuilder').on('afterCreateRuleInput.queryBuilder', function(e, rule) {

		var $container = rule.$el.find('.rule-filter-container');
	 	var countyRule =  $container.find('[name='+ rule.id +'_filter]');
.......
stateValueControl.on("change", (function(){

				var selectedStateCode = $(this).val();
   		 		countyValueControl.empty();
	   				
   				$.each( statesToCountyMap[selectedStateCode], function( key, item ) {
   					countyValueControl.append($('<option>', {
   				        value: key,
   				        text : item
   					}));
   					
   				 });
		 	}));
..............

Here is my issue now: 
I'm using predefined set of rules and I have user profiles to pre define Rules when the User opens the QueryBuilder page. In other words when I initialize QueryBuilder I call at the end
	  	$('#adhocBuilder').queryBuilder('setRules', rules);
When I do this I can NOT use anymore the events and I can NOT build state to county relationship.
Can you please let me know when I use setRules method how can I catch when the Rule has been created, so I can add my logic there?

Thanks in advance!
Nick

**Comment by mistic100** [comment]
Please fix your issue with valid markdown for code block.

----

The only thing I can say is that you must attach events before calling `setRules` and event before initializing the plugin.

**Comment by nikataus** [comment]
Thanks,
I just wanted to know if there are any events I can use when I called setRules, as they way the Rules are created is different when I clicked AddRule button.

**Comment by mistic100** [comment]
It does not differ. The same events are called, in teh same order.

**Comment by nikataus** [comment]
Well, When I call setRules, the 'afterCreateRuleInput.queryBuilder' is not called at all! That's my issue...
When I click AddRule button and add County Rule then 'afterCreateRuleInput.queryBuilder' is called and everything works fine.
Is that expected or I'm not doing something right?

**Comment by mistic100** [comment]
Can you just post the full code online ?
