### ISSUE TITLE
Editable filters for Rules

### ISSUE THREAD

**Issue by aciurea** [mistic100/jQuery-QueryBuilder#395]
Hello!

I want to edit the filters for Rules.
 For example: if I have '@lang' = 'en'
 I want to do something like this: '@language' = 'en'. For now there is a "select element" and I can choose only filters that are defined before there are passed to query builder.
I tried to modify your library but for future releases this is not the solution.
Is there a way that you can implement this?
Thanks!

**Comment by mistic100** [comment]
Once again I don't understand what you want.

**Comment by aciurea** [comment]
![image](https://cloud.githubusercontent.com/assets/11313484/20488456/b1dd7ce2-b00f-11e6-99b2-4d8533e32415.png)

I want the field with "lang" inside to be editable

**Comment by mistic100** [comment]
As you certainly understood this is not how the builder works, filters are part of the config and they are static. You can programatically add/remove filters with `set-filters` plugin but they cannot be edited.

It's just not possible unless rewriting the whole library.

**Comment by aciurea** [comment]
Ok, I understand. Thank you very much.
