### ISSUE TITLE
Distinction between 'no rules' and 'invalid rules'

### ISSUE THREAD

**Issue by Ruud-cb** [mistic100/jQuery-QueryBuilder#397]
From user experience, users sometimes tent to remove all individual rules and then hit a Filter button again, which eventually calls:

`var rules = $('someElement')[0].queryBuilder.getRules();`

This returns an empty object, that is quite logical of course, there are no rules anyway. In that case we could manually reset everything and pull all records from the server again.
But when we have set a few rules, forgot to fill a field and hit filter, the model is also invalid which also returns an empty object. Resetting everything at this point is not a good idea of course.

Can we have a distinction from `getRules()` (or any other new method) to check if there are no rules at all or rules exist with errors? Perhaps just always return the rules where the first object always contains a boolean indicating if the model is valid or invalid.

**Comment by mistic100** [comment]
Good idea. I imagine this behavior :

- if the builder is valid: returns the rules as usual
- if the builder is empty and `allow_empty: true`: returns an empty object
- if the builder is invalid: there will be a new option for the `getRules` method
  - default behavior: returns `null`
  - `getRules({return_invalid: true})`: returns the rules with an additional ` invalid`  property

**Comment by Ruud-cb** [comment]
perfect, thanks!

**Comment by mistic100** [comment]
I read again the code and in fact I think your first message is wrong : if I call `getRules` with an empty builder I don't get an empty object, I get `{ condition: 'AND', rules: [] }`  and I effectively get an empty object of the builder is invalid.

So what exactly is your need ?

**Comment by Ruud-cb** [comment]
Ah I didn't configure `allow_empty: true`. Now I indeed receive the same object as you mentioned. Well for me it is perfect then, perhaps someone else would desire to have the rules returned when it is invalid.
