### ISSUE TITLE
Prevent drop on a specific rule

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#399]
Hi,

I saw there is new config no_sortable which removes the drug handle which is good. However is it possible to configure panel where you can not drag and drop item? For example I have preset a Rule say State and configured only AND condition so that I can only add more rules/groups behind but I don't want to allow Rules/Groups to be drag and dropped before that State Rule. Please let me know if that is doable.

Thanks,

**Comment by mistic100** [comment]
Isn't that an obscure explanation for a "no_drop" flag ?

Otherwise please post a picture of what you mean.

**Comment by nikataus** [comment]
Yes, if you can configure area where you can not drop another Rule or Group - like disabled.
