### ISSUE TITLE
Reverse search of item?

### ISSUE THREAD

**Issue by HolyOne** [mistic100/jQuery-QueryBuilder#400]
I have a field "email" in my database.
I select email from querybuilder and I have 2 options, BeginsWith and Endswith

Implementing BeginsWith is easy

      begins_with: function (v) {
          return {
              '$regex': "^\\Q" + v[0] + '\\E.*',
          };

But for endswith part, I have another field in my database which is the reverse copyd of email field. (For Indexed search) its name is "_email"

  How can I create ends_with function so it wont scan the email field but it will scan another field "_email" for reversed copy? (I can reverse the string, I just cant make it search another field after selecting ends_with from submenu)

**Comment by mistic100** [comment]
That's something you will have to do outside the builder by traversing the json object and make the necessary changes.

**Comment by HolyOne** [comment]
That was hard to do, to traverse and change the bson document from
serverside, but it seems the right way to go
Thanks
