### ISSUE TITLE
Unable to Remove a Rule before "setRules"

### ISSUE THREAD

**Issue by raj-vel** [mistic100/jQuery-QueryBuilder#401]
Hello,
I have a typical scenario on setRule functionality and explained it below.
-- Day1: There are 3 filters (Id1, Id2, Id3) defined
-- Day1: I selected filters Id1 and Id2 and saved the rules
-- Day1: When i come back and load query builder, Id1 and Id2 are loaded in query builder
--Day2: Due to some need, Id1 is removed from filters in DB. So the filter will NOT have Id1 going forward. But it was used on one of the Rules
--Day2: When the user tries to load that query builder, "setRules" throws error saying that "Id1" is not defined

My requirement is to load the query builder with only "Id2" and without any exception which is caused due to missing "Id1". When i tried this in JSFiddle, i didn't get exception on "setRules" however "Id2" is also not selected when the query builder is loaded. I have given the JSFiddle link below. Thank You.

https://jsfiddle.net/z84wakwh/1/

**Comment by mistic100** [comment]
When I load your fiddle I do get an error in the console, and of course the second filter is not loaded : the parsing stops.

I will think about a "symetric" option to #397

**BUT** you should really migrate your data when you make such changes, keeping invalid data in your database is a **very** bad idea.

**Comment by raj-vel** [comment]
I iterate through the list of rules and identified the dead rules.  In the dead rules, i am trying to replace it with [ ] rule or [ { empty: true } ], but it also throws error.  Basically I tried to replace empty rule instead of that dead rules, that also didn't work, throwed the same error. And below is the example of what i tried

// set rules
$('#builder').queryBuilder('setRules', {
  "condition": "AND",
  "rules": [
     {
      empty: true
    },
     {
      "id": "id2",
      "field": "id2",
      "type": "string",
      "input": "text",
      "operator": "in",
      "value": "VALUE-2"
    }
    
  ]
});

**Comment by mistic100** [comment]
Are you sure you use version 2.4.0 ? it works on the demo https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/examples/index.html#L490
