### ISSUE TITLE
Support for very long filters list

### ISSUE THREAD

**Issue by pavelber** [mistic100/jQuery-QueryBuilder#402]
Is it possible (may be with some plugin) to make field name to be a text box with "hints as you type" ?

I.e. field name is not a combobox, but free text field and as a user types in it, ajax request will bring possible field names with such prefix

**Comment by mistic100** [comment]
You can wire any jquery plugin to the value input (read the doc) so you can use Selectize or such plugin.

**Comment by pavelber** [comment]
I need it for the field name, not value!

**Comment by mistic100** [comment]
Sorry :s
You can inspire yourself of the Bootstrap selectpicker plugin https://github.com/mistic100/jQuery-QueryBuilder/tree/dev/src/plugins/bt-selectpicker which applies Selectpicker to filter and operator dropdown to create a new plugin that applies Typehead to the filter dropdown.

**Comment by pavelber** [comment]
Not sure that I have enough javascript knowledge :(

Thank you
