### ISSUE TITLE
Input filter function called twice?

### ISSUE THREAD

**Issue by mnbeer** [mistic100/jQuery-QueryBuilder#407]
Within `setRules add()`

both of the following lines: 

```
model.filter = self.getFilterById(item.id);
model.operator = self.getOperatorByType(item.operator);
```
call `defineModelProperties`, which issues ` this.model.trigger('update', this, field, value, oldValue);`, which in turn seems to call the filter input function.  This can result in duplicate elements inserted in .rule-value-container (and in my case, duplicate ajax calls fetching the data to fill the container).

Perhaps the trigger should be deferred until the all properties are set, rather than firing upon each property change?

**Comment by mistic100** [comment]
I never encountered duplicates elements, please provide a demo of the problem.

**Comment by mnbeer** [comment]
Sorry, I have not had time to build a demo of the problem. It is on my todo list. I was able to work around it with a very small hack so I have not returned to this issue.
