### ISSUE TITLE
Custom rule data (checkbox)

### ISSUE THREAD

**Issue by pavelprokes** [mistic100/jQuery-QueryBuilder#408]
Hi!

I'm working with querybuilder long time and it is great tool! Now I have about the task add a checkbox on every rule (row). I made simple plugin with adding a checkbox rules with some default value from options. Now I need some help. How can I manipulate with this checkbox value into querybuilder? I mean .. how set the default variable. After the call getRules / setRules get every rule checkbox value into data?

Thank you!
Pavel

**Comment by mistic100** [comment]
How could I help you don't publish a demo of your plugin ?

I can just say that there are events and filter (see the doc) that you can use.

**Comment by pavelprokes** [comment]
Ok! Thank you! I solved this.
