### ISSUE TITLE
How to set the default value for a select input rule?

### ISSUE THREAD

**Issue by Ruud-cb** [mistic100/jQuery-QueryBuilder#410]
On the demo's I see that a default rule value is selected for a select box, but nothing shows me how to set the default value for the select box?
When I choose the field 'Category', it automatically takes 'Books' as first rule.
Am I missing something within my own application?

If it is something other then my application:
Perhaps make use of `default_value` and set it element to `selected` if it is.

So inside **template.js**, this line: https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/template.js#L198
would change to:
```
Utils.iterateOptions(filter.values, function (key, val) {
    h += '<option value="' + key + '" '+ (filter.default_value === key ? ' selected' : '')+'>' + val + '</option> ';
});
```
(did not check for errors).

**Comment by mistic100** [comment]
Just tested on the example page with a `default_value` and it works, because of this line https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/core.js#L616 and the model change listeners, no need to modify the template.

```js
  {
    id: 'category',
    type: 'integer',
    input: 'select',
    default_value: 3,
    values: {
      1: 'Books',
      2: 'Movies',
      3: 'Music',
      4: 'Tools',
      5: 'Goodies',
      6: 'Clothes'
    }
  }
```

**Comment by Ruud-cb** [comment]
Thanks, was indeed my application that modified the rules somewhere else.
