### ISSUE TITLE
Use Jquery autocomplete in QueryBuilder

### ISSUE THREAD

**Issue by Ruud-cb** [mistic100/jQuery-QueryBuilder#413]
Happy newyear!

So I've implemented selectize, works perfect for the filtering part and getting the right value out there. Selectize seems to be smart and automatically assigns the `Id` value to the `rule.value`. Awesome.

Now, I'm not 100% happy with Selectize. It only shows items that are really in the search string although the back-end provides more data (use of abbreviation, synonyms), it has 100+ outstanding PR's and 300+ issues, which makes me worried it won't be supported that much in the future. Kind of a big deal actually...

So I'm POCing jquery autocomplete in there, but it seems that I am missing something. I can search for values, I can select one and it correctly shows in the UI, but the rules don't have any value.
jquery autocomplete does have a `onSelect` event, which gives me the item. Any chance I can throw that into the querybuilder? Or how would I need to configure the plugin to do that automatically.

My configuration:

```
filter.plugin = 'autocomplete';
filter.plugin_config = {
    url: "/AircraftType/GetItems",
    source: function (query, callback) {
        var url = "";
        if (this.options) {
            url = this.options.url;
        }
        $.ajax({
            url: url + "?term=" + query.term,
            type: 'GET',
            error: function () {
                callback();
            },
            success: function (data) {
                callback(data);
            }
        });
    },
    select : function(event, ui) {
        $("#internationalFilters .queryBuilder")[0].queryBuilder.trigger("change");
    },
```

Data format:

```
{
id : 479,
label :"B707-3",
value : "B707-3",
}
```

The tricky part: The rules are not static, they get loaded from the back-end. In this example I have the url hardcoded but that will eventually come from the back-end as well. So it's not really easy to find the correct rule, set it's value and do a `setRules()`. I hope I can configure the plugin beforehand.

Best would be, for both selectize and this, to get the id and the value from the rules, so the rules can be stored and loaded correctly.

**Comment by mistic100** [comment]
Your trigger change is not correct, you need to trigger this event on the input holding the autocomplete, not the whole builder.

**Comment by Ruud-cb** [comment]
Yes I know, I would love to, but from this event I have no reference to the input element. The event only has a `currentTarget` to the autocomplete list.
After some more digging, a `change` event seems to has hold of the input element as `currentTarget`
I'm able to do this now:
 
```
change: function (event, ui) {
    var el = event.element;
    $(event.currentTarget).trigger('change');
},
```
That now sets the `rule.value` to the text. But now, it needs to set the Id. Any recommendations?
Thanks for your time though @mistic100, your fast response is really appreciated, there should be more open-source 'managers' like you.

**Comment by mistic100** [comment]
That's the responsibility of autocomplete to populate the input with the desired value, it must be configurable, if not you can do it yourself in the select callback

**Comment by mistic100** [comment]
You must alter the input value and then trigger a change, do not manually modify the rule value.

**Comment by Ruud-cb** [comment]
Ok, I will try that but it doesn't seem to be a success.
Back to selectize then, do you know how to get the `id` and the `label` (or name) when I retrieve the rules?
Let's say I have everything saved, I can use the `valueSetter` to add an option to selectize and set it's value. 

```
    filter.valueSetter = function (rule, value) {
        if (value) {
            rule.$el.find('.rule-value-container input')[0].selectize.addOption(value);
            rule.$el.find('.rule-value-container input')[0].selectize.setValue(value.id);
        }
    },
```
Unfortunately, the `valueGetter` doesn't have a value (or a label?) when I call `getValue()`. Do you know how to configure Selectize, or your query builder, to include the label (text) when I call `getRules()`?

**Comment by mistic100** [comment]
A rule can only one value (a basic type not an object), the technical id of the item you choosed or an enum value or a free input. it cannot store an id AND the label, up to you to fetch the label from the server.

**Comment by mistic100** [comment]
And about Autocmplete, did you try `$(event.currentTarget).val(ui.item.id);` ? it should work

**Comment by Ruud-cb** [comment]
`$(event.currentTarget).val(ui.item.id);` Does work but that of course changes the input text to the id, which is not what we want of course. Normally there would be a hidden field that holds the id and that can be used later to get the id. But I'm stuck in doing something similar in the query builder. Like adding an additional property to the rule should do the job. 
The reason I try this is because everything is very generic, getting the label later from the server or on the serverside would require a lot of additional code (and thus performance issues), I would need to find out (or specify) of what type it is, what database table / repository to target and what the column would be to use for the label. All that could be avoided by just storing the label AND Id somewhere in the query builder. I don't like messing around with elements and selectors, but a hack is worth it. Preferred jquery.ui.autocomplete.

So: Is it possbile from the `$(event.currentTarget)`, to retrieve the rule? How? 
I just came up with this: Access the `data` property of the filter condition to store the id? That would be good?
Do the same the other way around would be easy then, just set the id in the `data` property.

**Comment by Ruud-cb** [comment]
I got it.

```
change: function (event, ui) {
    $(event.currentTarget).trigger('change');
    var ruleElem = $(event.currentTarget.offsetParent);
    var data = ruleElem.data();
    data.queryBuilderModel.filter.data =  ui.item;//contains id and label
},
```

This sets the data for the rule, and once we do `getRules()` the specific rule has a data object with the id and the label. `data` property is specified in the documentation. So I think it's correct to use it for this.
I store that on the server, once it comes back I will set the `data` property again with the saved rules.

Thanks a lot for your time! Really appreciated 👍 .

**Comment by prcongithub** [comment]
@Ruud-cb Where can I find the complete working plugin code? I need to something similar for my usecase,

**Comment by Ruud-cb** [comment]
> @Ruud-cb Where can I find the complete working plugin code? I need to something similar for my usecase,

@prcongithub sorry I don't have access to that code anymore and it is probably outdated.
