### ISSUE TITLE
Pagination for select field.

### ISSUE THREAD

**Issue by machindrakarpe** [mistic100/jQuery-QueryBuilder#415]
We have huge number of items in select option which need to be download from server after user select option left to operator on the basis of selected option we need to download select options and we need to add pagination as well.
How we can achieve above ?

Thanks!

**Comment by mistic100** [comment]
you are using ten times the same word "option" for apparently different things, I can't understand you.

Are talking about filters, operators or input values ?

**Comment by machindrakarpe** [comment]
On the basis of filter we need to get list of values from server with pagination. How can achieve same?

**Comment by mistic100** [comment]
Use a plugin like Selectize that allows async data sources, see the source of the Widgets example http://querybuilder.js.org/demo.html#widgets

**Comment by machindrakarpe** [comment]
I already tried **Selectize** but it does not allow pagination.

**Comment by machindrakarpe** [comment]
Is there any other way wich allow pagination for value ?

**Comment by mistic100** [comment]
Plugins, search on google, there are plenty of them, select2, selectivity, typehead...
