### ISSUE TITLE
Question on demo Widgets with coordinates (custom input)

### ISSUE THREAD

**Issue by dhuneault** [mistic100/jQuery-QueryBuilder#416]
The valueGetter doesn't return the last values if you change the first select (A,B,C) and the second select has no selection.

The default value is B and 3.  If you change the first to C, the second select has no selection.

Then click the Get Rules, you'll get the value C.3, but the second select has no selection!!!

I use the same technics with 3 selects in my project, and only the first one is correctly returned by valueGetter or getRules. 

How to get the last values of every selects???

Thanks!

D.

**Comment by mistic100** [comment]
Problem is the builder is only informed of the "change" event of the first select, because we do not trigger a change event on the second one after modifying the options, hence "valueGetter" is not called a second time and the model value is outdated.

Just pushed an update of the demo.

**Comment by mistic100** [comment]
```js
$container.find('[name$=_2]')
          .html(h).toggle(!!h)
          .val('-1').trigger('change'); // <=====
```
