### ISSUE TITLE
Issue adding second custom HTML filter using BETWEEN operator

### ISSUE THREAD

**Issue by donCarlosOne** [mistic100/jQuery-QueryBuilder#417]
Hey, great control.

I'm designing a trigger filter that uses a function to define the trigger:

```js
dateIntervalFilter = {
    	type: 'string',
		input: function(rule, name) {

			return '<input type="text" id="input_{0}" />&nbsp;<select id="select_{0}" name="select_{0}"><option value="Days">Days</option><option value="Weeks">Weeks</option><option value="Months">Months</option></select>'.format(name);
		},
		valueGetter: function(rule) {

			var retVal;

			if(!_.isEmpty(rule.$el.find('.rule-value-container [name$=_1]').val())) {

            	retVal = ">='P{0}{1}' && <='P{2}{3}'".format('0',rule.$el.find('.rule-value-container [name$=_0]').val().substr(0, 1), '0', rule.$el.find('.rule-value-container [name$=_1]').val().substr(0, 1));
            }
            else {
            	retVal = 'P{0}{1}'.format('0', rule.$el.find('.rule-value-container [name$=_0]').val().substr(0, 1));
            }
        }
	},
```

This works fine when it is first rendered:

![image](https://cloud.githubusercontent.com/assets/2841617/21888273/2ff06b96-d8cc-11e6-9783-45476b6f3cd8.png)

But throws an error when changing the operator to BETWEEN (or NOT BETWEEN), and kills subsequent javascript processing.  The HTML is rendered correctly:

![image](https://cloud.githubusercontent.com/assets/2841617/21888318/64110e80-d8cc-11e6-9484-eea6ca409621.png)

and this is the error thrown:

> 
Uncaught TypeError: Cannot read property '0' of undefined
    at g.setRuleInputValue (query-builder.standalone.min.js:7)
    at g.updateRuleValue (query-builder.standalone.min.js:7)
    at g.updateRuleOperator (query-builder.standalone.min.js:7)
    at b.update (query-builder.standalone.min.js:7)
    at b.dispatch (jquery-2.2.4.min.js:3)
    at b.r.handle (jquery-2.2.4.min.js:3)
    at Object.trigger (jquery-2.2.4.min.js:4)
    at n.fn.init.triggerHandler (jquery-2.2.4.min.js:4)
    at b.trigger (query-builder.standalone.min.js:8)
    at k.set [as operator] (query-builder.standalone.min.js:8)

**Comment by donCarlosOne** [comment]
As a side note, this error occurs ANY time the operator is changed from "equal" to another setting.

**Comment by mistic100** [comment]
Please use not minified code.

But I'm pretty sure your valueGetter is not doing what you want at all : everything you return will be escaped, it cannot contains SQL (or other) code

**and it's missing a return statement**

it would more be something like :

```js
valueGetter: function(rule) {
  if (!_.isEmpty(rule.$el.find('.rule-value-container [name$=_1]').val())) {

    return [
      "'P{0}{1}'".format('0', rule.$el.find('.rule-value-container [name$=_0]').val().substr(0, 1)),
      "'P{0}{1}'".format('0', rule.$el.find('.rule-value-container [name$=_1]').val().substr(0, 1))
    ];
  }
  else {
    return 'P{0}{1}'.format('0', rule.$el.find('.rule-value-container [name$=_0]').val().substr(0, 1));
  }
}
```

**Comment by azotklas** [comment]
I also have a problem
![default](https://cloud.githubusercontent.com/assets/12971978/22208745/040414d4-e195-11e6-9942-04811fb16c32.PNG)
     ```
{
		type: t('is in the range'),
		nb_inputs: 2,
		multiple: true,
		apply_to: ['string'],
		placeholder: t('first value - second value')
	}
```

**Comment by mistic100** [comment]
Please create a real issue with your full conf and a proper description of the problem.
