### ISSUE TITLE
How to add fieldS?

### ISSUE THREAD

**Issue by azotklas** [mistic100/jQuery-QueryBuilder#419]
i used Angular
I have operators (is,is not, is in the last, between ).
Once I choose "is in the last" I want to see next to the text box and drop list

[size] - [is] - [input='text']
[size] - [is not] - [input='text']
[size] - [is in the last] - [input='text'] - [select]
[size] - [between] - [input='text'] - [input='text']

how to do it?

**Comment by mistic100** [comment]
Set the filter's `input` as a function to manually build your HTML, you also must define `valueGetter`  and `valueSetter` 
See the doc and the example sources on the website.

**Comment by mistic100** [comment]
This config is only available per filter, so you must define it for ev ery filter using this operator

**Comment by azotklas** [comment]
@mistic100 The example shows how to do this visually. but the code is not clear how this is implemented!

**Comment by mistic100** [comment]
Sorry for that. I cannot provide further details.

**Comment by mistic100** [comment]
Ad i don't know how it could be more clear https://github.com/mistic100/jQuery-QueryBuilder/blob/gh-pages/assets/demo-widgets.js#L112-L161
build the html, define the getter, define the setter
