### ISSUE TITLE
Rules builder

### ISSUE THREAD

**Issue by schalla27** [mistic100/jQuery-QueryBuilder#420]
Hi 

can the jquery Query builder be used as a Rules builder where the user can customize a set of rules.
Based on the output of a rule, can I have logic to show hide checkboxes, change labels or invoke another set of rules?

**Comment by mistic100** [comment]
You will have to detail much more your need. Here it doesn't mean anything for me.

**Comment by jsdev** [comment]
@schalla27 yes jquery query builder has hooks to do whatever you want.

**Comment by schalla27** [comment]
I am wondering if this query builder can be used as the UI for  a rules engine.A admin user will have access to choose fields and then set up validations on those fields. These validations are of two kinds: The first set of rules decide what fields to go on the template. The second set of rules/validations are set up on the fields.  Lets say, the user drags a checkbox to the form. Now if the checkbox is checked, he wants to show another textbox. On  a side note, for building the form I a looking into jquery form builder.

**Comment by mistic100** [comment]
I'm afraid I can't help you, it's too specific. Play with the lib and decide yourself.

**Comment by schalla27** [comment]
well Thanks!
