### ISSUE TITLE
How to avoid optimization

### ISSUE THREAD

**Issue by viktor-oleksyshyn** [mistic100/jQuery-QueryBuilder#421]
Hello, I have found interesting behavior. Example steps:

1. Filled query builder:
   _AND
    &nbsp;Price  less 10
     &nbsp;Price  more 5
      &nbsp;&nbsp;AND
       &nbsp;&nbsp;&nbsp;Category not equal Books
       &nbsp;&nbsp;&nbsp;Category not equal Music_

2. Saved used **var temp = $(...).queryBuilder('getSQL').sql**
3. Restored using **$(...).queryBuilder('setRulesFromSQL', temp)**
4. query builder looks:
   _AND
     &nbsp;Price  less 10
     &nbsp;Price  more 5
     &nbsp;Category not equal Books
     &nbsp;Category not equal Music_

I understand that there is no sense to have those groups with AND in both cases, but if I would like to change second AND to OR - after restore I need to remove 2 last rules and recreate group.

Is it possible somehow to keep rule groups as they are?

Best regards,
Viktor

**Comment by mistic100** [comment]
Impossible, this is bound the tokenizer of sql-parser
