### ISSUE TITLE
Question: Are there any "Order By" plugins?

### ISSUE THREAD

**Issue by gawpertron** [mistic100/jQuery-QueryBuilder#422]
Are there any "order by" plugins to specify sorting order using similar UI? Resulting in e.g. 

`{sort : [{field : "foo_bar", direction : "ASC"}, {field : "choo_char", direction : "DESC"}]}`

**Comment by mistic100** [comment]
QueryBuilder is only for where clauses.
Referencing to #310 for every other parts of the query
