### ISSUE TITLE
Incorrect quotes in Mongo export

### ISSUE THREAD

**Issue by pavelber** [mistic100/jQuery-QueryBuilder#424]
I have a filter of type "string" and I'm using "IN" operator (see screenshot)
![image](https://cloud.githubusercontent.com/assets/4849450/22416768/35e2d028-e6d9-11e6-8997-7c759f27a1cd.png)

I got in the mongo export `"{"$and":[{"SubjectID":{"$in":["TCGA-EE-A2A6, TCGA-EE-A2GE"]}}]}"`
instead of `
"{"$and":[{"SubjectID":{"$in":["TCGA-EE-A2A6", "TCGA-EE-A2GE"]}}]}"`

(quotes on each item)

**Comment by mistic100** [comment]
This has been answered numerous times : the builder CANNOT know it should split the value on comma.

Use the filter "value_separator" option.
