### ISSUE TITLE
[Help Req]  How to make the "Add Group" button not add a rule?

### ISSUE THREAD

**Issue by mreishus** [mistic100/jQuery-QueryBuilder#425]
The addGroup function's second parameter specifies if the newly created group will have a rule inserted. 
 It defaults to true if undefined.

```
QueryBuilder.prototype.addGroup = function(parent, addRule, data, flags) {
    addRule = (addRule === undefined || addRule === true);
```

The default group template creates an "Add Group" button:
```  
            {{? it.settings.allow_groups===-1 || it.settings.allow_groups>=it.level }} 
                <button type="button" class="btn btn-xs btn-success" data-add="group"> 
                <i class="{{= it.icons.add_group }}"></i> {{= it.lang.add_group }} 
                </button> 
            {{?}} 
```

This is bound to run the addGroup function via the `data-add="group"` attribute it has.
```
        this.$el.on('click.queryBuilder', Selectors.add_group, function() {
            var $group = $(this).closest(Selectors.group_container);
            self.addGroup(Model($group));
        });
```

I would like this button to never add a rule to the new group.  That is, I would like it to run `self.addGroup(Model($group), false);` instead of `self.addGroup(Model($group));`.  However, I can't think of a way to do this without modifying the source of queryBuilder.   Do you have an idea how I can achieve this?

**Comment by mistic100** [comment]
Hello

here is a quick untested solution :

```js
// overload addGroup to make addRule=undefined behaves like addRule=false
var _addGroup = $.fn.queryBuilder.constructor.prototype.addGroup;

$.fn.queryBuilder.constructor.prototype.addGroup = function(parent, addRule, data, flags) {
  return _addGroup.call(this, parent, addRule===true, data, flags);
};
```

**Comment by mreishus** [comment]
This worked... thanks, mistic!
