### ISSUE TITLE
Ignore empty rules (not empty values)

### ISSUE THREAD

**Issue by Ruud-cb** [mistic100/jQuery-QueryBuilder#426]
Hi,
We have the option to add an empty rule to the builder. But I believe the builder should ignore the empty rule.
To illustrate: In our application, once a user selects a parameter te filter on, an empty rule is automatically added:
![image](https://cloud.githubusercontent.com/assets/10037514/22458110/4652b190-e79b-11e6-91a9-dac43bdb6906.png)
This so the user can easily select new parameters to filter on. The add and group button are hidden in a 'simple filter mode'.

 I've setup custom validation so all rules should come across this callback method. Now the empty rule doesn't, of course.
Could you add an option to allow empty rules or ignore empty rules? I know we already have allow empty values.

Workaround now would be to use `allow invalid rules`, then check every rule if it is not valid and empty.

EDIT: Workaround works, but it will still show an indicator that "no filter is selected". Setting property `valid` to true doesn't help either.

**Comment by Ruud-cb** [comment]
So for this feature, we have the following options:

1. Don't show error icon/message when `allow_invalid` is true when calling `getRules()`
However: This would require another functionality to manually set errors. I think it is not recommended.
2. Don't skip an empty rule when doing validation. Now when I call `getRules()`, all rules are getting validated (using a callback in my scenario) expect for the empty rule one. Probably because it is missing data somewhere. This way the user can decide on validation if he wants to show an error when an empty rule is not set. Might be in need of code adjustments in some if-elses where it requires some data for validation, didn't look at the code yet but it might be a hack.
3. Add a property to the filter options, telling it to skip empty rules (most easy one?). Simply before deciding a particular rule is invalid, check if it has at least ANY property set (operator, filter, value, (sub)rules, condition).

@mistic100 What do you prefer? I'm considering doing it.

**Comment by mistic100** [comment]
1. no
2. i don't understand
3. there already an "allow_empty" flag at filter level, but in your case you don't event have a filter, so it's not suitable

I propose : ass a "skip_empty" option for the `getRules()` method which will ignore rules without filter selected and discard them in the output

**Comment by Ruud-cb** [comment]
Alright, seems easy to implement.
