### ISSUE TITLE
setRules/specifying rules not applying value 

### ISSUE THREAD

**Issue by donCarlosOne** [mistic100/jQuery-QueryBuilder#427]
I've encountered an issue creating a new queryBuilder using query-builder.standalone.js and applying existing rules (saved from a user's previous session).  Regardless of how I apply the rules, either during initialization or by explicitly calling setRules after creating the queryBuilder, this fails - and gives a hard error preventing further script execution.

I've traced the issue to the QueryBuilder.prototype.setRules method.  In line 1695, self.getOperatorByType references model.value - which has not been set yet, causing the reference to it to crash.

I see that model.value is set AFTER calling self.getOperatorByType, which never gets executed.

I've worked around this by setting model.value immediately prior to executing self.getOperatorByType, and it works as expected.

```js
if (model.filter) {
                        model.value = item.value;
                        model.operator = self.getOperatorByType(item.operator, !options.allow_invalid);

                        if (!model.operator) {
                            model.operator = self.getOperators(model.filter)[0];
                        }

                        if (model.operator && model.operator.nb_inputs !== 0 && item.value !== undefined)         {
                            model.value = item.value;
                        }
                    }
```

**Comment by mistic100** [comment]
And what is the error exactly ?

`getOperatorByType` does not references model.value https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/data.js#L301-L315

**Comment by donCarlosOne** [comment]
Here's some additional info.  Perhaps it is not getOperatorByType, but when I step through the code, that is the last line of code executed.  Here are some screen shots.

Call Stack
![image](https://cloud.githubusercontent.com/assets/2841617/22510256/fb9dee62-e899-11e6-9fe1-09f7b82a75b4.png)

Code that calls getOperatorByType
![image](https://cloud.githubusercontent.com/assets/2841617/22510274/09cc1676-e89a-11e6-9572-1f0c1f89498c.png)

Error occuring, with value displayed as undefined (it should be '2017/02/01')
![image](https://cloud.githubusercontent.com/assets/2841617/22510307/227f555c-e89a-11e6-854e-38abd30f3f70.png)

Below is the error:

Uncaught TypeError: $value.find(...).val(...).trigger is not a function
    at QueryBuilder.setRuleInputValue (query-builder.standalone.js:2148)
    at QueryBuilder.updateRuleValue (query-builder.standalone.js:1284)
    at QueryBuilder.updateRuleOperator (query-builder.standalone.js:1275)
    at Model.update (query-builder.standalone.js:930)
    at Model.dispatch (jquery-3.1.1.min.js:3)
    at Model.q.handle (jquery-3.1.1.min.js:3)
    at Object.trigger (jquery-3.1.1.min.js:4)
    at r.fn.init.triggerHandler (jquery-3.1.1.min.js:4)
    at Model.trigger (query-builder.standalone.js:2527)
    at Rule.set [as operator] (query-builder.standalone.js:2583)
QueryBuilder.setRuleInputValue @ query-builder.standalone.js:2148
QueryBuilder.updateRuleValue @ query-builder.standalone.js:1284
QueryBuilder.updateRuleOperator @ query-builder.standalone.js:1275
update @ query-builder.standalone.js:930
dispatch @ jquery-3.1.1.min.js:3
q.handle @ jquery-3.1.1.min.js:3
trigger @ jquery-3.1.1.min.js:4
triggerHandler @ jquery-3.1.1.min.js:4
trigger @ query-builder.standalone.js:2527
set @ query-builder.standalone.js:2583
(anonymous) @ query-builder.standalone.js:1695
add @ query-builder.standalone.js:1656
QueryBuilder.setRules @ query-builder.standalone.js:1719
QueryBuilder.init @ query-builder.standalone.js:672
QueryBuilder @ query-builder.standalone.js:296
$.fn.queryBuilder @ query-builder.standalone.js:3136
createTriggerSet @ tableMapping.js:512
createTriggerOptions @ tableMapping.js:393
(anonymous) @ tableMapping.js:421
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
A @ jquery-3.1.1.min.js:4
(anonymous) @ jquery-3.1.1.min.js:4

**Comment by donCarlosOne** [comment]
Didn't mean to close ... hit wrong button

**Comment by mistic100** [comment]
Can you post your config and rules ? I never had this problem and I don't understand why.

**Comment by mistic100** [comment]
I took a deeper look at the code and I don't understand why doesn't crash every time... might be some concurency with other part of the code.

When we enter `setRuleInputValue` the value in `undefined`  thus `val` is used as a getter and not a setter (damn it jQuery), and of course there is no `trigger` method on a string.

I need your conf to find what's going on.

**Comment by donCarlosOne** [comment]
The rules are set dynamically ... by capturing an existing set of rules, storing them, and then redisplaying them when the user accesses the same panel again.  Here's a screenshot, followed by one with the rules ...

![image](https://cloud.githubusercontent.com/assets/2841617/22546851/8154b664-e947-11e6-812f-a93df31ef548.png)

![image](https://cloud.githubusercontent.com/assets/2841617/22546882/9dd9e426-e947-11e6-8899-b19afb1a8b10.png)

The app then reapplies the stored rules when creating a new instance of the form on the screen ...

`
rules = projects[_.findIndex(projects, {
				ProjectEntityId: $('#selProject').val()
			})].WorkflowMaster[_.findIndex(project.WorkflowMaster, {
				WorkflowMasterEntityId: $('#selWorkflowMaster').val()
			})].WorkflowMasterSpecs.wizardRules;

			_.each(rules, function(rule) {

				if(rule.type === "date") {

					rule.value = rule.value.replace("-", "/");
				}
			});

			if (!_.isEmpty(rules)) {

				triggerOptions.rules = rules[triggerSet + 1];
			}

			triggerOptions.filters = filters;
			triggerOptions.operators = filterOperators;
			$('#triggerSets').empty();
			createTriggerSet();

...

createTriggerSet = function() {

		$('#triggerSets').append(mapWizardTriggerTemplate.format(++triggerSet));

		$('#queryBuilder_{0}'.format(triggerSet)).queryBuilder(triggerOptions).on({
			'afterCreateRuleInput.queryBuilder': function(e, rule) {

				if (rule.filter.id === 'date') {

					var input = rule.$el.find('.rule-value-container [name*=_value_]');

					input.on('dp.change', function() {
						input.trigger('change');
					});
				}
			}
		});
`

**Comment by mistic100** [comment]
That doesn't really help... create a simple use case without your functional code, it's not my task to understand your code and extract relevant info.

On a side node you should use _.find instead of _.findIndex, much cleaner use :-)

**Comment by rkrameshkumar71** [comment]
core.es5.js:1020 ERROR TypeError: jQuery(...).queryBuilder is not a function(…)defaultErrorLogger @ core.es5.js:1020webpackJsonp.../../../core/.es5.js.ErrorHandler.handleError @ core.es5.js:1080next @ core.es5.js:4503schedulerFn @ core.es5.js:3635webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:239webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:186webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:127webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:91webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56webpackJsonp.../../../core/.es5.js.EventEmitter.emit @ core.es5.js:3621(anonymous function) @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142webpackJsonp.../../../core/.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844onHandleError @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:396webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:195webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499invokeTask @ zone.js:1540globalZoneAwareCallback @ zone.js:1566

**##  **I am Getting this error if i am creating another angular program and there i am implementing then it is working fine but when i am implementing Jquery query builder in my project it will showing above error i think js files are conflicting but i don't no how to resolve this solution any on can help me.****

my angular.cli.json file code is below

{
"project": {
"version": "1.0.0-beta.28.3",
"name": "new-mis"
},
"apps": [{
"root": "src",
"outDir": "dist",
"assets": [
"assets",
"favicon.ico"
],
"index": "index.html",
"main": "main.ts",
"test": "test.ts",
"tsconfig": "tsconfig.json",
"prefix": "app",
"mobile": false,
"styles": [
"styles.css",
"../src/assets/styles/custom-bootstrap.less",
"../node_modules/fullcalendar/dist/fullcalendar.css",
"../node_modules/primeng/resources/themes/omega/theme.css",
"../node_modules/bootstrap-select/dist/css/bootstrap-select.css",
"../node_modules/ng2-daterangepicker/daterangepicker.component.css",
"../node_modules/primeng/resources/primeng.css",
"../node_modules/font-awesome/css/font-awesome.css",
"../bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css",
"../node_modules/nouislider/distribute/nouislider.min.css",
"../node_modules/jQuery-QueryBuilder/dist/css/query-builder.default.min.css"

],
"scripts": [
    "../node_modules/jquery/dist/jquery.js",
    "../node_modules/bootstrap/dist/js/bootstrap.js",
    "../node_modules/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js",
    "custom.js",
    "../node_modules/moment/moment.js",
    "../node_modules/chart.js/dist/Chart.js",
    "../node_modules/fullcalendar/dist/fullcalendar.js",
    // "../node_modules/material-design-lite/dist/material.js",
    "../node_modules/bootstrap-select/dist/js/bootstrap-select.js",
    "../node_modules/ng2-daterangepicker/lib/daterangepicker/daterangepicker.component.js",
    "../node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js",
    "../bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js",
    "../node_modules/nouislider/distribute/nouislider.js",
    "../node_modules/ng2-nouislider/src/nouislider.js"
],
"environmentSource": "environments/environment.ts",
"environments": {
    "source": "environments/environment.ts",
    "dev": "environments/environment.ts",
    "prod": "environments/environment.prod.ts"
}
}],
"addons": [],
"packages": [],
"e2e": {
"protractor": {
"config": "./protractor.conf.js"
}
},
"test": {
"karma": {
"config": "./karma.conf.js"
}
},
"defaults": {
"styleExt": "css",
"prefixInterfaces": false,
"inline": {
"style": false,
"template": false
},
"spec": {
"class": false,
"component": true,
"directive": true,
"module": false,
"pipe": true,
"service": true
}
}
