### ISSUE TITLE
None of the branches are working except master branch.

### ISSUE THREAD

**Issue by bmannava-invn** [mistic100/jQuery-QueryBuilder#429]
None of the branches are working except master branch.
Expecting "bower install" not only at the root folder but it also expecting to run under examples folder.

There is NO library available in bower library related to Jquery-QueryBuilder .

**Comment by bmannava-invn** [comment]
index.js:30 Uncaught ReferenceError: require is not defined
getting this error at doT library.

**Comment by skghosh-invn** [comment]
I am facing similar issues as well. Is there a timeline when you plan to resolve the open issues?

**Comment by bmannava-invn** [comment]
index.js:30 Uncaught ReferenceError: require is not defined
getting this error at doT library.

this issue resolve by using following version

"doT": "1.0.3"

if I execute as master branch bower.json  "doT": ">=1.0.3"  
its broken angular environment.But individually its working.

**Comment by mistic100** [comment]
I will take a look later but you should include dot.js, not index.js, from this library.

And I don't understand your very first message.

**Comment by mistic100** [comment]
No answer, I close
