### ISSUE TITLE
updateRuleOperator question: Input is not updated

### ISSUE THREAD

**Issue by JuliaBayer** [mistic100/jQuery-QueryBuilder#431]
Hey there,

i have a problem regarding the updateRuleOperator function.
Let's assume I have:
- 1 filter with 2 operators
- both operators have 4 input elements
- the input elements differ for each of the operators

Now, when changing from one operator to the other, the input elements are not updated as none of the  arguments in the following if clause in the updateRuleOperator function is true:

```javascript
if ($valueContainer.is(':empty') || !previousOperator || rule.operator.nb_inputs !== previousOperator.nb_inputs) {
    this.createRuleInput(rule);
}
```
Is there any existing solution, yet? If yes, sorry that I've overseen it ;)
If not, how about using a optgroup comparison here, too (as you probably don't want to delete the whole if clause)?
``` 
rule.operator.optgroup !== previousOperator.optgroup
```

Thanks in advance!
Julia

**Comment by mistic100** [comment]
Hi

Can you confirm you are building the input with `filter.input` as a function ?

There are proposals for a better configuration at operator level here #284 and here #251 but it's far from being ready (not started at all in fact).

----

The clause was added to not delete the user input when switching between similar operators, "similar" being a vague concept.

Better than adding another "vague" clause I propose to add a "forceRenderInput" flag to operators.

**Comment by JuliaBayer** [comment]
Hey
Yes you're right. I'm building the input with `filter.input`.
The "forceRenderInput" also sounds like a good idea, but I still like the optgroup idea (and I meant to extend the clause by the optgroup comparison, not replacing it).
I'll try to explain.

If I have 1 filter with 4 operators, each having 2 inputs.
The first input is the same for all.
The second input is either of the type string or number.
2 operators use the string type, the other two the number type, but they need to belong to the same filter.

As you said, it's nice to save the user input while switching between 'similar' operators. With the optgroup flag it would be possible to group the 2 'string' operators, as well as the 2 'number' operators.

And when it comes to the operator update, the extended if clause

```javascript
if ($valueContainer.is(':empty') || !previousOperator || rule.operator.nb_inputs !== previousOperator.nb_inputs || rule.operator.optgroup !== previousOperator.optgroup) {
    this.createRuleInput(rule);
}
```
would save the input when switching between the 2 'string' operators but not when switching between a 'string' and a 'number' operator.

So I guess I would add both possibilities, the forceRenderInput flag and the optgroup comparison.

What do you think?

**Comment by mistic100** [comment]
Finally sticked to your initial proposal

**Comment by JuliaBayer** [comment]
Great, thank you!
