### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by mathiasfn** [mistic100/jQuery-QueryBuilder#433]
I seem to have a lot of trouble getting this lovely plugin to work with browserify and gulp.

i've tried both manually downloading and using NPM, no luck with neither.

i've tried to require all 4 files in the dist folder, but i get the same problem every time, $ is undefined, even though it's included earlier in the code and made global as "window.$".

I can't seem to find any docs specifying how to make this work with browserify/gulp.

So to sum my question up, is it even suppose to with browserify/gulp or am i just doing something wrong?

Thanks in advance!

**Comment by mistic100** [comment]
Gulp has nothing to do with this, it's just a build tool.

As for browserify I don't use it and I don't know how it works.

For the little I read, Browserify is based on "require" node-style loading, and QueryBuilder does not allow that, only CommonJS-style loading (with "define").

I am pretty sure you can find on Google how to load non-node modules with Browserify.

**Comment by mistic100** [comment]
You can also try to replace `src/.wrapper.js` by this and rebuild the lib.

```js
(function(root, factory) {
    if (typeof define == 'function' && define.amd) {
        define(['jquery', 'doT', 'jQuery.extendext'], factory);
    }
    else if (typeof module === 'object' && module.exports) {
        module.exports = factory(require('jquery'), require('dot'), require('jquery-extendext'));
    }
    else {
        factory(root.jQuery, root.doT);
    }
}(this, function($, doT) {
"use strict";

@@js

}));
```

NOT TRIED

**Comment by mathiasfn** [comment]
Right now i've downloaded is manually since im unsure as how to build the lib, do i need grunt for this?

**Comment by mathiasfn** [comment]
Still no luck, it seems the factory function just returns undefined :/

**Comment by mathiasfn** [comment]
Can you tell me more about the "direct loading in window" possibility?

Sorry for the troubles, we're just really interrested in using your plugin :)

**Comment by mistic100** [comment]
Of course it returns undefined ! It's a jQuery plugin, the methods are added to the jQuery namespace and that's all.

By direct loading I mean just include query-builder.standalone.js in your page.

**Comment by mathiasfn** [comment]
Ah of course, however, through all of my attempts i havn't been able to make it add to the jQuery namespace

**Comment by mistic100** [comment]
I cannot help you more.

**Comment by mistic100** [comment]
http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm => Method 2

**Comment by mathiasfn** [comment]
That's how far i made it myself, but even though i get to require it successfully and are able to see it in my websites sources, it doesn't seem to add the function to my global $ for some reason

**Comment by mistic100** [comment]
How do you know it's not loaded ? And it's plugin, so it's added to $.fn, and not $

**Comment by mathiasfn** [comment]
Ahh thats my bad, i was looking directly in $...

It works perfectly now, thank you so much for your time, much appreciated!
