### ISSUE TITLE
How to add optgroups to values field  in query builder like that of the operator field

### ISSUE THREAD

**Issue by sathishkumar17** [mistic100/jQuery-QueryBuilder#435]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [jsDelivr](https://www.jsdelivr.com/projects/jquery.query-builder) to be used on such platforms).

**Comment by mistic100** [comment]
This is not a valid issue, add details or I delete it.

**Comment by andrewfam** [comment]
Line 2185 in the query-builder.js

h+= '<select class="form-control" name="' + name + '"' + (filter.multiple ? ' multiple' : '') + '>';
                if (filter.placeholder) {
                    h+= '<option value="' + filter.placeholder_value + '" disabled selected> fasd' + filter.placeholder + '</option>';
                }

                if (filter.optgroup_on){
                    $.each(filter.values, function(groupName, options) {
                        h += '<optgroup label="' + groupName + '">'
                        Utils.iterateOptions(options, function(j, option) {
                            h+= '<option value="' + j + '">' + option + '</option> ';
                        });
                        h += '</optgroup>'
                    });
                    
                } else {
                    Utils.iterateOptions(filter.values, function(key, val) {
                        h+= '<option value="' + key + '">' + val + '</option> ';
                    });
                }
                h+= '</select>';
                break;

I did the above to add optgroups for values with the format of the values as per http://stackoverflow.com/questions/13956667/create-html-select-with-optgroup-from-json

**Comment by mistic100** [comment]
You do know that by modifying the lib you lock yourself to a specific version and will not be able to get bugs fixes ?

If you want the feature to be implemented create a new issue with correct details.
