### ISSUE TITLE
date type does not return timestamp

### ISSUE THREAD

**Issue by aryeharmon** [mistic100/jQuery-QueryBuilder#437]
How can make the date filter return a timestamp when exporting with mongoDB?

**Comment by mistic100** [comment]
Are you using a datepicker widget ? Configure it to export as a timestamp. Or define "valueGetter" on the filter

**Comment by aryeharmon** [comment]
i am using the bootstrap datetime picker plugin.

**Comment by mistic100** [comment]
```js
valueGetter: function(rule) {
  var raw = rule.$el.find('.rule-value-container input').val();
  return moment(raw).format('x');
}
```

**Comment by aryeharmon** [comment]
@mistic100 thank you.

**Comment by harishsnapcheck** [comment]
@mistic100 thanks you so much.
