### ISSUE TITLE
During 'setFilters' found error TypeError: filters.forEach is not a function

### ISSUE THREAD

**Issue by tahiralvi** [mistic100/jQuery-QueryBuilder#438]
I have following data for filters which I want to update with old filters, but got error of **TypeError: filters.forEach is not a function**

Data which try to use in setFilters 
[filter data file](https://docs.google.com/document/d/16ySkCSUY2eeenN7EKvYjX14o_UTCwOqPXz5kqZKaCIg/edit)

Use below code to set new filters,

```
$('#builder-import_export').queryBuilder("reset");
 $('#builder-import_export').queryBuilder('setFilters', true, data);
 $("#builder-import_export").queryBuilder("setRules", rules_basic);
```

Anyone with the same problem or anyone let me know where I am wrong?

I am using Firefox version 51.0.1 (32 bit)

**Comment by mistic100** [comment]
I will certainly not open a dropbox link from a stranger. Read this https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown and post your code the issue.

**Comment by tahiralvi** [comment]
@mistic100 Thanks, I have update the dropbox link.

**Comment by mistic100** [comment]
Seriously ? The problem is not Dropbox, the problem is posting an unsafe link, whatever the host is.

**Comment by tahiralvi** [comment]
@mistic100, I am really sorry for unsafe link but the latest link is from google drive.

**Comment by mistic100** [comment]
And I will not open it, gdrive is not a proof of zero malware.

We are on github, paste your code here with code highlight tags.

**Comment by tahiralvi** [comment]
The Ajax code which call for the data,
```javascript
var items = "";
            $.getJSON("@Url.Action("GetQuestionsListJSON", "Configuration")?surveyId=" + $("#DDLQuestionairs").val(), function (data)
            {
               if ($('#ModalRules').is(':visible') == true) {
                  
                   $('#builder-import_export').queryBuilder("reset");
                    $('#builder-import_export').queryBuilder('setFilters', true, data);
                    $("#builder-import_export").queryBuilder("setRules", rules_basic);
                }


            });
```

The C# code is below,

```
public JsonResult GetQuestionsListJSON(int? surveyId)
        {
            // type =  string, integer, double, date, time, datetime, boolean
            // input=  text, textarea, radio, checkbox, select
            List<QuestionRuleFilter> LstQuestions = new List<QuestionRuleFilter>();
            QuestionRuleFilter item = new QuestionRuleFilter();            
            if (surveyId != null && surveyId > 0)
            {
                List<SurveyQuestion> LstSurveyQuestion = db.Surveys.Where(m => m.Id == surveyId).SingleOrDefault().Questions.ToList();
                LstSurveyQuestion = LstSurveyQuestion.Where(m => m.QuestionType == QuestionType.SingleChoice || m.QuestionType == QuestionType.MultipleChoice || m.QuestionType == QuestionType.Boolean).ToList();
                foreach (SurveyQuestion oSurveyQuestion in LstSurveyQuestion)
                {
                    item = new QuestionRuleFilter();
                    item.id = Convert.ToString(oSurveyQuestion.Id);
                    item.label = Convert.ToString(oSurveyQuestion.QuestionText);
                    item.type = "string";
                    LstQuestions.Add(item);
                }
            }
            else
            {
                item = new QuestionRuleFilter();
                item.id = Convert.ToString(" ");
                item.label = Convert.ToString(" ");
                item.type = "string";
                LstQuestions.Add(item);
            }
            return Json(JsonConvert.SerializeObject(LstQuestions), JsonRequestBehavior.AllowGet);

        }
```

**Comment by mistic100** [comment]
At first I don't see anything wrong.

Did you debug the data received from the server ? Are you sure it's an array ? (If you have a "modern" browser it's the only reason for getting this error I can imagine)

**Comment by tahiralvi** [comment]
@mistic100, I got the solution.

When I received the json call, the result is in JSON String then I Convert it to JSON Object. and then assign the parsed json to querybuilder.

`var obj = $.parseJSON(data);`

Many many thanks for the concern and thumbs up for quick answering.

**Comment by mistic100** [comment]
This is a common remark for almost every user I helped here : why isn't it COMMON SENSE to open your debugger when you have a problem and instead immediately jump on the issue tracker ?

I'm happy you solved it though.
