### ISSUE TITLE
Simple Usecase

### ISSUE THREAD

**Issue by minedun6** [mistic100/jQuery-QueryBuilder#441]
Is it possible to have a simple use case of this plugin ?
I mean I just opened the example file and checked it and it seems there is a lot of options, just How can I try this out as simple and quick as possible ?
Another point is, I don't want to use the "selectize" plugin by default, maybe I need to use the "select2" plugin and the "bootstrap datepicker" plugin, how can I go about setting this up ?

Thanks for the awesome plugin.

**Comment by mistic100** [comment]
http://querybuilder.js.org/demo.html Basic -> See Source

---

Just replace `plugin` and `plugin_config` on the filter with whatever suits your need.

**Comment by minedun6** [comment]
Indeed for the first part of the question, I didn't honestly see the source.
For setting up other plugins, can you provide a bit more help on how to do it, just need to set up the select2 plugin.

**Comment by mistic100** [comment]
Help about what ? There is an option for the plugin name and an option for it's config, it couldn't be more simpler.

The demo widgets has an example for three different jQuery plugins, I am sure you can sort it out yourself.
