### ISSUE TITLE
[Question] Search without case sensitive.. 

### ISSUE THREAD

**Issue by lsh486love** [mistic100/jQuery-QueryBuilder#443]
Hi, 

Suppose that there is data in mongodb for example, "C:\Program File (x86)\Samxung" in Info field. 

Then I would like to enter and search with this query => {"$and":[{"Info":{"$regex":"s"}}]}
no result is shown but {"$and":[{"Info":{"$regex":"S"}}]} works. 

How can I modify the source code without case sensitive?? 

Or ... is there a specific reason that QueryBuilder has the case sensitivity? 

Thank you !!!.

**Comment by mistic100** [comment]
No reason, it's just not adressed.

You can reconfigure the Mongo exporter like that :

```js
$('#builder').queryBuilder({
  mongoOperators: {
    contains: function(v) { return { '$regex': Utils.escapeRegExp(v[0]), '$options': 'i' }; }
  }
});
```
Added ` $options: i`

**Comment by lsh486love** [comment]
@mistic100  Oh thank  you. I modified it as you informed.
