### ISSUE TITLE
$(...).queryBuilder is not a function

### ISSUE THREAD

**Issue by gib65** [mistic100/jQuery-QueryBuilder#444]
Hello,

I downloaded QueryBuilder from this site:

querybuilder.js.org/#installation

It says it depends on the following dependencies:

jQuery >= 1.10
Bootstrap >= 3.1 (CSS Buttons and Utilities only)
$.extendext
doT.js >= 1.0.3
MomentJS (optional, for Date/Time validation)

So I downloaded all of those.

It also tells me to download and reference query-builder.css and query-builder.js. So I download them and reference them from index.html.

My folder now looks like this:

https://i.stack.imgur.com/8dgyw.png

I also included a folder for JQuery 1.11.1 and referenced it from index.html.

index.html looks like this:

    <html>
    <head>

    <link href="JQuery\jquery-ui.css" rel="stylesheet" />
    <link href="JQuery\jquery-ui.structure.css" rel="stylesheet" />
    <link href="JQuery\jquery-ui.theme.css" rel="stylesheet" />
    <script type="text/javascript" src="JQuery\jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="JQuery\jquery-ui.min.js"></script>

    <link rel="stylesheet" href="query-builder.css" />
    <script type="text/javascript" href="query-builder.js"></script>

    </head>

    <body>

    <div id="builder"></div>

    <script>

    $(document).ready(function() {
    $('#builder').queryBuilder();
    });

    </script>

    </body>

    </html>

But if you go to http://www.shahspace.com/querybuilder/index.html you see it's not working.

The download page reads like boostrap and other dependencies are supposed to be installed through visual studio. I'm just using an ordinary Notepad file.

Is there anything extra I need to do to set all this up correctly? What files in Bootstap, $.extendext, doT.js etc. do I need to reference?

**Comment by mistic100** [comment]
Look at your script tag you wrote href and not src.

And you will be missing extendext and dot.js, unless you use the standalone version of query builder.

**Comment by gib65** [comment]
Oops!

Thanks for pointing that out mistic. I fixed the script tag and now it shows up. Sometimes I just miss the obvious.

**Comment by Maninandha** [comment]
Hi ,
Could you help me for this issue

<head>

    <script type='text/javascript' src="https://cdn.jsdelivr.net/jquery/3.1.1/jquery.min.js"></script>
    <script type='text/javascript' src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type='text/javascript' src="https://cdn.jsdelivr.net/jquery.query-builder/2.4.1/js/query-builder.standalone.min.js"></script>
    <script type='text/javascript' src="https://cdn.jsdelivr.net/jquery.query-builder/2.4.3/js/query-builder.min.js"></script>
    <script type='text/javascript' src="../../../../../node_modules/dot/doT.min.js"></script>
    <script type='text/javascript' src="../../../../../node_modules/jquery-extendext/jQuery.extendext.min.js"></script>
    <script type='text/javascript' src="../../../../../node_modules/jQuery-QueryBuilder/dist/js/query-builder.js"></script>
    <script type='text/javascript' src="../../../../../node_modules/jQuery-QueryBuilder/dist/js/query-builder.standalone.js"></script>
</head>
<div class="container">
    <h1>Hello {{name}}</h1>
    <div id="builder"></div>
    <button (click)="reset()">reset</button>
    <button (click)="getRules()">Rules</button>
    <button (click)="getESBool()">ES</button>
</div>


-------------------------------------------------------------
and my compopnent like this 

import { Component, OnInit } from '@angular/core';
declare var jQuery: any;


@Component({
  selector: 'app-gsrStatusReport',
  templateUrl: './gsrStatusReport.component.html',
  styleUrls: ['./gsrStatusReport.component.css']
})
// export class GsrStatusReportComponent implements OnInit {

//   constructor() { }

//   ngOnInit() {
//     jQuery('.filter').selectpicker('refresh');
//     jQuery('.filter').selectpicker('val', 1);
//     jQuery('.slabs').selectpicker('refresh');
//     jQuery('.slabs').selectpicker('val', 1);
//   }

// }
export class GsrStatusReportComponent implements OnInit {
  name = 'Angular';

  rules_basic: any = {};

  private _queryBuilder(initilal_rules: any) {

    $('#builder').queryBuilder({
      plugins: ['bt-tooltip-errors'],

      filters: [{
        id: 'name',
        label: 'Name',
        type: 'string'
      }, {
        id: 'category',
        label: 'Category',
        type: 'integer',
        input: 'select',
        values: {
          1: 'Books',
          2: 'Movies',
          3: 'Music',
          4: 'Tools',
          5: 'Goodies',
          6: 'Clothes'
        },
        operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
      }, {
        id: 'in_stock',
        label: 'In stock',
        type: 'integer',
        input: 'radio',
        values: {
          1: 'Yes',
          0: 'No'
        },
        operators: ['equal']
      }, {
        id: 'price',
        label: 'Price',
        type: 'double',
        validation: {
          min: 0,
          step: 0.01
        }
      }, {
        id: 'id',
        label: 'Identifier',
        type: 'string',
        placeholder: '____-____-____',
        operators: ['equal', 'not_equal'],
        validation: {
          format: /^.{4}-.{4}-.{4}$/
        }
      }],

      rules: initilal_rules
    });

  }

  ngOnInit() {
    let $ = jQuery;
    this.rules_basic = {
      condition: 'AND',
      rules: [{
        id: 'price',
        operator: 'less',
        value: 10.25
      }, {
        condition: 'OR',
        rules: [{
          id: 'category',
          operator: 'equal',
          value: 2
        }, {
          id: 'category',
          operator: 'equal',
          value: 1
        }]
      }]
    };

    this._queryBuilder(this.rules_basic);
  }

  reset() {
    $('#builder-basic').queryBuilder('reset');
  }

  setRules(rules: any) {
    $('#builder').queryBuilder('setRules', rules);
  }

  getRules() {
    var result = $('#builder').queryBuilder('getRules');

    if (!jQuery.isEmptyObject(result)) {
      alert(JSON.stringify(result, null, 2));
    }

    return result;
  }

  getESBool() {
    var result = $('#builder').queryBuilder('getESBool');

    console.debug(result)
    if (!jQuery.isEmptyObject(result)) {
      alert(JSON.stringify(result, null, 2));
    }

    return result;
  }

}


/*
Copyright 2016 Google Inc. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at http://angular.io/license
*/

I have done npm install for all dependencies.

As soon as reply me

**Comment by mistic100** [comment]
Create a new issue **and use code blocks** (triple back quote)

**Comment by rkrameshkumar71** [comment]
core.es5.js:1020 ERROR TypeError: jQuery(...).queryBuilder is not a function(…)defaultErrorLogger @ core.es5.js:1020webpackJsonp.../../../core/.es5.js.ErrorHandler.handleError @ core.es5.js:1080next @ core.es5.js:4503schedulerFn @ core.es5.js:3635webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:239webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:186webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:127webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:91webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56webpackJsonp.../../../core/.es5.js.EventEmitter.emit @ core.es5.js:3621(anonymous function) @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142webpackJsonp.../../../core/.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844onHandleError @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:396webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:195webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499invokeTask @ zone.js:1540globalZoneAwareCallback @ zone.js:1566

I am Getting this error if i am creating another angular program and there i am implementing then it is working fine but when i am implementing Jquery query builder in my project it will showing above error i think js files are conflicting but i don't no how to resolve this solution any on can help me.

my angular.cli.json file code is below

{
"project": {
"version": "1.0.0-beta.28.3",
"name": "new-mis"
},
"apps": [{
"root": "src",
"outDir": "dist",
"assets": [
"assets",
"favicon.ico"
],
"index": "index.html",
"main": "main.ts",
"test": "test.ts",
"tsconfig": "tsconfig.json",
"prefix": "app",
"mobile": false,
"styles": [
"styles.css",
"../src/assets/styles/custom-bootstrap.less",
"../node_modules/fullcalendar/dist/fullcalendar.css",
"../node_modules/primeng/resources/themes/omega/theme.css",
"../node_modules/bootstrap-select/dist/css/bootstrap-select.css",
"../node_modules/ng2-daterangepicker/daterangepicker.component.css",
"../node_modules/primeng/resources/primeng.css",
"../node_modules/font-awesome/css/font-awesome.css",
"../bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css",
"../node_modules/nouislider/distribute/nouislider.min.css",
"../node_modules/jQuery-QueryBuilder/dist/css/query-builder.default.min.css"

    ],
    "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "../node_modules/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js",
        "custom.js",
        "../node_modules/moment/moment.js",
        "../node_modules/chart.js/dist/Chart.js",
        "../node_modules/fullcalendar/dist/fullcalendar.js",
        // "../node_modules/material-design-lite/dist/material.js",
        "../node_modules/bootstrap-select/dist/js/bootstrap-select.js",
        "../node_modules/ng2-daterangepicker/lib/daterangepicker/daterangepicker.component.js",
        "../node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js",
        "../bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js",
        "../node_modules/nouislider/distribute/nouislider.js",
        "../node_modules/ng2-nouislider/src/nouislider.js"
    ],
    "environmentSource": "environments/environment.ts",
    "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
    }
}],
"addons": [],
"packages": [],
"e2e": {
    "protractor": {
        "config": "./protractor.conf.js"
    }
},
"test": {
    "karma": {
        "config": "./karma.conf.js"
    }
},
"defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
        "style": false,
        "template": false
    },
    "spec": {
        "class": false,
        "component": true,
        "directive": true,
        "module": false,
        "pipe": true,
        "service": true
    }
}

**Comment by rkrameshkumar71** [comment]
I am Getting this error if i am creating another angular program and there i am implementing then it is working fine but when i am implementing Jquery query builder in my project it will showing above error i think js files are conflicting but i don't no how to resolve this solution any on can help me.
