### ISSUE TITLE
[Question] how to validate mongodb query in a plain text with QueryBuilder..

### ISSUE THREAD

**Issue by lsh486love** [mistic100/jQuery-QueryBuilder#445]
Hello, 
Actually I'm done with binding querybuilder and it's well working. 
but I would like to make a custom filter through direct input. 

To comprehend easily, I wrote codes with JSfiddle here :
[https://jsfiddle.net/rzL9kw10/8/](https://jsfiddle.net/rzL9kw10/9/)

As you see in the code, there is a input text, and someone will enter mongodb query. 
and click "Apply". 

Then, a message will show the query is validated or not. 

In this case, what should I do?? 

Or.. any other suggestion??  

Thank you in advance for your help.

**Comment by mistic100** [comment]
Please fix your markdown link.

**Comment by lsh486love** [comment]
Oops, sorry for the trouble. 
[](https://jsfiddle.net/rzL9kw10/9/)

**Comment by lsh486love** [comment]
[https://jsfiddle.net/rzL9kw10/9/](https://jsfiddle.net/rzL9kw10/9/
)

**Comment by lsh486love** [comment]
@mistic100 Okay, then can setRulesFromMongo return a value, if the parameter is invalid? 

`var query = "{$and:....}";
var result = someInstance.querybuilder('seRulesFromMongo', query);  
alert(result); `

can I use it like that way?

**Comment by lsh486love** [comment]
Can I modify it for query validation in a getRulesFromMongo function..??? 

```
    setRulesFromMongo: function(data) {
        this.setRules(this.**getRulesFromMongo**(data));
    }


    **getRulesFromMongo**: function(data) {
        if (data === undefined || data === null) {
            return null;
        }

        var self = this;

        // allow plugins to manually parse or handle special cases
        data = self.change('parseMongoNode', data);
       
       ///////// If there is something wrong, return error. ?? 

        // a plugin returned a group
        if ('rules' in data && 'condition' in data) {
        ///////////////	alert("error!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
            return data;
        }


```

**Comment by mistic100** [comment]
First of all, this method will performs itself all checks againstt configured filters, and throw appropriate errors.

If you want additional checks, subscribe to the 'parseMongoNode.queryBuilder.filter' event (read the doc about events) where you can throw en Error to stop the process (seatch Mozilla Dev Network about Error)

**Comment by lsh486love** [comment]
@mistic100 Thank you for your help. 

I keep admiring your advice and this solution.. 

I really appreciate if you could privide me the example for the addtional check.. 
and I cannot apply " parseMongoNode.queryBuilder.filter.. " as you informed.. 

Thank you so much..

**Comment by mistic100** [comment]
Actually what i said is useless.

If you want to use Query Builder internal validation :

```js
try {
  var mongoQuery = JSON.parse(userInput);
  builder.queryBuilder('setRulesFromMongo', mongoQuery);
}
catch (e) {
  console.log(e); // handles errors here
}
```

For anything else, do it yourself. period.
