### ISSUE TITLE
Selecting Multiple Inputs in CheckBox 

### ISSUE THREAD

**Issue by panchoSalsa** [mistic100/jQuery-QueryBuilder#446]
Hello,
I am having difficulties understanding how to allow my  checkbox to select multiple inputs.

for example I want to build the query "cur_race = '11,13' ", but when I select two inputs i get an error: 
Uncaught TypeError: Cannot read property 'condition' of null.

I am new to web development so any help will be appreciated..

I have tried using a callback during validation but that did not work.

  {
    id: 'cur_race',
    label: 'race',
    type: 'string',
    input: 'checkbox',
    default_value: '13',
    values: {
      '10': 'White',
      '11': 'Black or African American',
      '12': 'Asian',
      '13': 'Latino',
      '14': 'American Indian or Alaska Native',
      '15': 'Native Hawaiian or Other Pacific Islander',
      '88': 'Other',
      '77': 'Refuse'
    },
    operators: ['equal', 'not_equal',]
  },

**Comment by mistic100** [comment]
First rule of development : provide a complete example of your problem (on jsfiddle) for example.

**Comment by panchoSalsa** [comment]
Hey mistic100,
thank you so much for creating a very nice library and for replying back.
I have created the jsfiddle example https://jsfiddle.net/ffranco/nsq0pw1b/

I hope you can understand the issue Im having.
For example if I select White and Black or African American then the GetSQL throws an error
Cannot read property 'condition' of null.

I need the query to be " cur_race = '10,11' "

Or if I select all the choices then I need the query to be 
" cur_race = '10,11,12,13,14,15,88,77' ''


Your help will be much appreciated since this is the last detail I need in order to complete my application.

**Comment by mistic100** [comment]
Well first of all what you want is not valid SQL, it will never work. It should be `cur_race IN('10', '11')`.
And that's why the rules turns red with "Operator equal cannot accept multiple values".

So define `operators: ['in', 'not_in']` and will solve the problem.

**Comment by panchoSalsa** [comment]
I have tried ['in', 'not_in'] before and that is not what I need. The operator 'in' will include people who are Latino OR African American. I need the query to narrow down the search to people who consider themselves to be both Latino AND African American. 

As for the SQL part of cur_race = '10,11' it will work because the database takes a string for the value of cur_race.

**Comment by mistic100** [comment]
Well your database is very strangely designed don't you know about foreign keys ?

You can use `valueGetter` callback to join your values before it is transformed in SQL (check examples on the website)
