### ISSUE TITLE
508 Compliance

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#447]
Hi, 

We have some requirements for 508 compliance and I know that's not priority for developer on the plugin. I just wanted to check if there is any plan to make this plugin 508 complaint? 
For example when I run a tool I get some errors like "A form control does not have a corresponding label", etc. on the generated controls for the Rules. 
Also is it possible to extend your implementation and make some HTML changes like adding labels, etc.
I know it's tedious work but wanted to check with you on that.

Thanks,

**Comment by mistic100** [comment]
You realize it's not possible to add a label to every control ? It would be totally bloated and unreadable.
These rules make sense for forms, not for complex components like this one.

It's already possible to extend the templates http://querybuilder.js.org/#templates
