### ISSUE TITLE
Query builder "IN" operator

### ISSUE THREAD

**Issue by trextroy** [mistic100/jQuery-QueryBuilder#449]
Hi,

I am currently using the 'In' operator for query generation. 
eg. expression IN (value1, value2, .... value_n);

However I am not able to enter multiple values for this operator. I have single input box . is there any way we can enter multiple values prob with semicolon, or comma or something ? 

Please help.

**Comment by mistic100** [comment]
Hi,

please search before posting, this has been answered countless times

You must use a select, or checkboxes, or use the `value_separator` [filter parameter](http://querybuilder.js.org/#filters) or even use `valueGetter` and `valueSetter` callbacks.
