### ISSUE TITLE
IN operator for integer values

### ISSUE THREAD

**Issue by stanep** [mistic100/jQuery-QueryBuilder#451]
Hi thank you for good work, question if I have an integer and want to use 'IN' operator I can not enter any values except numbers in text box(I try to use value_separator="," )
Any ideas?

**Comment by mistic100** [comment]
Already addressed, in the next version you will be able to use a simple text input for integer data types, and thus make value_separator working.
https://github.com/mistic100/jQuery-QueryBuilder/commit/4d6c44e83a98ce70ca2d3157934c2e2d8c707276

This release has no planned date.

**Comment by PIlepRusel** [comment]
is this deployed on latest version ?

**Comment by mistic100** [comment]
If you click on the commit you can see it is available since 2.4.2
