### ISSUE TITLE
Error with getRulesFromSQL(): data.left.values is undefined

### ISSUE THREAD

**Issue by gordon-matt** [mistic100/jQuery-QueryBuilder#452]
First off, excellent work on the query builder. I've just recently discovered it and it's very nice indeed.

However, I have discovered a problem with `getRulesFromSQL` when passing in a string.

I am passing in the following string:

**"BookingsCount" = 200** (The quotation marks are there due to my using PostgreSQL; I set the field names on the quotation marks)

The error message I get is as follows:

**data.left.values is undefined** (line 4791)

I can see in your code (**query-builder.standalone.js**) that you do the following if a string is passed in:

```
if (typeof data == 'string') {
            data = { sql: data };
        }
```

So you turn it into an object, but only give it the "sql" property and then you go on to use other properties below in the code, like `data.operation`, `data.left` and `data.right` when they don't exist.

Can this be easily fixed?

**Comment by mistic100** [comment]
fields name do not have to be quoted in Postgres, unless it's a reserved word in which case you have to use a back-quote.

----

I identified the issue, it will ship with the next release.

**Comment by gordon-matt** [comment]
I'm glad you were able to identify the issue quickly. Will the next release be soon? If not, would you be so kind as to please post the fix here so I can apply it my existing release in the meantime?

**Comment by gordon-matt** [comment]
@mistic100 

OK I got the latest code and built the distributable files. So I have the fix, but unfortunately there is yet another bug: I am getting the following error:

**Error: Undefined filter "BookingsCount"**

The configuration for that field is as follows:

**{
      "id": "booking-count",
      "field": "\"BookingsCount\"",
      "label": "# Bookings",
      "type": "integer",
      "input_event": "change",
      "validation": {
        "step": 1
      },
      "operators": [
        "equal",
        "not_equal",
        "in",
        "not_in",
        "less",
        "less_or_equal",
        "greater",
        "greater_or_equal",
        "between",
        "not_between",
        "is_null",
        "is_not_null"
      ]
}**

**Comment by mistic100** [comment]
Either change the id of your filter or read the yellow block http://querybuilder.js.org/plugins.html#sql-support

```js
$('#builder').on('getSQLFieldID.queryBuilder.filter', function(e) {
  if (e.value === 'BookingsCount') {
    e.value = 'booking-count';
  }
});
```

**Comment by gordon-matt** [comment]
@mistic100 OK thanks, that seems to be working well. However, surely there must be a way this can be done automatically? The query builder already has the complete configuration with the `id`, `field `and `label`, etc... Why can't `getRulesFromSQL` use the configuration to lookup the correct IDs from the field names instead of me having to do the above for every field on every page (table) that I have a QueryBuilder? If you think that's doable, let me know and I will open a separate issue as a "Change Request".
