### ISSUE TITLE
Apply Filters to js Array?

### ISSUE THREAD

**Issue by StoneJunction** [mistic100/jQuery-QueryBuilder#453]
Is there an easy way (or a plugin already written) to apply the rules to a clientside js array rather than to sql/mongo db?

**Comment by mistic100** [comment]
`getRules` and `setRules` http://querybuilder.js.org/#methods works with a db agnostic model.

If you are not talking about that, please be more precise in your question.

**Comment by mistic100** [comment]
That's an interesting request but in my sense too much complicated to implement.

Where SQL and Mongo are standardized, every developper can describe its JS objects what ever he wants.

**Comment by mistic100** [comment]
I close for now.

@jeremywall is working on an implementation for https://github.com/jwadhams/json-logic-js which, I hope, could be integrated when done

**Comment by sedegas** [comment]
This is exactly what I need as well.

**Comment by jfscoertzen** [comment]
I think I found a way. Export the rule to mongodb style query the pass the query to sift.js

https://github.com/crcn/sift.js/tree/master

**Comment by jfscoertzen** [comment]
<img width="823" alt="screen shot 2018-06-15 at 14 57 37" src="https://user-images.githubusercontent.com/2377987/41469155-8bfe7e40-70ac-11e8-936e-047e0c5c36cc.png">
<img width="408" alt="screen shot 2018-06-15 at 14 57 42" src="https://user-images.githubusercontent.com/2377987/41469162-91d600b8-70ac-11e8-9775-4d0f919208ee.png">
<img width="533" alt="screen shot 2018-06-15 at 14 57 48" src="https://user-images.githubusercontent.com/2377987/41469167-9576dd50-70ac-11e8-80ee-bde8d0bfef1e.png">

**Comment by jfscoertzen** [comment]
![ezgif-2-1bff55f590](https://user-images.githubusercontent.com/2377987/41470805-0e06c776-70b2-11e8-8f47-f43226700605.gif)

**Comment by painos** [comment]
Cool! Would you share your sift() function?

**Comment by ferreira-guilherme** [comment]
Any breakthrough in that? That would be a very interesting feature. I am in demand that this functionality would solve my problem.

**Comment by Ravenglass** [comment]
This would be extrememly useful...
