### ISSUE TITLE
Demo Solution Not Working !!!!!

### ISSUE THREAD

**Issue by jackryu** [mistic100/jQuery-QueryBuilder#459]
Hello ,

I am new with jQuery-QueryBuilder-2.4.1  i download sample solution but this solution is not working i am using windows 7 and .Net.

> error :  "You must execute bower install in the example directory to run this demo." in  examples/examples/index.html

i am trying after installing "bower" global and in example directory but this is not working please help i need this plugin.

![image](https://cloud.githubusercontent.com/assets/6933841/24476580/70ed05da-14f1-11e7-9428-e5e07094dbb1.png)

![image](https://cloud.githubusercontent.com/assets/6933841/24476589/7ddf1fe4-14f1-11e7-9838-2d4b6f5814b5.png)

**Comment by mistic100** [comment]
you must also run bower install in the root folder

**Comment by jackryu** [comment]
> **Your Team created nice plugin.......!!!!!!!!!!!!!!!**
