### ISSUE TITLE
Problem rendering custom template

### ISSUE THREAD

**Issue by ronnieduke** [mistic100/jQuery-QueryBuilder#460]
Hey there,
I'm working on tweaking the markup of the rules template and running into some issues. I searched through several github issues and documentation and still couldn't quite get there. I was finally able to get _something_ custom to show, but now I've reached a new hurdle where it does not appear to render the doT.js strings properly. Here is my code in my rails view:

```
var styleTemplate = 
    {
        rule : function(rule_id){
            return '\
			<li id="{{=it.rule_id }}" class="rule-container"> \
			  {{? it.settings.display_errors }} \
			    <div class="error-container"><i class="{{= it.icons.error }}"></i></div> \
			  {{?}} \
			  <div class="rule-filter-container"></div> \
			  <div class="rule-operator-container"></div> \
			  <div class="rule-value-container"></div> \
			  <div class="btn-group rule-actions"> \
			      <button type="button" class="btn btn-xs btn-danger" data-delete="rule"> \
			        <i class="{{= it.icons.remove_rule }}"></i> {{= it.lang.delete_rule }} \
			      </button> \
			    </div> \
			</li>';
        }
    };
$('#builder-basic').queryBuilder({  
 templates: styleTemplate,
...
// Filters and options //
...
});
```
So this rendered the custom rule template, but the variables in the HTML do not seem to be processing:

![image](https://cloud.githubusercontent.com/assets/742579/24821716/0c04f334-1ba5-11e7-8010-d78db83fcf74.png)

I'm using the 2.3.3 version that comes with the rails gem [https://github.com/SixiS/jquery_query_builder-rails](https://github.com/SixiS/jquery_query_builder-rails)

**Comment by mistic100** [comment]
Hello

the doc says **Templates can be provided as a doT.js template string or a function taking an object of variables and returning an HTML string**

so your first problem is that the function parameters is not `rule_id` but an object containing the rule_id
and more important : if you use a function you must return the **final** HTML

I suggest you don't use a custom a function and use the features of doT.js for your needs (if/else, loops, etc). Or if it's too complicated your function must do

```js
return doT(template)(params);
```

but this is not good in term of performances (the template is reinterpreted at each run)

**Comment by ronnieduke** [comment]
Thanks for the reply! I was able to get it to work using your suggestions. 

Cheers!
