### ISSUE TITLE
Possible to add new button near add rule

### ISSUE THREAD

**Issue by jackryu** [mistic100/jQuery-QueryBuilder#463]
Hello Team,

Possible to add new button near add rule button and attached my event with custom button.  

Reference Image.

![capture-10](https://cloud.githubusercontent.com/assets/6933841/24967904/327b0152-1fc9-11e7-99be-4ab20654de38.JPG)

**Comment by mistic100** [comment]
Hello (there is no "team", just me)

You need to :
 1. override the `rule` template see: http://querybuilder.js.org/#templates
 2. listen to clicks on the button and get the corresponding rule if needed, this can be done via event delegation :
```js
$('#builder').on('click', '.class-of-your-button', function(e) {
  var rule = $('#builder').queryBuilder('getModel', $(e.target).closest('.rule-container'));
  // do your action
});
```

**Comment by jackryu** [comment]
Thanks i will try....
