### ISSUE TITLE
Sortable feature doesn't work anymore

### ISSUE THREAD

**Issue by wgojboss** [mistic100/jQuery-QueryBuilder#464]
Hi,

Few months ago, I've integrated QueryBuilder in my project enabling the sortable feature and it worked like a charm.
But I've just updated my version and I've noticed that this feature doesn't work anymore.
At first I thought maybe it was due to Chrome new version but even with Firefox the issue is present.
The problem can be reproduced directly on the demo page at the plugin section : http://querybuilder.js.org/demo.html

**Comment by mistic100** [comment]
@wgojboss @dabega 2.4.3 is published with the fix
