### ISSUE TITLE
CDN Down?

### ISSUE THREAD

**Issue by tbrent** [mistic100/jQuery-QueryBuilder#467]
Apologies if this isn't the right place to post this. I'm trying to ramp up on QueryBuilder but it looks like the CDN is down. I will workaround by installing dependencies locally, but just alerting the group since there are likely current users whom are probably made very unhappy by this. 

https://cdn.jsdelivr.net/jquery.query-builder/2.4.3/js/query-builder.standalone.min.js

**Comment by mistic100** [comment]
2.4.3 was published two hours ago, the CDN needs time to update

**Comment by mistic100** [comment]
As jsdelivr still not updated and PR are taking more and more time to be reviewed, and switched everything to unpkg.com
