### ISSUE TITLE
jQuery-QueryBuilder 2.4.3 does not include artifacts when installed with bower

### ISSUE THREAD

**Issue by akshaisarma** [mistic100/jQuery-QueryBuilder#468]
Bower version: ```1.7.7```

If you ```bower install jQuery-QueryBuilder#2.4.3```, there is no dist folder in ```bower_components/jQuery-QueryBuilder```. It's fine in <= 2.4.2

**Comment by mistic100** [comment]
Sorry, tagged on the wrong branch. A chance Bower versions are directly tied to git tags.

Please uninstall version 2.4.3, clean your cache `bower cache clean jQuery-QueryBuilder` and start again
