### ISSUE TITLE
Support Postgres boolean values

### ISSUE THREAD

**Issue by gordon-matt** [mistic100/jQuery-QueryBuilder#469]
`true `and `false `values are being automatically converted to `1` and `0`, respectively. This is suitable for **MSSQL**, but not for **Postgres**, which requires `true/false`, not `1/0`. Is there an option in the query builder config for this? If not, please add this option.

**Comment by mistic100** [comment]
In the next version you will be able to configure it globally in the `plugins` section :

```js
$builder.queryBuilder({
  plugins: {
    'sql-support: { boolean_as_integer: false }
  }
});
```

**Comment by gordon-matt** [comment]
I can confirm this solution is working. Thank you.

**Comment by ilyagtangelogamescom** [comment]
working!
