### ISSUE TITLE
QueryBuilder is not a function error!!

### ISSUE THREAD

**Issue by jackryu** [mistic100/jQuery-QueryBuilder#470]
Hello - 
Query Builder  is perfectly work on my page. but if i am try below code in my external .JS its showing 
"Query Builder is not a function" error

![image](https://cloud.githubusercontent.com/assets/6933841/25092893/5ccead2c-23ad-11e7-8940-f04d57182dd3.png)

![image](https://cloud.githubusercontent.com/assets/6933841/25092913/86ce256c-23ad-11e7-9b58-fb4428c9daa2.png)

**and below code perfectly working in my "CustomRule.aspx" Page**

 ```
<script src="../plugins/jquery/jquery.min.js"></script>

    <link href="../plugins/querybuilder2/bootstrap-select.css" rel="stylesheet" />
    <link href="../plugins/querybuilder2/query-builder.default.min.css" rel="stylesheet" />

    <link href="../plugins/querybuilder2/bower_components/selectize/dist/css/selectize.bootstrap3.css" rel="stylesheet" />


    <script src="../plugins/querybuilder2/bootstrap.min.js"></script>
    <script src="../plugins/querybuilder2/query-builder.standalone.min.js"></script>
    <script src="../plugins/querybuilder2/bower_components/interact/interact.js"></script>
    <script src="../plugins/querybuilder2/bower_components/bootbox/bootbox.js"></script>
    <script src="../plugins/querybuilder2/bower_components/selectize/dist/js/standalone/selectize.min.js"></script>
    <script src="../plugins/querybuilder2/bower_components/sql-parser/browser/sql-parser.js"></script>

    <script>

        function SetUnit(query) {
            var $q = new $.Deferred();
            var oData = [];
            var filter = JSON.stringify({ 'param': query });
            $.ajax({
                type: "POST",
                url: '../WebService.asmx/ExecuteReader',
                contentType: "application/json; charset=utf-8",
                data: filter,
                dataType: "json",
            }).fail(function (jqXHR, textStatus, errorThrown) {
                $q.reject(jqXHR, textStatus, errorThrown);
                console.log('Reject...', jqXHR);
            }).done(function (data, textStatus, jqXHR) {
                $q.resolve(data, textStatus, jqXHR);
                console.log('Completed Done!!.....', data);
            }).progress(function () {
                console.log('in processing.....');
            });
            return $q.promise();
        }

        ; (function ($) {


            //var filter = JSON.stringify({ 'param': query });
            //$.ajax({
            //    type: "POST",
            //    url: '../WebService.asmx/ExecuteReader',
            //    contentType: "application/json; charset=utf-8",
            //    data: filter,
            //    dataType: "json",
            //    async: true,
            //    success: function (responce) {
            //        oUNIT_NAME = jQuery.parseJSON(responce.d);
            //    },
            //    error: function (xhr, status, err) {
            //        console.log(xhr);
            //    },
            //}).then(function () {

            //});
            $('[data-toggle="tooltip"]').tooltip();
            var $b = $('#builder');
            var options = {};
            var query = "SELECT  UnitID as id,Unit as name FROM [dbo].[T_UNIT_ID]";
            SetUnit(query).done(function (responce, textStatus, jqXHR) {
                options = {
                    allow_empty: true,
                    //default_filter: 'name',
                    sort_filters: true,
                    optgroups: {
                        core: {
                            en: 'Group', en: 'Clam', en: 'Group',
                            en: 'Provider', en: 'Group', en: 'Group'
                        }
                    },

                    plugins: {
                        'bt-tooltip-errors': { delay: 100 },
                        //'sortable': null,
                        'filter-description': { mode: 'bootbox' },
                        //'bt-selectpicker': null,
                        'unique-filter': null,
                        'bt-checkbox': { color: 'primary' },
                        'invert': null,
                        'not-group': null
                    },

                    // standard operators in custom optgroups
                    operators: [
                      { type: 'equal', optgroup: 'basic' },
                      { type: 'not_equal', optgroup: 'basic' },
                      { type: 'in', optgroup: 'basic' },
                      { type: 'not_in', optgroup: 'basic' },
                      { type: 'less', optgroup: 'numbers' },
                      { type: 'less_or_equal', optgroup: 'numbers' },
                      { type: 'greater', optgroup: 'numbers' },
                      { type: 'greater_or_equal', optgroup: 'numbers' },
                      { type: 'between', optgroup: 'numbers' },
                      { type: 'not_between', optgroup: 'numbers' },
                      { type: 'begins_with', optgroup: 'strings' },
                      { type: 'not_begins_with', optgroup: 'strings' },
                      { type: 'contains', optgroup: 'strings' },
                      { type: 'not_contains', optgroup: 'strings' },
                      { type: 'ends_with', optgroup: 'strings' },
                      { type: 'not_ends_with', optgroup: 'strings' },
                      { type: 'is_empty' },
                      { type: 'is_not_empty' },
                      { type: 'is_null' },
                      { type: 'is_not_null' }
                    ],


                    filters: [
                        {
                            id: 'Unit',
                            label: 'UNIT NAME',
                            type: 'string',
                            input: 'select',
                            multiple: true,
                            plugin: 'selectize',
                            plugin_config: {
                                valueField: 'name',
                                labelField: 'name',
                                searchField: 'name',
                                sortField: 'id',
                                options: JSON.parse(responce.d)
                            },
                            operators: ['in', 'not_in', 'is_null', 'is_not_null'],
                            valueSetter: function (rule, value) {
                                rule.$el.find('.rule-value-container select')[0].selectize.setValue(value);
                            }
                        },
                         {
                             id: 'PLAN_NM',
                             label: "PLAN Name",
                             value_separator: ',',
                             type: 'string',
                             optgroup: 'core',
                             size: 30,
                             validation: { allow_empty_value: false },
                         },
                    ],
                };

                // init
                $('#builder').queryBuilder(options);

            });


            $('#builder').on('validationError.queryBuilder', function (e, rule, error, value) {
                console.log('Warning : ', error);
                $('#btnUpdateQuery').addClass('hidden');
                $('#btnInqueryRule').addClass('hidden');
                $('#sqlResult').css('display', 'none').html('');
                swal({
                    title: "Filter not validate!!",
                    text: error,
                    type: "warning",
                    showCancelButton: false,
                    closeOnConfirm: true
                });
            });


            $('#builder').on('afterCreateRuleInput.queryBuilder', function (e, rule) {
                if (rule.filter.plugin == 'selectize') {
                    rule.$el.find('.rule-value-container').css('min-width', '200px')
                      .find('.selectize-control').removeClass('form-control');
                }
            });


            // set rules from SQL
       
            // reset builder
            $('.reset').on('click', function () {
                $('#builder').queryBuilder('reset');
                $('#sqlResult').css('display', 'none').html('');
            });

            $('#btnExecRule').on('click', function () {
                var res = $('#builder').queryBuilder('getSQL', $(this).data('stmt'), false);
                var queryStr = res.sql + (res.params ? '\n\n' + JSON.stringify(res.params, undefined, 2) : '');
                $('#sqlResult').css('display', 'block');
                $('#sqlResult').html(queryStr);
                $('#btnUpdateQuery').removeClass('hidden');
                $('#btnInqueryRule').removeClass('hidden');
            });

        })(jQuery);


    </script>
```

**Comment by mistic100** [comment]
I don't know how your website works I can't help you on that. Looks perfectly fine on my side.

**Comment by jackryu** [comment]
Ok - How to get exciting Query Builder object.

`like this var qb=$("myBuilder");`

**Comment by mistic100** [comment]
`var builder = $('#builder')[0].queryBuilder;` 
It's in the doc http://querybuilder.js.org/#methods

**Comment by jackryu** [comment]
How to check "queryBuilder" reference is exist or page not...  ?

**Comment by mistic100** [comment]
http://stackoverflow.com/questions/400916/how-can-i-check-if-a-jquery-plugin-is-loaded

**Comment by jackryu** [comment]
Thanks for quick reply - (Sorry for Asking query again and again) but i am stack on final point. but thanks a lot for support. @mistic100

**Comment by jackryu** [comment]
Problem find but i don't have  a solution..

my all code in this block

; (function ($) {


})(jQuery);

if i am add my SetQuery Function in this block its working but if i am call this function out of this scope its not work.... and if i am remove this block then my complete plugin is not  work....

![image](https://cloud.githubusercontent.com/assets/6933841/25094986/3b3cf3d0-23b7-11e7-948e-4a5eeac8a445.png)

its work like this - but i need to call red selected function in my other JS file ...... Please Help if possible this is your plug in you understand well if i am trying to resolved. i need lot of time because i need to review all code..

**PLEASE HELP IF POSSIBLE .....**

**Comment by rkrameshkumar71** [comment]
core.es5.js:1020 ERROR TypeError: jQuery(...).queryBuilder is not a function(…)defaultErrorLogger @ core.es5.js:1020webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080next @ core.es5.js:4503schedulerFn @ core.es5.js:3635webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:239webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.SafeSubscriber.next @ Subscriber.js:186webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber._next @ Subscriber.js:127webpackJsonp.../../../../rxjs/_esm5/Subscriber.js.Subscriber.next @ Subscriber.js:91webpackJsonp.../../../../rxjs/_esm5/Subject.js.Subject.next @ Subject.js:56webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621(anonymous function) @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:392webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ zone.js:142webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844onHandleError @ core.es5.js:3912webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.handleError @ zone.js:396webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ zone.js:195webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:499invokeTask @ zone.js:1540globalZoneAwareCallback @ zone.js:1566


I am Getting this error if i am creating another angular program and there i am implementing then it is working fine but when i am implementing Jquery query builder in my project it will showing above  error i think js files are conflicting but i don't no how to resolve this solution any on can help me.
================================================================
my angular.cli.json file code is below 
================================================================
{
    "project": {
        "version": "1.0.0-beta.28.3",
        "name": "new-mis"
    },
    "apps": [{
        "root": "src",
        "outDir": "dist",
        "assets": [
            "assets",
            "favicon.ico"
        ],
        "index": "index.html",
        "main": "main.ts",
        "test": "test.ts",
        "tsconfig": "tsconfig.json",
        "prefix": "app",
        "mobile": false,
        "styles": [
            "styles.css",
            "../src/assets/styles/custom-bootstrap.less",
            "../node_modules/fullcalendar/dist/fullcalendar.css",
            "../node_modules/primeng/resources/themes/omega/theme.css",
            "../node_modules/bootstrap-select/dist/css/bootstrap-select.css",
            "../node_modules/ng2-daterangepicker/daterangepicker.component.css",
            "../node_modules/primeng/resources/primeng.css",
            "../node_modules/font-awesome/css/font-awesome.css",
            "../bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css",
            "../node_modules/nouislider/distribute/nouislider.min.css",
            "../node_modules/jQuery-QueryBuilder/dist/css/query-builder.default.min.css"

        ],
        "scripts": [
            "../node_modules/jquery/dist/jquery.js",
            "../node_modules/bootstrap/dist/js/bootstrap.js",
            "../node_modules/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js",
            "custom.js",
            "../node_modules/moment/moment.js",
            "../node_modules/chart.js/dist/Chart.js",
            "../node_modules/fullcalendar/dist/fullcalendar.js",
            // "../node_modules/material-design-lite/dist/material.js",
            "../node_modules/bootstrap-select/dist/js/bootstrap-select.js",
            "../node_modules/ng2-daterangepicker/lib/daterangepicker/daterangepicker.component.js",
            "../node_modules/@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js",
            "../bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js",
            "../node_modules/nouislider/distribute/nouislider.js",
            "../node_modules/ng2-nouislider/src/nouislider.js"
        ],
        "environmentSource": "environments/environment.ts",
        "environments": {
            "source": "environments/environment.ts",
            "dev": "environments/environment.ts",
            "prod": "environments/environment.prod.ts"
        }
    }],
    "addons": [],
    "packages": [],
    "e2e": {
        "protractor": {
            "config": "./protractor.conf.js"
        }
    },
    "test": {
        "karma": {
            "config": "./karma.conf.js"
        }
    },
    "defaults": {
        "styleExt": "css",
        "prefixInterfaces": false,
        "inline": {
            "style": false,
            "template": false
        },
        "spec": {
            "class": false,
            "component": true,
            "directive": true,
            "module": false,
            "pipe": true,
            "service": true
        }
    }
}
