### ISSUE TITLE
Query builder appears but it is horizontally compressed

### ISSUE THREAD

**Issue by CarbonMan** [mistic100/jQuery-QueryBuilder#471]
This is the way queryBuilder appears in a jQuery dialog box.
![image](https://cloud.githubusercontent.com/assets/5210833/25170561/54ef5944-252e-11e7-9f91-cc85d4d3e148.png)

Here is the code. It might be difficult to put this into jsFiddle but if you need more I'll give it a try.
```
var qryDiv = document.createElement("div");
qryDiv.id = "builder";

var dlgDiv = document.createElement("div");
dlgDiv.id = "queryDialog";
dlgDiv.setAttribute("title", "Query");
dlgDiv.appendChild(qryDiv);
document.body.appendChild(dlgDiv);

$(function () {
    /**
    * Message received from hub
    */
    IOTKEY.on("hubReceived", function hubReceived(ev) {
        var msg = ev.message;
        if (msg.type == "query") {
            $('#builder').queryBuilder('setFilters', true, msg.query.filters);
            if (msg.query.rules)
                $('#builder').queryBuilder('setRules', msg.query.rules);
            $("#queryDialog").dialog('open');
        }
    });

    function runQuery() {
        var rules = $('#builder').queryBuilder("getRules");
        console.log(rules);
        dialog.dialog("close");
    }

    var dialog = $("#queryDialog").dialog({
        autoOpen: false,
        height: 400,
        width: 750,
        modal: true,
        buttons: {
            "Run": runQuery,
            Cancel: function () {
                dialog.dialog("close");
            }
        }
    });
    // queryBuilder requires a starting filter.
    // http://stackoverflow.com/questions/31099569/jquery-querybuilder-not-working
    $('#builder').queryBuilder({
        allow_empty: true,
        filters: [{id:1}],
        rules: {
            condition: 'AND',
            rules: []
        }
    });
});
```

**Comment by mistic100** [comment]
Aren't you missing Bootstrap CSS ?

**Comment by CarbonMan** [comment]
Bootstrap is loaded. 
`
<head>
    <meta charset="utf-8" />
    
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/semantic-2.1.8.min.css">
    <link rel="stylesheet" type="text/css" href="css/jquery-ui-1.12.1.min.css">
    <script type="text/javascript" src="js/jquery-2.2.0.min.js"></script>
</head>
`
Maybe I'll have to work this into a fiddle to troubleshoot it properly.

**Comment by CarbonMan** [comment]
The user agent stylesheet has the divs as display: block as a default. Overriding them to display: inline has resolved the problem
`    <style>
        .rule-header{
            display: inline
        }
        .error-container{
            display: inline
        }
        .rule-filter-container{
            display: inline
        }
        .rule-operator-container{
            display: inline
        }
        .rule-value-container{
            display: inline
        }
    </style>
`

**Comment by mistic100** [comment]
And aren't you missing QueryBuilder CSS ?

**Comment by CarbonMan** [comment]
Your right, so sorry to have wasted your time.

BTW: in attempting to solve this I found the link on http://querybuilder.js.org/index.html to [query-builder.css](https://cdn.jsdelivr.net/jquery.query-builder/2.4.3/css/query-builder.default.min.css) was coming back with File not found.

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/issues/467 it's been a whole though, the bot of jsdelivr is slow
