### ISSUE TITLE
Jqery querbuilder get the option value insted of key

### ISSUE THREAD

**Issue by carthikn** [mistic100/jQuery-QueryBuilder#472]
```js
filters: [{
          id: 'name',
          label: 'Name',
          type: 'string'
        }, {
          id: 'category',
          label: 'Category',
          type: 'integer',
          input: 'select',
          values: {
            1: 'Books',
            2: 'Movies',
            3: 'Music',
            4: 'Tools',
            5: 'Goodies',
            6: 'Clothes'
          },
          operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
        }, {
          id: 'in_stock',
          label: 'In stock',
          type: 'integer',
          input: 'radio',
          values: {
            1: 'Yes',
            0: 'No'
          },
          operators: ['equal']
        }]
```
For this var result = $('#builder').queryBuilder('getRules');
		  if (!$.isEmptyObject(result)) {
			  var out = JSON.stringify(result, null, 2);
			
			 alert(out);
			
		  }

in this i can see the value of category is 1 i need the value to be Book

**Comment by mistic100** [comment]
Nothing forces you to use hashmaps for values.

All accepted formats are detailed here : http://querybuilder.js.org/#filters -> values -> More details

```js
type: 'string',
values: ['Books', 'Movies', '...']
```

**Comment by carthikn** [comment]
Thanks for you reply 
My question is i need both key and value but in getRules i can able to get only the key not value.
How can i  get that.

**Comment by mistic100** [comment]
Sorry you cannot, QueryBuilder only returns the keys, not the label, you could create compound keys like `id--label` and split/join where you need.

**Comment by carthikn** [comment]
Thanks for your valuable time for reply.

**Comment by mistic100** [comment]
Actually there is way, using the rule's data

UNTESTED :

```js
$('#builder').on('afterUpdateRuleValue.queryBuilder', function(e, rule) {
  if (!rule.data) {
    rule.data = {};
  }
  if (rule.filter.id === 'category') {
    rule.data.label = rule.filter.values[rule.value];
  }
  else {
    rule.data.label = undefined;
  }
});
```

when calling `getRules` each rule will have an additional `data` object with the label
