### ISSUE TITLE
Can't set custom rule

### ISSUE THREAD

**Issue by mwoitter** [mistic100/jQuery-QueryBuilder#473]
Hi all!
Thanks to the team for QueryBuilder, it's very usefull!
I'm sorry, for this issue but after few hours alone, I need help.
I would like to create a group when a specific filter is selected and to add a rule with specific filter and value in the new group.
I can create an empty rule but not a custom one. The API says "addRoot(parent, data, flags)" but can you give me an example of the "data" part?

Thanks!

**Comment by mistic100** [comment]
Hello (not team here just me, thank you).

There is no `addRoot` method, `setRoot` should NEVER be used, you have to use `addGroup` and `addRule`.

Something like :

```js
var $b = $('#builder');

// get the root group
var root = $b.queryBuilder('getModel');

// create an empty group
var group = $b.queryBuilder('addGroup', root, false);

// create a rule
var rule = $b.queryBuilder('addRule', group);

// populate the rule
rule.filter = $b.queryBuilder('getFilterById', 'my_filter_id');
rule.operator = $b.queryBuilder('getOperatorByType', 'equal');
rule.value = 'Foo';
```

The `data` is just for storing custom data associated with your group/rule.
