### ISSUE TITLE
IE Error when using 'setRulesFromSQL'

### ISSUE THREAD

**Issue by papakonstantinouko** [mistic100/jQuery-QueryBuilder#476]
Hello, I get an error when calling the following on IE

`$('.builder').queryBuilder('setRulesFromSQL', this.query);`

it's all fine though on Chrome and Firefox. The error I get is the following 
![image](https://cloud.githubusercontent.com/assets/4752620/25398781/737d6856-29ed-11e7-80a0-978c5a50a372.png)

What can I do to resolve this?

**Comment by mistic100** [comment]
Hi

don't you have the line number of the error ?

**Comment by mistic100** [comment]
And which version of IE ?

**Comment by papakonstantinouko** [comment]
No, how do I find the line number? What I posted is the console of the following code

` try {
          $('.builder').queryBuilder('setRulesFromSQL', this.query);
        } catch (error) {
          console.log(error); }`

It is the latest IE. version: 11.1066.14393.0

**Comment by papakonstantinouko** [comment]
This is from an Angular 4 project. Maybe if I do not use the minified version I shall get more info?

**Comment by mistic100** [comment]
I don't know more about the IE debugger than you. Of course you should use the unminified version to track the error.

** setup a jsfiddle/plunkr**

**Comment by papakonstantinouko** [comment]
I updated to latest version from 2.4.1 and it magically disappeared. Thanks for helping.

**Comment by mistic100** [comment]
nothing is magical
