### ISSUE TITLE
Empty value when using Eonasdan/bootstrap-datetimepicker

### ISSUE THREAD

**Issue by temesinko** [mistic100/jQuery-QueryBuilder#478]
Using the bootstrap-datetimepicker by Eonasdan and calling the method getRules() will result in the field getting marked with an "empty value" error. If I access the input's value via $('input[name={...}]').val() I get the right value the QueryBuilder should also be able to retrieve.

My filter configuration:
`{
    "id":"ext_birthday",
    "field":"birthday",
    "label":"Geburtstag",
    "type":"date",
    "operators":
    [
        "equal",
        "not_equal"
    ],
    "validation":
    {
        "format":"YYYY-MM-DD"
    },
    "plugin":"datetimepicker",
    "plugin_config":
    {
        "locale":"de",
        "format":"YYYY-MM-DD",
        "widgetPositioning":
        {
            "vertical":"bottom"
        }
    }
}`

**Comment by mistic100** [comment]
Already discussed here https://github.com/mistic100/jQuery-QueryBuilder/issues/176 please read entirely for the final solution.
