### ISSUE TITLE
bootstrap datetimepicker plugin

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [mistic100/jQuery-QueryBuilder#479]
I'd like to use the [bootstrap datetimepicker](https://eonasdan.github.io/bootstrap-datetimepicker/); it seems to integrate well by setting it up in the `filter`, e.g.
```
plugin: 'datetimepicker',
plugin_format: { format: 'YYYY-MM-DD HH:mm:ss' }
```
However, whenever I go to build the query it doesn't seem to be able to get the value being entered ("Empty value" error).

Do I need to specify the `valueGetter` property?  What am I missing?

**Comment by mistic100** [comment]
Answered EXACTLY the same thing today #478 

Please search before asking, thank you.
