### ISSUE TITLE
Certain queries cause a parse error

### ISSUE THREAD

**Issue by papakonstantinouko** [mistic100/jQuery-QueryBuilder#482]
Hello, I get parse errors when I call 
`$(this.builder.nativeElement).queryBuilder('setRulesFromSQL', this.query);`

where query is 
`name not like 'total%'`

the error says **Error: Parse error on line 2: Unexpected 'LITERAL'**

there are other cases where I get this error, how can I approach this issue? I have the latest version.

**Comment by papakonstantinouko** [comment]
I have the latest version

**Comment by mistic100** [comment]
Are you using my fork ? https://github.com/mistic100/sql-parser
The original does not support NOT LIKE

**Comment by papakonstantinouko** [comment]
Am doing now, thank you.
