### ISSUE TITLE
"between" validation

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#484]
Hi,

I'm trying to provide validation to some of filters, and I'm aware that I can add validation object and implement/customize the built in callback function, but wanted to check if there is something already built in and configurable - for example when I use filter that has dates or filter like age where between operator can be used - I need to add simple validation if the second parameter is larger (age) or later (date) before I submit the form. 

Thanks,

**Comment by mistic100** [comment]
There is not such built-in check, but it's indeed a good feature to add.

**Comment by nikataus** [comment]
Thank you.

**Comment by mistic100** [comment]
Fixed in #593
