### ISSUE TITLE
How to get Parent Rules and Child Rules hierarchies for a Rule on "Change Rule" event ?

### ISSUE THREAD

**Issue by santoshnd** [mistic100/jQuery-QueryBuilder#489]
I want to capture "change " events (change rule/add /delete events) and find out all the parent rules hierarchy and 
all the children rules hierarchy 
related to this rule.

I want to do some value changes to all children rules based on the values of all the parent rules for the modified rule.

Kindly suggest and help how can I get the parent and child rule hierarchy in this case ?

Your help is highly appreciated.

Thanks & Regards.

**Comment by mistic100** [comment]
The Rule and Group objects are explained here http://querybuilder.js.org/#inside_the_box and here http://querybuilder.js.org/api/Rule.html#members & http://querybuilder.js.org/api/Group.html#members

From a rule you access the parent group with `parent` property and from a group you access rules and groups children with `rules` property or with `each()` method.
