### ISSUE TITLE
Best practice to extend QueryBuilder impl

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#491]
Hi,

I made some changes to query-builder.standalone.min.js to provide 508 compliance and more specifically I changed: 
g.templates.group
g.templates.rule
g.templates.filterSelect
g.templates.operatorSelect
g.prototype.getRuleInput

It works fine. However, I wanted to touch base with you and see what would be the best way to extend your code and change these without the need to change it again when I get your new version of the code. In other words to have separate file that define these and extend the default implementation. 
Thanks,

**Comment by mistic100** [comment]
Hello

There are events for each template parts, use them to inject your labels (see how the sortable plugin injects its button)

**Comment by mistic100** [comment]
Also got don't have to modify the build file ! Look at the doc, it explains how to redefine templates.

But the events solution is the best.

**Comment by nikataus** [comment]
Will it also work for extending g.prototype.getRuleInput?

**Comment by mistic100** [comment]
There is an event too. Don't remember it's name, it's in the doc.

**Comment by nikataus** [comment]
OK! Thanks a lot! I will check it out later.

**Comment by nikataus** [comment]
ok, I have couple of questions. I'm trying to do something like: 

$('#adhocBuilder').on('getGroupTemplate.queryBuilder.filter', function(h, level) {
		  
			 var $h = $(h.value);
			 $b = $h.find("button[data-add='rule']");
			 $b.attr("aria-label", "Add Rule button for Group " + code_for_group_id);
		});	
I want to append the group_id that comes from iterator. I know I can get that from id attribute of DL element, but I also know you will change the HTML structure! So is there a way to append group_id in the code above? 
Also in the event I'm using code to get the button element and append an attribute... is that ok? what if you change your template and replace the button, then my code will need to change too... 
I see in the sorting plugin you are using rule_header to find the right element, but it's different in my case.
Please let me know what your thoughts are.
Thanks!

**Comment by mistic100** [comment]
First of all you forgot a `e.value = $h.prop('outerHTML');` at the end.

Use `$h.attr('id')` to get the id, there is hardly any chance this would break in the future.

Your way to get the button is the only way.

Of course if I totally rework the template you will have to modify your code, but this will be a in a major version. And after all it's totally normal, you can't hope to alter the behaviour of a library without planning to adapt in the future.

**Comment by nikataus** [comment]
Thanks a lot, it worked! I did not forget to reset the value at the end .. I was just trying to show what I was doing in general :).
