### ISSUE TITLE
How to Reuse same Filter in Multiple Rules  but with different Input Values ?

### ISSUE THREAD

**Issue by santoshnd** [mistic100/jQuery-QueryBuilder#492]
I want to reuse a filter for multiple rules across multiple groups.
But the input values(drop down list) of the same filter will vary from one rule to other.
Actually a subset of the filter input values need to be used inside different rules across different groups.
Please help how can I achieve this in query builder.

**Comment by mistic100** [comment]
I suggest you create multiple filters with the same field property but different values.

**Comment by mistic100** [comment]
You can also use the `getRuleFilters.queryBuilder.filter` changer (see the doc about events) to reduce the available filters for a particular rule depending of its position in the graph.

**Comment by santoshnd** [comment]
Thanks a lot for the inputs.
Based on the inputs I am trying to use  - changer:getRuleValue  API  but
struggling with the right syntax to work with - 

What is wrong with below code line - 
angular.element('#builder').on('getRuleValue.changer.queryBuilder', function(e, rule){ 
}

What is correct syntax for -  "getRuleValue.changer.queryBuilder" event.

Please suggest and help.

Regds.

**Comment by mistic100** [comment]
It's "filter" not "changer" http://querybuilder.js.org/#events

**Comment by nayaaltahan** [comment]
> I suggest you create multiple filters with the same field property but different values.

Hey, any example on how i can do that?
