### ISSUE TITLE
Is it possible to use "==" instead of "equal" on numeric controller

### ISSUE THREAD

**Issue by akcaykamil** [mistic100/jQuery-QueryBuilder#494]
Hi , 
is that possible to use "==" instead of "equal" on numeric controller ?
I mean , i have a control which is like below.
{  
         "type":"integer",
         "id":283,
         "input":"number",
         "field":"@ISTIPNO",
         "value":"1231",
         "operator":"equal"
      }
I want to use == .
Is that possible  or how to do that ?
Ps:It's not a sql controller.

**Comment by mistic100** [comment]
Hello

what exactly is your need ?
If it's display only, use the `lang.operators` config http://querybuilder.js.org/#lang
If it's for the JSON output, you will have to make the change manually OR define a new operator http://querybuilder.js.org/#operators

**Comment by akcaykamil** [comment]
Thats exactly what i want to do.
{ type: 'equalsIgnoreCase', 	optgroup: 'other', nb_inputs: 1, multiple: false, apply_to: ['strings'] } 
I'm coding that piece but it is not working for strings.It's working for number but not working for "strings".

**Comment by akcaykamil** [comment]
And also i want to show "equal" and "not_equal" for just for strings.Also is that possible?

**Comment by mistic100** [comment]
It's `string` without `s`.

Everything is explained in the doc, you can do whatever you want with `apply_to` (as long as you respected the keywords)

**Comment by akcaykamil** [comment]
Thanks for your response ,Damien,
I shouldexamine the document carefully :)
Best regards ,
And thanks for that API.
