### ISSUE TITLE
How to make the Rule's Criteria Field read-only/non-editable

### ISSUE THREAD

**Issue by santoshnd** [mistic100/jQuery-QueryBuilder#495]
Once a new Rule is added to Query-Builder, I want the 'Criteria' field of the Rule should go read-only/non-editable.
'Operator ' and 'Input Values' Field of the Rule will be editable/changeable.

Ex-  
Criteria         Operator          Value
--------         -----------        ---------

Continent    Equal To           Asia

Now, the drop-down with value 'Continent' should go read-only  and
other two drop-down with values 'Equal To' and  'Asia'  should be editable/changeable.

This behavior should be applicable for each Rule getting added.
Kindly help with your inputs - how this can be achieved ?
Any API/method/properties of Query-builder I can use to achieve this ?

**Comment by mistic100** [comment]
If the filter is read-only, how do the user chose the initial value after adding a new rule ?

**Comment by santoshnd** [comment]
After Add Rule and initialization of criteria field(age/continent) I want to make the select box go read-only for that Rule.
Then I will add  new Rule and initialize it with different criteria field and make it read-only.

There will be number of Rules with read-only Criterias. This is the requirement.

That's why I am looking for - how to achieve this behavior.

**Comment by santoshnd** [comment]
What is wrong with this small code snippet :- 

   var builderModel = $('#builder').data('queryBuilder').model;
   var newRule =  $('#builder').queryBuilder("addRule", builderModel.root);
   newRule.filter = $('#builder').queryBuilder("getFilterById", 'continent');
   newRule.flags.filter_readonly = true;

  Here, why the  "filter_readonly = true" flag is not working ?
  Is the syntax correct - newRule.flags.filter_readonly = true;    ???
 
  Please help my understanding to make the "filter_readonly = true" .
 
  Best Regards.

**Comment by nikataus** [comment]
Hi Santoshnd, 
I can't give you the best advise for the code above, however you can easily add code in the event when you add new Rule like afterCreateRuleInput, and get the Filter control and add simple JQuery code to make it read only control.

**Comment by monice** [comment]
@santoshnd I suggest you debug on method 'QueryBuilder.prototype.applyRuleFlags' of query-builder.js. You will get the anwser. After, disabled some input, select to make it readOnly.

**Comment by mistic100** [comment]
@santoshnd you cannot modify the rule's flag after it has been added.
That's why the addRule method takes the wanted flasg as third argument
http://querybuilder.js.org/api/QueryBuilder.html#addRule
