### ISSUE TITLE
feature request: support for MySQL 5.7 JSON format

### ISSUE THREAD

**Issue by sjoerdmaessen** [mistic100/jQuery-QueryBuilder#497]
Being able to work with JSON would be a great addition enabling the querybuilder to be used on MySQL JSON column types aswel. for example:

`result.column->"$.chapter.title" = "x"`

**Comment by mistic100** [comment]
Please be **waaay more explicit** in your request. I have no idea how MySQL JSON fields work.
Why is it not working now ? What is needed for it to work ? How should it be displayed ? etc, etc

**Comment by sjoerdmaessen** [comment]
Thank you for getting back to the request, let me explain the request in more detail. 
With the release of MySQL 5.7 JSON Data Type support is added, please see https://dev.mysql.com/doc/refman/5.7/en/json.html for full details. This enables MySQL users querying JSON documents. Querying is not that different compared to the "traditional" way of querying a MySQL database. But the syntax for accessing JSON columns inside a document is a bit different compared to querying regular columns. There are many different ways to query JSON data type columns like the use of "JSON_EXTRACT" but the easiest syntax to work with in my opinion is the use of the column-path operator "->".

An example, consider a table "person" with multiple columns, 1 column is the column "name":
`SELECT * FROM person WHERE name = 'test'`
Is the statement that is used the simply extract a person where it's name is "test". 

Now we have the same table but instead of a column "name" we have JSON data type column called "data" with the value:
`{
	"family": {
		"name": "test"
	}
}`

Of course this is not the best column name but good enough for an example. So now, querying the JSON data type column our query would look like this:
`SELECT * FROM person WHERE data->"$.family.name" = "test"`
And of course if we would only be interested in the name our query would look like the following:
`SELECT data->"$.family.name" FROM person WHERE data->"$.family.name" = "test"`

I've attached the database data & structure dump of the JSON based example.

As for displaying, I think it could still be the same as the current Import/Export SQL example at: http://querybuilder.js.org/demo.html

I think the trickiest part would be "telling" the builder, by introducing a new property. wether a column is a JSON data type column or not.

I hope I have explained the workings of the JSON data type. A very good presentation about this subject can be found at: https://www.slideshare.net/morgo/mysql-57-json

If you have any more questions, please let me know. 
[29-05-2017-smaessen.txt](https://github.com/mistic100/jQuery-QueryBuilder/files/1036403/29-05-2017-smaessen.txt)

**Comment by mistic100** [comment]
What prevents you to define your filter with `field: 'data->"$.family.name"'` ?
Perhaps it does not work because of special chars, if it's the case it must be fixed.
But it would be much simpler than adding another configuration property and special handling for this "edge" case.
