### ISSUE TITLE
Global event if form has been modified

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#498]
Hi, 

I'm trying to add window.onbeforeunload where popup shows if the user leaves the page. I also want to implement something like dirtyForm flag, if the user has made any changes to the form and in general I want to catch all events like add new Rule, add new Group, change filter, change operator, change values, etc. 
I know I can implement all events and change this flag there, however I wanted to check if there is something like global event that will catch all these, and only implement it there, instead of all events. 
Let me know if you have any ideas to optimize my code.
Thanks for your help!

**Comment by monice** [comment]
```javascript
$('#builder').on('afterCreateRuleInput.queryBuilder afterUpdateRuleFilter.queryBuilder afterUpdateRuleOperator.queryBuilder', function(
    e, rule) {
    switch (rule.filter.id) {
        case 'group_by':
            // ...your code
            break;
        default:
            rule.moveAtBegin(rule.parent);
            break;
    }
});
```

**Comment by nikataus** [comment]
Hi Monice, 

I don't think you're catching all events:
For example - changing the values select control or changing the condition group element (AND/OR).
Thanks,

**Comment by monice** [comment]
All events is here: http://querybuilder.js.org/api/list_event.html. The above code is just my a usage, you can custom it. JavaScript is openness programming language.

**Comment by nikataus** [comment]
Thank you.

**Comment by mistic100** [comment]
I will add a global "change" event.

**Comment by nikataus** [comment]
Great! Thank you.

**Comment by nikataus** [comment]
Hi there, any information on when you will release 2.4.5? 
Thanks!
