### ISSUE TITLE
Change the icon of delete button as well as to remove the Add Rule button using Angular JS . 

### ISSUE THREAD

**Issue by aryanisml** [mistic100/jQuery-QueryBuilder#499]
Please provide guidelines as need to change the icon of delete button as well as to remove the Add Rule button using Angular JS . 
As i written the code inside in builder.on('afterApplyGroupFlags.queryBuilder', function(e, model){ } ) to remove the button and provide the icon but it only work for root level or parent level. So request to provide more guidelines to achieve the functionality.

**Comment by mistic100** [comment]
Change the icon : http://querybuilder.js.org/#icons

Always hide "Add rule" :

```js
$('#builder').queryBuilder({
  default_group_flags: {
    no_add_rule: false
  }
});
```
