### ISSUE TITLE
How to add new custom validation to a rule ?

### ISSUE THREAD

**Issue by santoshnd** [mistic100/jQuery-QueryBuilder#500]
How to define a new error condition and error message for a  rule ?

any example of .validate () method highly appreciated.

**Comment by oller** [comment]
http://querybuilder.js.org/index.html#validation

Define a `validation` object with the properties you require, per filter.

Look at the example: http://querybuilder.js.org/assets/demo-basic.js

**Comment by mistic100** [comment]
```js
validation: {
  callback: function(value, rule) {
    if (valid) {
      return true;
    } else {
      return ['{0} is not valid', value];
    }
  }
}
```
