### ISSUE TITLE
capture 'click ' event on rule value container's select  drop down control

### ISSUE THREAD

**Issue by santoshnd** [mistic100/jQuery-QueryBuilder#501]
Please consider a query - 
I want to capture the 'click ' event  when user clicks on the select box(drop down control) of rule's value container in order to see which options are available to select the value.

How can I capture this 'click' event. I tried following but not working - 

$('#builder').find('.rule-value-container').click(function(){
    var ele = $(this);
    ele.append('<option value=1>TA2_NEW_1</option>');
    ele.append('<option value=1>TA2_NEW_2</option>');
})

Please suggest regarding - "click" event handling. I don't find any API for 'click' event in the current API list. Kindly help my understanding.

**Comment by mistic100** [comment]
You must use event delegation

```js
$('#builder').on('click', '.rule-value-container', function(){
  var ele = $(this);
  ele.append('TA2_NEW_1');
  ele.append('TA2_NEW_2');
});
```

**Comment by santoshnd** [comment]
Thanks a lot for the response.
One more point, whenever I click on the select box(drop down control) of a rule-value-container,
I want to capture the 'click'  event and pass the 'Rule Object' associated with that rule-value-container to the  click event handler.
Is there any way to get the Rule Object corresponding the select box that user clicks to see the values in select box ?
 I want it with 'click event' and NOT with 'change' event.

Kindly help with your inputs.

**Comment by mistic100** [comment]
in your handler :

```js
var rule = $('#builder').queryBuilder('getModel', $(this).closest('.rule-container'));
```
