### ISSUE TITLE
Configuration for adding placeholder attr

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#502]
Hi,

I want to add placeholder attribute (like 'mm/dd/yyyy') to all date fields. Is there configuration for it or I have to change the template where you generate the input control?

**Comment by mistic100** [comment]
Huh ?
Use "placeholder" ? http://querybuilder.js.org/#filters

**Comment by nikataus** [comment]
ah, I might have missed that looking for complicated solutions :)
