### ISSUE TITLE
Validating dates 

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#505]
Hi,

I have several date fields and I want to implement validation for those fields. If the user types in manually (instead of using the popup control) something like 55/10/2000 (in other words invalid date) and moves to the next control it will assign new date - still correct but not what the user entered! I want to prevent this. What is the best way to do it? I checked boostrapValidation plugin, but wanted to check for different options.

**Comment by mistic100** [comment]
Why don't you start by showing your config ? (I am always asking the same simple thing).
I don't know which datepicker you use, if you use moment.js etc.

None the less what your are describing really looks like the automatic correction of the component you are using, not related to QueryBuilder.

**Comment by nikataus** [comment]
I'm using Java to dynamically build QueryBuilder config and here's code I have when I build Date fields:

case Constants.DATE_QUERYBUILDER_CONTROL_TYPE_NAME:
 rez.append( "plugin: " + "'datepicker'" );
                rez.append( ", " );
                rez.append( "plugin_config: ");
                rez.append( "{ ");
                rez.append( "format: " + "'mm/dd/yyyy'" );
                rez.append( ", " );
                rez.append( "todayBtn: " + "'linked'" );
                rez.append( ", " );
                rez.append( "todayHighlight: " + "true" );
                rez.append( ", " );
                rez.append( "autoclose: " + "true" );
                rez.append( ", " );
                rez.append( " }");
                
                rez.append( ", " );
                rez.append( "placeholder:" +  "'mm/dd/yyyy'" );

**Comment by mistic100** [comment]
So you must look at the configuration of this datepicker plugin.
QueryBuilder will never auto correct an invalid value.
