### ISSUE TITLE
Any plans for supporting multiple tables and relationships(joins).

### ISSUE THREAD

**Issue by syamat** [mistic100/jQuery-QueryBuilder#507]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by mistic100** [comment]
See #310
