### ISSUE TITLE
Usage with select2

### ISSUE THREAD

**Issue by Kritzzz** [mistic100/jQuery-QueryBuilder#509]
Hi,

I am wondering if there is a simple way to implement [select2](https://select2.github.io/) as a widget for dropdowns. I want the rule value to be a dropdown for all the countries in the world, each with their own flag and I already have a select2 standalone select field which works. Now I'd like to know how I would tell queryBuilder to use select2 as a widget. I've read the docs and tried to understand the demo for widgets, especially how it got _selectize_ to work (which I assume is very close to what I am looking for).

However, I can't really see how the _selectize_ widget is loaded. You include selectize via a script tag and then simply say `plugin: 'selectize'` in the filter settings? I don't see how that works, especially not for select2, since I can't just write `plugin: 'select2'` - I'm pretty sure I'd have to define that first somewhere else?

Could you give me some directions how to implement a dropdown with queryBuilder and select2?

Thanks in advance.

**Comment by mistic100** [comment]
Did you tried it ?

It's exactly how you must do it, there is nothing to define.

**Comment by mistic100** [comment]
If you want to know how it works https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/core.js#L646

**Comment by kevalbhatt** [comment]
@Kritzzz simple initialize query Builder with select2 as option and it should work.

    $('#builder-widgets').queryBuilder({
        plugins: ['bt-tooltip-errors'],
        filters: [{
            id: 'select2',
            label: 'select2',
            type: 'string',
            plugin: 'select2',
            plugin_config: {
                data: ["abc", "xyz"]
            },
            valueSetter: function(rule, value) {}
        }]
    })

**Comment by Kritzzz** [comment]
Hi,

thanks for your comments and sorry for the late reply. I got select2 to work, it turned out to be a webpack-related problem in the end - sorry for the confusion!

I have a quick follow-up question:

I'm currently looking to write my own "getRules" function since I need a slightly different JSON format. I'm wondering what would be the best way to extend the library - I know I can't just write my own code into query-builder.js since that would lock me to a specific version and prevent future updates. Is there an easy way to write my own function in a different .js-file that extends query-builder?

Thanks in advance!

**Comment by mistic100** [comment]
```
$.fn.queryBuilder.constructor.prototype.yourGetRules = function() {

};
```

**Comment by Kritzzz** [comment]
Thanks so much, this is exactly what I needed!

**Comment by xingguo3** [comment]
Hey Guys, I still have problems with select 2 in jquery querybuilder. 
It works normally on load. But when I add a same query, or select a different  filter and go back to select 2, the select drop box would not display as expected. Could you plz advise?
![image](https://user-images.githubusercontent.com/15721650/59658775-34b84b00-91d7-11e9-901b-cb679d42dd02.png)

**Comment by amirgee007** [comment]
@mistic100 is there any support for select2 tags as if i set tags : true it should work or not??

thanks

**Comment by cormip** [comment]
It works with tags when you set `multiple: true`.
