### ISSUE TITLE
Runtime Validation configuration

### ISSUE THREAD

**Issue by nikataus** [mistic100/jQuery-QueryBuilder#510]
Hi,

I'm trying to implement custom validation for our datepicker controls. I was just curious if it's a good idea and doable to add validation to the filter object when I add the rule (on('afterCreateRuleInput.queryBuilder')? I realize it's better to create the validation object as we setup the QueryBuilder, but that's what I'm targeting in the next release.

**Comment by mistic100** [comment]
Why do you want to do that ?

The problem is the validation object is owned by the filter, so if you try to alter it on rule creation (which should work actually), the validation will be applied to every other rule using the same filter.

**Comment by mistic100** [comment]
And `afterCreateRuleInput` is not the right event because at this time, the rule has no filter. You must use `afterChangeRuleFilter`.

**Comment by nikataus** [comment]
Thanks for your reply. Are you asking me why I want to add validation at runtime, or why I want to add it on afterCreateRuleInput  event ?

**Comment by mistic100** [comment]
... it's the same thing for me

**Comment by nikataus** [comment]
In my application I have a process on startup where I read DB model and generate all config structure for our Query Builder. We don't have time to change the DB and add implementation to generate that validation object. Instead I want to use your event system and add it at runtime. Which event I need to use I'm not sure and you're helping me out on that. But now you understand why it matters for me to add this validation in the event.
