### ISSUE TITLE
How to overwrite templates?

### ISSUE THREAD

**Issue by Andi82ka** [mistic100/jQuery-QueryBuilder#511]
Hey,

I would like to add a button to the rule template. I found already somebody asked similar question (https://github.com/mistic100/jQuery-QueryBuilder/issues/463#issuecomment-293631567).

But I need more detailed instructions. How to overwrite the rule-template? I found the function in original code: https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/template.js#L35

But how to overwrite this function with my own? I have to do that after init?
```
var $builder = $('#qbuilder').queryBuilder({
            plugins: ['sortable']
});
```
Would be happy to get some short example.

**Comment by mistic100** [comment]
```js
templates: {
  rule: 'Your HTML with doT.js syntax'
}
```

**Comment by Andi82ka** [comment]
Thx for this fast answer!! Works to overwrite. Is ist also anyhow possible to use it.translate? For me coming console error "TypeError: it.translate is not a function" when I do like that:

```
var $builder = $('#qbuilder').queryBuilder({
            plugins: ['sortable'],
            templates: {
                rule: '\
<li id="@{{= it.rule_id }}" class="rule-container"> \
  <div class="rule-header"> \
    <div class="btn-group pull-right rule-actions"> \
      <button type="button" class="btn btn-xs btn-danger" data-delete="rule"> \
        <i class="@{{= it.icons.remove_rule }}"></i> @{{= it.translate("delete_rule") }} \
      </button> \
    </div> \
  </div> \
  @{{? it.settings.display_errors }} \
    <div class="error-container"><i class="@{{= it.icons.error }}"></i></div> \
  @{{?}} \
  <div class="rule-filter-container"></div> \
  <div class="rule-operator-container"></div> \
  <div class="rule-value-container"></div> \
</li>'
            }
        });
```
