### ISSUE TITLE
Option to change buttons label of "Add rule" , "Add Group" and "Delete"

### ISSUE THREAD

**Issue by kevalbhatt** [mistic100/jQuery-QueryBuilder#512]
I want to change buttons label from

- “Add rule” => “Add filter”
- “Add group” => “Add filter group”

I found options to change icon for this buttons but don't found any option to change buttons label.

what I have done to change the label.

`$.fn.queryBuilder.regional.en.add_rule = "Add filter";
$.fn.queryBuilder.regional.en.add_group = "Add filter group";`

But this is not good solution.
So can you let me know if there is any better option other than the above ?

**Comment by kevalbhatt** [comment]
I found the options to changes the lang string.

```
this.ui.builder.queryBuilder({
    plugins: ['bt-tooltip-errors'],
    filters: filters,
    select_placeholder: '--Select Attribute--',
    lang: {
        add_rule: 'Add filter',
        add_group: 'Add filter group'
    }
});
```

**Comment by pratik24mac** [comment]
How to change Condition button color AND | OR.

**Comment by naziasaifisage** [comment]
> I found the options to changes the lang string.
> 
> ```
> this.ui.builder.queryBuilder({
>     plugins: ['bt-tooltip-errors'],
>     filters: filters,
>     select_placeholder: '--Select Attribute--',
>     lang: {
>         add_rule: 'Add filter',
>         add_group: 'Add filter group'
>     }
> });
> ```

Thanks, it is working :)
