### ISSUE TITLE
rule.data is undefined after getModel()

### ISSUE THREAD

**Issue by Andi82ka** [mistic100/jQuery-QueryBuilder#513]
Hello,

I added (with your help) an duplicate button to the rules. Because we have very long filter list and often need to add them 10 times with different values in an OR-group. So we just want to duplicate them and then change value. I did add the new rule like this:

```
$builder.on('click', '[data-duplicate=rule]', function(e) {
            var rule = $builder.queryBuilder('getModel', $(e.target).closest('.rule-container'));
            $builder.queryBuilder('addRule', rule.parent);
        });
```

This is adding an empty rule to this group. But of course I want the selected filter of this duplicated group. so I tried

```
 $builder.queryBuilder('addRule', rule.parent, rule.data);
```

But rule.data is not existing. Is it possible to get the data of the rule?

**Comment by mistic100** [comment]
Please carefully read the documentation: `data` is only for use data storage, it does not contains anything used by the builder.

you need :
```js
var newRule = $builder.queryBuilder('addRule', rule.parent);
newRule.filter = rule.filter;
newRule.operator = rule.operator;
newRule.value = rule.value;
```

**Comment by Andi82ka** [comment]
Thanks a lot! I got the data part totally wrong. It works fine now!
