### ISSUE TITLE
Add a group and setRules on a group without clearing state of queryBuilder

### ISSUE THREAD

**Issue by oller** [mistic100/jQuery-QueryBuilder#514]
Hi there,

A great library, well documented, thank you!

I'm afraid I couldn't find a specific method to achieve this, so just wondered if there's a suggested approach.  I've use case where I've the concept of 'templates' which effectively just `setRules` to the queryBuilder.

The issue is the user should be able to add multiple templates, each one in its own group.  `setRules` clears the state of the builder, so i'd have to I imagine `getRules`, manipulate the json object to insert the new group, then `setRules`

If the `addGroup` method supported a setRules object option, which it `setRules` for the group on adding would also achieve this.  Is that a worthwhile improvement?

I see `addGroup` and `addRule` both support a data option, but i'm not entirely clear how that could be used.  It seems `addRule` just adds a blank rule? I could add a group get the reference to the group, then add some rules, but I'm looking to effectively set rules, not just add blank rules.

Any suggestions appreciated,

Thanks!

**Comment by oller** [comment]
I solved this with some `getRules` -> object manipulation > `setRules`.  Closing this issue, feel free to reopen if you think `addGroup` could take a rules object parameter, which I think could be a useful feature.

**Comment by mistic100** [comment]
This answer might help you https://github.com/mistic100/jQuery-QueryBuilder/issues/513#issuecomment-308137165
