### ISSUE TITLE
Datepicker Error

### ISSUE THREAD

**Issue by parkerj** [mistic100/jQuery-QueryBuilder#519]
I've read the documentation, past issues, and no matter what I do, I keep getting an error. I am absolutely stumped. I am using the datepicker plugin from here: https://github.com/uxsolutions/bootstrap-datepicker

Here is my code:
```
{
    id: 'strc.startDate',
    label: 'Start Date',
    type: 'date',
    validation: {
      format: 'yyyy-mm-dd'
    },
    plugin: 'datepicker',
    plugin_config: {
      format: 'yyyy-mm-dd',
      todayBtn: 'linked',
      todayHighlight: true,
      autoclose: true
    },
    optgroup: 'strc',
    operators: ['equal','not_equal','less','less_or_equal','greater','greater_or_equal','is_empty','is_not_empty','is_not','is_null','is_not_null','between','not_between']
  }
```
Saving the date is not a problem, but during the callback of the saved SQL, I keep getting the following error and the date part of the rule does not show up, but it is saved:
```
Uncaught TypeError: $inputs[filter.plugin] is not a function
    at QueryBuilder.createRuleInput (query-builder.js:939)
    at QueryBuilder.updateRuleFilter (query-builder.js:961)
    at Model.update (query-builder.js:653)
    at Model.dispatch (jquery.min.js:4)
    at Model.v.handle (jquery.min.js:4)
    at Object.trigger (jquery.min.js:4)
    at Object.e.event.trigger (jquery-migrate.min.js:2)
    at e.fn.init.triggerHandler (jquery.min.js:4)
    at Model.trigger (query-builder.js:2198)
    at Rule.set [as filter] (query-builder.js:2254)
```
Here is the rule that is saved:
```
"strc.code = 'NOREG' AND strc.severity = 100 AND strc.startDate = '2017-06-25'"
```
What am I doing wrong? Am I not loading something that needs to be loaded?

**Comment by mistic100** [comment]
This error means that the jQuery plugin "datepicker" is not available (yet ?) on your page.

Without seeing a complete demo of your code I can't help more.

**Comment by parkerj** [comment]
You are awesome!!!!!!!!!! It was loading to late. It works now once I've relocated it.

> ps: you don't have to provide operators if you use them all

Ah, thanks for that tip!
