### ISSUE TITLE
Set multiple filters  

### ISSUE THREAD

**Issue by AnanthManickm** [mistic100/jQuery-QueryBuilder#521]
**Mutiple filters in same row**

I am new to use jquery- QueryBuilder in my application. Here I need to set two different filters as shown in the picture. If any one face this issue share your fix.   

<img width="875" alt="query_builder_filters" src="https://user-images.githubusercontent.com/22674503/27895816-1fccd79a-6233-11e7-8644-7229fadda802.PNG">

**Comment by mistic100** [comment]
What should be the output of such setup ?

There is no chance this functionality will ever be added, it involves too many changes in the builder

**Comment by AnanthManickm** [comment]
Thanks for your response.
