### ISSUE TITLE
Is there a way to change the generated Boolean value of '1' for true and '0' for false when I call $("#builder").queryBuilder("getSQL", false);

### ISSUE THREAD

**Issue by naveendb92** [mistic100/jQuery-QueryBuilder#523]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by mistic100** [comment]
You know the issue description is here to write things on ?

---

Yes it's possible (the doc is incomplete).

When you create the builder, add this option : `boolean_as_integer: true`

**Comment by mistic100** [comment]
```js
$('#builder').queryBuilder({
  plugins: {
    'sql-support: { boolean_as_integer: true }
  },
  .......
});
```

**Comment by mistic100** [comment]
Sorry this is not yet released, I will package 2.4.4 in a few hours

**Comment by naveendb92** [comment]
Oh okey. Thank you so much.

**Comment by mistic100** [comment]
2.4.4 released, I didn't updated to doc but by example above is valid

**Comment by naveendb92** [comment]
@mistic100  **Thank you so much**. Yes it worked for me.

Fiddle of the working code:
https://jsfiddle.net/k2f46297/135/

**Comment by naveendb92** [comment]
When I do **bower install jQuery-QueryBuilder**, I'm not able to find a **dist** folder which contains the **query-builder.standalone.min.js** and the css file. I tried also to download **Source code** from the link below and checked it, even there I'm not able to find JS & CSS files.

https://github.com/mistic100/jQuery-QueryBuilder/releases/tag/2.4.4

**Comment by mistic100** [comment]
The tag was created on the wrong branch, I will fix it.

**Comment by mistic100** [comment]
Clean your Bower cache and restart the update.

Sorry for that.

**Comment by naveendb92** [comment]
Yes everything is working fine now. Able to see dist folder with JS and CSS files. @mistic100  **Thank you once again**

**Comment by naveendb92** [comment]
Is there a way to restrict the user to select the date only from DatePicker, but not manual entry ?

**Comment by mistic100** [comment]
this is a config specific to the date picker you are using, not query builder

**Comment by naveendb92** [comment]
Yes understood. Thank you
