### ISSUE TITLE
can i create some selected filters as one group

### ISSUE THREAD

**Issue by bharathchandragoud** [mistic100/jQuery-QueryBuilder#524]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [jsDelivr](https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/) and [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by mistic100** [comment]
I closed your first issue because you didn't added any details and I will do the same here if you don't edit your message with details about what you want.

**Comment by bharathchandragoud** [comment]
below i have some filters , i am  thinking to add  2 or more filters add as one group , is it possible ?

with in that group i want list down group of filters
example : 
Date -Time is one group
     filter 1 : date filter
     filter 2 : time filter
     filter 3: date and time
location is another group
     filter 1 : city filter
     filter 2: country filter 


$('#builder').queryBuilder({
    plugins: ['bt-tooltip-errors'],
    filters: [{
            id: 'name',
            label: 'Name',
            type: 'string'
        },
{
    id: 'date',
    label: 'Datepicker',
    type: 'date',
    validation: {
      format: 'YYYY/MM/DD'
    },
    plugin: 'datetimepicker',
    plugin_config: {
      timepicker: true,
	  format: 'Y-m-d',
	  datepicker: true,
	  closeOnDateSelect: true,
	  
    }
  },
		{
            id: 'category',
            label: 'Category',
            type: 'integer',
            input: 'select',
			values: {
                1: 'Books',
                2: 'Movies',
                3: 'Music',
                4: 'Tools',
                5: 'Goodies',
                6: 'Clothes'
            },
            operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
        }, {
            id: 'in_stock',
            label: 'In stock',
            type: 'integer',
            input: 'radio',
            values: {
                1: 'Yes',
                0: 'No'
            },
            operators: ['equal']
        }, {
            id: 'price',
            label: 'Price',
            type: 'double',
            validation: {
                min: 0,
                step: 0.01
            }
        }, {
            id: 'id',
            label: 'Identifier',
            type: 'string',
            placeholder: '____-____-____',
            operators: ['equal', 'not_equal'],
            validation: {
                format: /^.{4}-.{4}-.{4}$/
            }
        }],
});

**Comment by mistic100** [comment]
I am not really sure I understood want you mean, your sentence is not clear at all.

Try the `optgroup` filter option : http://querybuilder.js.org/#filters
