### ISSUE TITLE
No target defined error

### ISSUE THREAD

**Issue by preraksola** [mistic100/jQuery-QueryBuilder#527]
I am using the library in my Angular application along with Angular material. I am trying to display the query builder in a `md-dialog` in my application. But as soon as I click the button to open the dialog,  I get the following error in the console and the dialog is not rendered.
> ConfigError: No target defined
    at Object.k.error (https://cdn.jsdelivr.net/jquery.query-builder/2.4.3/js/query-builder.standalone.min.js:7:11517)
    at r.fn.init.$.fn.queryBuilder (https://cdn.jsdelivr.net/jquery.query-builder/2.4.3/js/query-builder.standalone.min.js:7:12512)

In the controller of the dialog I have the following code:

```
let filters = [{
    id: 'getCPU',
    label: 'getCPU',
    type: 'integer',
    input: 'number',
    value_separator: ','
}, {
    id: 'getIO',
    label: 'getIO',
    type: 'integer',
    input: 'number',
    value_separator: ','
}];

let operators = [{
    type: 'equal',
    optgroup: 'basic'
}, {
    type: 'not_equal',
    optgroup: 'basic'
}];

$scope.policyBuilderConfig = {
    filters: filters,
    operators: operators,
    sort_filters: true,
    conditions: ['AND', 'OR'],
    allow_groups: true
 };

$('#builder').queryBuilder(
    $scope.policyBuilderConfig
);
```
An example which reproduces this issue can be found here: https://jsfiddle.net/prerak6962/dvbg2aw2/1/

Is there anything else that I need to do to make it work in a dialog?

**Comment by mistic100** [comment]
That's probably because the controller is initialized before the view is rendered, then the DOM is not ready.

But I couldn't tell you how to proceed, I never used Angular Material.

**Comment by preraksola** [comment]
Yeah, that was it. Upon initialising the query builder on document ready, it is working fine now.
```
angular.element(document).ready(function() {
    $('#builder').queryBuilder(
        $scope.policyBuilderConfig
    )
});
```
