### ISSUE TITLE
How to setRulesFromSQL when having more than one filter by database field

### ISSUE THREAD

**Issue by mauriciojsola** [mistic100/jQuery-QueryBuilder#528]
Hi Mistic,
First of all, I really appreciate your hard work and I have to say that your library is AWESOME!

So, given that said.... from your SQL plugin doc: 
"setRulesFromSQL assumes that you have only one filter by database field. If this is not the case, you can use the getSQLFieldID changer to determine the filter's id."

Do you have any example on how to determine the filter's id in order to support having more than one filter by field. Attached is an image about what I'm trying to achieve.
Basically, I need to use the OR multiple times for the same field.
If I use each field only once, the Builder is able to rebuild the whole layout. Otherwise, everything gets messed up...
I know I could use the IN clause and allow multiple values per filter, but it is not that flexible (for my case) and I'd like to see if I can get this sorted out anyway.
 
![query builder sql](https://user-images.githubusercontent.com/1199946/28092486-eb640c68-6669-11e7-8311-88126f5d6d50.png)

I hope you can help me with this.
Thanks in advance!

**Comment by mistic100** [comment]
Hello

```js
$('#builder').on('getSQLFieldID.filter.queryBuilder', function(e, field, value) {
   if (field === 'StoreFrontName') {
     // your logic to return the filter id
   }
   else {
     return field;
   }
});
```

**Comment by mauriciojsola** [comment]
Oh, that was very simple. 
Thanks for your help!
