### ISSUE TITLE
Input box for filters

### ISSUE THREAD

**Issue by preraksola** [mistic100/jQuery-QueryBuilder#529]
I have certain filters which accept some input for example `setAffinity(1)`. And the number of inputs can vary for different filters.

So what I am looking for is something like:

![screen shot 2017-07-17 at 12 18 31 pm](https://user-images.githubusercontent.com/8655814/28264329-bd4e5c90-6aea-11e7-89de-e3e363eb5185.png)

So is there a way I can achieve this?

**Comment by mistic100** [comment]
Not exactly what your mockup show (which is not possible) but you can have custom inputs after the operator with `input` function, `valueSetter` and `valueGetter` http://querybuilder.js.org/#filters

The *Coordinates* filter of the Widgets demo is an example of how to achieve this http://querybuilder.js.org/demo.html#widgets
