### ISSUE TITLE
Is there a way search on filters?

### ISSUE THREAD

**Issue by akcaykamil** [mistic100/jQuery-QueryBuilder#530]
Hi mistic100,
Is there a way search on filters ?
Something like on below.

![image](https://user-images.githubusercontent.com/7128997/28266128-e99b128c-6afb-11e7-9ddf-6a86c4b9f5f1.png)

**Comment by aliaksandrKachurka** [comment]
You can use [bt-selectpicker](http://querybuilder.js.org/plugins.html#bt-selectpicker) plugin with _liveSearch_ enabled:
```
$('#qb').queryBuilder({
    plugins: {
        'bt-selectpicker': {
            liveSearch: true
        }
    }
});
```

**Comment by mistic100** [comment]
Thank you @aliaksandrKachurka this feature didn't exist when I created the plugin.
It's indeed the best solution so far.

This question was asked many times, with always different needs and complications, this is why I always refused to propose a build-in solution, plugins are here to address specific needs.
