### ISSUE TITLE
Dynamically adding same filter twice 

### ISSUE THREAD

**Issue by stanep** [mistic100/jQuery-QueryBuilder#532]
Hi , I am building the app where I am building dynamically filters and rules. In code line 864 you have this line 
        if (definedFilters.indexOf(filter.id) != -1) {
            Utils.error('Config', 'Filter "{0}" already defined', filter.id);
        }
Why we can not "reuse" filters more than once. If somebody building complex filters I see the need to use same filter more than once.

**Comment by mistic100** [comment]
Filters are necessary unique, but you can create two filters with different `id` but the same `field`
