### ISSUE TITLE
Mouse cursor icon doesn't change back when rearranging query builder groups

### ISSUE THREAD

**Issue by heportillo** [mistic100/jQuery-QueryBuilder#537]
If you click on the ![screen shot 2017-07-28 at 10 25 27 am](https://user-images.githubusercontent.com/13731406/28721664-1f3104e8-737f-11e7-9444-eb03ae593245.png) icon the mouse pointer changes to a move cursor. And it sticks that way until you go back and move one of the groups around. If I click on the move icon move my mouse away from it, I want my mouse cursor to change back to a default cursor icon.

Here's a video:
![jquery-mouse-cursor](https://user-images.githubusercontent.com/13731406/28721757-71c83e92-737f-11e7-951f-07e146fcb89d.gif)

**Comment by jvincilione** [comment]
This is an issue with interact.js (https://github.com/taye/interact.js)

**Comment by mistic100** [comment]
So issue no longer exists with interact 1.3
