### ISSUE TITLE
Need to add new dropdown after the first dropdown appeared

### ISSUE THREAD

**Issue by maverick14** [mistic100/jQuery-QueryBuilder#538]
Wanted to add new html element (dropdown,textbox) after the first dropdown and before the operator selection.
Please check the attached image.

![add_dropdown_after_firstone](https://user-images.githubusercontent.com/1592988/28829406-3daaff44-76f1-11e7-96cf-3e5970dbe2b4.PNG)

needed help urgently.
Thanks in advance.

**Comment by mistic100** [comment]
This has been asked multiple times (see #153) and declined because I don't have time to do the major overhaul this requires.

You will have to find another way to address your need, see the other issue for possible solutions, this #530 might help you too.

**Comment by maverick14** [comment]
can you please give some sort of suggestion, that might help me in adding a new dropdown after the fist dropdown.??

Thank you

**Comment by maverick14** [comment]
Hi the reference #153 , what you have given here is needed when some one wanted to have a search filter on a particular dropdown, 
My ask  here is that I wanted to generate a new dropdown element after the first dropdown, it didn't mean of having too much fields in dropdown like you said in #153 

Sorry if I'm not able to clear you my question.

Thanks in advance.

**Comment by nuttyroll** [comment]
@maverick14 It can easily be accomplished by using filter change event and appending your dropdown after that. @mistic100 has done an excellent job on this plugin which can easily be extended if you read the documentation.

**Comment by xingguo3** [comment]
> @maverick14 It can easily be accomplished by using filter change event and appending your dropdown after that. @mistic100 has done an excellent job on this plugin which can easily be extended if you read the documentation.

Any Example for reference?
