### ISSUE TITLE
Reference to #538 ,  Need to add new dropdown after the first dropdown appeared

### ISSUE THREAD

**Issue by maverick14** [mistic100/jQuery-QueryBuilder#539]
Hi the reference #153 , what you have given here is needed when some one wanted to have a search filter on a particular dropdown , but my request here is that I wanted to **generate a new dropdown element after the first dropdown**, it didn't meant of having too much fields in dropdown like you said in #153

I need to have a new dropdown after the first dropdown. Please check it here:

![add_dropdown_after_firstone](https://user-images.githubusercontent.com/1592988/28830879-b786512a-76f5-11e7-96dd-7be5ad876d3b.PNG)

New Drop down **after** Allergycode dropdown and **before** operator selection dropdown

Sorry if I'm not able to clear you my question.

Thanks in advance.

**Comment by mistic100** [comment]
First of all : you can answer to a closed issue !

**I totally understood what you meant** and I maintain my answer : not possible and won't be for a very long time.

**Comment by maverick14** [comment]
Thanks a lot
