### ISSUE TITLE
IN query syntax

### ISSUE THREAD

**Issue by fusion2013** [mistic100/jQuery-QueryBuilder#540]
Hello,

I am using querybuilder, and having issue while using IN operator. In one column we are using selectize plugin. 

This is the function we are calling 
 **$('#querybuilder').queryBuilder('getSQL', false, true).sql**; and getting following response  **cittaTxt IN('Bari,Futani')**, this we are directly using in MySql, but it is not working as there is no comma after every word.

Is anyone has faced this issue. 

Let me know what would be the possible way to solve the issue.

Thanks.

**Comment by mistic100** [comment]
Use the value_separator option on the filter

**Comment by fusion2013** [comment]
Thanks, It solved issue :)

**Comment by vishalkrv** [comment]
Thanks for the solution, it helps in case of string datatype, but how to solve  in case of numeric datatypes as the input box only accepts numeric values and there is no way to enter a separator. Is it possible to override the template in case of in operator?

**Comment by mistic100** [comment]
```
type: 'integer',
input: 'text'
```
http://querybuilder.js.org/#filters
