### ISSUE TITLE
Support for datatypes like bigint

### ISSUE THREAD

**Issue by naveendb92** [mistic100/jQuery-QueryBuilder#541]
Currently if the datatype is of type **bigint**, the Query Builder won't show up. How can I solve this and be able to add new datatypes also ?

**Comment by mistic100** [comment]
The types are only there to control the inputs, thus it's only JavaScript types. QueryBuilder is database agnostic.

What is the problem with typing your filter "integer" ? The output will be the same.

**Comment by naveendb92** [comment]
I agree with your point. And I can do the conversion. 

But the JSON that's gets created from **$('#builder').queryBuilder('getRules');** will be used to store back in DB and has to be stored with the **Original data type** e.g: (bigint or binary) and not with the **converted data type** e.g: (integer or double).

**Comment by mistic100** [comment]
You can also store your custom type in the `data` field http://querybuilder.js.org/#filters

**Comment by naveendb92** [comment]
Yeah. Even this sounds good. Thank you **!!**

**Comment by naveendb92** [comment]
Yeah. Even this sounds good. Thank you **!!**
