### ISSUE TITLE
How to define default value for empty array select

### ISSUE THREAD

**Issue by CZechBoY** [mistic100/jQuery-QueryBuilder#543]
Hi,
how can I define default value if the value is empty array?
```js
$qb.queryBuilder({
    operators: [{
        type: 'approve',
        nb_inputs: 1,
        apply_to: 'select',
        multiple: true
    }],
    filters: [{
        id: 'abc',
        label: 'Abc',
        input: 'select',
        operators: ['approve'],
        default_value: 'all',
        values: {all: 'All', 5: 'a', 10: 'b', 12: 'c'}
    }]
});
```
And json rules:
```js
{
    "id": "abc",
    "operator": "approve",
    "value": []
}
```

It does not select the value "All" :-(

Is it possible somehow?
Thanks.

**Comment by mistic100** [comment]
@CZechBoY talks about `setRules` method, not the user input.

I will plan it.

**Comment by CZechBoY** [comment]
@mistic100 yes, I'm setting values for queryBuilder with setRules method.

Thanks.

**Comment by mistic100** [comment]
@CZechBoY will be in the next version

You will have to remove the `value` property or set it to `undefined` while calling `setRules` in order to use the `default_value`. An empty array will not work.
