### ISSUE TITLE
Value in json is string, but filter type is number

### ISSUE THREAD

**Issue by CZechBoY** [mistic100/jQuery-QueryBuilder#544]
Hi,
I have this queryBuilder
```js
$qb.queryBuilder({
operators: [{
                    type: 'create',
                    nb_inputs: 1,
                    apply_to: 'select'
                }],
filters: [{
                    id: 'abc',
                    label: 'abc',
                    input: 'select',
                    type: 'integer',
                    operators: ['create'],
                    values: [1,2,3,4,5,6]
                }]
});
```
but in exported json the value for filter is always string (quoted number).

Is there any option to change that?

Thanks.

**Comment by jvincilione** [comment]
I'm pretty sure SQL doesn't care if it's a string or an int (I know mysql doesn't for sure). Are you running into an issue?

**Comment by mistic100** [comment]
I never seen the interest in having the good type in the JSON output, usually you have a backend parser that translate it to a POJO (or same thing in other languages) and do not to worry about types.

But it could be done.

**Comment by CZechBoY** [comment]
Yes, I hotfixed it with explicitly casting to integer. But it would be nice to have correct type in javascript too :-)

Thank you.

ps. I do not use it for sql filter of course. I use it as configurator and then save json to database and other service reads it.
