### ISSUE TITLE
How to get value of filter in afterUpdate

### ISSUE THREAD

**Issue by CZechBoY** [mistic100/jQuery-QueryBuilder#545]
Hi,
I would like to change `<select`> to jquery autocomplete plugin.
I somehow replaced the `<input>` (yes, I changed select to integer) but I do not know how to get rule value in `afterUpdate` event. `rule.value` is always undefined or empty string "".

How can I do it?
Thanks.

**Comment by mistic100** [comment]
Show your code !

**Comment by CZechBoY** [comment]
ok then, it is same as always...

```js
var $qb = $(...).queryBuilder({
    operators: [{
                        type: 'ip_on_list',
                        nb_inputs: 1,
                        apply_to: 'number'
                    }],
                filters: [{
                    id: 'ip',
                    label: 'ip',
                    type: 'integer',
                    operators: [
                        'ip_on_list'
                    ]
                }]
});

$qb.on('afterUpdateRuleOperator.queryBuilder.filter', function (e, rule) {
                var $ruleValueContainer = rule.$el.find('.rule-value-container');
                var $ruleValueSelect = $ruleValueContainer.find('[name="' + $ruleValueContainer.closest('li.rule-container').prop('id') + '_value_0"]');

                var value = undefined;  // idk
                makeAutocomplete($ruleValueSelect, value);
});

**Comment by mistic100** [comment]
The workflow of building a rule is as follow : init filter -> init operator -> init input.
Hence when the operator was just selected, there is not input yet, so no value.

As I don't know what you want to achieve I'm afraid I cannot help you more. I suggest you look at the other events available, put some break points to see the execution order.

**Comment by CZechBoY** [comment]
I want to get value when I'm filling queryBuilder with saved json via setRules.

**Comment by mistic100** [comment]
Even tough I now this library perfectly I have absolutely no idea what you want.
Imagine you go to the doctor and just say "I am hurt", do you think he will be able to help you ?

For your previous message here is want I can answer :
```js
$('#builder').queryBuilder('setRules', rules');
rules = rules; // here you have your values
```

But it's pretty stupid right ?

**Comment by CZechBoY** [comment]
Yes, but how do I get the value for the rule? That is not in any answer. And that is the main problem - I do not know how to get value of every rule. As stated in first comment - I want to create autocomplete input with value from setRules json.
Now I know how to replace input with autocomplete but I do not know how to get value for that rule.

**Comment by mistic100** [comment]
So the autocomplete is to be applied on the value field ? If so why did you went to "afterUpdateRule**OPERATOR**" ? This is what made your question totally unclear.

So the best way is to use an jQuery autocomplete, because that way you just have to use `plugin` and `plugin_config` http://querybuilder.js.org/#filters

```js
{
                    id: 'ip',
                    label: 'ip',
                    type: 'integer',
                    operators: [
                        'ip_on_list'
                    ],
                    plugin: 'autocomplete',
                    plugin_config: { /* the config of the autocomplete */ }
}
```

**Comment by CZechBoY** [comment]
And which plugin is that? I have my own and I want to use that :-)
idk which type of filter should be, but I want there single integer value (no multiple values).
`afterUpdateRuleOperator` - because after editing operator I create the autocomplete input, `afterUpdateRuleValue` is too late because the value is updated by that autocomplete.
Is it clearer now?

**Comment by mistic100** [comment]
try google, there are plenty of good plugins.

If you want your own non jquery plugin, init it on the "afterCreateRuleInput" event, and use "afterUpdateRuleValue" to sync it (update the GUI went the builder populates the value).

**Comment by CZechBoY** [comment]
ok, and how to get the value in that event?

**Comment by CZechBoY** [comment]
OK, I tried `afterCreateRuleInput` event, but the value is always `undefined`.

```js
$qb.on('afterCreateRuleInput.queryBuilder.filter', function (e, rule) {
    console.log(rule.value); // undefined
});

**Comment by mistic100** [comment]
Yes, after create input is exactly what it means : just after the input creation (empty). If you need the value, the other event is the way to go.

**Comment by CZechBoY** [comment]
Ok, I will use `afterUpdateRuleValue`.

Thanks for support!
