### ISSUE TITLE
How to call a jquery function on the textbox input 

### ISSUE THREAD

**Issue by maverick14** [mistic100/jQuery-QueryBuilder#546]
Hi,
When the input textbox got generated after the selection from select box, need to call a jquery function on that textbox.

How to get it done ??

Thanks in advance..

**Comment by mistic100** [comment]
Is this "function" a jquery plugin ? Then use the `plugin` property of the filter.

Otherwise use events :
```js
builderElt.on('afterCreateRuleInput.queryBuilder', function(e, rule) {
  // apply on rule.$el
});
```

**Comment by maverick14** [comment]
NO the function is not jquery plugin, it is a different function that will do some operation in textbox

**Comment by WilliamStam** [comment]
would suggest you wrap your function inside a jquery "plugin" etc (not sure if theres another way?. 

https://github.com/mistic100/jQuery-QueryBuilder/issues/553

check the post right above the "closed" (at the end) for a basic "plugin"
