### ISSUE TITLE
API Documentation: 'getRuleFilterTemplate' should be 'getRuleFilterSelect'

### ISSUE THREAD

**Issue by rachelbrickey** [mistic100/jQuery-QueryBuilder#548]
I created a new plugin called "condition-ids" which injects an element from rule.data into the html for the filter. The following code snippet didn't work until I changed 'getRuleFilterTemplate' to 'getRuleFilterSelect'. 

```
$("#my-query-builder").queryBuilder.define("condition-ids", function () {
    this.on("getRuleFilterTemplate.filter", (h, rule) => {
        if (rule !== undefined && rule.data !== undefined) {
            var $h = $(h.value);
            $h.attr("data-condition-id", rule.data.conditionid);
            h.value = $h.prop("outerHTML");
        }
    });
});
```

Please update the API documentation to show that 'changer:getRuleFilterSelect' is the correct name of the changer triggered by 'createRuleFilters', not 'changer:getRuleFilterTemplate'.

http://querybuilder.js.org/api/QueryBuilder.html#.event:changer:getRuleFilterTemplate

**Comment by mistic100** [comment]
Thank you, the generated doc will be update with the next release.
