### ISSUE TITLE
Invalid input "number"

### ISSUE THREAD

**Issue by Matthewsre** [mistic100/jQuery-QueryBuilder#549]
```
                var dayCountFilter = [
                {
                    id: 'days',
                    label: 'Days',
                    input: 'number',
                    type: 'integer',
                    operators: ['equal']
                }];
```

When trying to use this filter, I get the following error:

> Invalid input "number"

According to the docs, this is a valid value. I do not see it being used in the examples index page.

**Comment by mistic100** [comment]
You probably need to update the lib http://querybuilder.js.org/changelog.html#6003397

**Comment by Matthewsre** [comment]
Yup, mistake on my part. Wrong version was pulled down (2.1). This has been a great project to work with, thank you for all of your effort on this.
