### ISSUE TITLE
Multiple Select Failed with no error

### ISSUE THREAD

**Issue by lpabcdefgh** [mistic100/jQuery-QueryBuilder#550]
Hello there,

My query builder has got only 1 select, in which there are 3 items.  For each item, they can use operators(begin with, not begin with, equals, not equals...etc).  In the initiator, I have specified that multiple: false.

However, the user can still add multiple items.  For example, after adding 'item 1 equals to value1', they can still add item 1 equals to anothervalue'.  I can't figure out a way to prevent this, not so sure if this is a bug or whether if I did something wrong.  Below is part of my init.

```js
filters: [{
            id: 'subject',
            label: 'SUBJECT',
            type: 'string',
            multiple: false,
            operators: ['equal', 'not_equal', 'begins_with', 'not_begins_with', 'contains', 'not_contains'],
        }, {
            id: 'class',
            label: 'CLASS',
            type: 'string',
            multiple: false,
            operators: ['equal', 'not_equal', 'begins_with', 'not_begins_with', 'contains', 'not_contains'],
        }, {
            id: 'name',
            label: 'NAME',
            type: 'string',
            multiple: false,
            operators: ['equal', 'not_equal', 'begins_with', 'not_begins_with', 'contains', 'not_contains'],
        }],
```

Best regards,
Shaun

**Comment by mistic100** [comment]
You misunderstood the meaning of "multiple" : it only controls the multiplicity of the select absolutely not the unicity of the filter itself.

Whan you need is the Unique Filters plugin http://querybuilder.js.org/plugins.html#unique-filter

**Comment by lpabcdefgh** [comment]
Hello Mistic100,

Thanks for the prompt reply, appreciated!  Thanks for clearing that up for me, and sorry for submitting the issue without fully understanding it.

I'll use that plugin to sort it out then.  Thanks a lot!

Best regards,
Shaun
