### ISSUE TITLE
Help - How to output as condition builder?

### ISSUE THREAD

**Issue by yarafatin** [mistic100/jQuery-QueryBuilder#552]
Is there an existing plugin that will output querybuilder rules as a simple AND/OR expression like - 
((Firstname = ddd) AND (Firstname = ffff AND (Firstname = dd OR Firstname = ff)))?
The output I expect is similar to Knockoutjs query builder - https://kindohm.github.io/knockout-query-builder/

**Comment by mistic100** [comment]
Isn't that SQL ? http://querybuilder.js.org/plugins.html#sql-support
