### ISSUE TITLE
[suggestion/help] Selectbox that allows normal text overwrite

### ISSUE THREAD

**Issue by WilliamStam** [mistic100/jQuery-QueryBuilder#553]
first off sorry for opening an "issue" with the Q, wasnt sure where else to really ask it. 

the desired result is when you select for instance "equals" you get a selectbox. but to also include a text box for "custom" values. like in my system i have a few cases where i need to do something like where `categoryID = '1'` (select box) for a category or a user can overwrite it to be `category = '@category' ` (value entered into text box)

since im using composer to keep all my libraries updated (vendors) im reluctant to make a plugin to add to the `\vendor\mistic100\jquery-querybuilder\src\plugins` folder.

so i think what i need is a "jquery plugin"

````
(function( $ ) {
	$.fn.selectWithValue = function() {
		this.each(function() {
			console.log(arguments);
		});
		return this;
	}
}( jQuery ));
````

how do i get the values for the select box to be passed through to the 'plugin' at this point? (values) as well as the "default value"

````
{
		"id": "categoryIDs",
		"label": "Category (Select)",
		"type": "string",
		"input": "text",
		"plugin": "selectWithValue",
		"plugin_config": [],
		"values": [
                   {
			"1": "Announcements"
		    }, {
			"2": "News"
		    }
                ],
		"operators": ["equal", "not_equal"]
	},
````
so far it only looks like i get the callee from arguments. 

the type will have to be string cause the selectbox will return an ID but the textbox needs to return a string etc. if i can get the "data" passed to the plugin im sure i can write something up for it but at this point i cant seem to get that to work :( (its a monday aswell, so good chance im just overlooking something small - sorry)

**Comment by mistic100** [comment]
Hello,

First of all you can totally make a standalone QueryBuilder plugin, see the "Standalone plugin" section http://querybuilder.js.org/dev/plugins.html

in your plugin "this" is the input you bind the plugin to, you can do `$(this).closest('.rule-container').data('queryBuilderModel')` to get the Rule object

**Comment by WilliamStam** [comment]
this makes me soo happy! will close when i get it to work. thank you!

**Comment by WilliamStam** [comment]
quick note aswell:

`QueryBuilder.define('my_plugin', function(options) {` becomes `$.fn.queryBuilder.define('my_plugin', function(options) {` 

the caps got me a bit since i just added the `$.fn` in. QueryBuilder and queryBuilder

**Comment by WilliamStam** [comment]
made a jsbin. supposed to be a blank plugin. am i n00bing out again?

https://jsbin.com/kadevodare/edit?js,console,output

basicaly 

````
Uncaught TypeError: $inputs[filter.plugin] is not a function
    at QueryBuilder.createRuleInput (_javascript.4828284828.js:34852)
    at QueryBuilder.updateRuleFilter (_javascript.4828284828.js:34882)
    at Model.update (_javascript.4828284828.js:34460)
    at Model.dispatch (_javascript.4828284828.js:5206)
    at Model.elemData.handle (_javascript.4828284828.js:5014)
    at Object.trigger (_javascript.4828284828.js:8201)
    at jQuery.fn.init.triggerHandler (_javascript.4828284828.js:8275)
    at Model.trigger (_javascript.4828284828.js:36771)
    at Rule.set [as filter] (_javascript.4828284828.js:36735)
    at HTMLSelectElement.<anonymous> (_javascript.4828284828.js:34387)
QueryBuilder.createRuleInput @ _javascript.4828284828.js:34852
QueryBuilder.updateRuleFilter @ _javascript.4828284828.js:34882
update @ _javascript.4828284828.js:34460
dispatch @ _javascript.4828284828.js:5206
elemData.handle @ _javascript.4828284828.js:5014
trigger @ _javascript.4828284828.js:8201
triggerHandler @ _javascript.4828284828.js:8275
trigger @ _javascript.4828284828.js:36771
set @ _javascript.4828284828.js:36735
(anonymous) @ _javascript.4828284828.js:34387
dispatch @ _javascript.4828284828.js:5206
elemData.handle @ _javascript.4828284828.js:5014

````

it has issues with this

````
if (filter.plugin) {
        $inputs[filter.plugin](filter.plugin_config || {});
    }
````

heres the "plugin"

````

$.fn.queryBuilder.define('selectOrValue', function(options) {

	var Selectors = $.fn.queryBuilder.selectors;

	// init selectpicker
	this.on('afterCreateRuleFilters', function(e, rule) {

	});

	this.on('afterCreateRuleOperators', function(e, rule) {

	});

	// update selectpicker on change
	this.on('afterUpdateRuleFilter', function(e, rule) {

	});

	this.on('afterUpdateRuleOperator', function(e, rule) {

	});

	this.on('beforeDeleteRule', function(e, rule) {

	});
}, {

});
````

**Comment by mistic100** [comment]
The 'plugin' filter property is NOT a QueryBuilder plugin, it is just a jQuery plugin. QueryBuilder plugins are global to the whole builder, jQuery plugins are only for the value input/select.

**Comment by WilliamStam** [comment]
removing it from  
````
$('#builder').queryBuilder({
  plugins: ['bt-tooltip-errors'],
```` 
made no difference. still same error

**Comment by mistic100** [comment]
No, no, your problem  is `plugin:'selectOrValue',`
selectOrValue is not a jQuery plugin, it is a QueryBuilder plugin

**Comment by WilliamStam** [comment]
makes sense.. so querybuilder plugins cant be cherry picked for filters. like setting an input to selectOrValue wont work. selectOrValue needs to overwrite all selects etc

**Comment by mistic100** [comment]
But your can ass your own property to the filter definition (like `enableMySelect: true`), and the QueryBuilder will do something when seing this property.

This is how filter description work for example https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/filter-description/plugin.js (the `getFilterDescription` method reads the new `description` property)

**Comment by WilliamStam** [comment]
we have success!

https://jsfiddle.net/42t6chv6/



````
/* INFO: usage is to simply add plugin:'selectOrValue', to the filters of the querybuilder */
(function( $ ) {
	$.fn.selectOrValue = function() {
		this.each(function() {
			var $this = $(this);
			var $container = $this.closest('.rule-container')
			var _data = $container.data('queryBuilderModel').__;
			/* INFO: the _data.value isnt available yet at this point so we use a settimeout to delay it a bit */
			setTimeout(function(){
				$this.hide();
				$selectBox = $("<select/>");
				$selectBox.attr("class","form-control")
				$selectBox.append($('<optgroup/>', {label: "Options"}).html($.map(_data.filter.values, function(txt,val){
					return $('<option/>', {text: txt, value:val});
				})));
				$selectBox.append($('<option/>', {text: "Custom", value:''}));

				$selectBox.on("change",function(){
					var val =$(this).val();
					if (val==''){
						$this.show();
					} else {
						$this.val(val).hide();
					}
				})


				$selectBox.val(_data.value)
				$this.before($selectBox);

				$this.on("change",function(){
					var val = $this.val();
					if ( $("option[value='" + val + "']",$selectBox).val() !== undefined) {
						$selectBox.val($this.val())
					} else {
						$selectBox.val("")
						$this.show();
					}

				})
			}, 50)
			/* INFO: the select shows unless the value doesnt exist in the select in which case it shows the text box next to the selectbox */
		});
		return this;
	}
}( jQuery ));
````
