### ISSUE TITLE
integrating jQuery-Builder under angular2/4

### ISSUE THREAD

**Issue by davidnomo** [mistic100/jQuery-QueryBuilder#555]
I am trying integrate jqueryBuilder under angular2/4 but I got an error.

ERROR TypeError: __WEBPACK_IMPORTED_MODULE_1_jquery__(...).queryBuilder is not a function

Here is what i have done 
jQuery & jQuery-QueryBuilder imported properly in package.json
Angular-cli.json has the jQuery.min.js call in script section
Individual component has jquery and queryBuilder imports 
jQuery type definition file has jqueryBuilder definition in jQuery interface section i.e.     queryBuilder(options?: any, callback?: Function):JQuery;

is there anyone who has implemented jQuery-builder under angular2/4 properly and right?

Any suggestion most welcome

**Comment by mistic100** [comment]
Any discusion about Angular is in  #141

**Comment by OpTiCz27** [comment]
Can we start a seperate thread for Angular 2/4? Angular 1 is a different beast.

**Comment by mistic100** [comment]
If you don't have anything new, please no. If someone come with an (almost) working implementation (for any framework) we can start discussing about it, but I don't want to multiply the "how to ?" issues. Thank you.
