### ISSUE TITLE
[BUG?] issues with 'change.querybuilder' event

### ISSUE THREAD

**Issue by WilliamStam** [mistic100/jQuery-QueryBuilder#556]
https://jsfiddle.net/42t6chv6/2/

add rules etc to see the event fired. as soon as you click [x delete] on any rule or group - it doesnt fire the change event. 

is this a bug? 

i tried adding the 'afterDeleteRule.queryBuilder' to it aswell, but it doesnt fire the event either 
`.on("change.queryBuilder afterDeleteRule.queryBuilder", function() {`

------------------------

changing the operator fires the `change.queryBuilder` event twice.

**Comment by mistic100** [comment]
"change.queryBuilder" does not exist yes #498

I tried your fiddle with "afterDeleteRule.queryBuilder" and it works very well

**Comment by WilliamStam** [comment]
sorry was editing the comment. so things might get wonky with this....

if the event doesnt exist yet then what event is being fired to output "changed" in the log area?

https://jsfiddle.net/42t6chv6/3/

#confused

**Comment by WilliamStam** [comment]
latest fiddle https://jsfiddle.net/42t6chv6/5/ `afterDeleteRule.queryBuilder` now seems to work, it didnt earlier - i think, was battling with it for about an hour -  :/ some days code can be really infuriating.

still no idea where `change.queryBuilder` comes from if its not added yet. and the operator select fires "it" twice

**Comment by mistic100** [comment]
No it's not a WIP.

This event is just the input/select events bubbling up in the DOM, it is not triggered by the builder but by the browser.

**Comment by WilliamStam** [comment]
so best way to do a "change" would be something like
````
.on("afterAddRule.queryBuilder afterAddGroup.queryBuilder afterApplyGroupFlags.queryBuilder afterApplyRuleFlags.queryBuilder afterClear.queryBuilder afterCreateRuleFilters.queryBuilder afterCreateRuleInput.queryBuilder afterCreateRuleOperators.queryBuilder  afterDeleteGroup.queryBuilder afterDeleteRule.queryBuilder afterInit.queryBuilder afterReset.queryBuilder afterSetRules.queryBuilder afterUpdateGroupCondition.queryBuilder afterUpdateRuleFilter.queryBuilder afterUpdateRuleOperator.queryBuilder afterUpdateRuleValue.queryBuilder", function(event) {
````
 (i just took all the api "after" events)

**Comment by WilliamStam** [comment]
so reason for all my "issues" this is what im using queryBuilder for. basically to build the where string for "dummies". working great! (thank you for your patience, help and most of all for having developed this awesome plugin!)


![image](https://user-images.githubusercontent.com/182800/29449729-2aab23b6-83fc-11e7-8ef4-1fa4ff3b1d92.png)

**Comment by mistic100** [comment]
nice, always a pleasure to know how it is integrated.

**Comment by nikataus** [comment]
So what William suggests can be used until global "change" event has been implemented in 2.4.5 release?

**Comment by mistic100** [comment]
of course, this is only existing events

**Comment by nikataus** [comment]
Thanks, just confirming :),

**Comment by vmitchell** [comment]
Hey Damien,
I think there is no 'change' event fired when deleting a rule. There is a separate event for deleting a rule of course, but still 🔨
