### ISSUE TITLE
Uncaught TypeError: Cannot set property 'extendext' of undefined

### ISSUE THREAD

**Issue by ravidannani** [mistic100/jQuery-QueryBuilder#557]
Hi,

 I was stuck up with this issue from last 2 days and not sure how to resolve this issue.

 I had implemented the query builder for angular2 application by following the below reference link.
https://embed.plnkr.co/13rGVC/. But it was shown below error in console window.

![jqueryextendextissue](https://user-images.githubusercontent.com/27359086/29439317-81fc7c18-83da-11e7-8c2f-bb7e51815920.png)

Even though it was working properly and able to generate JSON expression by calling getRules., But unable to generate SQL expression by calling 'getSQL' . I thought this is because of the above issue and started searching online but could not get much information.

Below are the more information related to this issue.
[1].  Executing the below method from my component file
  getSQLStatement() {
    var result = $('#builder').queryBuilder('getSQL');
    console.debug(result)
    if (!jQuery.isEmptyObject(result)) {
      alert(JSON.stringify(result, null, 2));
    }
    return result;
  }
  
[2]. From there, referencing the querybuilder.min.js. Attached is the file

[querybuilder.min.txt](https://github.com/mistic100/jQuery-QueryBuilder/files/1232994/querybuilder.min.txt)

Note - I have tried to use query builder standalone version instead of querybuilder.min.js but no luck.

Please let me know if I missed anything or need more information.

**Comment by mistic100** [comment]
As the documentation says you either need to include "doT.js" and "jQuery.extendext.js" or use the standalone version.

The error you mention is not present in your plunkr.

And I have not problem making "getSQL" or "getESBool" methods working either.

So want exactly is your problem ?

**Comment by ravidannani** [comment]
Thank you for your response.

I also imported both dot and jQuery.extendext and imported in my type script file in the below way. But still showing the same issue. 

import doT from 'dot/doT';
import jQueryExtendext from 'jquery-extendext';

The plunkr link is working with the standalone version. But for me, it is throwing issues.

Is there any way to come up from this issue? Please let me know.

**Comment by ravidannani** [comment]
FYI,, After calling the getSQL, getting the below error in type script

![image](https://user-images.githubusercontent.com/27359086/29454855-64052a32-842c-11e7-8a5f-b03c1835334d.png)

**Comment by ravidannani** [comment]
Hi,

I am still having the query builder issue. Please check the error in below. 

![image](https://user-images.githubusercontent.com/27359086/30631106-cf0dacda-9e00-11e7-94f4-5a406bc8e2c5.png)

I am getting this issue while calling 'getSQL' or 'getMongo'. It is working for 'getRules'

Could you please please please let me know the issue cause and take me to forward..

**Comment by hassantahir01** [comment]
Hi @tobysmith61 
I faced the same issue and I resolved by including 'query-builder.standalone.js'  file instead of 'query-builder.js' .Hope it may help other
