### ISSUE TITLE
Disable operator select box for a particular filter

### ISSUE THREAD

**Issue by preraksola** [mistic100/jQuery-QueryBuilder#558]
For filters with `type = boolean` I need to disable the operator dropdown box. Is there a way I can define filter level flags? In the docs, I could only find rule level flags.

**Comment by mistic100** [comment]
You can configure flags at filter level. By if you leave only one operator available fro booleans, it will, de-factor, be readonly.

```js
builderElmt.queryBuilder({
  filters: [
    {
      id: 'active',
      type: 'boolean',
      operators: ['equal']
    }
  ]
});
```

**Comment by preraksola** [comment]
I tried that, but does not work. Here's the fiddle for it: https://jsfiddle.net/prerak6962/pf52oqbk/2/
The `Bool test` filter has only one operator.

**Comment by mistic100** [comment]
What about using the last version ? (2.4.4)
https://jsfiddle.net/pf52oqbk/3/

**Comment by preraksola** [comment]
Yes, it worked with the 2.4.3 version.
(2.4.4 is not available on jsdelivr, so I tried with the 2.4.3)

Thanks 👍

**Comment by mistic100** [comment]
Huh ? https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/

**Comment by preraksola** [comment]
Over here: http://www.jsdelivr.com/projects/jquery.query-builder

![screen shot 2017-08-22 at 10 13 49 am](https://user-images.githubusercontent.com/8655814/29555387-ce7d2dda-8722-11e7-937f-b19c341f515d.png)

**Comment by mistic100** [comment]
jsDelivr changed their behavior a while ago, the right link is the one I gave. And it's also what is documented on their homepage http://www.jsdelivr.com/

**Comment by MartinKolarik** [comment]
@mistic100 yes, that's right. Our website will be updated within two weeks to list npm packages too.

**Comment by mistic100** [comment]
I updated the badge link in the readme.

**Comment by preraksola** [comment]
Okay, my bad. I directly picked up the version from the landing page.
Thanks for the info.
