### ISSUE TITLE
Change the operator name

### ISSUE THREAD

**Issue by carthikn** [mistic100/jQuery-QueryBuilder#559]
Hi,
I want to change the operator in and not_in to include and Exclude.
The operator operation should be same as in and not_in but only thing is to rename it and display it as include and exclude,

Thanks in advance.

**Comment by mistic100** [comment]
http://querybuilder.js.org/#usage -> `lang`

```js
builderElmt.queryBuilder({
  lang: {
    operators: {
      not_in: 'exclude'
    }
  }
});
```
