### ISSUE TITLE
how to use this in laravel 5.4

### ISSUE THREAD

**Issue by amirgee007** [mistic100/jQuery-QueryBuilder#560]
hi i want to add this plugin in my laravel app how can do this?

**Comment by mistic100** [comment]
Sorry this is not the place to ask for frameworks implementation.

Try on Stackoverflow where you will most likely find Laravel users.

**Comment by timgws** [comment]
@amirgee007 see https://github.com/timgws/QueryBuilderParser

**Comment by mistic100** [comment]
Yep, I forgot this one, it's even listed on the website http://querybuilder.js.org/index.html#backends

**Comment by amirgee007** [comment]
thanks
