### ISSUE TITLE
plugin: 'datetimepicker' issue..

### ISSUE THREAD

**Issue by lsh486love** [mistic100/jQuery-QueryBuilder#562]
I create the option as follow: 

```
var option = {

    		plugins: [
      	    	    'bt-tooltip-errors',
      	    	    'not-group'
      	    	  ],
      	    	  display_errors: true, 
      	    	  filters: [{
    	    	    id: 'Time',
      	    	    label: 'DateTime',
      	    	    type: 'datetime',
      	    	    plugin: 'datetimepicker',
      	    	    plugin_config: {
      	    	    	format: 'YYYY-MM-DD HH:MM'
      	    	    },
      	    	    operators: ['less', 'less_or_equal', 'greater', 'greater_or_equal']
      	    	  }]
    			
      	    	};

$('#builder').queryBuilder(option);
```

But when I save the search conditions, only  YYYY/MM/DD is saved. 
Here is the alert message. 

![filter](https://user-images.githubusercontent.com/863747/29957206-1c01067e-8f27-11e7-8ee6-a4fbcea0f198.png)

in spite of `type: 'datetime',` ...  

Please help me..

**Comment by lsh486love** [comment]
I need time value with date..

**Comment by lsh486love** [comment]
And.. this is a screenshot on chrome web debugger.
![f2](https://user-images.githubusercontent.com/863747/29958297-f9a446bc-8f2c-11e7-8386-83fbc9c25654.png)

**Comment by lsh486love** [comment]
Ah.. the problem doesn't seem querybuilder, but datetimepicker..

I use bootstrap datetimepicker when I choose the date and time on the picker window and click save button, the condition is empty. 
But when I entered some text like 'abc', the above error is not occurred. 

So I think I choose the date and time, the input text should be recognized before calling 'getmongo' function. 

Do you have any tip? would this be datetimepicker issue?

**Comment by mistic100** [comment]
Please create a fiddle.

And your format is invalid, it should be "YYYY-MM-DD HH:mm" http://momentjs.com/docs/#/displaying/format/

**Comment by lsh486love** [comment]
ohh!! I found the same issue and you might fix the problem by adding filter. 

issue number : #176 
I looked what you wrote. but... how can I add listen filter for datetimepicker??? 

===================================================
When using external plugins on values is often appear that they don't fire the standard "change" event on the input, thus QueryBuilder model is not updated and validation fails.

Current solution is to manually bridge events see #176

A nicer solution would be to tell QueryBuilder to listen to "change" and a configurable list of events.
For Bootstrap DateTimePicker it would be listen: 'dp.change'
===================================================

**Comment by lsh486love** [comment]
Oh.. I got it!! i fixed the problem!!! 
Thank you so much. 

`input_event: 'dp.change' `

**Comment by mistic100** [comment]
Did you fully read this ticket ? the solution is at the very bottom
