### ISSUE TITLE
datetime picker with optional time

### ISSUE THREAD

**Issue by carvemerson** [mistic100/jQuery-QueryBuilder#566]
Is it possible use a datetime picker with the time field optional?

![screenshot from 2017-09-14 17-53-20](https://user-images.githubusercontent.com/6718864/30455268-a890d1f2-9975-11e7-81d1-bf4687705134.png)

I have tried to use a custom validation using a callback function, but when the datetime field is not completely filled, the value passed to the callback function is empty. 
Part of the code below:

```
{
    type: 'datetime',
    input: 'text',
    validation: {
         callback: function(value, rules) {
               console.log(value); // print ""
               return true;
         }
     }
 }
```

**Comment by mistic100** [comment]
Please setup a live demo

**Comment by carvemerson** [comment]
I had solved my problem using the default value.

**Comment by sahilkatia1** [comment]
@carvemerson  Can you please share your code?
