### ISSUE TITLE
how to disable add group from entire queryBuilder

### ISSUE THREAD

**Issue by ramdrupal7** [mistic100/jQuery-QueryBuilder#567]
how to disable add group from entire queryBuilder
but i init this 

  var options = {
	    allow_empty: true, flags: { no_add_group: true  }};
`$('#builder').queryBuilder(options);

But i think this is not working help me out  on this

**Comment by mistic100** [comment]
```js
$builderEl.queryBuilder('setRules', {
  flags: {
    no_add_group: true
  }
});
```
