### ISSUE TITLE
Missing information about namespace in event documentation

### ISSUE THREAD

**Issue by kgonia** [mistic100/jQuery-QueryBuilder#569]
Binding events to plugins requiring put name and namespace like this:

`this.on('name.namespace', function (translation, key, category) {
         console.log(key, translation);
 });`

but there is no information about it in documentation. Also there is no info which namespace we should use for each event. 

I had to debug code to find how to bind to translation.

**Comment by mistic100** [comment]
Please tell me how to make it clearer http://querybuilder.js.org/#events

**Comment by KrzychuJedi** [comment]
If it is self-explanatory where is information about what namespace I should use with 'translate' event? In hole section about event and in api there is no mention about 'filter.queryBuilder' namespace which should be used with this event.

Examples use namespaces but here http://querybuilder.js.org/api/QueryBuilder.html#events is no info about wich namespace use for each event.

**Comment by mistic100** [comment]
As I said **in the example** => `getGroupTemplate.queryBuilder.filter`

I understand it is confusing the wording is not the same in the generated API documentation, but for historical reasons the namespace is `filter` whish is a reserved word in jsDoc.

This is architecture which is very hard to describe in jsDoc I had to deal with it.

**Comment by mistic100** [comment]
The only thing that can be easily modified is the front page http://querybuilder.js.org/#events

**Comment by VinS101** [comment]
I also had the same issue. After spending 5 hours of trying different things, I was able to finally get afterAddGroup to fire. I had to put "afterAddGroup.queryBuilder" instead of just "afterAddGroup".

**Comment by LEarwax** [comment]
I am currently trying to get the "rulesChanged" event to fire. So far I've had zero luck. Is this the correct syntax for the event? 

`$("#builder-basic").on('rulesChanged.queryBuilder', onQueryFilterSelected);`

**Comment by dgw2jr** [comment]
> I am currently trying to get the "rulesChanged" event to fire. So far I've had zero luck. Is this the correct syntax for the event?
> 
> `$("#builder-basic").on('rulesChanged.queryBuilder', onQueryFilterSelected);`

I had no luck with 'groupToJson.queryBuilder' event myself. After stepping through the code I found the library was publishing this event as 'groupToJson.queryBuilder.filter'. When I listen for that event, my delegate was called.
