### ISSUE TITLE
Translate event - wrong params

### ISSUE THREAD

**Issue by KrzychuJedi** [mistic100/jQuery-QueryBuilder#570]
In version 2.4.4 wrong params are send to 'translate.filter.queryBuilder' event. 

translation param is missing, 
instead of translation there is a key
instead of key there is as category

IMO problem is result of splice array in 'query-builder.standalone.js' in change function line 481 where slice is done.

**Comment by mistic100** [comment]
The translation is in `e.value` as explained here http://querybuilder.js.org/#events

**Comment by KrzychuJedi** [comment]
I thought that function will match params as explained here http://querybuilder.js.org/api/QueryBuilder.html#.event:changer:translate ;)
