### ISSUE TITLE
How to customize the validation of the rule value?

### ISSUE THREAD

**Issue by francoispluchino** [mistic100/jQuery-QueryBuilder#571]
For `in` and `not_in` operators, it is not possible to define a list of values for `number` inputs with the standard implementation.

By default, the field is an HTML5 input with a number type, so it is impossible to write a list of numbers separated by `;` (for example), and even if we create a plugin to modify the type of the input field by a text with the events `getRuleInput` and `afterUpdateRuleOperator`, the interface works correctly, but the validation does not pass. Therefore, calling the `getRules ()` method returns the `null` value, and not the rule.

How can I customize the rule validation in a plugin?

Because I can not listen the events [changer:validate](http://querybuilder.js.org/api/QueryBuilder.html#.event:changer:validate) and [changer:validateValue](http://querybuilder.js.org/api/QueryBuilder.html#.event:changer:validateValue):

```js
this.on('getRuleInput.filter', function(h, rule, name) {
    // triggered
});

this.on('afterUpdateRuleOperator.filter', function(h, rule) {
    // triggered
});

this.on('changer:validateValue', function(h, result, value, rule) {
    // not triggered
});

this.on('changer:validate', function(h, valid) {
    // not triggered
});
```

**Comment by mistic100** [comment]
You do not anything of that, use :

```js
type: 'integer',
input: 'text',
value_separator: ';'
```

**Comment by mistic100** [comment]
Your events are incorrect: it's `validateValue.filter` not `changer:validateValue`, it's explained in the doc http://querybuilder.js.org/index.html#events

**Comment by francoispluchino** [comment]
Indeed, it's more simple. Thanks for the events info, it's a mistake on my part, I have tested with `changer:validate.filter` ...

**Comment by francoispluchino** [comment]
Thank you for your quickly response!
