### ISSUE TITLE
I need clear example code for bootstrap typehead or any other autocomplete to use in query builder .

### ISSUE THREAD

**Issue by Maninandha** [mistic100/jQuery-QueryBuilder#572]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [jsDelivr](https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/) and [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by Maninandha** [comment]
I need auto complete search text box should use in jquery query builder
..
I am using angular 2 with jquery query builder ...

**Comment by mistic100** [comment]
I am not here to code for others.
Read the doc and the examples about plugins http://querybuilder.js.org/demo.html#plugins
Then if you cannot get it working, put your code online (jsfiddle) so I can tell you what is wrong.
