### ISSUE TITLE
This may work with older versions of JQuery than the docs say it does

### ISSUE THREAD

**Issue by samlobel** [mistic100/jQuery-QueryBuilder#574]
Are we sure that this only works with Jquery 1.10+? I'm running it with 1.7 and its working well. If that's the case, it would be great to have the docs represent this.

**Comment by mistic100** [comment]
it's not working with 1.9 because of unintended behaviour. These version I so old I do not care defining a complexe dependency (<= 1.8 ; >= 1.10)
