### ISSUE TITLE
When value_seperator defined for filters, should validation.format apply to the whole value or the split values?

### ISSUE THREAD

**Issue by oller** [mistic100/jQuery-QueryBuilder#575]
Just a thought, as stated in the title, if I have the following config:

```js
        "value_separator":",",
        "operators":[  
            "equal",
            "in"
        ],
        "validation":{  
            "format":"^[0-9]{3}$",
            "messages":{
                "format": "ID must be 3 digits"
            }
        }
```

To me, I think you could make the case the `validation.format` is for each individual value, so should be applied to the field value after the `value_separator` is applied.  I may be mistaken, but this doesn't seem to be the case.  

I can fix this amend the regex to account for the separator, but it just seems i'm specifying and accounting for the `value_separator` in multiple places then, which isn't ideal.

Just thought it'd be worth getting your thoughts on this.  Love this library, there's a method or setting for pretty much every requirement I've encountered so far!

**Comment by mistic100** [comment]
I think you are mistaken, or you don't use the latest version. 

If you take the examples/index.html file and add `value_separator: ',',  operators: ['in']` to the *Identifier* filter, you will be able to enter `1234-1234-1324,1234-1234-1234` and pass the validation

**Comment by oller** [comment]
Ah yes, it seems I needed a version bump.  Exactly what I was after.  Thank you, closing.....
