### ISSUE TITLE
disable selectize plugin

### ISSUE THREAD

**Issue by sahilkatia1** [mistic100/jQuery-QueryBuilder#578]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [jsDelivr](https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/) and [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by sahilkatia1** [comment]
Hi, I am working on existing project. Developers used selectize plugin. Now we want to disable selectize and keep it as textbox which should accept the desired data-types. But I am not able to disable selectize.


`$scope.setRuleFilters = function(response, optObj) {
		$scope.currRuleFilters = [];
		console.log(response);
		$scope.ruleFilters = response;
		$.each(response, function(fi, filterObj){
			$scope.ruleAttrObject[filterObj.ui_display_name] = {};
			$scope.ruleAttrObject[filterObj.ui_display_name].isSelected = false;
			var filterItem = {};
			filterItem.id = filterObj.json_path;
			filterItem.label = filterObj.ui_display_name;
			filterItem.type = "string";
			//filterItem.plugin = 'selectize';
			filterItem.operators = ['equal', 'not_equal', 'less', 'less_or_equal', 'greater', 'greater_or_equal', 'between', 'not_between'];
			filterItem.plugin_config = {
					valueField: 'json_path',
					labelField: 'ui_display_name',
					searchField: 'ui_display_name',
					sortField: 'ui_display_name',
					create: true,
					maxItems: 1,
					plugins: ['remove_button'],
					onInitialize: function() {
						this.addOption(optObj[filterObj.json_path]);
					}
			};
			filterItem.valueSetter = function(rule, value) {
				if(value && value.id){
					rule.$el.find('.rule-value-container input')[0].selectize.addOption(value);
					rule.$el.find('.rule-value-container input')[0].selectize.setValue(value.id);
				} else if(value){
					if(!rule.$el.find('.rule-value-container input')[0].selectize.options[value]){
						var obj = {
								json_path: value,
								ui_display_name: value,
								unit:""
						}
						rule.$el.find('.rule-value-container input')[0].selectize.addOption(obj);
						rule.$el.find('.rule-value-container input')[0].selectize.setValue(obj.json_path);
					} else {
						rule.$el.find('.rule-value-container input')[0].selectize.setValue(value);
					}
				}
			};
			$scope.currRuleFilters.push(filterItem);
		});
		$scope.setquerybuilder();
	};

	$scope.setquerybuilder = function(){

		var filters = $scope.currRuleFilters;
		var rules = {
				"condition": "AND",
				"rules": [{
					"id": "core_ID",
					"field": "core_ID",
					"type": "integer",
					"input": "text",
					"operator": "in",
					"value": "1240"
				},
				{
					"id": "store_id",
					"field": "store_id",
					"type": "integer",
					"input": "text",
					"operator": "in",
					"value": "1642"
				}]
		};

		$('#qb_condition_specification').queryBuilder('destroy');

		$('#qb_condition_specification').on('afterCreateRuleInput.queryBuilder', function(e, rule) {
			console.log($scope.ruleFilters, rule.filter.id, $scope.ruleAttrObject);
			$.each($scope.ruleFilters, function(fi, filterObj){
				console.log(filterObj);
				if(filterObj.ui_display_name === rule.filter.id){
					$scope.ruleAttrObject[filterObj.ui_display_name].isSelected = true;
				}
			});
			console.log($scope.ruleAttrObject);
		});

		$('#qb_condition_specification').queryBuilder({
			sortable: true,
			filters: $scope.currRuleFilters
		});

	};`

**Comment by mistic100** [comment]
You just did by commenting out the `plugin: 'selectize'` line. So what exactly do you want ?

**Comment by sahilkatia1** [comment]
i dont want selectize. Because its drop-down with selectize. I want simple text-box which should accept the desired data-type values.

`filterItem.type = 'string';`

**Comment by mistic100** [comment]
(you added the error after I answered)

Then remove the "valueSetter" which is referencing selectize.

You should take a break to read the documentation and try to understand what you are doing.

**Comment by sahilkatia1** [comment]
If I replace selectize with input under valueSetter it still gives me an error

**Comment by mistic100** [comment]
And did you try to remove the WHOLE property ?

**Comment by sahilkatia1** [comment]
yes it didn't work. I read in the documentation

**Comment by sahilkatia1** [comment]
This is what I am trying using input for valueSetter

`	filterItem.valueSetter = function(rule, value) {
				if(value && value.id){
					rule.$el.find('.rule-value-container input')[0].input.addOption(value);
					rule.$el.find('.rule-value-container input')[0].input.setValue(value.id);
				} else if(value){
					if(!rule.$el.find('.rule-value-container input')[0].input.options[value]){
						var obj = {
								json_path: value,
								ui_display_name: value,
								unit:""
						}
						rule.$el.find('.rule-value-container input')[0].input.addOption(obj);
						rule.$el.find('.rule-value-container input')[0].input.setValue(obj.json_path);
					} else {
						rule.$el.find('.rule-value-container input')[0].input.setValue(value);
					}
				}
			};
			$scope.currRuleFilters.push(filterItem);
		});
		$scope.setquerybuilder();
	};
`

**Comment by mistic100** [comment]
I repeat **REMOVE IT** 
This option is optional and you don't need it for the basic usage.

Don't you see that your code doesn't make any sense ? "adoption" is a method of selectize, of course it doesn't work for a standard input.

**completely remove the value better**

**Comment by sahilkatia1** [comment]
Thanks. I am sorry I didn't realize that you said to completely remove I just mistook your comment.
Is there any way to update it with new version feature as AND, OR button should  disabled before adding second rule?

**Comment by sahilkatia1** [comment]
Also, now when I try to save it shows me 

![image](https://user-images.githubusercontent.com/32306163/31520785-bac6a1b4-af6c-11e7-8e5e-2b3793465ec1.png)

**Comment by mistic100** [comment]
1. I don't understand

2. It's your code that is displaying the output not the library !

Can I suggest you take some time to understand what has been done instead of directly touching everything ? This would face both your and my time. Thank you.

**Comment by sahilkatia1** [comment]
@mistic100 I am sorry for asking that question. It was bug because of my bad. I fixed that. I thought its by jquery queryBuilder. Everything is good now. Thanks. But the last thing I wanted to do is just to disable the AND OR button before adding the second rule or third...
