### ISSUE TITLE
Default operator

### ISSUE THREAD

**Issue by jftsaraiva** [mistic100/jQuery-QueryBuilder#579]
How can we define an default operator? 

By example, with the following filter:
```
{
    id: 'category',
    label: 'Category',
    type: 'integer',
    input: 'select',
    values: {
      1: 'Books',
      2: 'Movies',
      3: 'Music',
      4: 'Tools',
      5: 'Goodies',
      6: 'Clothes'
    },
    operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
  }
```

I would like to keep the order: `'equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null'` and by default I wanna select `in` operator, but is select the first operator - in this example: `equal`.

I can find `default_condition`, `default_filter`, `default_value`, ... but I can't find `default_operator` or similar. I'm missing something?

**Comment by mistic100** [comment]
I'll add it.

In the meantime you can use "afterCreateRuleOperatorSelect.queryBuilder" event and change the rule operator (I am not sure about the event name, check the doc)
