### ISSUE TITLE
Update the AND OR button

### ISSUE THREAD

**Issue by sahilkatia** [mistic100/jQuery-QueryBuilder#580]
I want to update the jquery QueryBuilder with AND OR button as I can see in the new version of it. I am using old version of it. where it is enabled even on first row of rule. I want to disable it in old version as I can't update the version of queryBuilder at this time.

**Comment by mistic100** [comment]
Do you know you can write (and edit) the first message ?

**Comment by sahilkatia** [comment]
I want to update the jquery QueryBuilder with AND OR button as I can see in the new version of it. I am using old version of it. where it is enabled even on first row of rule. I want to disable it in old version as I can't update the version of queryBuilder at this time.

**Comment by mistic100** [comment]
Wow ! You sentence is absolutely not understandable !
I have no idea what you want.

Which version are you talking about ? What update do you want ? Cannot you post a screenshot ?

**Comment by sahilkatia** [comment]
here the image

![image](https://user-images.githubusercontent.com/14021901/31623938-adcb6aba-b266-11e7-9ba1-a72c7e7ddbe0.png)

Current version in my code is 2.3.0

**Comment by mistic100** [comment]
I have very little patient right now. If you don't make any effort I will stop answering.

So this is a screenshot of 2.3.0 (you could at least update to 2.3.3 !), what do you want with that ? There is no difference with 2.4.4.

**Comment by sahilkatia** [comment]
We made so many custom changes to the code. So its hard to update it with new version.

**Comment by mistic100** [comment]
http://www.lonecpluspluscoder.com/2014/12/29/im-strongly-opposed-modifying-third-party-library-code/
This is for C++ but applies to JavaScript, modifying third party library is NEVER the right solution.

**I cannot provide help on modified code** as I don't know what you did, and of course you cannot share it because the new code is licensed by your company.

Good luck.
