### ISSUE TITLE
How to change customized input value by jquery

### ISSUE THREAD

**Issue by AllennnnTaylor** [mistic100/jQuery-QueryBuilder#582]
I use jquery changed the input value.but when I use method "getRules" I got an empty string. I can get value if I input manually.
Here is the realted code:

```js
input : function(rule,input_name){
	    	return '<input name="'+ input_name +'_owner" type="text" class="form-control"/>'+
	    	'<button style="margin-bottom:0px" type="button" onclick="getOwnerFromLdap(this)" class="btn btn-default">LDAP</button>';
	    }
```

var result = $('#builder-basic').queryBuilder('getRules');

**Comment by mistic100** [comment]
You must trigger the `change` event on the input (from your `getOwnerFromLdap` function I guess), otherwise the builder cannot know the value changed.

**Comment by AllennnnTaylor** [comment]
I read your document about the method "change( type, value ) ",the description of this method is "Triggers an event on the builder container and returns the modified value".But there is not any description about the params. I guess "type" is the event type,in this case it's 'change'. "value" is the modified value.
I use the method change to trigger "change" event but it seems not work. Am I wrong?
```js
var cdata = $('#builder-basic').queryBuilder('change',data.Email);
console.log(cdata);// result is undefined
```

**Comment by mistic100** [comment]
Sorry you misunderstood. I am tolaking about the standard DOM event, not the QueryBuilder event.

```js
$(input).trigger('change');
```

**Comment by AllennnnTaylor** [comment]
Much appreciate
