### ISSUE TITLE
Multiple selects for filters

### ISSUE THREAD

**Issue by RaphaelGauthier** [mistic100/jQuery-QueryBuilder#584]
Hi,
I would like to know if it's possible to have two Select inputs for filters, the first one containing some filter categories, and the second one containing the actual filters (which would dynamically update according to the value of the first one). Something like this :

![multiple-select](https://user-images.githubusercontent.com/9928447/32047799-6b35bce4-ba47-11e7-8a06-277533c17711.png)

I checked the different plugins but don't find one for that. I also checked the `.setFilters([force,] filters)` method but it replaces all filters by new ones, not just those of a particular rule.
Is it feasible ? Should I create my own plugin ?

**Comment by mistic100** [comment]
Hello

See #521 

The only alternative is optgroups http://querybuilder.js.org/#filters
