### ISSUE TITLE
Query builder operator change triggered to update the value.

### ISSUE THREAD

**Issue by aryanisml** [mistic100/jQuery-QueryBuilder#586]
As per latest query builder library , in 'updateRuleOperator' function triggered the 'updateRuleValue' function as in core.js file mention that 'After the operator has been updated and the input optionally re-created' need to stop updateRuleValue called, is any option to avoid the updateRuleValue in updateRuleOperator function.

As currently we are upgrading library from 2.3.3 to 2.4.3 and operator changes it again called the valueSetter function.
So want to know which is the option to stop the updateRuleValue called.

**Comment by mistic100** [comment]
This is not possible, this was done for keeping data consistent and cannot be disabled.

You should not change the operator from the valueSetter.
