### ISSUE TITLE
Re-constructing filter from text.

### ISSUE THREAD

**Issue by ravi-unifi** [mistic100/jQuery-QueryBuilder#59]
Hi, 
Is there an easy way to re-construct the sql json from the sql text ? For eg: I am using this library to construct rules and form a query text which i save in our data store. I want to be able to re-construct the filter rules given the text as input ? setRules expects the whole json to be passed and it would be convenient if we can have a way to reconstruct the filters from just plain text ?

**Comment by mistic100** [comment]
The parser relies on https://github.com/mistic100/sql-parser currently loaded via NPM in direct (#master). I'll look ahead if my pull-requests are merged into upstream or "officially" publish my fork.

**Comment by mistic100** [comment]
See demo http://mistic100.github.io/jQuery-QueryBuilder/demo.html#import_export
