### ISSUE TITLE
From http to https for below two links

### ISSUE THREAD

**Issue by sahilkatia1** [mistic100/jQuery-QueryBuilder#591]
Below two links I used in my current application but we are moving from http to https. Most of the libraries worked with https except these two. Please let me know alternative of it.
<link href="http://querybuilder.js.org/dist/selectize/dist/css/selectize.bootstrap3.css" rel="stylesheet">
["link href="http://querybuilder.js.org/dist/bootstrap-select/dist/css/bootstrap-select.min.css"](url)

[link href="http://querybuilder.js.org/dist/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet"](url)

**Comment by mistic100** [comment]
Do not a link from my documentation, use a CDN
https://www.jsdelivr.com/package/npm/bootstrap-select
https://www.jsdelivr.com/package/npm/selectize

(You cannot post HTML in Github issues, that's why your code does not display, or use the "code" button in the toolbar)

**Comment by sahilkatia1** [comment]
it didn;t work
