### ISSUE TITLE
Is it possible to create filters with dynamic values (like 'Today', 'Yesterday', 'Next week' ...)?

### ISSUE THREAD

**Issue by pedrofurtado** [mistic100/jQuery-QueryBuilder#592]
@mistic100 

The plugin has some default filter operators for Date (like 'equal', 'less or equal than', ...). But the value of each of these operator is a specific date, like '2017-01-01' or something like that:

![capturar](https://user-images.githubusercontent.com/10530520/32576393-f1d8f8c6-c4bd-11e7-9d7b-7ae054deeaf1.PNG)

Is it possible to fill the filter value with a special value (like a constant TODAY, for example) instead of select some date on datepicker?

![capturar2](https://user-images.githubusercontent.com/10530520/32576391-f1b85094-c4bd-11e7-8f9c-73de11cf4a05.PNG)

If I fill programatically the filter value as 'TODAY' and focus the field, it is lost the previous last 'TODAY' value and open the datepicker, reseting the field to blank.

Thanks!

**Comment by mistic100** [comment]
Hello,

this is tied to the input plugin you are using (here Bootstrap Datepicker), if you can do it in an input outside QueryBuilder then you can do it inside QueryBuilder (given you configure the `validation` correctly).

I do not provide support for any plugins that could be used with QB

**Comment by pedrofurtado** [comment]
@mistic100 

Thanks for feedback! 

Creating a custom validation (that handles with these special values) could be a great approach. Is there some tutorial or example code about how to create a extra custom validation for date?

Because I want to maintain the current validation made in plugin with Date, but extending it to consider also these special values (like 'TODAY', 'YESTERDAY', and so on).

Thanks!

**Comment by mistic100** [comment]
I can only redirect you to the doc which describe what `validation.callback`  must do http://querybuilder.js.org/#validation
Use moment.js when you must validate a date
