### ISSUE TITLE
Between/Not-Between Validation

### ISSUE THREAD

**Issue by naveendb92** [mistic100/jQuery-QueryBuilder#593]
Is the possible to add some validations like:
1. Check if **first** value is greater than **second** value.
2. Check if **second** value is less than **first** value.

**Comment by mistic100** [comment]
You are exactly describing the existing "between" and "not between" operators

**Comment by naveendb92** [comment]
True. For the "between" and "not between" operators I want to add some basic validation.

**Comment by mistic100** [comment]
Add what ? What you described already exists, so I don't understand what you want !

**Comment by mistic100** [comment]
I realized the values are not checked for these operators, I will add it., And you can do it yourself with `validation.callback`  (see the doc)

**Comment by naveendb92** [comment]
Sure, let me try. 
Thank you

**Comment by naveendb92** [comment]
Seems like there is a bug for Between/Not-Between validation feature.

I have tested in the official site under Demos section **http://querybuilder.js.org/demo.html**

Below is the link for snapshot where it validates correctly, telling that **12** is greater than **1**
https://user-images.githubusercontent.com/29221698/33923855-6a44332e-dff9-11e7-8a47-4f11d60f5fdb.png

And, now if I increment the second value by 1. i.e., between 12 and 2. It doesn't validate. Below is the link for the snapshot.
https://user-images.githubusercontent.com/29221698/33923992-02ba1556-dffa-11e7-8cd4-053df77c693f.png
