### ISSUE TITLE
Need help implementing filter Dependencies

### ISSUE THREAD

**Issue by ocobacho** [mistic100/jQuery-QueryBuilder#599]
For example I have a Country and a State field I need to filter states by the country selected. And also validate that a country needs to be selected before selecting the state. What would be the best way to implement this?

**Comment by mistic100** [comment]
Use the events http://querybuilder.js.org/#events

listen to `afterUpdateRuleValue.queryBuilder` to change the list of available states.
you will also need a bit of logic the keep everything in sync if the user can delete/add the rules, change the filters, etc (there is event for each action)

**Comment by ocobacho** [comment]
Ok, thanks for the quick reply.
