### ISSUE TITLE
Error: Bootstrap Tooltip is required to use "bt-tooltip-errors" plugin. 

### ISSUE THREAD

**Issue by bharathchandragoud** [mistic100/jQuery-QueryBuilder#602]
When i am using bootstrap 4V getting this error:-
??/wp-includes/js/jquery/jquery.js,/wp-content/js/postmessage.js?m=1377267974j:3
r.handle @ ??/wp-includes/js/jquery/jquery.js,/wp-content/js/postmessage.js?m=1377267974j:3
query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:8 Uncaught Error: Bootstrap Tooltip is required to use "bt-tooltip-errors" plugin. Get it here: http://getbootstrap.com
    at Object.l.error (query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:8)
    at g.define.placement (query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:8)
    at g.<anonymous> (query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:7)
    at Array.forEach (<anonymous>)
    at g.initPlugins (query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:7)
    at g.init (query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:7)
    at new g (query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:7)
    at a.fn.init.$.fn.queryBuilder (query-builder.standalone.min.js?ver=f0005f07f7a7ae51d161b96cc7089f19:8)
    at Object.eval (eval at <anonymous> (load-scripts.php?c=gzip&load[]=jquery-core,jquery-migrate,utils,quicktags&ver=f0005f07f7a7ae51d161b96cc7089f19:2), <anonymous>:16:60)
    at i (load-scripts.php?c=gzip&load[]=jquery-core,jquery-migrate,utils,quicktags&ver=f0005f07f7a7ae51d161b96cc7089f19:2)

**Comment by mistic100** [comment]
Bootstrap V4 is not supported 
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/package.json#L13

**Comment by bharathchandragoud** [comment]
Is there any alternation for this error ?

**Comment by mistic100** [comment]
Do not use "bt-tooltip-errors" or adapt it yourself to work with BT4

**Comment by bharathchandragoud** [comment]
var jqXHR = jQuery.get(
                BISAjax.ajaxurl,
                {
                    action: 'bis_get_all_query_data',
                    plugInType:plugInType,
                    bis_nonce:bis_nonce
                });
        jqXHR.done(function (respose) {
            allFilters = respose["data"];
            
            var queryBuilder = jQuery('#bis-rule-builder').queryBuilder({
                
                operators: jQuery.fn.queryBuilder.constructor.DEFAULTS.operators.concat([
			{ type: 'is_set',  nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'is_not_set', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'pattern_match', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'domain_is', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'contains_only', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'does_not_contains', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'does_not_contains_any_of', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'contains_any_of', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'less_than', nb_inputs: 1, multiple: false, apply_to: ['string'] },
			{ type: 'greater_than', nb_inputs: 1, multiple: false, apply_to: ['string'] }
		]),
                lang: {
                    operators: {
                            is_set: 'is set',
                            is_not_set: 'is not set',
                            pattern_match: 'pattern match',
                            domain_is: 'domain is',
                            contains_only: 'contains',
                            does_not_contains: 'does not contains',
                            contains_any_of: 'contains any of',
                            does_not_contains_any_of: 'does not contains any of',
                            less_than: 'less than',
                            greater_than: 'greater than'
                    }
		},
               //plugins: ['bt-tooltip-errors'],
               display_empty_filter:false,
               autocomplete:false,
               select_placeholder:"Select criteria",
               filters: allFilters
            });

In my code i commented that  bt-tooltip-error plugin then also its show same error
