### ISSUE TITLE
Images/Glyphicons in operators dropdown list

### ISSUE THREAD

**Issue by maciejkaiser** [mistic100/jQuery-QueryBuilder#603]
Is there any possibility to add a glyphicon or image (with html tag) to the dropdown list for operators i.e. `"equal": "<img src='/img/equals.png' /> equals" ` or ` "equal": = "<span class='glyphicon glyphicon-whatever'></span> equals"` ?

**Comment by mistic100** [comment]
The dropdown is a &lt;select&gt; it cannot contains anything other than text.

Give it a try with bt-selectpicker plugin http://querybuilder.js.org/plugins.html#bt-selectpicker

**Comment by maciejkaiser** [comment]
Ok, but how to add any icon to the translate file? 

` "operators": {
        "equal": "<span class='glyphicon glyphicon-heart'></span> equal",
        "not_equal": "not equal",`
etc.

bt-selectpicker allows to use data-icon, but how to use it with your plugin :( ?

```
<select class="selectpicker">
  <option data-icon="glyphicon-heart">Ketchup</option>
</select>
```

http://silviomoreto.github.io/bootstrap-select/examples/#customize-options

**Comment by mistic100** [comment]
You can use the `icon` property of each filter, it will just add the `data-icon` attribute to the generated HTML.
Plugin BT Selectpicker supports this by default for font-icons.

You can still write your own plugin for advanced usage (images, etc)

**Comment by maciejkaiser** [comment]
It would be nice to use icons in operators really.

Just like :
`  { type: 'equal', optgroup: 'basic', **icon: 'name_of_glyphicon'** },
  { type: 'not_equal', optgroup: 'basic'**, icon: 'name_of_glyphicon'** }
]`

Any chance for that? 


i.e functionality like in devextreme filter builder
https://js.devexpress.com/Demos/WidgetsGallery/Demo/FilterBuilder/WithDataGrid/jQuery/Light/
