### ISSUE TITLE
queryBuilder('getRules') returns null during afterUpdateRuleValue.queryBuilder

### ISSUE THREAD

**Issue by nderen** [mistic100/jQuery-QueryBuilder#605]
I apologize in advance if I'm doing something wrong here; this is my first real foray into Javascript and it's possible that I'm misunderstanding some scope problem.

I'm trying to implement dynamic filters using optgroups for various messages being sent to my system. The idea is that the user can filter based on the type of message, then have the filter list get populated with that message type's fields, in very similar fashion to this example: https://github.com/mistic100/jQuery-QueryBuilder/issues/599 

In order to build the filter list dynamically, every time the user updates the current rules I'm trying to scan each rule in the builder to see if *any* of them are trying to filter on message type, then I'm loading that message's member fields from an external json schema. The menu might look something like this:
```
base
|__message_type
|__timestamp
message_type_1
|__member_field
message_type_2
|__alternate_field
```

The "message_type_1" group would only show up in the filter list would only show up if message_type equals message_type_1 is set in one of the rules; similarly for message_type_2. To accomplish this I'm trying to call getRules from within afterUpdateRuleValue.queryBuilder to retrieve all current rules so I can compare against message_type on the left-hand-side, but the call returns null.

Sample repro here, based on the demo code:
```
$('#builder-basic').on("afterUpdateRuleValue.queryBuilder", function(e, rule) {
  console.log("afterUpdateRuleValue called");
  let filterList = $('#builder-basic').queryBuilder('getRules');
  console.log(filterList.toString());
  $('#builder-basic').queryBuilder('setFilters', filterList);
});
```
I'm trying to log the results but null does not have toString(). If you remove that console.log call, queryBuilder('setRules') fails because filterList is null. To be clear I expect setRules to fail if null is passed, but it seems to me that filterList shouldn't be null.

Live demo. Change one of the "Category" options to anything else and inspect the JS console:
https://jsfiddle.net/y2yoqt09/

Am I using getRules correctly? If so, is there another way to get the contents of all existing rules in the current builder?

**Comment by nderen** [comment]
Looking at the code, setFilters to the rule list would fail anyway. But just for illustrative purposes, it still shouldn't be null; in my own codebase I have extra functions to grab filters based on rule values; the idea is that I could iterate over the results of getRules and add new filters as needed.

**Comment by mistic100** [comment]
First of all your code doesn't make sense : `getRules` returns a JSON representation of the rules entered by the user (filter + operator + value triplets) while `setFilters` expects a list of filters (like the `filters` initial config).

----------

I ran your jsfiddle I the result of `getRules` is NOT null, it logs `[object Object]` because of the use of `toString` and if you use `JSON.stringify` it returns perfectly valid JSON object.

**Comment by mistic100** [comment]
![sans titre-1](https://user-images.githubusercontent.com/41597/33735969-48aaabba-db91-11e7-9431-c7f94a7cede1.png)

**Comment by nderen** [comment]
I'm now seeing that too; I think uBlockOrigin might have been messing with my demo. I'm still seeing the issue locally however; let me see if I can put together another demo.

**Comment by nderen** [comment]
Hmm, wait, no; I've disabled UBO and PrivacyBadger, but I'm still getting null if I change one of the Category dropdowns to anything other than Category:
![image](https://user-images.githubusercontent.com/22897086/33736676-5712bbb4-db48-11e7-9ec5-e5ecb89123fa.png)
I do get a valid JSON object if I change it back to Category. Updated fiddle:
https://jsfiddle.net/y2yoqt09/1/

**Comment by mistic100** [comment]
Well yes of course, because the builder IS invalid : the rule has no value, select "yes" or "no" and you will get the JSON.

**Comment by nderen** [comment]
Interesting. But some of the other rules do have values; how would I go about retrieving their current state on change, even if that change invalidates the state of one of the rules? I could set a default for the rules but that still doesn't preclude users from removing the value from the rule.

**Comment by mistic100** [comment]
I don't see the point in your particular case, you said you need the value to update the list of available filters so just wait the value to be set.

----

Anyway it's in the doc http://querybuilder.js.org/#methods

```js
$builder.queryBuilder('getRules', { allow_invalid: true });
```

**Comment by mistic100** [comment]
And also the `afterUpdateRuleValue` event you are listening gets somes parameters, in particular the changed rule object with it's filter, operator and value

**Comment by nderen** [comment]
Alright, I'll give that a try. I think I did try that yesterday, but again, JS beginner, I probably messed up the syntax.

And yeah, I've been using the changed rule object in my code. My issue has been if someone chooses to filter on the same message_type twice, then changes one of them to something else. If I'm only looking at the currently-changed rule all I see is that message_type is no longer in rule.filter.field. If I reset the filter list based on that, then the fact that message_type is set elsewhere isn't considered when I rebuild the list.

Thanks!
