### ISSUE TITLE
After click the get rules we want to get the empty query values without getting error

### ISSUE THREAD

**Issue by baskar383** [mistic100/jQuery-QueryBuilder#606]
Kindly please refer the screen shot: 
![getting_empty](https://user-images.githubusercontent.com/17172610/33825955-52b2bdbe-de89-11e7-9100-88160d4cee11.png)

**Comment by mistic100** [comment]
Issues Guidelines are meant to be **read** and deleted afterward.

I insist on the **read** because what you ask is in the doc http://querybuilder.js.org/#methods

```js
$builder.queryBuider('getRules', {allow_invalid: true});
```

**Comment by baskar383** [comment]
Thanks a lot.
