### ISSUE TITLE
we want to change the add rule behaviour

### ISSUE THREAD

**Issue by baskar383** [mistic100/jQuery-QueryBuilder#607]
we want to change the add rule behaviour. Kindly please refer screenshot: 
![rulesbehaviour](https://user-images.githubusercontent.com/17172610/33826379-ca08a260-de8a-11e7-811a-61e8e5be0748.png)

**Comment by mistic100** [comment]
This is not possible from scratch. You can either enable the "Sortable rules" plugins are do it manually by using event. More precisely the "afterAddRule" event.

Something like (incomplete, not tested) :

```js
$builder.on('afterAddRule.queryBuilder', function(e, rule) {
  var group = rule.parent;

  if (group.length() > 1) {
    var target = ....; // here you implement your logic to find after which rule you want to new rule

    rule.moveAfter(target);
  }
});
```

Check http://querybuilder.js.org/index.html#inside_the_box to know what is available on Rule and Group objects.

**Comment by baskar383** [comment]
Thanks a lot..
