### ISSUE TITLE
Between/Not-Between Validation bug

### ISSUE THREAD

**Issue by naveendb92** [mistic100/jQuery-QueryBuilder#612]
Seems like there is a bug for Between/Not-Between validation feature.

I have tested in the official site under Demos section http://querybuilder.js.org/demo.html

Below is the link for snapshot where it validates correctly, telling that 12 is greater than 1
https://user-images.githubusercontent.com/29221698/33923855-6a44332e-dff9-11e7-8a47-4f11d60f5fdb.png

And, now if I increment the second value by 1. i.e., between 12 and 2. It doesn't validate. Below is the link for the snapshot.
https://user-images.githubusercontent.com/29221698/33923992-02ba1556-dffa-11e7-8cd4-053df77c693f.png

**Comment by mistic100** [comment]
I identified the problem (comparing strings instead of numbers), it will be solved with #544

**Comment by naveendb92** [comment]
Thank you.
