### ISSUE TITLE
React QueryBuilder integration

### ISSUE THREAD

**Issue by yrodrigez** [mistic100/jQuery-QueryBuilder#614]
Hi, i'd like to integrate the querybuilder with react but i'd like to use my own components for the fields such as a Calendar for date pick and my own select component, i started yesterday with the Calendar but i don't know where to set the value....

```js
QueryBuilder.define("datepicker", function (options) {
      this.on("getRuleInput.filter", function (h, rule, name) {
        let {plugin} = rule.filter;
        if (plugin === "datepicker")
        ReactDOM.render(<Cx store={that.props.instance.store}>
          <DateField value:bind="$date"/>
        </Cx>, rule.$el[0].lastElementChild)
  });
}); 
```

**Comment by mistic100** [comment]
You need to use the `valueSetter` on each filter http://querybuilder.js.org/#filters

Or overwrite the `setRuleInputValue` method.

```js
const _setRuleInputValue = QueryBuilder.prototype.setRuleInputValue;

QueryBuilder.prototype.setRuleInputValue = function(rule, value) {
  let {plugin} = rule.filter;

  if (plugin === 'datepicker) {
  }
  else {
    _setRuleInputValue.apply(this, rule, value);
  }
};
```

**Comment by yrodrigez** [comment]
Does this works to render a new node for the datepicker? or do i continue using the `on("getRuleInput.filter")`

**Comment by yrodrigez** [comment]
![i130 cimgpsh_orig](https://user-images.githubusercontent.com/6799275/34214701-274b88a4-e59b-11e7-8015-797412194ed0.png) this is what i mean, the input is not deleted, is added again!

**Comment by mistic100** [comment]
In your "getRuleInput" handler, set `h.value = '';`

**Comment by yrodrigez** [comment]
Is there a `getRuleInput` `re-render` function? where do we can find info about this?

**Comment by mistic100** [comment]
You can call `createRuleInput` method.

Very important : QueryBuilder was never intended to be used with widgets that are not controlled by jQuery, everything was developed with jQuery plugins lifecycle in mind.
So every information I am giving might be completely false and might be unstable in your app.

I am afraid I have to stop giving help about React because I cannot test anything.

**Comment by mistic100** [comment]
Another (better ?) solution is to listen to the `afterUpdateRuleValue` trigger and manually refresh the component from here (given you can access the React API from the DOM element).

**Comment by yrodrigez** [comment]
Thank you very much for your answer @mistic100 i am aware about the React thing you're saying but it's required to integrate this with react 
The problem that i'm having right now is that the QueryBuilder is not showing the rules when i set the value on it and is working with all rules but DateTime rules...
