### ISSUE TITLE
Custom operators with two values

### ISSUE THREAD

**Issue by ChrisLock90** [mistic100/jQuery-QueryBuilder#616]
Hi,

I'm looking to create a custom operator that returns two values, I have it all set up working fine.

The next part is that I want the first box to allow an integer for the value after the operator and the second box to be a selectize drop down.

The reason for this is I want it to be possible to enter 

Operator = "in the last"
Int = "2"
Dropdown = "hours" 

With the drop down allow minuites, hours, days, weeks, months.

Is this currently possible? Something along the lines of:

type: ['integer', 'select']

Thanks

**Comment by mistic100** [comment]
This cannot be done, see #284

**Comment by akshayNirhali02** [comment]
@mistic100  any updates on above issue sir ?
mine case is similar.
