### ISSUE TITLE
cannot get the client example to work

### ISSUE THREAD

**Issue by elvira1989** [mistic100/jQuery-QueryBuilder#617]
please help ! cannot get it work always get this message 
![untitled](https://user-images.githubusercontent.com/34816854/34328359-d8be4714-e8e5-11e7-876b-3d837b6521c7.png)

can you explain how to fix it ? 
i download the project unzipped it and run the example 
what am i doing wrong ?

**Comment by mistic100** [comment]
Hello
what you must do is clearly written "run `bower install`" in both the example folder and the root folder.

Also if you open your web console (like every developer should do) you will see a bunch on 404 errors to every file.

**Comment by mistic100** [comment]
And if you downloaded the `dev` branch you will also have to build to library : `npm install && grunt`

Download the `master` branch to avoid that.

**Comment by elvira1989** [comment]
@mistic100 thx for your fast response!
i never use bower and dont actually know how to download it to specific folder ?
and of course why i need bower ? 
its because i dont have server-side ?

**Comment by mistic100** [comment]
Sorry I am not here to teach you how the web ecosystem works, there is excellent documentation online.
