### ISSUE TITLE
What are the steps followed to save a rule value to set a custom rule?

### ISSUE THREAD

**Issue by yrodrigez** [mistic100/jQuery-QueryBuilder#619]
I'm implementing a new date selector to the QueryBuilder (With time and date) and i would like to know the followed steps to save those values in the QueryBuilder instance... so, i tried
```js
QueryBuilder.prototype.setRuleInputValue = function (rule, value) {
  let {plugin} = rule.filter;
  if (plugin === 'datepicker') {
    if (value)
      _setRuleInputValue.call(this, rule, window.moment(value));
  } else {
    _setRuleInputValue.call(this, rule, value);
  }
};
``` 

But it's not working... the value is not validated and when changing the operator doesn't makes any change eather....

i think i don't understand very well where those values are stored, is there an object that store all those values or maybe are all they stored in the view?

BTW i'm using the `standalone` version

Thanks in advance!

**Comment by mistic100** [comment]
What are you trying to do **exactly** ?

You shouldn't modify the QueryBuilder method unless you have a very very specific use case.
QueryBuilder already supports the datetime format + validation : http://querybuilder.js.org/#filters => `type: 'datetime'`

**Comment by mistic100** [comment]
See my answer on #614 

You will have way less troubles developing your own query builder, fully integrated in React lifecycle.
