### ISSUE TITLE
Uncaught TypeError: $(...).queryBuilder is not a function

### ISSUE THREAD

**Issue by abrarakazi** [mistic100/jQuery-QueryBuilder#623]
<head>
    <link href="~/Content/query-builder.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-select.min.js"></script>

    <script src="~/Scripts/query-builder.standalone.min.js"></script>
</head>

<div id="builder"></div>

 $('#builder').queryBuilder({
        filters: JsonStr
    });

// the below code gets error : Uncaught TypeError: $(...).queryBuilder is not a function
   $("#btnCompare").on('click', function () {
        var result=   $('#builder').queryBuilder('getRules');
    });

**Comment by abrarakazi** [comment]
any jquery event like document.ready/buttonclicks throws the error : 
Uncaught TypeError: $(...).queryBuilder is not a function

**Comment by mistic100** [comment]
standalone = query-builder + extendext + dot

that means you have query-builder and extendext twice in your app

**Comment by mistic100** [comment]
and there is nothing wrong with code, so check you files actually exist in the right place

**Comment by abrarakazi** [comment]
Thank you so much for the prompt reply. You saved me a lot of time.

**Comment by abrarakazi** [comment]
Sorry but it didnt work after removing the extra js;

<head>
    <link href="~/Content/query-builder.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-select.min.js"></script>
  
    <script src="~/Scripts/query-builder.standalone.min.js"></script>
</head>

**Comment by mistic100** [comment]
I cannot help you more. You have all the necessary files so it should work.
If it doesn't you have either a missing file, an error somewhere that blocks the execution of whatever.

If you want more help, create a full test case on jsfiddle.

**Comment by abrarakazi** [comment]
Ok i will create a jsfiddle and post the link here.

**Comment by mistic100** [comment]
And when posting code on github use triple back quote otherwise half your code is hidden

**Comment by abrarakazi** [comment]
Ok

**Comment by abrarakazi** [comment]
Ok thanks mistic100, the issue was that duplicate jquery files were loaded. Resolved it by removing the duplicate js files. Thanks.
