### ISSUE TITLE
Error: A rule is using filter .... 

### ISSUE THREAD

**Issue by abrarakazi** [mistic100/jQuery-QueryBuilder#624]
'''var JsonStr = [
     { id: "Name", type: "string", input: "text" }, { id: "Age", type: "integer", input: "number" }];

Ok so i am selecting Name in dropdown first and i have a button on my page (Button: Change Input) which is clicked to change the input type text of Name filter which is string to SELECT. 

But when i select the filter in drop down and then click on button it gives me the error : Error: A rule is using filter "Name".

    $("#btnCompare").on('click', function () {       
        $('#builder').queryBuilder('removeFilter', 'Name');
        $('#builder').queryBuilder('addFilter', "{'id':'Test','input':'select','type':'string','values':'['A','B']'}",1);
    });
'''

**Comment by mistic100** [comment]
Did you at least read the doc ? 
http://querybuilder.js.org/plugins.html#change-filters

Use the `force` flag

```js
$('#builder').queryBuilder('removeFilter', 'Name', true);
```

**Comment by abrarakazi** [comment]
but when i remove it and use the new filter code : 
 var JsonStr = [
     { id: "TreatmentCode", type: "string", input: "text" }, { id: "Age", type: "integer", input: "number" }, { id: "ConsultationFeesSelect", type: "string", input: "select", values: ['test', 'test2'] }
    ];
 $('#builder').queryBuilder('removeFilter', 'TreatmentCode', true);
   $('#builder').queryBuilder('addFilter', { id: 'Test', input: 'select', type: 'string', values:['1','2'] }, 0);

it doesnt add anything the builder filter goes empty without any error

**Comment by abrarakazi** [comment]
is there a way to only update a particular rule and its filter instead of updating the filters and eventually removing the rule ?

**Comment by mistic100** [comment]
No, a filter definition cannot be updated. You can only delete it (thus removing the rule using it) a recreate it.
