### ISSUE TITLE
TypeError: d[e.plugin] is not a function

### ISSUE THREAD

**Issue by YanetABUC** [mistic100/jQuery-QueryBuilder#625]
Hi! Congrats for such a wonderful tool! I read all documentation, tried some examples but I keep getting the same error.

Let me explain, I want to user Pikaday as datepicker instead of Bootstrap Datepicker. I created a standalone plugin and everything goes fine until I select a field of type date. Here is my code

On my php template (I'm using Yii):
```
Yii::app()->clientScript->registerScriptFile('/scripts/vanilla-modal.min.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile('//maps.google.com/maps/api/js?key=' . Yii::app()->params['googleApiBrowserKey'] . '&libraries=drawing', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile('/js/area.js?v=20', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile('//cdn.jsdelivr.net/selectize/0.12.3/js/standalone/selectize.js', CClientScript::POS_END);

Yii::app()->clientScript->registerScriptFile('/js/moment.min.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile('/scripts/pikaday.js', CClientScript::POS_END);

Yii::app()->clientScript->registerCssFile('/css/bootstrap.min.css');
Yii::app()->clientScript->registerCssFile('/scripts/jquery-query-builder/query-builder.default.min.css');
Yii::app()->clientScript->registerScriptFile('/scripts/jquery-query-builder/query-builder.standalone.min.js', CClientScript::POS_END);

Yii::app()->clientScript->registerCssFile('//cdn.jsdelivr.net/selectize/0.12.3/css/selectize.bootstrap3.css');
Yii::app()->clientScript->registerCssFile('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css');
Yii::app()->clientScript->registerScriptFile('/js/bootstrap.min.js', CClientScript::POS_END);

Yii::app()->clientScript->registerScriptFile('/scripts/interact.min.js', CClientScript::POS_END);
Yii::app()->clientScript->registerScriptFile('/scripts/saved_search.js?v=4', CClientScript::POS_END);
```
On my saved_search.js:

```
$('.js_query_builder').queryBuilder({
        operators: globalOperators,
        plugins: ['querybuilder_pikaday'],
        filters: [...,{
        ....
         type: 'date',
          validation: {
              format: 'MM/DD/YYYY'
           },
           plugin: 'querybuilder_pikaday',
           plugin_config: {
              format: 'MM/DD/YYYY'
            },
        },...]
      });

//Plugin
$.fn.queryBuilder.define('querybuilder_pikaday', function (options) {
  this.on('afterCreateRuleInput', function(e, rule) {
    if (rule.filter.id === 'date') {
      var $input = rule.$el.find('.rule-value-container [name*=_value_]');
      var pickerStart = new Pikaday({
        field: $input,
        format: 'MM/DD/YYYY'
      });
    }
  });
});
```
When I select a field with date value I always get the error "TypeError: d[e.plugin] is not a function" on console and pikaday calendar didn't appear

I know this can be a silly question but after read all issues on this repo, read documentations and testing a lot of examples, I'm still getting the error.

Can you help me, please?

**Comment by mistic100** [comment]
Hello

if you read the doc entirely please tell me how to make more clear. You mixed the global "plugins" (http://querybuilder.js.org/#usage) which are QueryBuilder plugins and the filter "plugin" (http://querybuilder.js.org/#filters) which is a standard jQuery plugin (in the $.fn namespace) applied to the input element.

To be convinced of that : the Widgets demo uses a datepicker and a slider and none of them exists in the source as QueryBuilder plugins https://github.com/mistic100/jQuery-QueryBuilder/tree/dev/src/plugins

----

So what you need : 
1. delete this "querybuilder_pikaday", you do not need a QueryBuilder plugin.
2. add the jQuery plugin in your app https://github.com/dbushell/Pikaday/blob/master/plugins/pikaday.jquery.js
3. register it in the filter's "plugin" property

```js
{
        ....
         type: 'date',
          validation: {
              format: 'MM/DD/YYYY'
           },
           plugin: 'pikaday',
           plugin_config: {
              format: 'MM/DD/YYYY'
            },
        }
```

**Comment by YanetABUC** [comment]
Thank you very much!
