### ISSUE TITLE
[feature request] Let custom templates handle plugin markup 

### ISSUE THREAD

**Issue by chriskr** [mistic100/jQuery-QueryBuilder#626]
We use custom templates and the sortable plugin. We have changed the markup structure a bit. Our issue is that the plugin inserts its markup in a bit a too magic way, not where we would like to have it. It would be better if the according markup could be added to the custom template.

Currently we use an event black list and overwrite the `QueryBilder.prototype.on` to ignore `'getGroupTemplate.filter'` and `'getRuleTemplate.filter'` so that we have full control over the markup. One suggestion would be to add an event blacklist to the options with the same purpose.

**Comment by mistic100** [comment]
Too complicated and 100% error prone (what about other plugins using the same events ? developers which will disable the wrong event and break everything ?).

I propose a simple option `insert_drag_handle` which can disable this block https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/sortable/plugin.js#L148-L161

**Comment by chriskr** [comment]
Ok, sounds good. To be sure that I understand you correctly, `insert_drag_handle` would be an optional flag on the plugins options. If it is set to `false`, that block will be disabled. I create an according pull request tomorrow.

**Comment by mistic100** [comment]
Done, Added "disable_template" option for plugins invert, not-group, sortable

**Comment by chriskr** [comment]
Thanks!
