### ISSUE TITLE
Cannot able to prefill the date in the datepicker and value got cleared when blurred out of input

### ISSUE THREAD

**Issue by sridhar391** [mistic100/jQuery-QueryBuilder#628]
- When having the widget as Date picker and Type as date and having the value ,
- If u place the cursor in input, the date picker should be prefilled with given date  but it is not prefilled and 
- When u place the cursor outside of the input the value got cleared

## Issue can be Reproduced by:
- Goto http://querybuilder.js.org/demo.html#widgets
- In that place the cursor in the input and date picker will be shown , but it is not prefilled with given date
- When placing the cursor outside the input the value got cleared

**Comment by mistic100** [comment]
This is because the Datepicker does not read the input value on open, I didn't search their issues is the problem is already referenced.

A solution is to trigger and update on value change :

```js
$('#builder').on('afterUpdateRuleValue.queryBuilder', function(e, rule) {
    if (rule.filter.plugin === 'datepicker') {
      rule.$el.find('.rule-value-container input').datepicker('update');
    }
  });
```

I will add it the demo.

**Comment by mistic100** [comment]
This solution crashes with Datepicker 1.5.1 but works with Datepicker 1.7.1
