### ISSUE TITLE
Is there a way to recreate the filters from URL parameters?

### ISSUE THREAD

**Issue by moe70** [mistic100/jQuery-QueryBuilder#629]
I want my users to be able to share links that will take other users to the exact filters that they created. Is this possible or is it something that I have to implement from scratch?

Thanks

**Comment by mistic100** [comment]
You have to do it yourself.

The simplest way is to call "getRules" and serialize in one line (`JSON.stringify(rules)`) and made some URL escape if needed, then on page load call "setRules".

Or you can make your own serialization in a custom and more compact format. "getRules" and "setRules" still being the only way to communicate the data with the builder.

If you go to the custom serializer you can create a QueryBuilder plugin, for example this project https://github.com/piotch/jQuery-QueryBuilder-Elasticsearch add a new "getESBool" method supercharging "getRules", in the same pattern you can create "getForURL" and "setFromURL" methods.
