### ISSUE TITLE
No "dist" folder while installing via satis

### ISSUE THREAD

**Issue by adargor** [mistic100/jQuery-QueryBuilder#631]
```json
{
    "name": "Composer Mirror",
    "homepage": "localhost:4680",

    "repositories": [
        { "type": "composer", "url": "https://asset-packagist.org"},
        { "type": "composer", "url": "https://packagist.org" }
    ],

    "config": {
        "preferred-install": "dist"
    },

    "require": {
        ...
        "bower-asset/jquery-querybuilder": "*",
        ...
    },
    "require-dependencies": true,
    "archive": {
        "directory": "dist",
        "format": "zip",
        "skip-dev": true
    }
```

![dist](https://user-images.githubusercontent.com/6592105/35107295-a18f184a-fc81-11e7-84bd-db4202f049ed.png)

**Comment by mistic100** [comment]
Add if you require an actual version ? No wildcard.

(I don't know satis and won't install it)

**Comment by adargor** [comment]
Same result

**Comment by mistic100** [comment]
I read some doc and learned that bower-asset it's a tool to load bower components via composer.
But you don't need that because query builder is already available on packaging.
Use "mistic100/jquery-querybuilder" then.

Envoyé depuis mon appareil Android.

-----Original Message-----

**Comment by adargor** [comment]
Requiring mistic100/jquery-querybuilder ends up with same result. I think this issue is caused by dev branch used as default in GitHub project.

**Comment by adargor** [comment]
Found one interesting thing. Tag 2.4.1 comes with dist folder, and other higher versions do not.

**Comment by mistic100** [comment]
I just cannot tell you.
All tags HAVE the dist folders https://github.com/mistic100/jQuery-QueryBuilder/tree/2.4.2 etc.

**Comment by mistic100** [comment]
dev being the default branch is a configuration on Github only, it does not affect the git repository itself.

**Comment by mistic100** [comment]
So for me everything is fine on my side, tags have the correct content, master too, NPM packages are clean and I want to have dev as the default branch.

I cannot be of any help. Feel free to comment if you find something.

**Comment by mistic100** [comment]
Found this https://github.com/composer/satis/issues/324
Composer applies the .gitignore file and I purposely ignored "dist" for not being commited on the dev branch.

The problem comes from an erroneous merge, "dist" should not be ignored on master branch.

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/commit/8d8d24bc2c5d483cf2a8618769221ffc6c789ca6

You should be able to install it with wildcard (tags 2.4.2 to 2.4.5 won't work)
