### ISSUE TITLE
Undefined filter in Jquery Builder

### ISSUE THREAD

**Issue by sfdctechuser** [mistic100/jQuery-QueryBuilder#633]
I am trying to use jquery builder in my lightning component and I am setting rules dynamically. 
When I set rules it throws error:
**Uncaught Action failed: c:BRCreateQueryBuilder$controller$getBuilderData [Undefined filter "gattexlead_flag"]**

**Below is my code:**
getBuilderData : function(component,event,helper)
{
var existingblock = component.get("v.wrapperBlock");
var $j = jQuery.noConflict();
console.log('in get builder');
var idB = component.get('v.index');
var filterJson = [];
var columnDetails = component.get('v.columnDetailsresponse');
for(var i=0;i<columnDetails.length;i++){
    if(columnDetails[i].datatype__c=='Numeric'){
        filterJson.push({id:"'"+columnDetails[i].tb_col_nm__c+ "'",label:columnDetails[i].tb_col_nm__c,type:'integer',input: 'select',operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null','less','less_or_equal','greater','greater_or_equal'],values:{1:'1',2:'0'}});
     }else{
        filterJson.push({id:"'"+columnDetails[i].tb_col_nm__c+ "'",label:columnDetails[i].tb_col_nm__c,type:'string',operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null'],value:{}});
     }
}
 console.log('**JSON**');
 console.log(filterJson);
 **/*
 0:{id: "'gattexlead_flag'", label: "gattexlead_flag", type: "integer", input: "select", operators: Array(10), …}
 1:{id: "'shire_id'", label: "shire_id", type: "integer", input: "select", operators: Array(10), …}
 */**
 //Check If existing rule
 var rules_basic;
 var checkExistingRule = component.get('checkRuleExists');
 console.log(checkExistingRule);
 debugger;
    if(checkExistingRule==false){
        $j('#group_'+idB).queryBuilder({
        filters: filterJson,
        rules: rules_basic
    });

 }else{
    rules_basic = JSON.parse(existingblock.criteriaLogic);
      console.log(rules_basic);
      **/*
      condition:"AND"
      rul

es: Array(1)
          0:
            field:"gattexlead_flag"
            id:"gattexlead_flag"
            input:"select"
            operator:"equal"
            type:"integer"
            value:"1"  */**
         $j('#group_'+idB).queryBuilder({
            filters: filterJson,
            rules: rules_basic
         }); 
     }

}

**Comment by mistic100** [comment]
Please edit your message and add markdown code blocks
https://guides.github.com/features/mastering-markdown/#syntax
