### ISSUE TITLE
sql export methods in node js

### ISSUE THREAD

**Issue by sarathbabuSwamynathan** [mistic100/jQuery-QueryBuilder#635]
* I want to export queries as sql using following function
.getSQL([mode [, linebreaks]])

* But in my case I want to do it in node server

*  I have installed jQuery-QueryBuilder  in my node server's node modules using npm

* But when i require it in my node server ( var querybuilder = require('jQuery-QueryBuilder');)
I am getting error which i have attached here with

* Any suggestion???? Thanks in advance.
![querybuildererror](https://user-images.githubusercontent.com/19778435/35860892-c9e05cf2-0b6b-11e8-8a18-8590c9aa421f.png)

**Comment by mistic100** [comment]
Did you read that ? https://github.com/mistic100/jQuery-QueryBuilder#dependencies
You need jQuery, jQuery.extendext and doT.js

**Comment by mistic100** [comment]
This library was never developped to work on server environnement, **I will not provide support for it.**

**Comment by sarathbabuSwamynathan** [comment]
when i did   -  npm install jQuery-QueryBuilder all dependencies are included in my node modules

Ho, I can do this in node server??

**Comment by mistic100** [comment]
No, it's a GUI component !

**Comment by sarathbabuSwamynathan** [comment]
Ok. Thank you.

**Comment by sarathbabuSwamynathan** [comment]
It is possible to parse structured JSON rules output from query builder using node js?

**Comment by sarathbabuSwamynathan** [comment]
yea, Thank you.
