### ISSUE TITLE
How to focus on perticular or group of rule where text field is empty

### ISSUE THREAD

**Issue by stahaquadri** [mistic100/jQuery-QueryBuilder#637]
how to focus on perticular rule or group of rule where text field is empty on click of html button.

**Comment by mistic100** [comment]
what ?

**Comment by stahaquadri** [comment]
In my jsp page i have added <div id="builder"></div> and i am appending querybuilder to it to display, but this <div> is on top in my page and form submit button is little down so i need to scroll down for submit button, on submit click i have written the code to get the  plain SQL "var sql_raw = $('#builder').queryBuilder('getSQL', false);", now if any text box is empty in queryrule than its showing red but user should scroll up and see, i want to focus that without scrolling and i tried to focus on <div> but execution is end with this code only "var sql_raw = $('#builder').queryBuilder('getSQL', false);". please reply if you still didn get, Thanks, PFA
![example](https://user-images.githubusercontent.com/14851726/36085908-265a0834-0fef-11e8-8e6f-6d37c1903d52.png)

**Comment by mistic100** [comment]
```js
function focusInvalidRule(group) {
  group.each(
    function(rule) {
      if (rule.error) {
        rule.$el.find('.rule-input-container input').focus();
      }
    },
    focusInvalidRule
  );
}

if (!$builder.queryBuilder('validate')) {
  focusInvalidRule($query.queryBuilder('getModel'));
}
else {
  sql = $builder.queryBuilder('getSQL', false);
}
```

Not tested but that's the idea
