### ISSUE TITLE
Backend parser in php - zend framework support

### ISSUE THREAD

**Issue by sarathbabuSwamynathan** [mistic100/jQuery-QueryBuilder#638]
* can i get back end parser with php - zend frame work support?

**Comment by mistic100** [comment]
You want help to create a parser or you want someone to create a parser ?

**Comment by sarathbabuSwamynathan** [comment]
I need parser like this
![parser](https://user-images.githubusercontent.com/19778435/36138614-1505227c-10c0-11e8-9511-b3823e4fc303.png)

**Comment by mistic100** [comment]
If I knew any it would be listed here.
I close, I don't do PHP development and I can't keep every 3rd party issues.

**Comment by sarathbabuSwamynathan** [comment]
Thank you for earliest reply.

**Comment by mistic100** [comment]
Don't hesitate to notify if you find one or do it yourself and want to share.

**Comment by sarathbabuSwamynathan** [comment]
Yea sure.
