### ISSUE TITLE
Question - Using different data types depending on the operator selected

### ISSUE THREAD

**Issue by gamosoft** [mistic100/jQuery-QueryBuilder#639]
Hello there, first of all thank you so much for this amazing piece of work, it's unbelievable! 👍 

I have a question on how to use different data types (or a workaround) depending on the selected operator.

I have date fields with the regular and custom defined operators (greater than, today, ...) which apply to the underlying 'date' type in javascript, so I can use the datepicker plugin as well and load/save data such as:

```
        "rules": [
          {
            "id": "modifiedon",
            "type": "date",
            "input": "text",
            "operator": "greater_than",
            "value": "14/04/1975"
          }
```

The issue is that I have to implement some more custom operators such as "greater than N days" where the user would be able to specify an integer value, then save such as:

```
        "rules": [
          {
            "id": "modifiedon",
            "type": "date",
            "input": "text",
            "operator": "greater_than_n_days",
            "value": "15"
          }
```

Submitting it to the backend is no problem since the service will take care of it.

What would be in your opinion the best approach to do that? I've done custom function to define several dropdowns and even popup entries.

Maybe a function that, depending on the operator chosen would render either the datepicker plugin or a custom textbox for users to enter data? How would I be able to do that?

Thanks a lot.
Kind regards.

**Comment by gamosoft** [comment]
I have been researching and it *seems* to do the trick:

```
        $('#qb').on('afterUpdateRuleOperator.queryBuilder', function (e, rule) {
            if (rule.filter.data && rule.filter.data.isdatetime) {
                var hybridOperators = ['LastNDays', 'LastNMonths', 'LastNYears', 'NextNDays', 'NextNMonths', 'NextNYears', 'OlderThanNDays', 'OlderThanNMonths', 'OlderThanNYears'];
                if (hybridOperators.indexOf(rule.operator.type) > -1) {
                    rule.$el.find('.rule-value-container input').datepicker('destroy');
                    rule.filter.type = 'integer';
                    rule.filter.validation = { format: /[0-9]+/ };
                    rule.value = '0';
                } else {
                    rule.$el.find('.rule-value-container input').datepicker();
                    rule.filter.type = 'date';
                    rule.filter.validation = { format: 'DD/MM/YYYY' };
                    rule.value = '';
                }
            }
        });
```

Basically using the data property of the filter, with a custom value, and then changing them like that.
Also, I cannot initialize the filter with the _plugin: 'datepicker'_ option but the above code (ish) should do the trick.

What do you think of this approach?

**Comment by mistic100** [comment]
It's the best you can do for now.

#251

**Comment by akshayNirhali02** [comment]
if we want multiple fields of different types and one of them need to use any plugin such as Selectize and others are normal.
any suggestion over this @mistic100 ?

**Comment by curunoir** [comment]
Hello @gamosoft 
I have a similar use case with the need to change the input type against an operator changed.

In my case I have a checkbox type which I would want to be typed if the user choose the 'equal' operator type.

`        $('#builder-rules').on('afterUpdateRuleOperator.queryBuilder', function (e, rule) {
                if (rule.filter.id && rule.filter.id === 'some_id' && rule.operator.type === 'equal') {
                    let inputContainerRule = rule.$el.find('.rule-value-container');
                    let existingNameInput = rule.$el.find('.rule-value-container input').attr('name');

                    inputContainerRule.html('<input class="form-control" type="text" name="' + existingNameInput + '">');
                    rule.filter.type = 'string';
                    rule.filter.input = 'text';
                    rule.value = 'some value';
                }
            }
        );`

This is doing the trick in the UI but when I want to get the rules object by calling **$('#builder-rules').queryBuilder('getRules');** the rule value will be always 'some value' even if the user has typed something else. I think there is something missing to link the replaced input into queryBuilder instance.

How did you manage to get the user value after the rule operator changed ?
