### ISSUE TITLE
Trying to add a new operator

### ISSUE THREAD

**Issue by laf** [mistic100/jQuery-QueryBuilder#644]
Hi Folks,

I'm currently looking to port a custom query builder we use to jQuery-QueryBuilder. Everything is working for us with the exception of having an operator for REGEXP in SQL.

I found: https://github.com/mistic100/jQuery-QueryBuilder/issues/403 which gave me the basis to add a new operator in which has led me to the code in the jsfiddle below:

https://jsfiddle.net/25w558vj/7/

Running this on the fiddle and my dev env I get a different error:

```
query-builder.standalone.min.js:7 Uncaught Error: Unable to parse WHERE clause
    at Object.h.error (query-builder.standalone.min.js:7)
    at k (query-builder.standalone.min.js:8)
    at getRulesFromSQL (query-builder.standalone.min.js:8)
    at g.setRulesFromSQL (query-builder.standalone.min.js:8)
    at init.$.fn.queryBuilder (query-builder.standalone.min.js:7)
    at (index):508
```

Now I thought that this might be due to sql-parser not support REGEXP so I 'patched' that and then get a different error: (sorry I don't have that to hand) which says something like REGEXP isn't valid.

I've since worked round all of this by just saving the native json the library can create and using that to re-import from. However, if possible I'd like to go back to just parsing the WHERE part of the SQL.

Do you have any ideas where the issue might be. Is it a case of:

  - I need to just add native support to sql-parser + QueryBuilder?
  - I need to use a bit more js to get QueryBuilder to recognise REGEXP but still need to patch sql-parser?
  - I need to use a bit more js to get QueryBuilder and sql-parser to work natively.

Thanks in advance.

**Comment by mistic100** [comment]
I am sorry but what exactly is your issue ? Sounds like you solved everything so what ?

**Comment by laf** [comment]
@mistic100 thanks for responding so quickly.

So I'm trying to add REGEXP as an operator and I did this as per https://github.com/mistic100/jQuery-QueryBuilder/issues/403. However that didn't work and I got the console error as per the original post. The issue is when trying to import the SQL rule back in. Am I missing something to add another operator without updating the source code?

**Comment by mistic100** [comment]
As you already said you need to update the SQL Parser to make it parse the REGEXP. And you also need to provide the corresponding `sqlRuleOperator` (sql->json) https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/sql-support/plugin.js#L40

In you fiddle you only configured `sqlOperators` (json->sql)

**Comment by mistic100** [comment]
I highly suggest you debug step-by-step inside the sql-parser plugin to fifure it out. Working with the AST is not easy.

**Comment by laf** [comment]
> As you already said you need to update the SQL Parser to make it parse the REGEXP. And you also need to provide the corresponding sqlRuleOperator (sql->json) /src/plugins/sql-support/plugin.js@dev#L40

I did assume that but I'll be honest, JS isn't my thing so I'm not sure what needs to be put into the sqlRuleOperator. I've looked in here for examples but not found anything so any pointers would be great.

**Comment by mistic100** [comment]
??? It cannot be more simple. The hardest part was updating the parser.
```js
sqlRuleOperator: {
  'REGEXP': function(v) {
    return { val: v, operator: 'regexp' };
  }
}
```

**Comment by laf** [comment]
> ??? It cannot be more simple. The hardest part was updating the parser.

The parser was just a simple copy / paste from an existing commit.

I'll give what you've suggested a shot, sorry for wasting your time.

**Comment by laf** [comment]
@mistic100 I've got this working in full now. Would it be worth while me submitting pull requests to this repo + the sql-parser one of yours to add native support for REGEXP in MySQL?

**Comment by mistic100** [comment]
for sql-parser yes, but not for QueryBuilder as the REGEXP is not supported by all SQL servers

**Comment by laf** [comment]
Pull request submitted @mistic100. Again, thank you for your time and the library.
