### ISSUE TITLE
XOR method

### ISSUE THREAD

**Issue by DamianW123456** [mistic100/jQuery-QueryBuilder#645]
Good Morning !

I am looking for a XOR method to the plugin and couldn't find it.
Is there possible to do it ? Do I need to extend queryBuilder or is there any solutions ?
Thanks for answers,
Damian

**Comment by mistic100** [comment]
Use the `conditions` option to add it along AND and OR
http://querybuilder.js.org/#options

**Comment by DamianW123456** [comment]
What do You mean?
I know that queryBuilder has AND, OR logic method.
In the coditions param I can just set above method and that's all.

**Comment by mistic100** [comment]
Yes you can, that's the point of the configuration.
