### ISSUE TITLE
datetime between does not parse correctly

### ISSUE THREAD

**Issue by rwagnon** [mistic100/jQuery-QueryBuilder#646]
I've searched the documentation and the internet for datetime/between usage and discussions.  I can't determine what to do.

The POSTed/"exported" json exports the dates as "1/1/2018, 1/31/2018" instead of ["1/1/2018", "1/31/2018"].  During GET/"import" the dates are mangled.

If I "hand edit" our stored values to ["1/1/2018", "1/31/2018"], the GET/"import" works.

I added moment.js in case it is required for this, but it didn't help.

I can see that the Widgets example works if I set a datetime/between.

Does anyone have an idea of what is wrong?

**Comment by mistic100** [comment]
I cannot help you without your configuration !!

If the demo works, look at the source http://querybuilder.js.org/assets/demo-widgets.js
