### ISSUE TITLE
Plugin as functions

### ISSUE THREAD

**Issue by metanav** [mistic100/jQuery-QueryBuilder#647]
Can we write rules converters for example,  https://github.com/piotch/jQuery-QueryBuilder-Elasticsearch without making them a plugin?
What I really want to get rules from getRules() and pass them to a converter function. What should I do to make such a function based on the methods as in  https://github.com/piotch/jQuery-QueryBuilder-Elasticsearch?  I just wanted to make sure the plugin is not dependent on any methods from the jQuery-QueryBuilder library so that transforming them to an independent function will be straightforward.

**Comment by mistic100** [comment]
Yes you can. I don't know what I can add, create a function that takes the JSON as input and transforms it.

But what is the problem with plugins ?

**Comment by metanav** [comment]
There are 2 reasons:
1. I want to keep the converter as a pure functions. So testing will be easier outside of the framework. 
2. I want to reuse (rewrite) few plugins for a different library: https://github.com/zebzhao/Angular-QueryBuilder

**Comment by mistic100** [comment]
So I answered: yes you can. Don't know what are really asking here. Just extract the function and make it autonomous.
