### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by abukres** [mistic100/jQuery-QueryBuilder#649]
I have run bower, npm and installed grunt and installed everything that it complained was missing. I have the bower_components, dist and node_modules with tens subfolders and the example.html still shows the button and no way to create the query.

What else do I need to do? I which there's a release zip file and all I have to do is unzip and it just runs instead of going through all those steps which can be broken at any stage.
Please put a release zip file which has everything for this to just run. I don't care how big it is. Downloading it will be a ton better than going through this agony.

**Comment by mistic100** [comment]
Did you also ran `bower install` inside the examples folder ?

**Comment by abukres** [comment]
Yes. It created a bower_components folder under the examples folder

**Comment by mistic100** [comment]
If you download/checkout the `dev` branch now you will just have to run `npm install` in the root directory, I removed all need for Bower.
