### ISSUE TITLE
Set only unique rule in query builder 

### ISSUE THREAD

**Issue by Pryanic** [mistic100/jQuery-QueryBuilder#651]
I want to allow only unique rules in my query builder how I can do it? 
I tried to make magic with beforeAddRule and afterUpdateRuleValue events, but this didn't help. Could you help me with this problem, please?

**Comment by mistic100** [comment]
Please describe what "unique rules" mean.

Try http://querybuilder.js.org/plugins.html#unique-filter

**Comment by Pryanic** [comment]
I use query builder and I have the following rules
 `rules= {
    condition: 'AND',
    rules: [
        {
            id: 'myId',
            label: 'label',
            type: 'string',
            operators: ['equal'],
            input: 'select',
            values: {
            'a':'a',
            'b':'b',
            'c':'c'
        }
        }
    ]
};`
And I want if in one rule user select label equal a in other blocks user can't select a

**Comment by Pryanic** [comment]
I want if user select a in first rule and b in second rule in the last rule only c available. Can I do it?
![image](https://user-images.githubusercontent.com/13783593/37345757-4af34c7a-26d6-11e8-96ed-f610af4e8f8f.png)

**Comment by mistic100** [comment]
Ok, it's the link I gave.

**Comment by mistic100** [comment]
Ok so it's not a "unique rule" at all, it's a unique value.

Yes you can use a combinaison of :

- `afterUpdateRuleValue.queryBuilder` and  `afterDeleteRule.queryBuilder` register which values are used
- `getRuleInput.filter.queryBuilder` alter the select HTML before insertion in the DOM

**Comment by Pryanic** [comment]
The first thing is clear for me and I tried to do it. But sorry I don't understand what is mean 

> getRuleInput.filter.queryBuilder alter the select HTML before insertion in the DOM

Can you show small example please?

**Comment by Pryanic** [comment]
I tried this it doesn't resolve all my probles. Now third rule can't set value from first or second rule, but first rule can set value from any rule

**Comment by mistic100** [comment]
I can only advise you to setup the event handlers, open your developer console and put a breakpoint inside them.

This the only way you understand what is going on and what you need to do. Copy-pasting my code won't help.
