### ISSUE TITLE
Select and input fields in value 

### ISSUE THREAD

**Issue by AbdurRehman26** [mistic100/jQuery-QueryBuilder#652]
Hi great plugin.. I just have one query 

This is the jsfiddle i am following and trying to add a select after the input , I was able to do it but when i try to get json response i get html 

https://jsfiddle.net/89byg4wh/95/

![image](https://user-images.githubusercontent.com/21219332/37401048-adf3a5e0-27a8-11e8-8632-38825e83ee07.png)

**Comment by mistic100** [comment]
What about linking YOUR code ?
