### ISSUE TITLE
Querybuilder version 2.5.0

### ISSUE THREAD

**Issue by fengzhihenxs** [mistic100/jQuery-QueryBuilder#655]
1. What are the improvements in Querybuilder version 2.5.0 compared with 2.4.5?

2.Querybuilder if the input type of the filters is the radio that is dragging the outermost border of the Querybuilder, the value selected by the radio appears to be a problem in the display。

3.Hope to give a solution to the problem

**Comment by mistic100** [comment]
Please to not open multiple issues about the same thing.

I know the problem but I cannot fix it, working with drag-and-drop is tricky as this bug is minor.
