### ISSUE TITLE
Angular 4 + jQuery-QueryBuilder

### ISSUE THREAD

**Issue by vaibhav2018** [mistic100/jQuery-QueryBuilder#656]
I was having this issue $(...).querybuilder is not a function

![scrshtext endext querybuilder not a function](https://user-images.githubusercontent.com/37400751/37706828-e03e41f8-2d26-11e8-91b5-780c7f1ad98d.png)

For code I've attached a public gitlab link
please check and guide me what I'm doing wrong
http://192.168.2.2:8008/vaibhav.gangwani/QueryBuilder.git

**Comment by mistic100** [comment]
192.168.0.0 is your private network !!!!!

If it says "$.extendext is not a function" you are probably missing the required dependencies linked in the documentation http://querybuilder.js.org/#dependencies

**Comment by vaibhav2018** [comment]
Sorry for the pvt link.
This is public: https://gitlab.com/gangwani/QueryBuilder.git

@mistic100 please check I added all dependencies in .angular-cli.json
But not sure if it is right!

**Comment by mistic100** [comment]
The documentation explicitely says :
> A  standalone version is available with $.extendext and doT.js included 

So you added QueryBuilder twice (normal + standalone), and each library twice too.
And the order is totally wrong : jQuery must be loaded first, it's the main dependency !

```json
"scripts": [
        "../node_modules/jquery/dist/jquery.min.js"
        "../node_modules/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js"
      ]
```

**Comment by vaibhav2018** [comment]
@mistic100 thanks, buddy it worked

But one thing again I am facing is the AND / OR buttons not rendered as buttons but only as text.
I have already pushed the code for same which I followed from
[](http://querybuilder.js.org/assets/demo-basic.js)
![and or](https://user-images.githubusercontent.com/37400751/37755263-c3929fd2-2dca-11e8-87df-1812625abc92.png)

It'd be completely fine if you close this issue and want me to open a new one for that.

**Comment by mistic100** [comment]
Once again I think you didn't read the documentation which states you need "Bootstrap >=  3.1 CSS" or use this http://querybuilder.js.org/dev/no-bootstrap.html

**Comment by ThakkarKhushbu** [comment]
Hello ,
I want to use https://querybuilder.js.org/dev/no-bootstrap.html , Query Builder without Bootstrap ,And then you need a bunch of CSS rules to mimic Bootstrap buttons ,

where i can add css?
