### ISSUE TITLE
Querybuilder towing problem

### ISSUE THREAD

**Issue by fengzhihenxs** [mistic100/jQuery-QueryBuilder#658]
Querybuilder if the input type of the filters is the radio that is dragging the outermost border of the Querybuilder, the value selected by the radio appears to be a problem in the display.as follows：

Before  towing：
![image](https://user-images.githubusercontent.com/37610470/37805843-9aae6c1a-2e77-11e8-8684-e36c9097a984.png)
Drag beyond the border：
![image](https://user-images.githubusercontent.com/37610470/37805888-c979ffb4-2e77-11e8-8eed-312b63507eff.png)

**Comment by mistic100** [comment]
The correct term is "dragging", not "towing".
This bug is probably already fixed if you update your libs => #660
