### ISSUE TITLE
bootstrap-tagsinput compatibility/integration

### ISSUE THREAD

**Issue by adamathefrog** [mistic100/jQuery-QueryBuilder#659]
I'd like to be able to allow users to use bootstrap-tagsinput to create freeform 'in' conditions. This is useful where the number of options is huge, or where it's things like IP addresses which can't easily have a dropdown.

At present these are presented like this : 

http://zeta.memetic.org/~adama/monosnap/chrome_2018-03-23_02-00-10.png

But I'd prefer (not least of which for readability) to be able to use this : 

https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

I managed to fight through implementing querybuilder, but my JS skill is still way too low to be able to work out how one would implement a new input style.

Is this something that's actually relatively easy to do? Or is it something you'd be willing to consider adding in future?

Oh, and thanks for the library. It very nicely solved a difficult probably for us!

**Comment by mistic100** [comment]
This case is already covered by the doc : use the `plugin` and `plugin_config` options on the filter http://querybuilder.js.org/#filters

As this widget is a jQuery plugin, it's straightforward :

```js
{
  id: 'bgp_peer_peer_asn',
  plugin: 'tagsinput'
}
```

If you want you values as array add `value_separator: ','`

**Comment by adamathefrog** [comment]
Hmm. Is it possible to do this only on certain filter/operator pairs?

Also, adding that as plugin doesn't have the expected outcome. It puts all of the possible options into the tags box when the filter has a values list, which is... of questionable usefulness.

If it doesn't have a values list, it gives an empty box (even if there should be something there), which is also questionably useful! :D

**Comment by mistic100** [comment]
No, there is open issue about that.

--------------

If you want help **create a jsfiddle** or at least show what you did !

**Comment by mistic100** [comment]
QueryBuilder provides a way to use any jQuery widget, it's up to you to configure it correctly.
