### ISSUE TITLE
Querybuilder towing problem

### ISSUE THREAD

**Issue by fengzhihenxs** [mistic100/jQuery-QueryBuilder#660]
Rules disappear when dragging, rules show problems （v2.4.5）
before：
![image](https://user-images.githubusercontent.com/37610470/37809827-00b631be-2e8c-11e8-8702-e6887638e098.png)
after（A rule disappears when it is displayed）：
![image](https://user-images.githubusercontent.com/37610470/37809862-36d1946e-2e8c-11e8-96ad-371099fcce8e.png)

**Comment by mistic100** [comment]
You should update to 2.5.0 with interact 1.3
https://github.com/mistic100/jQuery-QueryBuilder/releases/tag/2.5.0
