### ISSUE TITLE
Sortable in new version of QB drag by full row

### ISSUE THREAD

**Issue by landy2005** [mistic100/jQuery-QueryBuilder#662]
In previous version of QB (2.4.x) with sortable plugin, rows dragged by click on icon.
But in latest version (2.5) rows dragged by click on any place in row.

This produce some troubles (especially with selects).
When select with long list and try to click on scrollbar, than row dragged (instead scroll list).

Possible to return old behavior or make option for this plugin (ie drag_by_icon)?

**Comment by mistic100** [comment]
Can try to rename "allowForm" into "allowFrom" here https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/sortable/plugin.js#L52 ?

If this works I'll release a fix tonight.

**Comment by landy2005** [comment]
Yep, that fix issue :)
