### ISSUE TITLE
jQuery-QueryBuilder/Crossfilter2 integration

### ISSUE THREAD

**Issue by kbe69** [mistic100/jQuery-QueryBuilder#664]
Hi all,

I would like to integrate the excelent JQuery-QueryBuilder interface with Crossfilter using function filter (https://github.com/crossfilter/crossfilter/wiki/API-Reference#dimension_filterFunction). My first idea was to use json-logic-js.

I would like to know if someone already studied this cas?

Thanks

**Comment by mistic100** [comment]
For this kind of open question, please use StackOverflow.
