### ISSUE TITLE
Filter values dependency

### ISSUE THREAD

**Issue by kbe69** [mistic100/jQuery-QueryBuilder#665]
Hi all,

Is there an easy way to implement hiearchical filters?

The idea is that the proposed values for one filter depend on the selected value for another filter.

Thanks for your help

**Comment by mistic100** [comment]
I don't have time to create a full working example. But using the various events (see the documentation) you will be able to filter the available values.

Particularly `getRuleValueSelect.queryBuilder.filter` to alter the `<select>` HTML just before render.
