### ISSUE TITLE
Unable to get working with RequireJS

### ISSUE THREAD

**Issue by vedbhawsar** [mistic100/jQuery-QueryBuilder#666]
I am using the latest version 2.5.1 with requireJS. But it always give me **undefined function error**. Below is my configuration:

```
paths: {
    jquery: 'js/libs/jquery/jquery-2.1.1',
   'query-builder': 'js/libs/QueryBuilder/js/query-builder',
        'doT': 'js/libs/QueryBuilder/js/doT',
        'jquery.extendext': 'js/libs/QueryBuilder/js/jQuery.extendext'
  },
  shim: {
    'jquery.extendext': {
            deps: ['jquery'],
            exports: 'jquery.extendext'
        },
        'doT':
        {
            deps: ['jquery'],
            exports: 'doT'
        },
        'query-builder': {
            deps: ['jquery','jquery.extendext','doT'],
            exports: 'jquery.fn.queryBuilder'
        }
  }
```
Below is my calling on page
```

define([
  'jquery',
  'underscore',
  'backbone',
    'jquery.extendext', 'doT', 'query-builder',
    'bootstrap',
    
], function ($, _, Backbone) {
});
```

**Comment by vedbhawsar** [comment]
I have followed the issue #85 but even that is somehow not working. And that issue is for an older version. now we have `doT.js ` as a dependency. Can some please let me know the exact call for requireJS config section.

**Comment by mistic100** [comment]
You should not need the shims, everything is well defined in the loader :
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/dist/js/query-builder.js#L8

Probably the key for doT in `paths` must be `dot/doT`. And in you app itself, just require `query-builder` unless you use doT and extendext yourself

**Comment by mistic100** [comment]
Yeah and tell us where the error is thrown, otherwise it's very hard to help !!

**Comment by vedbhawsar** [comment]
@mistic100 Thanks for your reply, this would help.  I am getting the error on below line:

 ```
$('#divQueryBuilder').queryBuilder({
....
});
```
It says  **`Uncaught TypeError: $(...).queryBuilder is not a function`** 

I will change the config now and test again. Thanks.

**Comment by vedbhawsar** [comment]
Hey now I got it working. I removed the `shims` part form requireJS config and changed the key for `doT` as you suggested. Also in my I just 

> You should not need the shims, everything is well defined in the loader :
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/dist/js/query-builder.js#L8

> Probably the key for doT in paths must be dot/doT. And in you app itself, just require query-builder unless you use doT and extendext yourself

These saved me. Thanks a lot.

**Comment by vedbhawsar** [comment]
Closing the issue.
