### ISSUE TITLE
Case Insensitive Filter is raising error "Unable to parse WHERE clause" when using setRulesFromSQL 

### ISSUE THREAD

**Issue by ocobacho** [mistic100/jQuery-QueryBuilder#667]
I need a case Insensitive filter so I follow the solution on this issue https://github.com/mistic100/jQuery-QueryBuilder/issues/257 wich changes LIKE for ILIKE on the sql operators and that works great but when I try to load the sql back into the query builder it raises "Unable to parse Where clause" error. What I'm my missing here? is there a better way to do this? Thanks in advance.

**Comment by mistic100** [comment]
The last comment on the other issue stills apply.
