### ISSUE TITLE
Querybuilder without any rule when loaded

### ISSUE THREAD

**Issue by rajwantprajapati** [mistic100/jQuery-QueryBuilder#670]
I want, querybuilder to be loaded without any rule block as in screenshot.
![image](https://user-images.githubusercontent.com/34793260/38383476-3a130e48-392a-11e8-8ca5-a99327f479ba.png).

I tried to remove the created element (<dd> with class .rules-group-body) after init, but could not.
jsfiddle link: https://jsfiddle.net/42t6chv6/64/

Please help me on this.

**Comment by mistic100** [comment]
```js
$('#builder').queryBuilder({
 filter: [],
 allow_empty: true,
 rules: {condition: 'AND', rules: []}
});
```

**Modifying the DOM is guaranteed to break everything !!**, and this is valid for any library you can use, not only QueryBuilder. When a library has options and an API, use them.

**Comment by rajwantprajapati** [comment]
Thank you so much. It is working fine.
