### ISSUE TITLE
Suggest feature

### ISSUE THREAD

**Issue by standus** [mistic100/jQuery-QueryBuilder#671]
QB will be perfect with suggest feature with ajax functionality.
When I write characters in text field it will send ajax request and response will be list of choices.

**Comment by mistic100** [comment]
You can enabled any jQuery plugin (for example the Selectize) with the `plugin` and `plugin_config` options http://querybuilder.js.org/#filters

There is even a demo with source code http://querybuilder.js.org/demo.html#widgets
