### ISSUE TITLE
Last rule removed, not set condition buttons to enabled

### ISSUE THREAD

**Issue by gastonmunoz** [mistic100/jQuery-QueryBuilder#673]
When the last rule is removed, the condition buttons are still disabled.

**Comment by mistic100** [comment]
Excuse me, what ?

**Comment by gastonmunoz** [comment]
Delete all rules and the buttons "and", "or" are still disabled.

![1](https://user-images.githubusercontent.com/38219335/38507262-7ad6510e-3bf2-11e8-901c-8db0422e5164.PNG)
