### ISSUE TITLE
Generate form items stopped on first unknown filter

### ISSUE THREAD

**Issue by landy2005** [mistic100/jQuery-QueryBuilder#675]
We have rulesets (migrated at some way from old), where some items not need to use anymore.
But all other items should be editable.

Here lines marked with orange line is should be skipped.
<img width="1288" alt="observium network monitor noc - group 2018-04-11 11-21-25 1" src="https://user-images.githubusercontent.com/217520/38605104-15ee9956-3d7b-11e8-8b40-70e34de11f27.png">

But all items after 'device.location match Stack*' not generated in form. (Still should be: port.ifSpeed, port.ifType)

Parts of generated code:
[example.js](https://gist.github.com/landy2005/dadf9ce89ffc83b40c8a0e922c67d9ca)

version 2.5.1

**Comment by mistic100** [comment]
Do not use the init `rules` property bu use the `setRules` method with `allow_invalid: true`
http://querybuilder.js.org/#method-setRules

**Comment by landy2005** [comment]
yah, tnx. that resolve my issue :)
