### ISSUE TITLE
search text '$0' replace with ?

### ISSUE THREAD

**Issue by skemnaik** [mistic100/jQuery-QueryBuilder#676]
Search text '$0' replace with '?' while executing getSQL() method. I am using IE 11.
Not sure if there are any other key combinations replace these but I have found this first one.

I am trying to search InstrumentDescription equal 'BHP BILLITON ORD $0.50'
But execution of getSQL() returns, InstrumentDescription = 'BHP BILLITON ORD ?.50'

**Comment by mistic100** [comment]
How do you use `getSQL` ? If you don't use statements, do not set the first parameter

**Comment by skemnaik** [comment]
Thanks for your quick reply.
I am using following way to read sql text and display on my div tag 'query'.

var result = $('#builder-widgets').queryBuilder('getSQL');
var retrunQuery = ''
if (result != null && result.sql.length) {                    
      retrunQuery = result.sql;
}

$('#query').html(retrunQuery);

**Comment by skemnaik** [comment]
I can replicate issue on Demo pages of JQuery builder.
![jquerybuilder_issue1](https://user-images.githubusercontent.com/9865667/38796772-503e1a50-4154-11e8-8717-13ceea1b1b05.PNG)
