### ISSUE TITLE
selectpicker problem: tick is missing when component initialized

### ISSUE THREAD

**Issue by riskop** [mistic100/jQuery-QueryBuilder#677]
I use Bootstrap's selectpicker with multiple=true and liveSearch=true. It's working fine, but when the queryBuilder component is initialized with the rules the selectPicker component has no "ticks" on the selected values.

For example, if I initialize the component with value="value1", I would expect to see a tickmark next to value1 in the dropdown. However there's no one.

The missing tick:
![selectpicker_missing_tick](https://user-images.githubusercontent.com/1511373/38670639-9f3274fc-3e49-11e8-8265-058c2bf02fd4.png)

The expectation:
![selectpicker_expected](https://user-images.githubusercontent.com/1511373/38670668-bb475644-3e49-11e8-9793-5bfc394aee60.png)

Code to reproduce:

    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
      <title>jQuery QueryBuilder</title>
    
      <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
      <link href="http://querybuilder.js.org/assets/css/docs.min.css" rel="stylesheet">
      <link href="http://querybuilder.js.org/assets/css/style.css" rel="stylesheet">
    
      <style>
      </style>
    
      <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
      <script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.3.0/bootbox.min.js"></script>
      <script src="http://querybuilder.js.org/assets/js/docs.min.js"></script>
      <script src="http://querybuilder.js.org/assets/js/script.js"></script>
    </head>
    
    <body>
    
      <div class="container bs-docs-container">
        <div class="row">
          
    
          <div class="col-md-9" role="main">
    
    <section class="bs-docs-section clearfix">
      <h1 id="basic" class="page-header">
      selectpicker problem: tick is missing when component initialized
      </h1>
    
      <div class="col-md-12">
        <div id="builder-basic"></div>
    
        <div class="btn-group">
          <button class="btn btn-primary parse-json" data-target="basic">get json</button>
        </div>
      </div>
    </section>
    
    <link href="http://querybuilder.js.org/dist/bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css" rel="stylesheet">
    <link href="http://querybuilder.js.org/dist/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css" rel="stylesheet">
    <link href="http://querybuilder.js.org/dist/selectize/dist/css/selectize.bootstrap3.css" rel="stylesheet">
    <link href="http://querybuilder.js.org/dist/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
    <link href="http://querybuilder.js.org/dist/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">
    <link href="http://querybuilder.js.org/dist/jQuery-QueryBuilder/dist/css/query-builder.default.min.css" rel="stylesheet">
    
    <script src="http://querybuilder.js.org/dist/moment/min/moment.min.js"></script>
    <script src="http://querybuilder.js.org/dist/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
    <script src="http://querybuilder.js.org/dist/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js"></script>
    <script src="http://querybuilder.js.org/dist/selectize/dist/js/standalone/selectize.min.js"></script>
    <script src="http://querybuilder.js.org/dist/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="http://querybuilder.js.org/dist/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js"></script>
    <script src="http://querybuilder.js.org/dist/sql-parser/browser/sql-parser.min.js"></script>
    <script src="http://querybuilder.js.org/dist/interactjs/dist/interact.min.js"></script>
    
    <script>
    var rules_basic = {
      condition: 'AND',
      rules: [
      {
        id: 'sender',
        operator: 'in',
        value: 'value1'
      }
      ]
    };
    
    $('#builder-basic').queryBuilder({
      filters: [{
        id: 'sender',
        label: 'Sender',
        type: 'string',
        input: 'select',
        multiple: 'true',
        plugin: 'selectpicker',
        plugin_config: {
          liveSearch: 'true'
        },
        values: [
        'value1',
        'value2',
        'senderC',
        'senderCj',
        'senderCk'
        ],
        operators: ['in', 'not_in']
      }],
      rules: {
        condition: 'AND',
        rules: [
          {
            id: 'sender',
            operator: 'in',
            value: 'value1'
          }
        ]
      }
    });
    
    $('#btn-reset').on('click', function() {
      $('#builder-basic').queryBuilder('reset');
    });
    
    $('#btn-set').on('click', function() {
      $('#builder-basic').queryBuilder('setRules', rules_basic);
    });
    
    $('#btn-get').on('click', function() {
      var result = $('#builder-basic').queryBuilder('getRules');
    
      if (!$.isEmptyObject(result)) {
        alert(JSON.stringify(result, null, 2));
      }
    });
    
    
    // reset builder
    $('.reset').on('click', function() {
      var target = $(this).data('target');
    
      $('#builder-'+target).queryBuilder('reset');
    });
    
    // set rules
    $('.set-json').on('click', function() {
      var target = $(this).data('target');
      var rules = window['rules_'+target];
    
      $('#builder-'+target).queryBuilder('setRules', rules);
    });
    
    // get rules
    $('.parse-json').on('click', function() {
      var target = $(this).data('target');
      var result = $('#builder-'+target).queryBuilder('getRules');
    
      if (!$.isEmptyObject(result)) {
        bootbox.alert({
          title: $(this).text(),
          message: '<pre class="code-popup">' + format4popup(result) + '</pre>'
        });
      }
    });
    
    function format4popup(object) {
      return JSON.stringify(object, null, 2).replace(/</g, '&lt;').replace(/>/g, '&gt;')
    }
    </script>
    
    <style>
      .code-popup {
        max-height: 500px;
      }
    </style>
    
    </body>
    </html>

**Comment by mistic100** [comment]
The solution is here https://github.com/mistic100/jQuery-QueryBuilder/issues/661 : add my code or update to 1.13
