### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by LuigiBaute** [mistic100/jQuery-QueryBuilder#679]
I'd like to know if there's the possibility of providing a logo for this project _for free_ if so I'd like to know how we could get in touch. Cheers!

**Comment by LuigiBaute** [comment]
Good morning, I would like to know more details about your project so that the logo is as accurate as possible @mistic100

**Comment by mistic100** [comment]
I think the documentation and demos say it all http://querybuilder.js.org/

**Comment by LuigiBaute** [comment]
![1 2](https://user-images.githubusercontent.com/36426974/39558450-b85d9c7c-4e5c-11e8-91c6-b574743d3924.jpg)
How about?

**Comment by LuigiBaute** [comment]
![segunda propuesta del logotipo querybuilder 2018 1](https://user-images.githubusercontent.com/36426974/39677562-aed035be-5142-11e8-8893-1df2572577dd.jpg)

I tried to deliver what you guys asked, this is what I came up, Its on RGV... Hope you like it! ;)

**Comment by LuigiBaute** [comment]
@mistic100

**Comment by LuigiBaute** [comment]
Greetings, @mistic100 have you check the logo proposal? :)

**Comment by mistic100** [comment]
Honestly, I don't like it. The > and / thing does not integrate well with the text.
Still I am not a designer so I couldn't tell you how to  improve it :-s

**Comment by LuigiBaute** [comment]
The logo alone its understandable, I wanted to show you how the ''B'' were made unique as well, with some programming language, I could do the q and the b appear as googles if you want to take a look on that version? @mistic100

**Comment by LuigiBaute** [comment]
![3 1](https://user-images.githubusercontent.com/36426974/39962149-a93e24ea-5614-11e8-9390-653b31c062e2.jpg)

Greetings @mistic100 ,
I wanted to know your opinion on these ones, if you like any part of any logo I'll combine it however you like! Hope you enjoy it! Cheers!
