### ISSUE TITLE
Old jQuery-QueryBuilder to new version 

### ISSUE THREAD

**Issue by vidishanaresh** [mistic100/jQuery-QueryBuilder#680]
Hi mistic

Thanks for this great tool. I am using jQuery QueryBuilder 2.2.0. now i want to migrate my code to new version. Is there any major changes I need to do in source code.  

Thanks,
Rahul

**Comment by mistic100** [comment]
All the changelog is on the doc http://querybuilder.js.org/changelog.html
I cannot remember _everything_ that changed ! Try it.
