### ISSUE TITLE
How do I implement additional features in existing operators?

### ISSUE THREAD

**Issue by felipefreitasweb** [mistic100/jQuery-QueryBuilder#681]
Hello,

I am facing a small problem with mongodb.
I use the jquery Query Builder to generate my queries in mongodb, however in my collection I have some columns of the object type, and my query needs to be able to check if the value actually exists.
For example:

{"$and":[{"custom_tags.lead.**EMAILADD.value**":{"$ne":""}}]}

_This is the code that the querybuilder generates for me._

The problem is that there will not always be any columns, for example that part in bold does not exist. This code in mongodb returns "true"
I need my querybuilder, in the "is_not_empty" option also check if it exists, like this:

{"$and":[{"custom_tags.lead.EMAILADD.value":{"$exists": true, "$ne":""}}]}

I made this modification:

```
my_builder.queryBuilder({        
                ...
                mongoOperators: {
                    is_not_empty:  function(v) { return { '$exists': true, '$ne': '' }; },
                }
                ...
});
```
Apparently everything worked as it should, the problem is being **setRulesFromMongo**

my_builder.queryBuilder('setRulesFromMongo', rules);

![image](https://user-images.githubusercontent.com/9322269/38989336-e74fd532-43ac-11e8-9e99-8e2662460218.png)

How do I implement additional features in existing operators?

Thank you and sorry for my english...

**Comment by mistic100** [comment]
Right now it's impossible, the method doing the operator matching is private https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/mongodb-support/plugin.js#L357

I'll try to find a way, you can also submit a PR if you have a nice solution.
I think iterating over all the keys until we find a valid operator is a good solution, and crash only when multiple operators are found (with the special case for "between" of course)

**Comment by felipefreitasweb** [comment]
Just to be registered, I was able to solve using the is_not_null tag instead of is_not_empy, And it really makes sense.... thanks
