### ISSUE TITLE
Trying to add a class to a rule's input

### ISSUE THREAD

**Issue by hoverlover** [mistic100/jQuery-QueryBuilder#686]
I'm trying to add a class to a rule's input, but having no luck.  I've tried using the `data` attribute of the `filters` option, but it seems to be ignored.  It's more likely that I don't understand how that option is supposed to be used.

Here'w what I'm trying:

```javascript
  $('#builder').queryBuilder({
    filters: [{
      data: { class: "datepicker" },
      id: 'registered_at',
      label: 'Registered At',
      type: 'datetime'
    }]
  }).on("afterCreateRuleInput.queryBuilder", function(e, rule) {
    if (rule.data && rule.data["class"])
      rule.$el.find("input").addClass(rule.data["class"]);
  });
```

In the callback, `rule.data` is undefined.

Am I using the `data` attribute of the `filters` option incorrectly, and what's the best way to accomplish what I'm trying to do?

**Comment by mistic100** [comment]
The `data` attribute is only used when calling the "getRules" method, it does not actually populate the rule.

but in your event handler you can use `rule.filter.data['class']`

**Comment by hoverlover** [comment]
Thanks!  Worked great.
