### ISSUE TITLE
Querybuilder not clearing data objects on reset.

### ISSUE THREAD

**Issue by thebirdman7** [mistic100/jQuery-QueryBuilder#691]
I am writing an application where I need to save the queries generated out of querybuilder. I am using the default format (not Mongo or SQL).  I am passing my identity elements in the recommended data object on the group and rule levels. When the user clicks create to create a new rule, I call a reset at that time. However when I call the getrules for the new rules, it shows a data element from the last rule on the parent node of the rules.  Unfortunately, what this ends up doing is attaching all my new rules to my old rules. I can probably find a workaround for this, but wanted to let you know. If you have any suggestions that would be great.

Thanks.

**Comment by mistic100** [comment]
Can you show some code ? or better a demo ? Because clearly I don't understand.

**Comment by thebirdman7** [comment]
Thanks for the prompt reply. I will give your suggestion a try.

**Comment by thebirdman7** [comment]
That does work. Thanks!
