### ISSUE TITLE
Multi level dropdown

### ISSUE THREAD

**Issue by maciejkaiser** [mistic100/jQuery-QueryBuilder#692]
Hi,

Is there any possibility to make multi level dropdown on operators menu? I.e. Datetime operator with submenu of operators like 'today', 'in this month', 'in this year' etc.

Something like here:
https://bootsnipp.com/snippets/featured/multi-level-dropdown-menu-bs3

**Comment by mistic100** [comment]
No, but you could create it yourself with some custom operators (https://querybuilder.js.org/#operators) and a plugin.

Here is the plugin initializing Bootstrap selectpicker on the operators dropdown https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/bt-selectpicker/plugin.js
It's only a matter of hook on the good events (the list is here https://querybuilder.js.org/api/list_event.html)
