### ISSUE TITLE
Chosen plugin in the values dropdown

### ISSUE THREAD

**Issue by tamexecutiva** [mistic100/jQuery-QueryBuilder#693]
![image](https://user-images.githubusercontent.com/39101521/39778566-0cde5bcc-52dd-11e8-96d2-50aa638828e5.png)

Hi,
How can i add a chosen plugin to the values dropdown?
Tks.

**Comment by mistic100** [comment]
Hello
did you read the doc ? https://querybuilder.js.org/#filters
`plugin` and `plugin_config` is what you needs
there are even examples https://querybuilder.js.org/demo.html#widgets

**Comment by tamexecutiva** [comment]
@mistic100 thanks for the answer, but i can´t make it works. See my code below:

Look my code below

$('#builder-basic').queryBuilder({
            plugins: {
                'chosen-selectpicker': {
                },
            },
            filters: [{
                id: 'idArea',
                label: 'Área',
                type: 'integer',
                input: 'select',
                plugin: 'chosen-selectpicker',
                values: uaJson,
                operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
            }],
            lang_code: 'pt-BR',
        });

**Comment by mistic100** [comment]
Did you open your console ? You should have a bunch of errors saying "chosen-selectpicker" is not function.

Because you made it wrong, you want to enable a jQuery widget on a filter (`plugin` option), the widget is called "chosen" and it's not a QueryBuilder plugin (`plugins` global option).

```
$('#builder-basic').queryBuilder({
            filters: [{
                id: 'idArea',
                label: 'Área',
                type: 'integer',
                input: 'select',
                plugin: 'chosen',
                values: uaJson,
                operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
            }],
            lang_code: 'pt-BR',
        });
```

**Comment by tamexecutiva** [comment]
@mistic100 Thank you very much! That works!!!
