### ISSUE TITLE
DateTime filter doesn't work with MongoDB

### ISSUE THREAD

**Issue by vickyrathee** [mistic100/jQuery-QueryBuilder#694]
The query builder generate the JSON as below when "date" type is used with MomentJS, while this format doesn't work with MongoDB . Any workaround?

```
{
"$and":[
  {
    "CreatedOn":"2018/05/14"
  }
]}
```

This is my filter

```
{
                id: 'CreatedOn',
                label: 'CreatedOn',
                type: 'date',
                validation: {
                    format: 'YYYY/MM/DD'
                },
                plugin: 'datepicker',
                plugin_config: {
                    format: 'yyyy/mm/dd',
                    todayBtn: 'linked',
                    todayHighlight: true,
                    autoclose: true
                }
            }
```

**Comment by mistic100** [comment]
You need to manually convert the value to a Date or ISODate object on the server.

Why manually ? because ISODate is not Javascript standard, and even Date is not useable because this object is primary meant to be serialized and send to the server, thus no object support.

**Comment by vickyrathee** [comment]
Can't I do that on JavaScript? Something like...

var query = $('#queryBuilder').queryBuilder('getMongo');

console.log(JSON.stringify(query));

for (var filed in query) {
if(field == "CreatedOn")
{
 //set value as "ISODate(" +  value +")"
} 
}

Any suggestion or example code  about how to iterate through the query object and get all key/value to replace in JavaScript? I am fine with result as string, no JSON required.

**Comment by ferreira-guilherme** [comment]
@vickyrathee  You get some advance it?
I need to do that. I have a querybuilder (on mongodb) that contains a date plugin and I need to query dates by greater than or by less than. But the generated mongo query doesn't work on mongo.

**Comment by ferreira-guilherme** [comment]
I got it by changing my mongodb field from date type to string. But the string needs to be on ISO-8601 date format like "1974-11-18T02:00:00.000Z". Now I can query on mongodb using date in literal string
