### ISSUE TITLE
 Property 'queryBuilder' does not exist on type 'JQuery<HTMLElement>'

### ISSUE THREAD

**Issue by ShilpaPrajapati1992** [mistic100/jQuery-QueryBuilder#697]
**Issues guidelines**

Getting this error while using Jquery - query builder in Angular cli project .4
I have added 
interface jQuery {
    queryBuilder(options?: any, callback?: Function): any;
}
in typings.d.ts file too.

**Comment by mistic100** [comment]
Closing for broken guidelines
