### ISSUE TITLE
Wider/bigger field for value?

### ISSUE THREAD

**Issue by fralik** [mistic100/jQuery-QueryBuilder#698]
Is there any way to adjust the width of the value field to take all the available space?

For example, see Query Builder [demo page](https://querybuilder.js.org/demo.html), the very first demo. The field with value 10.25 has lots of space to the right of it before the button `delete` starts. I am attaching the image as well at which I marked the space with right arrow.
![querybuilder](https://user-images.githubusercontent.com/191278/40019044-60db5cf8-57be-11e8-88ad-798a914e7e46.png)

In my case the empty space is even bigger:
![query_space](https://user-images.githubusercontent.com/191278/40019156-b36129d0-57be-11e8-855b-cf070fb8aa60.png)

But the text I would like to enter might be long. So in the end it is quite difficult to use the field.

**Comment by mistic100** [comment]
I take note, it will be considered when working on a new design #279 (not planned)

Switching to a responsive flexbox layout will probably be the solution.
