### ISSUE TITLE
IN operator doesn't work with integer/double data types

### ISSUE THREAD

**Issue by priyank-purohit** [mistic100/jQuery-QueryBuilder#699]
Bug: the IN operator requires the use of `,` to separate the multiple values. However, when setting a column's data type as integer or double, Chrome prevents input of `,` and strips away the `,` when copy-pasting a list of values. The values separator filter option is intended only for text input types.

Edit: in Firefox it allows you to input the `,` but it isn't validated so it's fairly confusing.

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/issues/540#issuecomment-373111948

**Comment by priyank-purohit** [comment]
@mistic100 Doing that still leads to an error and I can't pull the currently built logic by the user.

Failing test case: `column IN 1,2,3,4,5` is a rule I built using this. Then when I do `.queryBuilder('getRules')` I get `null` back.

**Comment by mistic100** [comment]
and the error is ?

If you want more help please respect the guidelines : create a jsfiddle.

**Comment by priyank-purohit** [comment]
https://jsfiddle.net/54q2qhf9/5/ demonstrates the error when building an IN operator query.

Sorry I can't figure out how to get the error it generates. It returns null on error, and the `validate` method too doesn't return any descriptive error (still going through the docs).

**Comment by mistic100** [comment]
You are missing the `value_separator` option (first answer of the issue I linked)

**Comment by priyank-purohit** [comment]
Added it in, but still the same problem: https://jsfiddle.net/54q2qhf9/8/

**Comment by mistic100** [comment]
And the `defaut_value` should be coherent, thus an array

**Comment by priyank-purohit** [comment]
Ah, got it. Thank you!
