### ISSUE TITLE
Filter button doesn't work on presssing enter button (but work when twice enter)

### ISSUE THREAD

**Issue by vickyrathee** [mistic100/jQuery-QueryBuilder#700]
I have this simple Javascript function and wanted to execute it when the user press the "Enter" button to apply the filters.

The filter is added in query builder, but when pressing enter 1st time it display validation error. And then pressing 2nd time apply correctly. Any workaround or if there is any native solution to apply the filter on pressing enter button?

```
 window.addEventListener('keypress', function (e) {
            if (e.keyCode == 13) {
                $('#applyFilter').click();     
            }
        }, false);
```

**Comment by mistic100** [comment]
The keypress event is triggered before the input change event, thus when you try to get the rules, to builder model is not yet up to date.

Try to wait for the next event loop 

```js
setTimeout(function() {
   $('#applyFilter').click();  
}, 0);
```

**Comment by vickyrathee** [comment]
@mistic100 Thanks, this is working perfectly fine now

**Comment by mistic100** [comment]
Or you can remove your handler and use the "rulesChanged.queryBuilder" event https://querybuilder.js.org/api/QueryBuilder.html#.event:rulesChanged

```js
$('#builder').on('rulesChanged.queryBuilder', function() {
  $('#applyFilter').click();
});
```
