### ISSUE TITLE
Single operator on filter results in unnecessary span

### ISSUE THREAD

**Issue by 9b** [mistic100/jQuery-QueryBuilder#704]
The following filter definition will result in a `span` element being shown before the option select. This should not appear as it breaks the flow of the page and serves no value. If two operators are entered, it will render properly. 

```
filters: [{
	id: 'send_email',
	label: 'Send Email To',
	type: 'string',
	operators: ['equal']
}]
```
<img width="1303" alt="screen shot 2018-06-09 at 8 42 33 pm" src="https://user-images.githubusercontent.com/505557/41197279-1702efde-6c26-11e8-8bc4-1c068c18d9ba.png">

**Comment by mistic100** [comment]
The bug is actually that the select is not hidden, probably because you do not have a definition for the "hide" class.

https://getbootstrap.com/docs/3.3/css/#helper-classes-show-hide (it should be "hidden" but "hide" works)
