### ISSUE TITLE
Build jQuery-Query builder from options

### ISSUE THREAD

**Issue by ThakkarKhushbu** [mistic100/jQuery-QueryBuilder#708]
Hello , I am using jQuery-Querybuilder in my Angular 4 , It is working perfectly fine.

What I am doing is ,I am creating rule and group and fetching SQL using getSQL , and storing it into DB . Now in edit mode I want to bind Query builder using same option I have choose at Add time , i have check rule_basic but didn't work.

pls help

**Comment by mistic100** [comment]
If you want to populate the builder with a SQL query, use "setRulesFromSQL" method
this is in the doc https://querybuilder.js.org/plugins.html#sql-support juste bellow "getSQL" you already used.
