### ISSUE TITLE
[Question] Is there a way to trigger on change event when typing in rule value input?

### ISSUE THREAD

**Issue by jnsoo123** [mistic100/jQuery-QueryBuilder#709]
Im trying to set 
`${'.rule-value-container input'}.on('change', function(){ console.log('test') })` 
to work when im typing in the rule input box but it is not triggering when im typing in it. Is there a way on doing it?

**Comment by mistic100** [comment]
use the "keyup" event.

this is a question you should search/ask on stackoverflow, not here
