### ISSUE TITLE
Replacing bootstrap datepicker with jQueryUI datepicker

### ISSUE THREAD

**Issue by gamosoft** [mistic100/jQuery-QueryBuilder#712]
Hi there, I guess the title says it all but what would be the easiest way to replace the bootstrap datepicker with the one provided by jQuery UI (https://jqueryui.com/datepicker/)?

We already have a lot of code written using the bootstrap version, so we're aiming for the less disruptive take on the replacement.

Thanks a lot!

**Comment by mistic100** [comment]
Both have the same name in jQuery namespace, so just load jQuery UI instead of bootstrap and adapt the "plugin_options" on your filter.

**Comment by gamosoft** [comment]
That works just seamless, just need to tweak a few items and it all integrates nicely. 👍 

Thanks a lot mate!!!
