### ISSUE TITLE
Not working with Webpack

### ISSUE THREAD

**Issue by liamkeily** [mistic100/jQuery-QueryBuilder#715]
I am trying to include jQuery Query Builder with Webpack but not having any luck

This is what i'm currently trying to use:

```
import $ from 'jquery';
import 'jquery-extendext';
import 'dot';
import 'jQuery-QueryBuilder';
```

I get the error `"Uncaught TypeError: $.extendext is not a function"`

Are jQuery Builder and jquery-extendext written to work with CommonJS / Webpack 4?

I've done some debugging and if i change the code to 

```
import 'jquery-extendext';
console.log($.extendext);
import 'dot';
// import 'jQuery-QueryBuilder';
```

I can see that $.extendext is logged as below but jQuery-QueryBuilder isn't seeing it for some reason
```
ƒ () {
        var options, name, src, copy, copyIsArray, clone,
            target = arguments[0] || {},
            i = 1,
            length = arguments.length,
            deep = false,
           …
```

**Comment by mistic100** [comment]
As you can see in the sources, there is nothing fancy in how the dependencies are required.
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/dist/js/query-builder.js
https://github.com/mistic100/jQuery.extendext/blob/master/jQuery.extendext.js

I can not explain what is the problem right now.

PS : you don't need to import dot and extendext yourself.

**Comment by liamkeily** [comment]
I did a lot of debugging and for some reason the instance of jquery that jquery-extendext was trying to extend was different to the jquery instance being used by jQuery-QueryBuilder. 

I was able to fix the issue by adding the following to webpack.config.js. This ensures that the same instance of jquery is used everywhere.

```
resolve: {
        alias: {
            'jquery': path.resolve(path.join(__dirname, 'node_modules', 'jquery'))
        },
    },
```

**Comment by mistic100** [comment]
That was my first idea but Webpack _should_ dedupes the modules...

Good news it works.
