### ISSUE TITLE
is there any way to use boostrap tree view in filter option?? help

### ISSUE THREAD

**Issue by dev-roshan** [mistic100/jQuery-QueryBuilder#716]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [jsDelivr](https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/) and [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by mistic100** [comment]
You can create your own QueryBuilder [plugin](https://querybuilder.js.org/dev/plugins.html)

For example the [bt-selectpicker](https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/bt-selectpicker/plugin.js) plugin enables Bootstrap Selectpicker on both filters and operators dropdowns
