### ISSUE TITLE
Add dynamical change filter function for rule

### ISSUE THREAD

**Issue by Pryanic** [mistic100/jQuery-QueryBuilder#718]
I want to use the feature which allows me to dynamically change drop-down box values. As parameters, this function should take the number of the rule, and new values for drop down in this rule

**Comment by mistic100** [comment]
This is out of the scope of the library (with it's current architecture). If you want dynamic datasources you can use the "plugin" option of the filter with jQuery plugins like Selectize or Chosen.

From within these plugins specific code, once you got the HTMLElement corresponding to the rule container (`.rule-container` CSS class), use the `getModel` method to access the Rule object.

```js
const rule = $('#builder').queryBuilder('getModel', $(this).closest('.rule-container'));
```
