### ISSUE TITLE
Use in Xamarin?

### ISSUE THREAD

**Issue by imsmart-tech** [mistic100/jQuery-QueryBuilder#722]
HELP:

I am looking to port a web app to mobile using Xamarin for Android and iOS.
Is there any way I can use jQuery-QueryBuilder with Xamarin?

**Comment by mistic100** [comment]
You know Xamarin is not hybrid right ? Even though it can be developed in JavaScript it is not the same ecosystem at all.

So : no, you have to start again from scratch. If you want to reuse your codebase go for Cordova (at the cost of bad performances compared to native code).
