### ISSUE TITLE
Select List using Chosen Plugin not Setting Selected When Setting Rules

### ISSUE THREAD

**Issue by njones57** [mistic100/jQuery-QueryBuilder#723]
I am using the setRules ability of query builder to allow users to load pre-saved searches. I also have query builder setup to use Chosen.js for multi-select lists as we are doing that elsewhere on our site. When setting the rules for a multi-select, the selected values are not being set and no selected options are showing.

Here is my setup of the plugin:
```
$("#advanced-search-query-builder").queryBuilder({
		sort_filters: true,
		// Override the default icons to use the FontAwesome icons.
		icons: {
			add_group: "fas fa-plus-square",
			add_rule: "fas fa-plus-circle",
			remove_group: "fas fa-minus-square",
			remove_rule: "fas fa-minus-circle",
			error: "fas fa-exclamation-triangle"
		},
		plugins: {
			"filter-description": {
				mode: "inline",
				icon: "fas fa-info-circle"
			}
		},
		filters: [
			{
				id: "Status_List_Item_Id",
				label: "Status",
				type: "integer",
				input: "select",
				multiple: true,
				operators: ["in", "not_in"],
				values: [
					{ value: "123", label: "Draft" },
					{ value: "124", label: "New" },
					{ value: "125", label: "Active" },
					{ value: "332", label: "Investigated" },
					{ value: "126", label: "Closed" },
					{ value: "325", label: "Deleted" }
				],
				plugin: "chosen",
				plugin_config: {
					// Empty
				}
			}
		]
	});
}
```

And here is the rule set that I am loading into query builder
```
{
   "condition":"AND",
   "rules":[
      {
         "id":"Status_List_Item_Id",
         "field":"Status_List_Item_Id",
         "type":"integer",
         "input":"select",
         "operator":"in",
         "value":[
            123,124
         ]
      }
   ],
   "valid":true
}

**Comment by mistic100** [comment]
Same problem as #661

**Comment by mistic100** [comment]
you can also use the "valueSetter" filter option to force Chosen to updates (preferred over the event listener)

**Comment by njones57** [comment]
I'm not seeing the selected attribute being set on the generated <select> that chosen is based on so even if I called update on chosen I don't think it would work.

`<div class="rule-value-container">
   <select class="form-control" name="advanced-search-query-builder_rule_0_value_0" title="advanced-search-query-builder_rule_0_value_0" multiple="" style="display: none;">
      <option value="123">Draft</option>
      <option value="124">New</option>
      <option value="125">Active</option>
      <option value="332">Investigated</option>
      <option value="126">Closed</option>
      <option value="325">Deleted</option>
   </select>
   <div class="chosen-container chosen-container-multi chosen-with-drop chosen-container-active" title="advanced-search-query-builder_rule_0_value_0" style="width: 0px;">
      <ul class="chosen-choices">
         <li class="search-field">
            <input class="chosen-search-input default" type="text" autocomplete="off" value="Select Some Options" style="width: 187.203px;">
         </li>
      </ul>
      <div class="chosen-drop">
         <ul class="chosen-results">
            <li class="active-result highlighted" data-option-array-index="0" style="">Draft</li>
            <li class="active-result" data-option-array-index="1" style="">New</li>
            <li class="active-result" data-option-array-index="2" style="">Active</li>
            <li class="active-result" data-option-array-index="3" style="">Investigated</li>
            <li class="active-result" data-option-array-index="4" style="">Closed</li>
            <li class="active-result" data-option-array-index="5" style="">Deleted</li>
         </ul>
      </div>
   </div>
</div>`

**Comment by mistic100** [comment]
not seeing the "selected" attributes in the DOM does not mean the value is not actually selected, when a select value is changed programatically, the corresponding option is not updated. (https://jsfiddle.net/v580e712/1/)

just try it before saying it does not work (https://harvesthq.github.io/chosen/#change-update-events => Updating Chosen Dynamically)

**Comment by njones57** [comment]
I was just confused as other select lists in the application (rendered by .NET MVC) get the selected attribute applied. Using "valueSetter" worked. Thanks!

**Comment by mistic100** [comment]
if you want to paste code, use code blocks (button is in the toolbar)

**Comment by njones57** [comment]
I tried using the code blocks button, it always came out looking like this

```
<div class="rule-value-container">
   <select class="form-control" name="advanced-search-query-builder_rule_0_value_0" title="advanced-search-query-builder_rule_0_value_0" multiple="" style="display: none;">
      <option value="123">Draft</option>
      <option value="124">New</option>
      <option value="125">Active</option>
      <option value="332">Investigated</option>
      <option value="126">Closed</option>
      <option value="325">Deleted</option>
   </select>
   <div class="chosen-container chosen-container-multi chosen-with-drop chosen-container-active" title="advanced-search-query-builder_rule_0_value_0" style="width: 0px;">
      <ul class="chosen-choices">
         <li class="search-field">
            <input class="chosen-search-input default" type="text" autocomplete="off" value="Select Some Options" style="width: 187.203px;">
         </li>
      </ul>
      <div class="chosen-drop">
         <ul class="chosen-results">
            <li class="active-result highlighted" data-option-array-index="0" style="">Draft</li>
            <li class="active-result" data-option-array-index="1" style="">New</li>
            <li class="active-result" data-option-array-index="2" style="">Active</li>
            <li class="active-result" data-option-array-index="3" style="">Investigated</li>
            <li class="active-result" data-option-array-index="4" style="">Closed</li>
            <li class="active-result" data-option-array-index="5" style="">Deleted</li>
         </ul>
      </div>
   </div>
</div>
```

**Comment by lucasprag** [comment]
FYI, I tried this using the valueSetter, it worked and here is my code:
```
```
