### ISSUE TITLE
Add 'infinity' option to integer 'between' operator

### ISSUE THREAD

**Issue by spohara79** [mistic100/jQuery-QueryBuilder#724]
When setting type to 'integer', it would be nice to have an option to set the upper bound to infinity; e.g., represent it as '*'
Count between 1, *

**Comment by mistic100** [comment]
What is the difference to setting the `max` to `undefined` ? (or just do not configure it)

**Comment by mistic100** [comment]
Why no using "greater than" ? 
SQL does not have an infinity keyword, I don't see the benefit over a good old ">="

**Comment by spohara79** [comment]
Good point, I was being stupid.  I am using it in a different fashion than
for building SQL queries, but your suggestion will work for my use case.
Apologies for the noise.

**Comment by mistic100** [comment]
No problem. No question is stupid :-)
