### ISSUE TITLE
Is it possible to use CASE Statement as condition or any sql function in Where condition?

### ISSUE THREAD

**Issue by jhasumit100** [mistic100/jQuery-QueryBuilder#731]
**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [jsDelivr](https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/) and [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by mistic100** [comment]
Not it is out of scope.
You could create your own plugin to handle the required UI changes, alter the generated SQL and read the the AST generated by sql-parser.
Doc about plugins creation https://querybuilder.js.org/dev/plugins.html
