### ISSUE TITLE
Test collection of javascript objects against a built query.

### ISSUE THREAD

**Issue by khanyuriy** [mistic100/jQuery-QueryBuilder#732]
Hi!
Is there any way to test my javascript collection of objects against a built query?

I found plugins for converting query to sql, to mongo . Documentation said that there is parsers for backends. But where is the parser for frontend? How to test vanilla javascript array of objects?

Thanks!

**Comment by mistic100** [comment]
Hello,
you can create your own exporter for tools like http://jsonlogic.com or http://crossfilter.github.io/crossfilter
sql-support and mongo-support plugins are a good start to see how export and import rules for an external system.

**Comment by khanyuriy** [comment]
Thanx for reply! I'll try.

**Comment by gsustalo** [comment]
Hi!
@khanyuriy 
Have you advanced on this topic? It would be very interesting if you share it
Thank you!
