### ISSUE TITLE
MongoDB: Using $elemMatch

### ISSUE THREAD

**Issue by Barto0x192** [mistic100/jQuery-QueryBuilder#734]
Hi,

is there any possibility to use $elemMatch to search in MongoDB Arrays? I tried couple of things but was unable to find the solution.

MongoDB document example I'm trying to search in for a specific name of the element:

```
"mongoarray" : [
                {
                        "name" : "someName1"
                },
                {
                        "name" : "someName2"
                }
]
```

The query I'm searching for is something like this:
```
{
  "$and": [
    {
      mongoarray: {$elemMatch: {name: "someName2"}}
    }
  ]
}

```

Thanks in advance!

BR,
Barto

**Comment by mistic100** [comment]
How to you propose to configure it in the filter definition ?

**Comment by Barto0x192** [comment]
My idea is to implement some kind of custom query formatter as option to the filters. 

If custom formatter for a rule is given, the default rule parser will be skipped for this one. E.g.:

Type: Function, Parameter: user input Return: obj 

```
flexibleSearchOptions = {
  filters: [
    {
      id: 'id',
      label: 'Item-ID',
      type: 'integer'
    },
    {
      id: 'nameInArray',
      label: 'Name',
      type: 'string',
      queryFormatter: function(input){
         var query = {'mongoarray': {$elemMatch: {'name': input}}}   
         return query
      }
    }
  ]
}
```

As result, the query from 'queryFormatter' will be passed 1:1 to the query object. 

I hope you understand my idea. 

BR,
Barto

**Comment by mistic100** [comment]
This is already possible with the `ruleToMongo.filter.queryBuilder` event

```js
builderElmt.on('ruleToMongo.filter.queryBuilder', function(e, rule) {
  if (rule.filter.id === 'nameInArray') {
   e.value = {'mongoarray': {$elemMatch: {'name': e.value}}} ;
  }
});
```

**Comment by mistic100** [comment]
And for query parsing there is the `parseMongoNode.filter.queryBuilder` event but I don't exactly remember what it should do.

**Comment by Barto0x192** [comment]
Great, sorry for this, seems like i oversaw this in the API docs... 

This solution works for me, thanks again!
