### ISSUE TITLE
Lazy loading of values 

### ISSUE THREAD

**Issue by pramatheshh** [mistic100/jQuery-QueryBuilder#735]
I want to bind the values of some filters asynchronously after the control is rendered, currently there is no handler to do so, and i need to wait to get the results from server before rendering the query builder.
If there's a way to hook up some handler and we can bind this value later.

filters: [
              id: "User_Created_By",
				label: "Entered By",
				type: "string",
				input: "select",
				multiple: true,
				operators: ["in", "not_in"],
				values: _<some handler to bind this after control rendered>,_
				optgroup: "User",
				description: "User",
				plugin: "select",

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/issues/188#issuecomment-149940753
