### ISSUE TITLE
Dropdowns are not displaying in querybuilder. Just the buttons are displaying

### ISSUE THREAD

**Issue by RadKarimiShiraz** [mistic100/jQuery-QueryBuilder#736]
This is my cshtml head code:

<head>
    <title>$.extendext</title>
    <link rel="stylesheet" type="text/css" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/query-builder.default.min.css" />       

</head>
/////////////////////////////////////////////////
and this is a part of body

 <div class="dropdown_criteria">
        <h5 class="header">Criteria</h5>
         <div id="builder"></div>
         <script src="~/lib/jquery/dist/jquery.min.js"></script>
          <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
          <script src="~/lib/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js"></script>
          <script src="~/js/form-builder.js"></script>
          <script>
           alert('ee'); </script>
           <script>
            $('#builder').queryBuilder({filters: [{id: 1 }] }); </script>  </div>

///////////////////////////////////////////////
and my js file

 function gp_prepareQueryBuilder() {
            alert('ff')
            var rules_basic = {
                condition: 'AND',
                rules: [{
                    id: 'price',
                    operator: 'less',
                    value: 10.25
                }, {
                    condition: 'OR',
                    rules: [{
                        id: 'category',
                        operator: 'equal',
                        value: 2
                    }, {
                        id: 'category',
                        operator: 'equal',
                        value: 1
                    }]
                }]
            };

            $('#builder').queryBuilder({
                plugins: ['bt-tooltip-errors'],

                filters: [{
                    id: 'name',
                    label: 'Name',
                    type: 'string'
                }, {
                    id: 'category',
                    label: 'Category',
                    type: 'integer',
                    input: 'select',
                    values: {
                        1: 'Books',
                        2: 'Movies',
                        3: 'Music',
                        4: 'Tools',
                        5: 'Goodies',
                        6: 'Clothes'
                    },
                    operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
                }, {
                    id: 'in_stock',
                    label: 'In stock',
                    type: 'integer',
                    input: 'radio',
                    values: {
                        1: 'Yes',
                        0: 'No'
                    },
                    operators: ['equal']
                }, {
                    id: 'price',
                    label: 'Price',
                    type: 'double',
                    validation: {
                        min: 0,
                        step: 0.01
                    }
                }, {
                    id: 'id',
                    label: 'Identifier',
                    type: 'string',
                    placeholder: '____-____-____',
                    operators: ['equal', 'not_equal'],
                    validation: {
                        format: /^.{4}-.{4}-.{4}$/
                    }
                }],
                rules: rules_basic
            });
            /****************************************************************
                                    Triggers and Changers QueryBuilder
         *****************************************************************/

            $('#btn-get').on('click', function () {
                var result = $('#builder').queryBuilder('getRules');
                if (!$.isEmptyObject(result)) {
                    alert(JSON.stringify(result, null, 2));
                }
                else {
                    console.log("invalid object :");
                }
                console.log(result);
            });

            $('#btn-reset').on('click', function () {
                $('#builder').queryBuilder('reset');
            });

            $('#btn-set').on('click', function () {
                //$('#builder').queryBuilder('setRules', rules_basic);
                var result = $('#builder').queryBuilder('getRules');
                if (!$.isEmptyObject(result)) {
                    rules_basic = result;
                }
            });

            //When rules changed :
            $('#builder').on('getRules.queryBuilder.filter', function (e) {
                //$log.info(e.value);
            });
        }

//////////////////////////
and this is a picture of what i see. buttons without dropdowns

![photo_ - - _ - -](https://user-images.githubusercontent.com/40161953/47163086-22ada200-d302-11e8-805e-0f12d5b595c0.jpg)

**Comment by mistic100** [comment]
please create a jsfiddle to reproduc the problem.
