### ISSUE TITLE
Conflict between bootstrap and querybuilder

### ISSUE THREAD

**Issue by RadKarimiShiraz** [mistic100/jQuery-QueryBuilder#737]
Hi,
Is there any conflicts between bootstrap and querybuilder? I have add a querybuilder to my page but dropdowns are not displaying. What would be the problem?

Regards,
Rad

**Comment by mistic100** [comment]
Do not open the same issue twice.
Answer the question I asked in the other one.

Sent from MailDroid

-----Original Message-----
