### ISSUE TITLE
Exporting the SQL Query String back to server from the Sql Server Plugin

### ISSUE THREAD

**Issue by papyr** [mistic100/jQuery-QueryBuilder#738]
Hi, how can I Save/Submit the Query String back to the server from the Sql Server plugin.

**Comment by mistic100** [comment]
You will have to elaborate a little more, I don't understand.

All methods are described in the doc https://querybuilder.js.org/plugins.html#sql-support

**Comment by papyr** [comment]
Hi, I was asking once the user has created/selected his filters, 

1. how can we capture and send the query in SQL or JS form _back to the server as a string_ so that I may save in the Database as _Filter_V2_Invoices_2018_OCT_2nd_ etc.. 

User would like to save all his filters/string. I am trying to associate them with the file and save them in the database

2. Sometimes user wants to have two different filters for smae file for e.g. filter all employees male, and filter all employees married and save them so he can reuse them

**Comment by mistic100** [comment]
It is all in the doc, use "getSQL" and "setRulesFromSQl".
And check the examples sources

Sent from MailDroid

-----Original Message-----

**Comment by papyr** [comment]
thanks closing it. figured it out. 👍
