### ISSUE TITLE
How to add additional criteria in rule itself?

### ISSUE THREAD

**Issue by AriharasudhanV** [mistic100/jQuery-QueryBuilder#739]
Hi,

I would like to add additional criteria from same category in rule itself. Is it possible to do this. If it is possible could you please let me know how to do it. Here with i have attached the requirement in the below image.  From the image the category i "Expense details" and the rule is "paid amount > 80" and i would like to give additional criteria from the same category "Expense details" like "allowed amount > 70". I will disable the category selection in additional criteria or i will hide the category here. Kindly let me know is it possible with this plugin?

![requirement](https://user-images.githubusercontent.com/44609708/47721124-765eaa80-dc75-11e8-9660-213134b12626.PNG)

**Comment by mistic100** [comment]
Hello,
this is not possible

youd could probably create a plugin which does that : add a new button on the rule, when the button is clicked it replaces the rule by a sub-group containing the previous rule and a new one.

The new rule would have the flag "filter_readonly" and the group "condition_readonly" (see details about filters here https://querybuilder.js.org/#method-setRules).

This is a lot of work and tweaking.
