### ISSUE TITLE
Is there a way to add further operator/query sets to a rule?

### ISSUE THREAD

**Issue by drupov** [mistic100/jQuery-QueryBuilder#74]
Right now it's possible to define e.g. an array of operators (as in http://mistic100.github.io/jQuery-QueryBuilder/index.html#operators).

How can I add further query sets (with custom values) to a rule?

**Comment by mistic100** [comment]
What  ?

**Comment by drupov** [comment]
What I mean is having more options together for querying a string, e.g. to have a operator "begins_with" combined with one of the options ("Exact phrase" or "One of the words") together in one rule.

**Comment by mistic100** [comment]
No, you will have to create each single operator you need

Or use AND groups (with the same value)
