### ISSUE TITLE
Demo exporting Sql, cant find #btn-get-sql

### ISSUE THREAD

**Issue by weedkiller** [mistic100/jQuery-QueryBuilder#740]
Hello, I was checking the sample online with everything configured, for the _Sql Import Export Demo._

I was unable to find `#btn-get-sql`, i.e. the buttons dont have an Id, where is this coming from? do I need to 

 ```
$('#btn-get-sql').on('click', function() {
          var result = $('#Cool-builder').queryBuilder('getSQL', 'question_mark');

          if (result.sql.length) {
            alert(result.sql + '\n\n' + JSON.stringify(result.params, null, 2));
          }   });
```
      

![image](https://user-images.githubusercontent.com/21086190/47958989-53eacb00-dfae-11e8-9f3f-8530e37927f5.png)

**Comment by mistic100** [comment]
These are only for implementation demonstration purpose, the actual event handlers are in view-source: https://querybuilder.js.org/assets/demo.js

It doesn't mater how you do this, I added these demo to show how "getSQL" and "setRulesFromSQL" methods work.
