### ISSUE TITLE
Horizontal Layout in Builder -- shows better sequence

### ISSUE THREAD

**Issue by papyr** [mistic100/jQuery-QueryBuilder#742]
Hello, I am trying to introduce more users to the query builder, I love it. I would be happy to contribute back. Can you please show me how to modify layout to... show a [horizontal flow layout](https://github.com/mistic100/jQuery-QueryBuilder/issues/235)

Something to guide users along like so.. https://i.pinimg.com/236x/84/89/fe/8489fe1da688fe27fae2d91bccebfac0--progress-bar-website-design.jpg

Down the road, maybe a checkbox to transpose the layout between vertical/horizontal.

thanks

**Comment by mistic100** [comment]
What is your question ? I don't understand why you linked a screenshot of a stepline form.

**Comment by papyr** [comment]
The current layout adds steps/ query components, in a vertical sequences, one below the other.

I was asking if its possible to have the same sequential queries in a horizontal sequence of query steps selected, _one after the other_, i.e. left to right -> the other as the picture above.

**Comment by mistic100** [comment]
What would it look like ? can you make a mockup ?

**Comment by mistic100** [comment]
And by the way if it's only a matter of display you can probably do it yourself with a bunch of CSS.

**Comment by papyr** [comment]
Its not CSS, we have a grid table below, so we can show more cols.
A simple checkbox, or options in the plugin configuration for horizontal vs vertical flow layout would help. I attache the picture above -- I drew this below... the bottom part is also the sum part... which from another linked ticket.

![image](https://user-images.githubusercontent.com/12733414/48325337-17008300-e603-11e8-8617-51a1884cbcd6.png)

**Comment by mistic100** [comment]
Well, that's ultra specific, clearly I won't add this layout in the lib.

Sent from MailDroid

-----Original Message-----

**Comment by mistic100** [comment]
For what I understand your diagram each bloc is a seperated query, so I don't even understand why you want this integrated in QueryBuilder itself. Why don't you create your "timeline" yourself and use it to create/update/get a builder placed bellow ?

**Comment by papyr** [comment]
this was a high level brain storm to simply transpose the layout. I took time to create a mockup and communicate what i was tinking. I will close it. thanks
