### ISSUE TITLE
Since Add Group is already there, would it be possible to add SUM to col

### ISSUE THREAD

**Issue by papyr** [mistic100/jQuery-QueryBuilder#744]
I am trying to work out how to SUM a set of filtered results on a Col.

So far - the Filter box has operators inside the box, that fit inside the `Where `clause.

The entire box itself represents the results/group. So I wanted to suggest, if we could add a `SUM `function on the _outside/bottom of the box_ and let user select the col and perform a `sum  `like [here](http://bit.ly/2Dywz4w). The JS version here is also free.

**Comment by mistic100** [comment]
Do you want to use SUM in the WHERE clause or in the SELECT or somewhere else ?

Sent from MailDroid

-----Original Message-----

**Comment by papyr** [comment]
ok thanks

![image](https://user-images.githubusercontent.com/12733414/48325388-59c25b00-e603-11e8-9916-65eb10d4f1f2.png)
