### ISSUE TITLE
Dependency "doT" is not present in the list of deps

### ISSUE THREAD

**Issue by Xobtah** [mistic100/jQuery-QueryBuilder#747]
Hello,

I've had a problem integrating the QueryBuilder to my projet using Bower. I've installed it using "bower install --save jQuery-QueryBuilder" like indicated in the documentation, but when I start brunch with "brunch watch", I get this error:

"Error: Dependency "doT" is not present in the list of deps [angular, angular-route, angular-resource, jquery, rickshaw, d3, angular-ui-grid, angular-translate, angular-translate-loader-static-files, js-quantities, angular-filter, underscore, angular-loading-bar, angular-spinkit, PACE, jQuery-QueryBuilder, bootstrap, moment, jquery-extendext, dot]. Specify correct dependency in bower.json or contact package author."

I found a way to solve this problem by editing the lib's bower.json file, at line 20, replacing "doT": ">=1.0.3" by "dot": ">=1.0.3" with a little "t". Now I'm able to use the query builder.

My problem is that I have to industrialize the projet, and I'm unable to do it since when running "npm install", it installs the QueryBuilder with "doT" with a capital "T", and it doesn't work.
Could you please edit the bower.json file at line 20 with "dot": ">=1.0.3"?

**EDIT**: I've created a pull request attempting to fix this issue

Thank you

**Comment by mistic100** [comment]
The dependency name in Bower is "doT" not "dot" => https://bower.io/search

Why did you installed the dependency with bower if you use npm ? Stick to one package manage and it will work.

**Comment by Xobtah** [comment]
I would if I could, this is not my project, I have constraints on working with bower for front-end libs

**Comment by mistic100** [comment]
Ok but I cannot change the package name for a wrong one...

**Comment by Xobtah** [comment]
I've had a look into my bower_components/ folder, by calling "dot" with small "t" it gets the correct "doT" with a capital "T", only the call to the dependency is with a small "t"
I'm not sure about what this lib does, but I'm using it with the "dot" dependency and it's working perfectly, I only just can't deploy it

**Comment by mistic100** [comment]
Well this is a know problem with doT depending on your build system, because of these two lines https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/.wrapper.js#L3-L6

Because the Bower package name is doT but the require needs to use dot for NPM compatibility.
I cannot do anything, you will have to do a hack in your app, like rename the folder on postinstall step.

**Comment by Xobtah** [comment]
I'm going to do it, thank you for your help
