### ISSUE TITLE
How to replace / populate cols

### ISSUE THREAD

**Issue by papyr** [mistic100/jQuery-QueryBuilder#753]
Hi, sorry for the silly question, going through the documentation I dont see colms option.

So, during initialization of plugin I am trying figure out how to replace the column names (from server side). I can send it but, need to know what form and where to set the column names used, so that the SQL export works with col names?

**Comment by mistic100** [comment]
It is the "name" property of each filter, or the I'd if you don't give a name.

Sent from MailDroid

-----Original Message-----

**Comment by papyr** [comment]
thanks
