### ISSUE TITLE
Is there a way to describe the chosen filters as plain text?

### ISSUE THREAD

**Issue by PirunSeng** [mistic100/jQuery-QueryBuilder#756]
<img width="829" alt="screen shot 2019-01-04 at 10 01 03 am" src="https://user-images.githubusercontent.com/12696293/50671950-c5271880-1007-11e9-9ede-ebbd2d6be4f8.png">

Base on this screenshot, can we have a description like:
```
Price less 10.25
AND
(Category equals Movies OR Category equals Books)
```

**Comment by mistic100** [comment]
You have to do it yourself, you can look at how the SQL serializer works https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/sql-support/plugin.js
