### ISSUE TITLE
Hide Add group Button

### ISSUE THREAD

**Issue by SajithAthukorala** [mistic100/jQuery-QueryBuilder#758]
This is my code : 
`var rules_basic = {
        condition: 'AND',
            rules: [{
                id: 'category',
                operator: 'equal',
                value: 2

        }]
    };

    $('#builder-import_export').queryBuilder({
        plugins: ['bt-tooltip-errors'],
        filters: [{
            id: 'category',
            label: 'Category',
            type: 'integer',
            input: 'select',
            multiple:'true',
            rows:20,
            values: {
                <?php echo $tagset;?>
            },
            operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null']
        }],
        rules: rules_basic
    });
`
How do I remove add group button from here ?

**Comment by SajithAthukorala** [comment]
Found this 
default_group_flags: {condition_readonly: true,  no_add_group: true},

Documentation is really bad , I suggest to improve the documentation since this plugin is really helpful for developers .

**Comment by mistic100** [comment]
Feel free to contribute to the doc

Sent from MailDroid

-----Original Message-----
