### ISSUE TITLE
PlugIn - BT-SelectPicker MultiSelect Option

### ISSUE THREAD

**Issue by JFGauvin** [mistic100/jQuery-QueryBuilder#760]
Hi,

I would like to use the plugin bt-selectpicker on value and enable the multi-select of BootStrap.

Would that be possible to use it with those option from BootStrap ? If yes, can you show me an exemple how to implement ?
From BootStrap :
https://developer.snapappointments.com/bootstrap-select/examples/ 
(Select / Deselect All Options).
<select class="selectpicker" **multiple data-actions-box="true"**>

If not, is there an option to have a Multi-Select of Values not by checkbox ?

JSFiddle
https://jsfiddle.net/jfgauvin/y8xkuqpn/

Thanks

**Comment by JFGauvin** [comment]
Hi, 

Updated JSFiddle, I found the multiple property, but still missing the data-actions-box.
Any idea how to generate it properly ?

https://jsfiddle.net/jfgauvin/1Ltps6cn/2/


Thanks,

**Comment by mistic100** [comment]
Hi

did you read their doc ? https://developer.snapappointments.com/bootstrap-select/options/
the option to enable the actions box is named `actionsBox` (actually the same name as the data- attribute)

**Comment by JFGauvin** [comment]
Thanks, that's what I'm looking for, for reference if someone else search how to use the bootstrap select.

        $("#builder").queryBuilder({
            plugins: [

                'bt-checkbox',
            ],
            filters: [{
                id: 'name',
                label: 'Name',
                type: 'string'
            }, {
                id: 'category',
                label: 'Category',
                multiple: true,
                type: 'integer',
                input: 'select',
                values: {
                    1: 'Books',
                    2: 'Movies',
                    3: 'Music',
                    4: 'Tools',
                    5: 'Goodies',
                    6: 'Clothes'
                },
                operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null'],
                plugin: 'selectpicker',
                plugin_config: {
                    actionsBox: true,
                    liveSearch: true,
                    width: 'auto',
                    selectedTextFormat: 'count',
                    liveSearchStyle: 'contains',
                },

            }, {
                id: 'in_stock',
                label: 'In stock',
                type: 'integer',
                input: 'radio',
                values: {
                    1: 'Yes',
                    0: 'No'
                },
                operators: ['equal']
            }, {
                id: 'price',
                label: 'Price',
                type: 'double',
                validation: {
                    min: 0,
                    step: 0.01
                }
            }, {
                id: 'id',
                label: 'Identifier',
                type: 'string',
                placeholder: '____-____-____',
                operators: ['equal', 'not_equal'],
                validation: {
                    format: /^.{4}-.{4}-.{4}$/
                }
            }],
        });

**Comment by JFGauvin** [comment]
I did fix it with this style override... Not sure where this come from.. 


```
<style>
    .bootstrap-select .btn {
        height: 100%;
        width: 100%;
    }

    .bootstrap-select .dropdown-menu {
        width: 500px !important;
        max-width: 500px !important;
        overflow: hidden !important;
    }
</style>



```
