### ISSUE TITLE
Changing group template to place header under body won't allow dropping a rule into first index of a group

### ISSUE THREAD

**Issue by bgl3317** [mistic100/jQuery-QueryBuilder#765]
After changing the default group template to place `<div class="rules-group-header">...</div>` under `<div class="rules-group-body">...</div>`, a rule can no longer be dragged and dropped into the first index of a group via the sortable plugin. Is there anything I can do to make this work?

**Comment by mistic100** [comment]
Sorry it's not possible. The header is used as "element 0" to be able to drop on the first position.

If you move the header this can no longer work.
