### ISSUE TITLE
Event to get rule value changed

### ISSUE THREAD

**Issue by ferreira-guilherme** [mistic100/jQuery-QueryBuilder#768]
I'm looking for an event that fires only when the user "sets" a value in the filter.

If I use the "rulesChanged" event, the event fires many times (when add filter, when to change operator and etc). If I use the "afterUpdateRuleValue" event, the event will be triggered when the user selects a filter and when setting a value for that filter. Then the event is fired twice.

What I need? When the user sets a value for a filter or removes a filter, I will go to db and run the query and reload the information. If I use these two events, I will go to db unnecessarily

**Comment by mistic100** [comment]
Why don't you test in your `afterUpdateRuleValue` handler that there actually is a value for that rule ?
