### ISSUE TITLE
source not working for me

### ISSUE THREAD

**Issue by karthikks5595** [mistic100/jQuery-QueryBuilder#769]
Source not working for me.. I get only header and options..
they showed plugin missing error in console..
![image](https://user-images.githubusercontent.com/48587478/54423753-6da7d600-4737-11e9-990c-2066cccefcab.png)

**Comment by mistic100** [comment]
did you installed the dependencies with npm ?

**Comment by karthikks5595** [comment]
YEs i have installed all dependencies for that

**Comment by mistic100** [comment]
I started from fresh and I don't have your problem.

I would recommend running the "serve" script instead of directly opening the file, but on my computed it does not prevent the demo from working (just the icons not loading because of CORS).
