### ISSUE TITLE
Chosen plugin

### ISSUE THREAD

**Issue by ferreira-guilherme** [mistic100/jQuery-QueryBuilder#772]
I'm trying use the chosen plugin. I get the exemple on github. If i comment these lines an uncomment the query-builder.js reference line, the chosen plugin doesn't work:

```
<script src="../dist/js/query-builder.js"></script>
<!-- injector:js -->
<!-- <script src="../src/main.js"></script>
<script src="../src/defaults.js"></script>
<script src="../src/plugins.js"></script>
<script src="../src/core.js"></script>
<script src="../src/public.js"></script>
<script src="../src/data.js"></script>
<script src="../src/template.js"></script>
<script src="../src/utils.js"></script>
<script src="../src/model.js"></script>
<script src="../src/jquery.js"></script> -->
```
How can I "install" the chosen plugin? I need reference another js file besides the query-builder.js and the chosen.js files (chosen.jquery.js, chosen-selectpicker/plugin.js, jquery.js)

**Comment by mistic100** [comment]
Why do you change the existing scripts ?

Di you installed the dependencies (`npm install`) ?
