### ISSUE TITLE
Use chosen just on rule value

### ISSUE THREAD

**Issue by ferreira-guilherme** [mistic100/jQuery-QueryBuilder#773]
Is there a wat to use chosen plugin just on the rule value inputs? When I set chosen plugin on querybuilder, the rule filters get stylized by chosen.

**Comment by mistic100** [comment]
The chosen-selectpicker is ONLY applied on filters/operators https://querybuilder.js.org/plugins.html#chosen-selectpicker

To apply a plugin a value input, use the `plugin` options on the filter https://querybuilder.js.org/index.html#filters

**Comment by ferreira-guilherme** [comment]
> The chosen-selectpicker is ONLY applied on filters/operators https://querybuilder.js.org/plugins.html#chosen-selectpicker

Yes, that is the problem. Is there a way to don't apply this? I want that the chosen be applied just on value input

> To apply a plugin a value input, use the `plugin` options on the filter https://querybuilder.js.org/index.html#filters

This is working. I'm doing it.

**Comment by mistic100** [comment]
> > The chosen-selectpicker is ONLY applied on filters/operators https://querybuilder.js.org/plugins.html#chosen-selectpicker
> 
> Yes, that is the problem. Is there a way to don't apply this? I want that the chosen be applied just on value input

Just don't load the plugin at all ? Remove it from the general "plugins" setting

**Comment by ferreira-guilherme** [comment]
Thank you. Worked.
