### ISSUE TITLE
How to add second value into output

### ISSUE THREAD

**Issue by Tomac1** [mistic100/jQuery-QueryBuilder#774]
Hello guys,
 
 query builder is awesome job which helps me a lot. But I am not able to implement additional custom output value. 

As you can see I have multiple values and I need to get a bit number with false/true in particular order to the **second value** (value2). 

How can I add function which will generate this number? Is it **valueGetter**? It produces only one variable, right? **How can I get value2 as second output** (see the screenshot).

Thank you very much for your suggestions.

PS: I checked forum and examples but didn't see simillar issue.

![bit-string](https://user-images.githubusercontent.com/43252106/55003857-71f6ad80-4fd9-11e9-8ce5-bed1d27b1040.JPG)

**Comment by mistic100** [comment]
Is this new value bound to an input ?

- YES : define `input` as a function which returns the DOM for you complex input, and implement `valueSetter` to return both values as an array (**you cannot return two separated values**
   check https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/examples/index.html#L443

- NO : use the event `ruleToJson.filter.queryBuilder` to alter the JSON generated for a rule (**you still cannot have two separated values an must use an array instead**)

If you stil want a separated value you need to post-process your JSON, QueryBuilder cannot do it.

**Comment by Tomac1** [comment]
Thank you for fast reply. Yes this new value is bound to an input. But it not will be parsed back for reading. Its only used in backend processing.

I whink for that suppose will be better to hold first value unmodified as default value for query builder and only add another value which will be used for backend. 
I am looking for better JS way instead of post-processing. But I recognize that post-processing is possible way.
