### ISSUE TITLE
Preventing Jquery QueryBuilder from refresh after 'getRules' called

### ISSUE THREAD

**Issue by ShubhamSmahajan** [mistic100/jQuery-QueryBuilder#777]
Hi @mistic100  thanks for great tool..
Can please look into in my below question:

[https://stackoverflow.com/questions/55568527/preventing-jquery-querybuilder-from-refresh-after-getrules-called](https://stackoverflow.com/questions/55568527/preventing-jquery-querybuilder-from-refresh-after-getrules-called)

**Comment by mistic100** [comment]
Not related to QB, see my answer on SO
