### ISSUE TITLE
Translation not working in the operators

### ISSUE THREAD

**Issue by leandrogehlen** [mistic100/jQuery-QueryBuilder#78]
The translations does not working in the operators

**Comment by mistic100** [comment]
the format changed between 1.3 and the next release
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/dist/i18n/en.js
https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/i18n/en.js

I accepted your pull request whereas invalid because the next release is close
