### ISSUE TITLE
How to get the optgroups object of the selected fields in the getRule json object output?

### ISSUE THREAD

**Issue by saurabhsingh121** [mistic100/jQuery-QueryBuilder#780]
I have requirement to get the optgroups of selected field in the query builder, but as of I am aware queryBuilder('getRules') doesn't provide. For example:- I want to get optgroups object of selected field 'price' in the json output. How to get it? Please give some idea.

- optgroups object

 optgroups: {
        core: {
          en: 'Item'
        }
      }
- json output object

{
  "condition": "AND",
  "rules": [
    {
      "id": "price",
      "field": "price",
      "type": "double",
      "input": "text",
      "operator": "less",
      "value": "10.25"
    }
  ]
}

**Comment by mistic100** [comment]
You can use the `data` property of the filter https://querybuilder.js.org/index.html#filters
It will be copied as it on each rule using the said filter.

**Comment by saurabhsingh121** [comment]
@mistic100  Thanks for help. Your insight resolved my issue.
