### ISSUE TITLE
getRules or rulesChanged returns old values

### ISSUE THREAD

**Issue by AndreasZU** [mistic100/jQuery-QueryBuilder#785]
Hello mistic100,

first of all, thank you for this amassing tool. I love it and especially the event integration!
However i am stuck with this Issue:

My Implementation:
I create always an **input** after the rules, like after the select or checkbox (radio) etc...
This **customText** is stored in rule.data object in key "text".

In my example in JSFiddle i have some predefined filters and rules, which simulates already stored data.
In onload we see that Querybuilder is displaying all values fine, also my **rule.data.text** data is on the right place in my new input.

JSFiddle: https://jsfiddle.net/q62pfbeu/2/

BUG 1:
After onload, if we click "getRules"-Button we will get **not the predefined** value but the first entry(value) of the select-box.

BUG 2:
Start fresh.
If you change the select on the **second rule** or the value in my new custom input.
and press getRules-Button OR event: rulesChanged.queryBuilder
=> We are getting only the first entry(value) of the select from the **first rule**

Only after touching of rules (change-event) we are getting the right values.

Thank You in advance

Best regards,
Andreas

**Comment by mistic100** [comment]
I'll be honest, I don't want to take time to understand your custom code. If you have a specific bug with a concrete example without custom code I'll investigate but I cannot debug your code.

**Comment by AndreasZU** [comment]
Thank you for your quick replay!

I already analysed the hell out of the standalone.js file :D But without success, that why i am posting here.

The Problem is basically because of my new input, something is going wrong while retrieving data in your core-code.

Basically there are only 3 code parts:

1. getRuleValue.filter
   In this event, i am storing the input value to rule.data object

2. getRuleInput.filter
    In this event i am creating my additional input field

3. setRuleInputValue
    I am firing an change-event on that additional input field

That it. 
I would really appreciate, if you find some time to have a second look at the code. Maybe it is a small bug, who knows. But i am 99% sure that something is going wrong in the core-code.

**Comment by AndreasZU** [comment]
So i found the bug in **MY** code.

The Problem was with trigger('change'). It is not necessary at all. But because i fire that event, the value is set to the first one in the select.

`$value.find('[name=' + name + ']').val(rule.data.text).trigger('change');`

Fix:
`$value.find('[name=' + name + ']').val(rule.data.text);`

Sorry for wasting your time ;)
You can close this Issue
