### ISSUE TITLE
No Condition is Passed

### ISSUE THREAD

**Issue by jgriffen** [mistic100/jQuery-QueryBuilder#79]
I'd like to share how I fixed a small bug when applying the filters. The condition did not seem to pass in JSON and I investigated it. Turns out on line **1124** the code was

    return $group.find('>.rules-group-header input[name$=_cond]:checked').val();

That would always return undefined to me. So I changed the code to

    return $group.find('>.rules-group-header input[name$=_cond]').prop('checked', true).val();

This now returns *AND* or *OR* to me when I apply the filters. I hope this helps you out.

**Comment by mistic100** [comment]
```.prop('checked', true)``` is in no way a collection filter

what you are doing here is setting the "checked" property of both radio buttons to true (I imagine the browser only keep the last one) and returns the value of the first radio

I don't think it works as you expect

---

what browser are you using ?

**Comment by mistic100** [comment]
I found articles from 2011 recommending to use ":checked" so I believe it now works everywhere and your problem is elsewhere

**Comment by jgriffen** [comment]
I am using FireFox and Chrome to test. Only the AND condition was selected and it didn't get passed. I refreshed, hard refreshed, restarted my project, and restarted the browser. Nothing worked until I traced the issue back to that line. I used FireBug to test different options with the `prop` and it worked.

**Comment by mistic100** [comment]
No idea. The QUnits tests and my productions apps are running in Chrome, FF and IE.

**Comment by jgriffen** [comment]
Turns out that made it only return AND and never OR. By reverting it back, it now returns OR again. I'm not sure why I had this issue before. But there was no problem with it. Sorry for the confusion.
