### ISSUE TITLE
Universal format to store dates

### ISSUE THREAD

**Issue by l-o-u-k-e** [mistic100/jQuery-QueryBuilder#791]
I'm dynamically initializing QB date fields format according to user preferences stated on my app. I.e. each user can choose a date format among some different ones.
Is there any way (by a property or by a custom script in an event) to store collected dates in an universal format in a rule, despite the user chosen format?

**Comment by mistic100** [comment]
Most datepickers have two formats, one for display and one for storage. You can also use "valueGetter" / "valueSetter" if data processing is needed.
