### ISSUE TITLE
Export SQL, skip empty values

### ISSUE THREAD

**Issue by ManuelSilva85** [mistic100/jQuery-QueryBuilder#792]
Hello,

I'm sorry if this question has already been answered, but i haven't found anything related to it.

My client wants to have the possiblity to build a set of rules, like in the image bellow, and when getting the SQL statement skip the rule with an empty value. 

In this example, when getting the $('#builder').queryBuilder("getSQL"), it would output -> 'price = 50'. 

Is there an option that i am missing? Or is it just not possible? Thanks in advance.

![Screenshot_2019-06-04_22-16-40](https://user-images.githubusercontent.com/39205330/58914943-b90ac880-8717-11e9-9b01-5d79fbd3b651.png)

**Comment by mistic100** [comment]
Did you tried the allow_empty option ?


Sent from MailDroid

-----Original Message-----

**Comment by ManuelSilva85** [comment]
Hello,

Thanks for the quick answer. Yes i tried, but to no avail. Unless i'm not doing it correctly.

I made a quick codepen showing the way i am currently using the allow_empty, i also tried allow_empty_value in the filter level. The result am i currently expecting when the user clicks the 'Get SQL' button is 'category = 1', ignoring the 'name' rule that doesn't have a value. 

https://codepen.io/anon/pen/XwQEaa

Thank you for your time.

**Comment by mistic100** [comment]
Ok, I didn't remember what this option did.

Before calling "getSQL", you can iterate through the model and remove any empty rules. The model is accessible with "getModel" method, you will get a Group object that can be iterated https://querybuilder.js.org/api/Group.html#each

**Comment by hekin1** [comment]
@mistic100 I dont understand how to fetch the model with your solution.
I've tried this: 
```
$('#queryBuilder').queryBuilder('getModel', (x) => {
    console.log(x);
});
```
But the console log shows `jQuery.fn.init` function

**Comment by mistic100** [comment]
```
var x = $('#queryBuilder').queryBuilder('getModel');
```
