### ISSUE TITLE
Integration With JS DataTable

### ISSUE THREAD

**Issue by 77vetter1** [mistic100/jQuery-QueryBuilder#793]
I would like to integrate with DataTable so I can use DataTable functionality for Sorting, and Pagination. I will turn of filtering on the DataTable and use the QueryBuilder functionality for filtering.

I have looked online and couldnt find anything. I have tried it by just setting my table to be a DataTable :  $('#data-table').DataTable();

And when I use the QueryBuilder to add a filter the data gets displayed into my dataTable, but when I try to sort by one of the columns the data disappears. So somehow the sorting is clearing the table. 

Any ideas on getting QueryBuilder and DataTable to work together would be much appreciated.

**Comment by mistic100** [comment]
This is out of scope sorry, I can provide support for the library usage, not side usages with third party libraries.

By the way QB is meant to build filtering rules, not sorting. I think you are using the wrong tool.

Good luck.
