### ISSUE TITLE
Use of bootstrap theme with select2 plugin?

### ISSUE THREAD

**Issue by radiantone** [mistic100/jQuery-QueryBuilder#794]
Hi,
 I see this ticket[1] and I can use select2 in the query builder. But the theme is not set for bootstrap, which I use. Is there a way I can set it? I already have the select2-bootstrap css loaded.

[1] https://github.com/mistic100/jQuery-QueryBuilder/issues/509

**Comment by radiantone** [comment]
Also, how to use ajax remote data loading with select2 inside of jquery builder?

**Comment by mistic100** [comment]
Provide a demo of your problem. I cannot say more anything more than double check you have included all needed CSS files.

---

This is specific to select2, you can configure it however you want, included async datasources

**Comment by radiantone** [comment]
Ok, give me some time to set one up.

**Comment by fr0z3nfyr** [comment]
I vote for closing this issue due to:
1. inactivity
2. un-reproducibility 
    1. select2 default theme: [jsfiddle demo](https://jsfiddle.net/vwyLq21m/)
    2. select2 bootstrap theme: [jsfiddle demo](https://jsfiddle.net/fr0z3nfyr/vwyLq21m/1/)

**Comment by amirgee007** [comment]
is here any tagging option when using select2 as a plugin?
I already used as multiple true but seems like I cannot use tagging true same as select2.
any solution, please?

**Comment by fr0z3nfyr** [comment]
It should be `tags: true` as per `select2` docs. Please create a new issue if you believe you dug up a bug. Resurrecting a closed issue is not in the best interest
