### ISSUE TITLE
Customized Input Fields only work from default/pre-defined rules

### ISSUE THREAD

**Issue by xingguo3** [mistic100/jQuery-QueryBuilder#799]
Hi all, I fount that after I define input fields, it would only works normally as expected if I pre-defined rules.

Case 1: select 2
 Code:
![image](https://user-images.githubusercontent.com/15721650/59736378-f6309800-928b-11e9-9e97-d0e09fcb87a1.png)
Result: 
![image](https://user-images.githubusercontent.com/15721650/59736441-355ee900-928c-11e9-827b-92dc85697317.png)

Case 2: customized input fields: 
code:
![image](https://user-images.githubusercontent.com/15721650/59736483-5d4e4c80-928c-11e9-9baa-79b8f200859c.png)
Result: 
![image](https://user-images.githubusercontent.com/15721650/59736500-7bb44800-928c-11e9-8a30-70f56054e228.png)

If I add rules, it will show a  input field that I don;t expected. Did I miss some step after add rule?

**Comment by mistic100** [comment]
As stated in the issues guidelines, create an online demo.

Sent from MailDroid

-----Original Message-----

**Comment by xingguo3** [comment]
Thanks for the reply. 
I write a demo and it works fine. I guess it's might caused by duplicated css file.
