### ISSUE TITLE
Empty filter is an error?

### ISSUE THREAD

**Issue by mykbaker** [mistic100/jQuery-QueryBuilder#80]
Is there a way to prevent the filter from turning red and displaying errors only when it is empty?

**Comment by mistic100** [comment]
try

```js
$('#builder').on('validationError.queryBuilder', function(e) {
  if (e.error[0] == 'no_filter') {
    e.preventDefault();
  }
});
```

complete list of error codes here https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/query-builder.js#L107

**Comment by mistic100** [comment]
I updated the doc to explain this feature
http://mistic100.github.io/jQuery-QueryBuilder/#events

**Comment by mykbaker** [comment]
Unfortunately this turns off all the no_filter errors. I would like to only turn off the error if there is only one empty filter and no valid filters. Does that make sense? Is that possible?

**Comment by mistic100** [comment]
After calling getRules, and if you get an empty object, You could count the number of rules in the DOM and call "reset" if there is only one
