### ISSUE TITLE
[Question] What's the differences between QueryBuilder constructor and $('').queryBuilder()

### ISSUE THREAD

**Issue by garygao12580** [mistic100/jQuery-QueryBuilder#800]
Just as what I says.
I tried to use both constructor and jQuery function. But I got different results which constructor just show nothing.
Following are what I called:
 ```jsx
 const jqDom = $(this.ref.current);

 const options = {
      plugins: [
      ],
      filters: [],
       rules: []
    }
```

with constructor:

```jsx
this.queryBuilder = new QueryBuilder(jqDom, options);
```

with jQuery dom function:
```jsx

this.instance = jqDom.queryBuilder(options);
```

while the constructor function didn't play well

**Comment by mistic100** [comment]
This is how the constructor is used https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/jquery.js#L33-L35

QB is not designed to be used outside the "jQuery.fn" namespace

**Comment by garygao12580** [comment]
I see. I should call the init function by myself. Thanks.
