### ISSUE TITLE
Changing form name attributes?

### ISSUE THREAD

**Issue by Shpigford** [mistic100/jQuery-QueryBuilder#801]
I'd like to change the form name attributes. Is that possible?

For example, current default output is:
```
<input class="form-control" type="text" name="builder_rule_0_value_0">
```

But I'd like:
```
<input class="form-control" type="text" name="attributes[builder_rule_0_value_0]">
```

Or even:
```
<input class="form-control" type="text" name="builder[rule_0_value_0]">
```

Trying to make it easier for me to process the submitted form.

**Comment by mistic100** [comment]
Not possible without deep changes in the lib.

QB was **never** designed to be used as a form itself, you should call "getRules" method and work on the generated output. By directly accessing the inputs you will bypass all formatters and validators.

Closing as I cannot give you a solution.

**Comment by Shpigford** [comment]
@mistic100 Ah! Fair enough. Is there documentation (or have you seen any articles) on how to use QueryBuilder with a form?

Wondering what the recommend flow is for creating rules and then submitting them as part of a form submission process.

**Comment by mistic100** [comment]
What can I say ? You could get the JSON an put it in a hidden input, construct yourself a FormData and submit it. Send your data in AJAX...
QB gives a JSON object, up to you to choose the best solution for your application.
