### ISSUE TITLE
[Question] Has any suggestions with React?

### ISSUE THREAD

**Issue by garygao12580** [mistic100/jQuery-QueryBuilder#802]
We use React in our project. And I want to use React components for widgets. I wonder If you have any suggestions about that. Thank you.

**Comment by garygao12580** [comment]
I dot't know whether  it is useful to set filter's 'valueGetter' and 'valueSetter' ,   If I want to build some widgets with React. please give me a help.

**Comment by mistic100** [comment]
I don't know React so I cannot help you.

Also I'll close this issue because it is not a forum.

----

valueGetter and valueSetter are used if the underlying widget is not an real input or is more complex. It will indeed be useful to interface with React components.

**Comment by garygao12580** [comment]
thanks
