### ISSUE TITLE
[QUESTION]: event listeners attached to document or parent(s) 

### ISSUE THREAD

**Issue by fr0z3nfyr** [mistic100/jQuery-QueryBuilder#803]
Hi -

I apologize if this is not the right place to ask questions. 

I'm implementing a custom filtering capabilities (advanced search) to my data grids (for the curious ones, I'm using `DataTables`). I'm loving `jQuery-QueryBuilder` so far and gradually learning to control it to my liking using its extensive API (although, I find the API docs a little too confusing or inadequate at some places). 

That's about the background. I was just wondering whether `initializing` and `destroying` the `QueryBuilder` several times can likely pollute the DOM by attaching event listeners to any of the elements higher on the `DOM tree` or the `document` itself. I'm worried because, I use a `bootstrap modal` to `initialize` the `queryBuilder` on show and `destroy` on hide. So, this can happen a couple of times on the same page (because it is used for filtering like I said above). 

A quick glance at the DOM tree suggested (I may be wrong) that the plugin operates within it's own limited DOM scope and is unlikely to cause problems, but I just wanted to be sure. 

Also, is there a documented list of `events`/`properties`/`attributes` that are manipulated/attached during the lifespan (from `init` till `destroy`) of `QueryBuilder`? 

Cheers!

**Comment by mistic100** [comment]
QB does not leave anything in the DOM but has some small memory leaks I didn't adressed : #745

No the internals are not documented, check the code.

**Comment by fr0z3nfyr** [comment]
Cool! Do you have plans to look into fixing this memory leak in near future? I see that the attempts that were made don't actually help much

**Comment by mistic100** [comment]
You can see the developpement is paused for now, I'll keep track of the issue with #745
