### ISSUE TITLE
Custom value separator with (NOT) IN operators

### ISSUE THREAD

**Issue by fr0z3nfyr** [mistic100/jQuery-QueryBuilder#804]
Hi Mistic,

I was working on a setup that'd allow users to use the `IN` and `NOT IN` operators on `type: 'string', input: 'text'`. This work's as long as I set `value_separator: ','` in the setup and ask users to use `,` as separator. 

Now, the problem with `string` fields is that you can never be sure of the text that must be searched. So, let's say, a user wants to search `IN ('sunflower, rose and jasmine', 'lilly, lotus and duckweed')` (notice the `,` within the search strings), how does he enter the string. Same would be the case if I use a different separator like `|`. 

**EXPECTED:**
1. sunflower, rose and jasmine
2. lilly, lotus and duckweed

**ACTUAL:**
1. sunflower
2. rose and jasmine
3. lilly
4. lotus and duckweed

I plan on using an extra input field that will take user input for `value_separator`. How can I update `value_separator` on the fly such that validation and splitting of value (as done by `valueGetter`) is not a problem?

Alternatively, I can attempt to customize my `input` using a `function() { ... }` and use `valueGetter` and `valueSetter` like [demonstrated](https://querybuilder.js.org/demo.html#widgets) for `coordinates` in the linked demo. But, I don't want to get into the hassle of manual validation and other stuff with this approach.

**Comment by mistic100** [comment]
1. change `value_separator` on your filter, the filters array is accessible at
   ```js
   jQueryElement[0].queryBuilder.filters
   ```
2. trigger a input update to refresh the parsed value
   * simple way which will update everything :
    ```js
    jQueryElement.find('[name*=_value_]').trigger('change');
    ```
   * better way to update only the corresponding rules : get the model with "getModel" method, recursively loop the rules filtered by filter id, for each rule get the `$el` (DOM element) then select the value input and trigger the `change` event

**Comment by fr0z3nfyr** [comment]
Thanks Mistic! This seems to do the trick for me. I still have to check if this can have any unintended side effects on `BETWEEN` and `NOT BETWEEN` (any any other `operators` using `value_separator`).

**Comment by limbachia** [comment]
Hello Mistic, 

I am have the same question. I want to be able to take value separator as user input. I have never coded a single line in js, so I don't understand the solution you posted. Do you mind expanding on your solution with more code?
