### ISSUE TITLE
[Question]: Is there any option to have AND/OR between multiple rules, For example I want rule a, b, c, d e and intention is to have json query like = a AND b OR c OR d AND e. Without using "multiple groups". 

### ISSUE THREAD

**Issue by shrajpu** [mistic100/jQuery-QueryBuilder#806]
I have a use case like

Rule -----AND
Rule -----AND
Rule -----ANDRule -----AND

**Comment by mistic100** [comment]
Hello,
no it's not possible and will not.
First because this is not the way I conceived the library (target users do not know the precedence between AND and OR) and it would require too much changes.

**Comment by shrajpu** [comment]
> Hello,
> no it's not possible and will not.
> First because this is not the way I conceived the library (target users do not know the precedence between AND and OR) and it would require too much changes.

just updated my comment, please have a look once again on my use case.

**Comment by mistic100** [comment]
in your example how is this interpreted ?  

`(rule1 AND rule2) OR (rule3 AND rule4) OR rule5`
or
`(((rule1 AND rule2) OR rule3) AND rule4) OR rule5`

Anyway there is not change planned for this behavior, sorry.

**Comment by shrajpu** [comment]
The interpretation of our use case is like (rule1 AND rule2) OR (rule3 AND rule4) OR rule5. which is the default behavior of operator precedence.
