### ISSUE TITLE
use inside web components

### ISSUE THREAD

**Issue by pouyamiralayi** [mistic100/jQuery-QueryBuilder#809]
Hello there! i would be glad to hear from you guys the possibility of using query builder inside web components.
thanks in advance.

**Comment by mistic100** [comment]
why wouldn't it be possible ? did you try something ?

**Comment by pouyamiralayi** [comment]
Hi! thanks for your answer. i am in a project that bootstrap classes overlaps with the other css library i am using, so i decided to go for isolation, (in my case i desired to isolate the js libraries as well).
i used this structure for the web component:
`
const template = document.createElement('template');
template.innerHTML = `
<link rel="stylesheet" href="./css/bootstrap.min.css">
<link rel="stylesheet" href="./css/query-builder.default.min.css">
<script src="./jquery-3.4.1.min.js"></script>
<script src="./popper.min.js"></script>
<script src="./bootstrap.bundle.min.js"></script>
<script src="./jQuery.extendext.min.js"></script>
<script src="./doT.min.js"></script>
<script src="./moment.min.js"></script>
<script src="./query-builder.min.js"></script>
<style>
<div id="builder"></div>
<script src="/js/querybuilder.js"></script>
`;

class QueryBuilderCustom extends HTMLElement {

    constructor() {
        super();
        this.attachShadow({mode: 'open'});
        this.shadowRoot.appendChild(template.content.cloneNode(true));
        const builder = this.shadowRoot.getElementById('builder')
        console.log(builder)
        $('#builder', this.shadowRoot).queryBuilder({
            filters:[{
                id:'name',
                type:'string',
            }]
        })
    }

    appendStyleContent(content){
        var styles = [
            "./css/bootstrap.min.css",
            "./css/query-builder.default.min.css"
        ]
        for (var src of styles){
            var scr = document.createElement('link')
            scr.href = src
            scr.type = 'text/stylesheet'
            content.appendChild(scr)
        }
    }

    appendScriptContent(content){
        var scripts = [
            "./jquery-3.4.1.min.js",
            "./popper.min.js",
            "./bootstrap.bundle.min.js",
            "./moment.min.js",
            "./jQuery.extendext.min.js",
            "./doT.min.js",
            './query-builder.min.js',
        ]
        for (var src of scripts){
            var scr = document.createElement('script')
            scr.src = src
            scr.type = 'text/javascript'
            scr.onload = scr.onerror = null
            content.appendChild(scr)
        }
    }
}

window.customElements.define('query-tag', WhatsUp);

`

the css loads fine, but unless i specify js dependencies in my main html file, they won't be loaded inside the web component. it seems the <script> tags used inside the web component does not have any effects. is there any workaround for this?

my problem is mainly around this matter, so i guess this is not really a problem with query builder itself. 
thanks in advance.

**Comment by mistic100** [comment]
If this is a general question about librairies in WebComponents I cannot help you.

If changes are required to make it work, you can submit a PR but you will probably have problems with other librairies used by QB.
https://stackoverflow.com/a/50750294

**Comment by pouyamiralayi** [comment]
i appreciate your kind answer. i definitely go for a PR.
thanks in advance.
