### ISSUE TITLE
$not cannot be used with $regex for mongo plugin

### ISSUE THREAD

**Issue by risingsunomi** [mistic100/jQuery-QueryBuilder#81]
I fixed this issue on my fork but so you will know the code in https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/plugins/mongodb-support/plugin.js creates an error when using $not and $regex

My fix is in the default config - I have other custom code here so ignore that: 
https://github.com/risingsunomi/jQuery-QueryBuilder-Modified/blob/master/src/query-builder-mongodb-support.js

Let me know your thoughts on this

**Comment by mistic100** [comment]
that sucks...

BTW there is a problem in your commit, you wrote the same thing for not_begins_with and not_contains
and I don't understand your not_ends_with, why not using a negative look ahead ?

**Comment by risingsunomi** [comment]
I change the not_contains just now to fix that issue. Also with not_ends_with I guess I could use a look behind but didn't know if that works with mongodb (doesn't work with Javascript which I mostly have experience using regex in)

**Comment by mistic100** [comment]
from my tests, MongoDB supports negative lookbehind
I also added `'$options': 's'` for not_contains as the regex contains a dot
