### ISSUE TITLE
Boolean "not_equal" works, but "equal" does not...

### ISSUE THREAD

**Issue by jklymak** [mistic100/jQuery-QueryBuilder#815]
I have an app that filters on a boolean field:
```
{
  value: "active",
  label: "Active",
  filter: {
    type: "boolean",
    operators: ['equal', 'not_equal'],
    input: 'radio',
    values: [true, false],
  },
```

Oddly, if I toggle the operator to `not_equal`, the filter works properly, and items with `true` are shown if I select `false`, and conversely if I select `true`.  If I toggle the operator to `equal`, then neither `true` nor `false` work at all.  

(I'm honestly just hacking around, and not well versed in javascript, so I could be doing this all incorrectly.  If this isn't clear, I'll try and make a self-contained example)

**Comment by mistic100** [comment]
When you say
>  and items with true are shown if I select false, and conversely if I select true
you are talking another part of your app or something inside QueryBuilder ?

If you don't show how you are using the filters I don't know how I could help you. Did debugued step by step and analyzed what is the builder output and how it is used ?
Looks like a problem in a part of your app not directly related to QueryBuilder

**Comment by mistic100** [comment]
And yes please make a self-contained example as asked in the issue guidelines.

**Comment by jklymak** [comment]
Thanks, sorry to be vague.  I posted just in the hopes it was a known problem.  

While I'm working on the self contained example, the site is http://cproof.uvic.ca/deployments/.  The "Active" tag is the one I am trying to apply a boolean filter to (accessed via the "Filter Data" button).  

But I fully understand if that is too much digging, and will try in the next few days to make something smaller and self contained.

**Comment by mistic100** [comment]
Well is clearly alasql which is behaving strangely.

In your QueryBuilder configuration, try to add 

```
plugins: {
  'sql-support': {
    boolean_as_integer: false
  }
}
````

**Comment by jklymak** [comment]
Yes, that fixed it.  Sorry if that was obvious 😉  Thanks so much for the help!

**Comment by mistic100** [comment]
To be fair it was not really obvious, this option is not in the doc.
