### ISSUE TITLE
Hide operator label when only a single operator is used

### ISSUE THREAD

**Issue by joewandy** [mistic100/jQuery-QueryBuilder#816]
For some reason, when I only specify a single operator (using just 'equal' in the example below), 

```
        $('#builder').queryBuilder({
            filters: [
                {
                    id: 'padj_HK_vs_UN_gene',
                    label: 'padj_HK_vs_UN (gene)',
                    type: 'integer',
                    input: 'select',
                    values: {
                        1: 'Significant'
                    },
                    operators: ['equal']
                },
        });
```

an extra label ('equal') beside the dropdown list will appear

![image](https://user-images.githubusercontent.com/2523391/64528449-751ff480-d300-11e9-8199-f4474744f512.png)

This is not the case when multiple operators are used. Is there any way to prevent this label from appearing? Thank you.

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/issues/704

**Comment by joewandy** [comment]
Thanks. Following the issue above, I added this to my css as a workaround, and now the select is hidden correctly.
```
.hide {
  display: none !important;
}
```
