### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by aginpatrick** [mistic100/jQuery-QueryBuilder#818]
Hi,
I tried for the first time your component. I used the standalone version along with mapbox-gl.js. I tried something very simple but I get the following error: Uncaught ReferenceError: $ is not defined. I tried to put the query-builder.standalone.min.js before or after the mapbox-gl.js reference but the result is the same.

```
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.1/mapbox-gl.js'></script>
<script src='https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/js/query-builder.standalone.min.js'></script>
...
<div id="builder"></div>
...
<script>
$('#builder').queryBuilder({          <-------- error happens here
    filters: [id="f",type="string" ]
});
...
```

**Comment by mistic100** [comment]
You are missing the jQuery lib https://querybuilder.js.org/#dependencies
