### ISSUE TITLE
Some questions about plugin

### ISSUE THREAD

**Issue by centenario** [mistic100/jQuery-QueryBuilder#82]
Id like to get some info about plugin and hot to work with it.
1º) When i use function getSQL, how can i notice if some rule got any error? I know that when there's some arror res.sql is empty but it's possible too when there's not any rule selected so id like to know difference when is empty 'cause any error or not, cause if there's some error i abort the following operations but if not then i go on.

2º) I'd like to know how can set some value by default in inputs numerics. 
It uses some helpfull spinner but if i set step value in filter config, then number must be a multiplier, f.i. if i set step: 5, and final value is 27 i get error...why?, 

3º) how could i set an spinner for input time type?

Thanks in advance for your great job!

**Comment by mistic100** [comment]
1) no rules is always an error
- errors are displayed with a /!\ icon if [display_errors](http://mistic100.github.io/jQuery-QueryBuilder/#usage) is true
- Global and [filter level](http://mistic100.github.io/jQuery-QueryBuilder/#filters) `onValidationError` callbacks are called when an error occurs
- [`validationError.queryBuilder`](http://mistic100.github.io/jQuery-QueryBuilder/#events) event is thrown when an error occurs (the list of errors codes is also available on this page)

(so much things in this doc)

2) I don't understand what you mean...
You use [this `step`](http://mistic100.github.io/jQuery-QueryBuilder/#validation) ? well it's clear... it the step... 0, 5, 15, 25, 30, ... so no 27 (use the `callback` for advanced validation)

there is no default option currently, that's a good idea, but you can use `onAfterCreateRuleInput` filter callback to set this value

3) find a jQuery plugin which do that

**Comment by centenario** [comment]
Ok, thaks.
About 1, i use this querybuilder for getting where clause for SQL statements. Sometimes you dont need set any rule, so i think it's not any error. I dont know if it's possible get difference between error and no rules, if not, could it be some future feature.
Thanks is advance.

**Comment by mistic100** [comment]
#80

**Comment by mistic100** [comment]
#80 and #84 will be available in release 1.4.1
