### ISSUE TITLE
How about SQL Injection

### ISSUE THREAD

**Issue by garygao12580** [mistic100/jQuery-QueryBuilder#821]
**Issues guidelines**
As the title, I am very curious to assemble the Where condition in the front end, is there a risk of SQL injection?

**Comment by mistic100** [comment]
A best effort is done by calling the escapeString function on each string values 
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/utils.js#L145-L170

If you are (legitimately) worried you should use prepared statements and let your DBMS do the escaping.

**Comment by garygao12580** [comment]
Ok, thanks.
