### ISSUE TITLE
[Feature] Add index parameter in QueryBuilder.prototype.addRule function

### ISSUE THREAD

**Issue by garygao12580** [mistic100/jQuery-QueryBuilder#823]
![image](https://user-images.githubusercontent.com/24784430/65566495-9b42c700-df85-11e9-979e-63a8f172890e.png)

like the above picture, If I change the rule template and add the add button after every rule container. So when I click the add button, it will be nicely to add a rule after the clicked rule.
How should I achieve this ?

 I have two ideas, one of which is to move the current rule to the rule after the initial click in the afterAddRule event, but the problem I am having is that I can't get the index of the rule of the initial click, because the event delegate is used here. Another idea is to prevent the default behavior when beforeAddRule, and then control the logic behind it, but also encountered a problem, when setting the init rule will call the logic of the add rule at initialization, which will cause the init rule not to be initialized.
Please give me some good suggestions, thank you.

**Comment by garygao12580** [comment]
I just found a way to achieve this.
I changed the add button selector  to let event binding won't effect. And then I bind click event in afterAddRule event by myself.   I will call the QueryBuilder instance function `addRule` by myself.
But I find this function does not have the parameter of index. Sadly...
So I hope the the function can support this. I will make a PR for this.

**Comment by mistic100** [comment]
```
builder.$el.on('click.queryBuilder', '.your-button'), function() {
        var $rule = $(this).closest('.rule-container');
        var $group = $(this).closest('.rules-group-container');
        var newRule = builder.addRule(builder.getModel($group));
        newRule.moveAfter(builder.getModel($rule));
    });
```

**Comment by garygao12580** [comment]
Yes, you achieve this. Thank you so much.
