### ISSUE TITLE
'setRulesFromSQL' not working properly

### ISSUE THREAD

**Issue by vivekanand-pst** [mistic100/jQuery-QueryBuilder#824]
```javascript
        {
          id: 'YEAR(NOW()) - YEAR(date_of_birth)',
          label: 'Age',
          type: 'integer',
          input: 'number',
          validation: {
            min: 0,
            max: 100,
            step: 1,
          },
        },
```

The output from the above code which is correct:
```sql
YEAR(NOW()) - YEAR(date_of_birth) BETWEEN 30 AND 50
```
Creation of SQL is working properly.

but while use setRulesFromSQL with the same query it produces the following issue.

Error:

`Uncaught SQLParseError: Cannot find field name in {"operation":"-","left":{"name":"YEAR","arguments":{"value":[{"name":"NOW","arguments":null,"udf":true}],"distinct":false},"udf":true},"right":{"name":"YEAR","arguments":{"value":[{"value":"date_of_birth","value2":null,"nested":false,"values":["date_of_birth"]}],"distinct":false},"udf":true}}`

**Comment by mistic100** [comment]
First of all this issue should be in sql-parser repository  not here.

But anyway this won't work and never will, the filter's field can only be a column name, not an expression. I suggest you use a placeholder as field name (for instance `AGE_EXPRESSION`) and a do a string replace after getting the SQL and before setting the SQL.

**Comment by vivekanand-pst** [comment]
Thanks,
it's working properly with getRules and setRules.

**Comment by mistic100** [comment]
Correctly pasing SQL is not the same as storing data in a JSON.

I have no other solution.
