### ISSUE TITLE
Check if valid

### ISSUE THREAD

**Issue by itajackass** [mistic100/jQuery-QueryBuilder#826]
I'd like to use jquerybuilder on my form only if my select "ADVANCED FILTERS" are set to true.

If true, i need to check if the builder is valid before submit. If false, i need to ignore it.

Is there a valid method to do this? I don't find it.

Like:

if ( $("mybuilder").is("valid") ) { form.submit(); }

**Comment by felixOvianet** [comment]
Here is the magic:
```
if ( $('#mybuilder').queryBuilder('validate') ) { 
    form.submit(); 
}
```
