### ISSUE TITLE
Drag/drop UI bug in 2.5.2

### ISSUE THREAD

**Issue by gordon-matt** [mistic100/jQuery-QueryBuilder#827]
There is a big UI bug with the Query Builder (version 2.5.2). Whenever I click on a filter, it thinks I want to drag/drop it somewhere.

Until now, I have been using version 2.4.4, which does not have this problem. I created a fiddle for you to see this problem for yourself:

https://jsfiddle.net/5hf0era1/

2.4.4 doesn't have this problem (with the exact same configuration of all other CSS and JS resources). Not sure at what point after that the problem showed up, because I haven't used the query builder in a long time.

**Comment by mistic100** [comment]
With Interact 1.3.3 and above it works

**Comment by gordon-matt** [comment]
Thanks for the quick response. You are correct.
https://jsfiddle.net/cxs13yda/1/

It's odd that cdnjs doesn't have anything above 1.2.9. I'll have to find it elsewhere.

**Comment by mistic100** [comment]
The problem with cdnjs is that it's community managed, and it's very difficult to add new versions because of the size of the repo.

I suggest to use jsdelivr which is automatically updated with NPM releases.

**Comment by gordon-matt** [comment]
Thanks for the suggestion. I'll take a look.

**Comment by mistic100** [comment]
By the way querybuilder.js.org is hosted on Github Pages, it's not meant to be a CDN.

**Comment by gordon-matt** [comment]
Don't worry - I don't use it as a CDN.. it was only for the JS Fiddle.
