### ISSUE TITLE
Add new tag inside rule 

### ISSUE THREAD

**Issue by sumeyyadede** [mistic100/jQuery-QueryBuilder#832]
Hi, I want to add new tag into the rules but I could not do it. Actually, in query builder I get the filters ids from database. So when I click the ‘Get Rules’ button I take the this result:

![image](https://user-images.githubusercontent.com/43093118/67242883-74f93580-f424-11e9-88f4-259b7c6cb171.png)

But I could not insert id’s name to the rule in the query builder. I need to assign id’s name to somewhere inside rules. 

Also I tried to change field part as id name but I could not do it. 
How can I solve this problem? Please help me.

**Comment by mistic100** [comment]
I don't understand...

**Comment by sumeyyadede** [comment]
Okay, let me ask you again.I want to change the value of the field independently of id. I read the document and I saw that; 


![image](https://user-images.githubusercontent.com/43093118/67245827-ed62f500-f42a-11e9-8d16-e128d9bd16ca.png)


The default value of the field is 'id'. How can I change the field value?

**Comment by mistic100** [comment]
Huh, you set the `field` property alongside the `id` where you define your filters.

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/examples/index.html#L209

**Comment by sumeyyadede** [comment]
Okay, I understand my mistake and I can do it now. Thank you for answering.
