### ISSUE TITLE
Select option that group 2 query at the same time

### ISSUE THREAD

**Issue by itajackass** [mistic100/jQuery-QueryBuilder#835]
I don't know if exist an option to assign to a select like this:

  ```
  {
    id: 'insurances.custom_field_i_dont_know',
    label: 'Insurance',
    type: 'integer',
    input: 'select',
    values: {
      0: 'Insurance not present',
      1: 'Insurance still active',
      2: 'Insurance expired'
    },
    operators: ['equal', 'not_equal']
    }
```

multiple conditions at the same time inside my table.

Initial query: `SELECT * FROM insurances WHERE $query` (using PHP)

For example if I select option 0, then query must be `$query = "insurances.Present = 0";`

If my select is 1, then $query must be: `$query = "insurances.Present = 1 AND insurances.DateExpiring > NOW()";`

If my select is 2, then $query must be: `$query = "insurances.Present = 1 AND insurances.DateExpiring <= NOW()";`

**Comment by mistic100** [comment]
This is not possible, I don't think it will ever be.

The fact is you should not export the builder value as SQL but as JSON rules object and actually build the query on the server, that way you can do whatever transformation you want and you are safe against SQL injections.
