### ISSUE TITLE
Parse Datepicker format when submit

### ISSUE THREAD

**Issue by itajackass** [mistic100/jQuery-QueryBuilder#838]
I have an italian format for date (dd/mm/yyyy):

{
		id: 'DataScadenza',
		label: 'Expiring',
		type: 'date',
		validation: {
		  format: 'DD/MM/YYYY'
		},
		plugin: 'datepicker',
		plugin_config: {
		  language: "it",
		  format: 'dd/mm/yyyy',
		  todayBtn: 'linked',
		  todayHighlight: true,
		  autoclose: true
		}
	  }

when I submit my form, I get "DD/MM/YYYY" but I need for mysql query format as YYYY-MM-DD.
My array params have other fields type so i can't identify date fields to convert with PHP function.

Is there a way to parse in other format after submit a date?

**Comment by mistic100** [comment]
This must be configured in the plugin you use for datepicker, it has nothing to do with QueryBuilder.

If you use Bootstrap Datepicker the necessary config is documented https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#format
