### ISSUE TITLE
Multiple default_filter

### ISSUE THREAD

**Issue by igor90** [mistic100/jQuery-QueryBuilder#840]
Hi, 
First of all thank you, you have done a great work!

About my issue, I want to add new groups with default fields.
I did that on init using _rules_, but when I click  "add new group" it creates  with only one field which I can change using _default_filter_.

As I know I can't set _default_filter_ multiple values. 
I tried using array with ids from rules but it doesn't work.
What should I use for do that, which legal parameters and methods?

Thanks a lot!

PS. Main idea is every groups should have 4 default fields which can't be deleted.

Here is screenshot
![image](https://user-images.githubusercontent.com/5164730/68206476-735b7000-ffd5-11e9-8a0d-e843c10742ad.png)

And link
https://querybuildertags.vicing88888.now.sh/

**Comment by mistic100** [comment]
You can hook on "afterAddGroup" event and call "addRule" method from here
https://querybuilder.js.org/api/list_event.html#.event:afterAddGroup

**Comment by igor90** [comment]
Thank you for fast respond.

I tried to use that hook and that method, but it set data for rule data, not create rule:
![image](https://user-images.githubusercontent.com/5164730/68295613-6acd6d00-009b-11ea-8641-777ba214613f.png)
Or which object should I send to method?

**Comment by mistic100** [comment]
Huh ? It did create a rule, now you have two rules in your group : one created automatically and one created manually.
If you read the doc you will see that "data" is for holding user data not associated to the builder.

If you want to change the filter of this new rule, save the result of the "addRule" method in a variable and change it's [`filter` ](https://querybuilder.js.org/api/Rule.html#filter), it need the full filter object, which is retrived with `getFilterById` method

```js
$builder.on('afterAddGroup.queryBuilder', (e, group) => {
  const rule = $builder.queryBuilder('addRule', group);
  rule.filter = $builder.queryBuilder('getFilterById', 'negativeKey');
});
```

**Comment by igor90** [comment]
Yes, it works
Thank you!
