### ISSUE TITLE
Select Filter through an autocomplete input text field instead of a dropdown menu

### ISSUE THREAD

**Issue by Nickath** [mistic100/jQuery-QueryBuilder#841]
First of all thank you for this great plugin :)

I would like to know whether there is any way to be able to choose filter through an autocomplete input text instead of a dropdown select menu. I use the `selectize plugin` to achieve autocomplete in values selection. Is it possible to do this for filters selection in a similar way? Thanks in advance.

**Comment by mistic100** [comment]
It's not possible, closing on favor of #814 and #653
