### ISSUE TITLE
Replacing combobox control with a custom control

### ISSUE THREAD

**Issue by HolyOne** [mistic100/jQuery-QueryBuilder#844]
To create rules, we select an item from combo box (containing labels) , select a compare operation and a compare value.

My problem is I will have thousands of items to make comparision and I cannot list them in a combobox. I need a custom select UI control.

(Example: I have 100 tables and 20 columns on each and I want user to first select table then select column)
(Example2: I have thousands of fields to select from, user clicks browse button, a modal appears and he selects from the modal)

Is there a clean way I can replace the combo control ?

**Comment by mistic100** [comment]
Hello

there are at least two open issues about this subject, from multi-select configuration to free input with autocomplete, and numerous closed issues too.

My answer is : the need is known but I don't have time to implement it.
