### ISSUE TITLE
Unable to get working with requireJS

### ISSUE THREAD

**Issue by markehewitt** [mistic100/jQuery-QueryBuilder#85]
Has anyone been able to get this working with requireJS?   Our MVC app loads all scripts using requireJS.

**Comment by mistic100** [comment]
would have been cool to tell what you tried, what you get, etc.
you know, show you are not just expecting help

----

here is how I got it working

```js
requirejs.config({
  baseUrl: 'bower_components',
  paths: {
    'jquery': 'jquery/dist/jquery.min',
    'query-builder': 'jQuery-QueryBuilder/dist/query-builder.min',
    'microevent': 'microevent-mistic100/microevent.min',
    'jquery-extendext': 'jquery-extendext/jQuery.extendext'
  },
  shim: {
    'jquery-extendext': {
      deps: ['jquery'],
      exports: 'jQuery.extendext'
    },
    'query-builder': {
      deps: ['jquery-extendext'],
      exports: 'jQuery.fn.queryBuilder'
    }
  }
});

require(['jquery', 'jquery-extendext', 'microevent', 'query-builder'], function($) {

  $('#builder').queryBuilder({
    filters: [{
      id: 'id',
      type: 'string'
    }]
  });
  
});
```

For the next version I'll improve jQuery.extendext and QueryBuilder to simplify it to

```js
requirejs.config({
  baseUrl: 'bower_components',
  paths: {
    'jquery': 'jquery/dist/jquery.min',
    'query-builder': 'jQuery-QueryBuilder/dist/query-builder.min',
    'microevent': 'microevent-mistic100/microevent.min',
    'jquery-extendext': 'jquery-extendext/jQuery.extendext'
  }
});

require(['jquery', 'query-builder'], function($) {

  $('#builder').queryBuilder({
    filters: [{
      id: 'id',
      type: 'string'
    }]
  });
  
});
```

**Comment by markehewitt** [comment]
First I wanted to thank you for this, but most importantly I wanted to apologize for not handling my request better.  

The background is that my college's last day was yesterday and I got handed the job of building a custom reporting solution.  He has lots of experience in reporting and client side coding and I have almost none.   He had originally recommended your query builder and told me that he spent a day and a half trying to get it to work with requireJS and couldn't.  He never checked in any of his example code and I am new to the client side coding and assumed that if he couldn't figure it out, then how could I?

I did my own research into other possible query builders and kept coming back to yours as the best of breed.   With that in mind, I figured I would at least ask the question about requireJS.  So hopefully you accept my apologies for my lameness. 

Finally, after looking at your solution, I am guessing that he did not shim jQuery.extendext and list that as a dependency.  I do have one (hopefully valid) question about your solution, you define microevent path but don't define it as a dependency or seemingly use it anywhere?

**Comment by mistic100** [comment]
it's used in query-builder.js directly.

Why did I declared everything manually ? because I use Bower, if you don't and just drop all your dependencies on the same folder, you don't need it

now with the 1.4.1 version released early today you don't need the shims anymore (just make sure to get the last version of $.extendext too)

**Comment by markehewitt** [comment]
I used 1.4.1 with requireJS and your configuration and it worked perfectly.  Thank you very much.
