### ISSUE TITLE
Built new rule evaluator for python

### ISSUE THREAD

**Issue by shunyeka** [mistic100/jQuery-QueryBuilder#850]
I have built a rule evaluator for python similar to https://github.com/SixiS/jquery_query_builder-rails.

Here's the links

Github: https://github.com/shunyeka/jQuery-QueryBuilder-Python-Evaluator
Pip Package: https://pypi.org/project/jqqb-evaluator/

**Comment by mistic100** [comment]
Thanks, I added it to the doc
