### ISSUE TITLE
Dynamic dropdown value based on selected operator

### ISSUE THREAD

**Issue by AmitChotaliya** [mistic100/jQuery-QueryBuilder#852]
I am trying to do the following.

* Have two custom operators 'in_others' and 'not_in_others' for string field.
* I would like populate the value section with dropdown with list of values when only this operator selected. Other operators the value can be text field.

I used event `QueryBuilder.afterUpdateRuleOperator`. When any of the above value is selected I am updating the value to dropdown and populating values to it. When I run `getRule` it fails validation.

Can someone please point me how to achieve this specific scenario?

**Comment by mistic100** [comment]
Please submit a live exemple of what you tried, I cannot help you with so little details.

**Comment by dolep** [comment]
I'm trying to change the rule type for a filter based on the operator that is selected.  I am able to change the DOM and change the input to what I want, but it doesn't have the change function attached to it and the value of the input doesn't get set to the value of the filter.  I hate to waste your time, but I've been stuck on this for two days now.

``

`$(function () {
        // Fix for Selectize
        $('#builder').on('afterCreateRuleInput.queryBuilder', function (e, rule) {
            if (rule.filter.plugin == 'selectize') {
                rule.$el.find('.rule-value-container').css('min-width', '300px')
                    .find('.selectize-control').removeClass('form-control')
                    .find('.selectize-dropdown').removeClass('form-control');
            } else if (rule.filter.id == 'skillSets') {
                console.log(e);
                console.log(rule);
            }
        });
        $('#builder').queryBuilder({
            plugins: ['bt-tooltip-errors'],
            filters: [{
                id: 'skillSets',
                label: 'Skill Sets',
                type: 'string',
                plugin: 'selectize',
                plugin_config: {
                    valueField: 'skillSetValue',
                    labelField: 'skillSetName',
                    searchField: 'skillSetName',
                    sortField: 'skillSetName',
                    create: false,
                    maxItems: 1,
                    plugins: ['remove_button'],
                    onInitialize: function () {
                        var that = this;
                        $.getJSON('/Resumes/Search/getSkillSets', function (data) {
                            data.forEach(function (item) {
                                //console.log(item);
                                that.addOption(item);
                            });
                        });
                    }
                },
                operators: ['equal', 'contains']
            }]
        }).on("afterUpdateRuleOperator.queryBuilder", function (event, name) {
            if (name.__.filter.id == "skillSets") {
                if (name.__.operator.type == "contains") {
                    var skillName = name.$el.find(".rule-value-container > input").attr("name");
                    name.$el.find(".rule-value-container > input").removeAttr("name");
                    name.$el.find(".rule-value-container").children().each(function () {
                        $(this).appendTo("#hiddenSkillSets");
                    });
                    delete name.__.filter.valueSetter;
                    name.__.filter.value = "poop";
                    name.$el.find(".rule-value-container").append("<input type='text' class='form-control' name='" + skillName + "' />");
                }
            }
        });
    });`

Thanks!!
