### ISSUE TITLE
How to refresh filters and rules ?

### ISSUE THREAD

**Issue by hamelraj89** [mistic100/jQuery-QueryBuilder#854]
filter values are dynamics, so when i change column name i have to call API to get values to assign particular filter. 

but here filters data not changing in UI but when i check **console.log()** filters are changed. 

and change event running many time for one click ?

**finally** what i want is when i select column i need to call external **API** reassign values for particular **filter**
```
$('#builder-basic').change(function(e) {
  
  var index = filters.findIndex(f => f.id === e.target.value);

  filters[index]['values'] = [];

  $('#builder-basic').queryBuilder({
    plugins: ['bt-tooltip-errors'],
    
    filters: filters,

    rules: rules_basic
  });
   
});
```

**Comment by mistic100** [comment]
I suggest you use a plugin on you filters like selectize or chosen which have built-in datasource feature for the values.
