### ISSUE TITLE
If then Statements with QueryBuilder

### ISSUE THREAD

**Issue by martian0718** [mistic100/jQuery-QueryBuilder#856]
Is there a way to implement if then statements in the QueryBuilder?? So I'm working on a project where I want to create a set of rules, and based off those rules execute a certain action and output the data from a MySQL database. For example, let's say I have a table of people, and I may want to say, "if age is greater than 16, then a boolean variable "canDrive" is set to true". Then based off this I can query or output the table of people with this new value for canDrive to the front end. Thank you for reading this and please let me know if this is possible!

**Comment by mistic100** [comment]
QueryBuilder can only build the WHERE part of the query, nothing more.

Any other logic must be implemented on yout own.
