### ISSUE TITLE
i want to use this plugin for react native

### ISSUE THREAD

**Issue by sam9010** [mistic100/jQuery-QueryBuilder#857]
hi
i want to use this plugin for react native app 
 i search about  it but i can find it
help me plz

**Comment by mistic100** [comment]
Hello

i cannot help you, I never used React

I suggest you read articles like  
https://reactjs.org/docs/integrating-with-other-libraries.html  
https://notes.devlabs.bg/how-to-use-jquery-libraries-in-the-react-ecosystem-7dfeb1aafde0

**Comment by sam9010** [comment]
@mistic100  i want in react native
no react

**Comment by mistic100** [comment]
UI libraries cannot be used in React Native (that's what google tells me)
