### ISSUE TITLE
use jstree plugin for showing filters

### ISSUE THREAD

**Issue by hvp130230** [mistic100/jQuery-QueryBuilder#858]
Can I use jstree plugin for displaying the filters?

**Comment by mistic100** [comment]
Probably, by creating a custom QueryBuilder plugin.

This plugin for example uses Bootstrap Selectpicker to replace the standard filters and operators selectboxes.  
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/bt-selectpicker/plugin.js
