### ISSUE TITLE
Remove/add plugin based on operator?

### ISSUE THREAD

**Issue by Shpigford** [mistic100/jQuery-QueryBuilder#859]
What's the proper way to remove or add a plugin based on the chosen operator?

For instance, I have a Release Date filed that currently set to `type: "date"` that's using the `datepicker` plugin with a "between" operator.

However, I want to let users pick less/greater operators and just input an integer instead of picking a date.

```javascript
{
  id: "release_date",
  label: "Release Date",
  type: "date",
  operators: ["less", "greater", "between"],
  unique: true,
  description: "When were the tracks released?",
  plugin: "datepicker",
  plugin_config: {
    format: "yyyy-mm-dd",
    assumeNearbyYear: true,
    autoclose: true
  }
}
```

So, if they choose less/greater, the type would change to `integer` and it would _not_ use the `datepicker` plugin.

Here's what I've got thus far, but not sure how to actually remove or add the datepicker plugin based on the change.

```javascript
$("#builder").on("afterUpdateRuleValue.queryBuilder afterUpdateRuleFilter.queryBuilder afterUpdateRuleOperator.queryBuilder afterUpdateGroupCondition.queryBuilder afterDeleteRule.queryBuilder afterDeleteGroup.queryBuilder",
  function(e, rule) {
    if (rule.filter.id == "release_date" && (rule.operator.type == "less" || rule.operator.type == "greater")) {
      var $input = rule.$el.find($.fn.queryBuilder.constructor.selectors.rule_value);
      $input.prop({ type: "number" });

      // NOT SURE HOW TO REMOVE OR RE-ADD PLUGIN
    }
  }
);
```

**Comment by mistic100** [comment]
#251
