### ISSUE TITLE
error: "Operator equal cannot accept multiple values" does not show on screen

### ISSUE THREAD

**Issue by Lush3** [mistic100/jQuery-QueryBuilder#86]
I'm using            
            type: 'integer',
            input: 'select',
            multiple: true,
            plugin: 'selectize',
if the Equal operator is selected and multiple options are selected an appropriate error message is created but it is just thrown instead of showing up in the tooltip validation like the other error messages.

**Comment by mistic100** [comment]
I suppose it's something that should not happen in normal operation.

I suggest you just use "in" operator, with one value it the same as "equal"

**Comment by Lush3** [comment]
Yes I agree the user should not select equal and then pick more than 1 option. You are already creating the error message it should just get back to the user. I can just use In instead of equal but the user expects an Equal option. Also if I use the generated sql directly in is less efficient than equal.

on a side note, impressive response time to comments.

**Comment by mistic100** [comment]
I realize this error is part of the SQL plugin, thus two problems :
- I don't have a system to allow translations in plugins
- I don't have a reference to the DOM object from where the rule comes

--

and "in" is not less efficient than "equal" as it's generally transformed to multiple "OR equal" by the engine
and even it was it's **totally** negligible compared to network and IO operation

**Comment by Lush3** [comment]
I solved the problem by testing for multiple values when using equal with select
<pre>
               case 'select':
                    if (filter.multiple) {
                        if (value[i].length === 0) {
                            result = ['select_empty'];
                            break;
                        }
             <b>           if (operator.type === 'equal' && value[i].length > 1) {
                            result = ['equal_with_multiple'];
                            break; </b>
                        }
                    }
                    else {
                        if (value[i] === undefined) {
                            result = ['select_empty'];
                            break;
                        }
                    }
                    break;
</pre>
and adding the error to your errors:
"equal_with_multiple": "Operator Equal can not accept multiple values"

**Comment by mistic100** [comment]
well it's not really scalable, what about "not_equal", "begins_with", etc ?

the best solution I imagined is to add an option to operators object https://github.com/mistic100/jQuery-QueryBuilder/blob/master/src/query-builder.js#L131
(the current `accept_values` is in fact the number of inputs displayed, whereas the each input can be multiple or not)

**Comment by Lush3** [comment]
Excellent point. 
Yours sounds like the better plan.
