### ISSUE TITLE
Add preset rule

### ISSUE THREAD

**Issue by IGORMMMMM** [mistic100/jQuery-QueryBuilder#861]
I have preseted rules and i need a way to add them in the query after the users rules without remove theirs.
Is there some way ?

**Comment by mistic100** [comment]
Simplest way is to call "getRules", alter the JSON and call "setRules".

Most performant way is to call ["addRule"](https://querybuilder.js.org/api/QueryBuilder.html#addRule) and alter the Rule object.

**Comment by IGORMMMMM** [comment]
like this ?
` $('#btn-set-last').on('click', function() {
      $('#builder').queryBuilder('addRule', last);
    });
`
its returning _e.addRule is not a function_

**Comment by mistic100** [comment]
No, the parameter of "addRule" is not the configuration of the rule, it is the parent group (this is visible in the API doc)

```js
const rootGroup = $builder.queryBuilder('getModel');
const rule = $builder.queryBuilder('addRule', rootGroup);
rule.filter = $builder.queryBuilder('getFilterById', last.filter);
rule.operator = $builder.queryBuilder('getOperatorByType', last.operator);
rule.value = last.value;
```

Not the best API, I know...

Regarding your error, please create an online demo if it persists.

**Comment by IGORMMMMM** [comment]
it worked, but Is there a way to put it as a function in a button like 'setRules'? or add groups

dont belittle your api, it helps a lot, is easy to use and manipulate

let me explain

i have a sistem where the user select the conditions of the query and generate a report, then I store this query for they to use later, but I need a way to insert it with the historic buttons, 
now i am using 'setRules' but my boss want it to add without removing what is in the builder

my database is SQL

**Comment by mistic100** [comment]
What is preventing you to put this code in the "on click" callback ?

**Comment by mistic100** [comment]
And to add group there is the "addGroup" method, please read the API doc for other methods.

**Comment by IGORMMMMM** [comment]
it worked, I had an error in the code
and how 'addGroup' would work i saw the documentation but i'm very new to js and i didn't understand it very well

`$('#btn-set-last').on('click', function() {
    var addGroup =  $('#builder').queryBuilder('getRulesFromSQL',last);
    const rootGroup = $('#builder').queryBuilder('getModel');
    `
what i put after this to add the saved query

**Comment by mistic100** [comment]
Excuse me but I think you didn't make any effort. The signature of "addGroup" is exactly the same as "addRule".

```js
const rootGroup = $builder.queryBuilder('getModel');
const subGroup = $builder.queryBuilder('addGroup', rootGroup);
const subRule = $builder.queryBuilder('addRule', subGroup );
```
