### ISSUE TITLE
Can’t change input type in rule-value-container

### ISSUE THREAD

**Issue by patopeth** [mistic100/jQuery-QueryBuilder#864]
Hi, Ive been struggling for a while trying to convert an input into a textarea.
I notice that by putting a div with a class=rule-value-container in rule inside templates automatically generates a textbox inside that div. What I need is to find a way to generate a textarea instead. Is that even possible?. I’ve tried several ways with no success.

**Comment by mistic100** [comment]
Are you really talking about the "operator" ? the second item of a line ? because by default it is a dropdown, not an input.

**Comment by patopeth** [comment]
> Are you really talking about the "operator" ? the second item of a line ? because by default it is a dropdown, not an input.

No, I’m talking about the rule-value-container which generates an input. I’d like to make it generate a textarea instead and I was wondering if that is possible and how to do it. Thanks!

**Comment by mistic100** [comment]
Then just set `input: 'textarea'` when declaring your filter as documented https://querybuilder.js.org/#filters
