### ISSUE TITLE
MissingLibraryError: SQLParser is required to parse SQL queries. Get it here https://github.com/mistic100/sql-parser

### ISSUE THREAD

**Issue by cherishjia** [mistic100/jQuery-QueryBuilder#867]
Am i use 
$('#builder').queryBuilder('setRulesFromSQL',"aggregation.agg_level = '2'")
to set rules,but i got  

MissingLibraryError: SQLParser is required to parse SQL queries. Get it here https://github.com/mistic100/sql-parser

can you help me me to resolve this issue

**Comment by mistic100** [comment]
Don't you understand the error message ?
Install the lib and add it to your page.

Sent from MailDroid

-----Original Message-----

**Comment by mistic100** [comment]
Check the "Requirements" section https://querybuilder.js.org/plugins.html#sql-support
