### ISSUE TITLE
Initialize many rules with selectize controls

### ISSUE THREAD

**Issue by t34rus** [mistic100/jQuery-QueryBuilder#868]
Hi

I need to use the same selectize control for different rules. So i cannot initialize it in standart way load or onInitialize finction, because i do not know needed attribute.

So i chose this way
Provide additional datajs field for rule and pass initial values like json object
```javascript
[{"id":"basic2"},{"id":"basic-new"}, {"id":"active"}]
```

then pass it to rule 
```javascript
var rule = Object.assign({}, control)
            rule.id = attr.id;
            rule.data = {"attrId": attr.id};
            rule.label = attr.title;
            rule.optgroup = attr.groupTitle;
            rule.description = attr.description;
            rule.datajs = attr.datajs;
            default_rules.push(rule);  
```

and then add use afterCreateRuleInput.queryBuilder
```javascript
$builder.on('afterCreateRuleInput.queryBuilder', function (e, rule) {
        if (rule.filter.plugin == 'selectize') {
            var selectize = rule.$el.find('.rule-value-container input')[0].selectize;
            if (rule.filter.datajs) {
                var items = [] ;
                    JSON.parse(rule.filter.datajs).forEach(function(i) {
                        items.push({id:i.id,name:(i.name?i.name:i.id)})
                    });
                    selectize.addOption(items);
            }
        }
});
```

Is the proper way to use selectize with jQueryQueryBuilder ?

Could you advice the best way?

Thanks for you work!

**Comment by mistic100** [comment]
Does it work ? If yes then it's good enough. I don't have any advice for such specific usage.

**Comment by t34rus** [comment]
> Does it work ? If yes then it's good enough. I don't have any advice for such specific usage.

Yes, it is work, but looks a bit crazy...

Thanks a lot!
