### ISSUE TITLE
Custom controls with nb_inputs:2

### ISSUE THREAD

**Issue by t34rus** [mistic100/jQuery-QueryBuilder#871]
Hi

I can not find proper solution to get job with between and custom controls

First i create control with custom operator
```javascript
type: 'date',
        operators: ['between_custom'],
        input: function(rule, name) {
            var $container = rule.$el.find('.rule-value-container');
            return '\
          <select name="'+ name +'_type"> \
```
than add custom operation to builder
```javascript
operators: $.fn.queryBuilder.constructor.DEFAULTS.operators.concat(
            {type: 'regexp', nb_inputs: 1, multiple: false, apply_to: ['string']},
            {type: 'between_custom', nb_inputs: 2, multiple: false, apply_to: ['date','datetime']},
        )
```

For UI it is work as i expect, but buider dot not get values from each control and process only first one
```javascript
"type": "date",
            "operator": "between_custom",
            "value": "days+",
```

Does it support in your solution ???

And where is the best way to convert value (days+) from my custom control to SQL syntax ?
And is it possible to add custom type to builder (for example date_custom) and process it value in another way

**Comment by mistic100** [comment]
You cannot add custom types.

In order to make the builder accessing values of custom inputs you need to provide "valueSetter" and "valueGetter" on the filter.

----

Please open another issue for custom SQL generation (with more details)

**Comment by t34rus** [comment]
> You cannot add custom types.
> 
> In order to make the builder accessing values of custom inputs you need to provide "valueSetter" and "valueGetter" on the filter.

Yes,
i create custom setter and getter for my custom controls and it works fine with less or equal operation...but when i select between operation i see two controls on UI but only first is taken for query
How to ask builder get value from two custom controls ???

**Comment by mistic100** [comment]
What do your valueGetter looks like ? It's **your** responsability to return values from both inputs.

**Comment by t34rus** [comment]
```javascript
      valueGetter: function(rule) {
            var typeControl = $(rule.$el.find('.rule-value-container [name$=_type]'));
            var inputControl = $(rule.$el.find('.rule-value-container [name$=_input]'));
            var value = typeControl.val();
            if (value.endsWith("-") || value.endsWith("+") ) {
                var N = inputControl.val();
                value = value + N;
            }
            return value;
        },
```
Could you please give advise how to change it for two custom controls ?

**Comment by mistic100** [comment]
What you do this
```js
var inputControl = $(rule.$el.find('.rule-value-container [name$=_input]'));
```
You should get a collection as the rules contains two inputs, just iterate over them with each and get their specific values.

(if you don't know when you call methods like "val" on a jQuery collection it actually queries the first item of the collection)

**Comment by mistic100** [comment]
I cannot be more specific as you only show parts of your code, be assuming your "input" function returns a single input, it get called twice 
https://github.com/mistic100/jQuery-QueryBuilder/blob/73cb350b57610d2632e1eda4bb52c27195a303af/src/core.js#L702-L707

and then the rule has two inputs with similar names

**Comment by t34rus** [comment]
So... just add iterate over controls and it works fine
```javascript
 valueGetter: function(rule) {
            var values = [];
            var typeControls = $(rule.$el.find('.rule-value-container [name$=_type]'));
            var inputControls = $(rule.$el.find('.rule-value-container [name$=_input]'));
            for (var i = 0; i < typeControls.length; i++) {
                var typeControl = $(typeControls.get(i));
                var inputControl = $(inputControls.get(i));
                var value = typeControl.val();
                if (value.endsWith("-") || value.endsWith("+") ) {
                    var N = inputControl.val();
                    value = value + N;
                }
                values.push(value)
            }
            if (values.length==1){
                return values[0];
            }
            return values;
        },
```

```javascript
 "type": "date",
            "operator": "between",
            "value": [
                "week-1",
                "now"
            ],
```
