### ISSUE TITLE
Combination of Conditions?

### ISSUE THREAD

**Issue by aravinthanpnk** [mistic100/jQuery-QueryBuilder#875]
Does this library support to build the below SQL Query?

`(name='foo' and age>20) or (place='india' and distance>20)`

**Comment by mistic100** [comment]
Yes, you can try it on the demo page.

![Screenshot_2020-05-16 jQuery QueryBuilder](https://user-images.githubusercontent.com/41597/82125902-559f6c80-97a9-11ea-891c-275c5966c4dd.png)
