### ISSUE TITLE
Documentation for events in api [event example]

### ISSUE THREAD

**Issue by veragreen119** [mistic100/jQuery-QueryBuilder#876]
I was having issues binding an event since there is no example in the api or note saying that to bind an event you must fallow it up with .queryBuilder

for example you can't just go 
```
        $('#queryBuilder').on('afterCreateRuleInput', ()=>{
             console.log('IM RUNNING YAYAYAY');
        });
```

you must use
```
        $('#queryBuilder').on('afterCreateRuleInput.queryBuilder', ()=>{
             console.log('IM RUNNING YAYAYAY');
        });
```

It would be nice if this was somewhere on the documentation page as the only way i found it was in here https://github.com/mistic100/jQuery-QueryBuilder/blob/cc03c3336c2a6aaa60ca9a83af506232d4f034b2/examples/index.html#L510 in the example after much googling and head desking :)

it might be nice to add it in the api somewhere so that people know you cant just use the event name as one would amuse.  Somewhere here might be nice: 
https://querybuilder.js.org/api/QueryBuilder.html#events

**Comment by mistic100** [comment]
it's right here https://querybuilder.js.org/#events

to other page cannot be be modified has being autogenerated from the source code
