### ISSUE TITLE
Querybuilder adds % at the begin and end of the expression when user select "Contains" as an operator

### ISSUE THREAD

**Issue by rutvimistry** [mistic100/jQuery-QueryBuilder#881]
I am finding a way to get rid of  '%' character added at the end of expression by the querybuilder.

i am writing expression for example

Text LIKE '13'

Querybuilder shows SQL as

Text LIKE '%13%'

this '%' character changes whole meaning of the where clause. Can you help me with this.

Thank you!

**Comment by mistic100** [comment]
There is no chances QueryBuilder is able to parse `Text LIKE '13'`, it will fail here https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/sql-support/plugin.js#L53-L74

if you want to use strict equality, use "equal", not "contains" or similar operators

**Comment by rutvimistry** [comment]
Thank you @mistic100  for suggestion. However i cannot pass "EQUAL" in backend, it won't give me right result.

**Comment by mistic100** [comment]
what kind of backend returns different result for `Text = 13`and `Text LIKE '13'` ???

anyway, QB respects standards, you can create a custom operator if you want
- https://querybuilder.js.org/#operators
- https://querybuilder.js.org/plugins.html#sql-support (Operators section)

**Comment by rutvimistry** [comment]
i guess for expression like this Text LIKE '1,[1-2],[3-9]'. it does create difference.

Thanks for sharing links for custom operator. I will try to work around that.

**Comment by mistic100** [comment]
The operator was designed to simply be a textual "contains", it was never designed to offer all options of the SQL LIKE operator.
