### ISSUE TITLE
Input Box instead of Drop Down Selector for Filter Field

### ISSUE THREAD

**Issue by bgeels** [mistic100/jQuery-QueryBuilder#882]
Is there a way to have the filter selector initialized as an input box instead, i.e. the user would type the name of the field instead of selecting from a predefined list. Image included below. Thanks!

<img width="698" alt="Screen Shot 2020-06-12 at 1 12 16 PM" src="https://user-images.githubusercontent.com/4997487/84529188-03ba0b80-acaf-11ea-9e00-3fdcd1eb138a.png">

**Comment by mistic100** [comment]
#814
