### ISSUE TITLE
How can I use select2 in rule filter?

### ISSUE THREAD

**Issue by ranahamid** [mistic100/jQuery-QueryBuilder#883]
I have added the filters.
![image](https://user-images.githubusercontent.com/30179345/85113769-a1768300-b239-11ea-8eef-770e64e5c646.png)

Now, I want to use select2 in the filter dropdown as I have more than 600 hundred filter options.  How can I use the select2 into this?

**Comment by mistic100** [comment]
You have to create your own QB plugin. Basically it is the same as "bt-selectpicker" plugin but using select2
https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/src/plugins/bt-selectpicker/plugin.js

general documentation about plugins https://querybuilder.js.org/dev/plugins.html (the **"Standalone" plugin** paragraph is very important)
