### ISSUE TITLE
How to use SqlSupport events

### ISSUE THREAD

**Issue by richard-slabbert94** [mistic100/jQuery-QueryBuilder#886]
Hi there!

Thanks for a great plugin!  I have been using it for a few years now and it has made my life a lot easier - thanks.

I just have a question regarding adding an event to plugins.SqlSupport.changer:ruleToSQL.  I have tried a few things to trap the event without success yet.

This is what I have tried:

```
jQuery("#builder").on('ruleToSQL.plugins.SqlSupport', function(expression, rule, value, valueWrapper) {
	console.log(expression, rule, value, valueWrapper);
});
```

I have also tried `'ruleToSQL'` and `'ruleToSQL.queryBuilder'`.

Can anyone help me out?

Thanks a lot :)

**Comment by mistic100** [comment]
`ruleToSQL.queryBuilder.filter`

**Comment by richard-slabbert94** [comment]
Hi Damien,

Thank you so much!

I really appreciate the help.

Richard
