### ISSUE TITLE
value_separator not working with type: 'string' 

### ISSUE THREAD

**Issue by Z-alexZ** [mistic100/jQuery-QueryBuilder#887]
Hey all,

do somebody have a solution for working with a value_separator and the type string.

It does **NOT** work with:
{
    id: 'comment',
    label: 'comment',
    type: 'string',
    input: 'text',
		value_separator: ';',
    operators: ['in']
  }

_result: "value":"asd;ast"_

It works with an integer:
{
    id: 'comment',
    label: 'comment',
    type: 'integer',
    input: 'text',
		value_separator: ';',
    operators: ['in']
  }

_result: "value":[1,2,3]_

**Comment by mistic100** [comment]
Can you provide a demo ? It works on the example (https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/examples/index.html#L215) when using "in" operator
