### ISSUE TITLE
QueryBuilder quick question

### ISSUE THREAD

**Issue by graley** [mistic100/jQuery-QueryBuilder#889]
Good morning.  Thanks so much for creating the jQuery QueryBuilder.  We’ve been using it in our production application for many years.

I hope you don’t mind a quick question.   We’ve been charged with trying to integrate the QueryBuilder within a new React application.  Do you have any recommendations for the best approach for doing this?  

Should we try to integrate Bootstrap and jQuery into our React application and then try to use the QueryBuilder?  Or do you think we would be better served to use a React version of the QueryBuilder? I’m not sure if there is even one that is close to your original version.

As usual we’re under a tight timeline.  Thanks so much for your help.

**Comment by mistic100** [comment]
#802 
#614 
#222 

I don't know any existing integration
