### ISSUE TITLE
 "Arithmetic Operators"

### ISSUE THREAD

**Issue by RiteshS21** [mistic100/jQuery-QueryBuilder#890]
Does jQuery Query Builder "**Arithmetic Operators**" has support in it?
Can we have arithmetic operators like **+,-,/,*** in the red highlighted area?

![Annotation 2020-10-01 181121](https://user-images.githubusercontent.com/26337464/94810494-b4404c80-0411-11eb-8ee2-27f42e33a3d9.jpg)

**Comment by mistic100** [comment]
custom operators are added with https://querybuilder.js.org/#operators

**Comment by RiteshS21** [comment]
Thank you!!!! 
now able to add custom operators.
