### ISSUE TITLE
Plans for removing dependency of moments?

### ISSUE THREAD

**Issue by Jojs** [mistic100/jQuery-QueryBuilder#891]
Hi

Is there any plans for removing the dependency of Moments?
Re:
https://momentjs.com/docs/#/-project-status/

Best regards - Jan

**Comment by mistic100** [comment]
I don't have time for this, and moment is not dead yet.

If, one day, QueryBuilder is rewriten, the date handling will propably be done via configurable adapter (thus allowing date-fns, luxon, or any lib)
