### ISSUE TITLE
New Feature : Entity Mode

### ISSUE THREAD

**Issue by krishnasoft21** [mistic100/jQuery-QueryBuilder#892]
Is there a way to add additional field for entity to current filters ? It would be great if anyone has done this and share a link or info on how to achieve this.

**Comment by mistic100** [comment]
What do you mean ?

Sent from MailDroid

-----Original Message-----

**Comment by krishnasoft21** [comment]
> What do you mean ? Sent from MailDroid
> […](#)
> -----Original Message----- From: krishnasoft21 <notifications@github.com> To: mistic100/jQuery-QueryBuilder <jQuery-QueryBuilder@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Sent: ven., 16 oct. 2020 22:05 Subject: [mistic100/jQuery-QueryBuilder] New Feature : Entity Mode (#892) Is there a way to add additional field for entity to current filters ? It would be great if anyone has done this and share a link or info on how to achieve this.
> -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #892

I mean, considering a scenario where there are many tables and each table has more than 30 fields then, the current application loads them all together. I'm looking for a way to have an extra dropdown to display table names and based on user selection of table we can load appropriate fields into the fields dropdown. I'm wondering if it is possible with current solution or if any one has done similar to this. Any suggestions would be greatly appreciated. Thanks!

**Comment by mistic100** [comment]
Ok.
This is the same as #653 and #576
