### ISSUE TITLE
Search in filters

### ISSUE THREAD

**Issue by RiteshS21** [mistic100/jQuery-QueryBuilder#894]
I need a search facility like select2 in the filter condition highlighted below:

![tempsnip](https://user-images.githubusercontent.com/26337464/96678693-d59cb480-138f-11eb-92d6-04a4ba313292.png)

- Does anyone have an idea of how to do this.
- Or if it is already implemented by someone, could you please provide the code.
Thanks in advance!!

**Comment by mistic100** [comment]
https://github.com/mistic100/jQuery-QueryBuilder/issues/883
