### ISSUE TITLE
Missing last filter off the bottom of the page

### ISSUE THREAD

**Issue by mikehobson** [mistic100/jQuery-QueryBuilder#897]
Hi,

I have a web page with 8 tabs, each tab has its own instance of jquery query builder. I have a long list of filters so to be efficient I have created the filters into an array and I then use "setfilters" to apply the to each query builder

```
$('#builder-basic1').queryBuilder({
    plugins: {
      'bt-tooltip-errors':{ delay: 100 },
      'bt-selectpicker': {
            liveSearch: true
        },
      'bt-selectpicker': {
            liveSearch: true
        },   
      'filter-description':{}       
  },

filters: [{

    id: 'timep',
    operator: 'equal',
    value: []
  }],

  rules: rules_basic
});
```

under the $(document).ready function I declare and array

```var objArr= [{
    id: 'timep',
    optgroup: 'Game Stats',
    label: 'Time (in mins)',
    type: 'integer',
     operators: ['equal', 'less', 'less_or_equal', 'greater', 'greater_or_equal', 'between'],

  },
  {
    id: 'scorediff',
    optgroup: 'Game Stats',
    description: 'This is the difference between both teams score line. You can use this when testing for a draw if you set it to zero',
    label: 'Score Difference',
    type: 'integer',
    operators: ['equal', 'less', 'less_or_equal', 'greater', 'greater_or_equal', 'between'],
  },
```

And finally, I apply that array to each query builder

    $("#builder-basic1").queryBuilder('setFilters',true, objArr);
    $("#builder-basic2").queryBuilder('setFilters',true, objArr);
    $("#builder-basic3").queryBuilder('setFilters',true, objArr);
    $("#builder-basic4").queryBuilder('setFilters',true, objArr);
    $("#builder-basic5").queryBuilder('setFilters',true, objArr);
    $("#builder-basic6").queryBuilder('setFilters',true, objArr);
    $("#builder-basic7").queryBuilder('setFilters',true, objArr);
    $("#builder-basic8").queryBuilder('setFilters',true, objArr);

This works really well and it means I only have to define my huge list of filters once. The first tab the list of filters is fully displayed but on all other tabs the last item disappears off the bottom of the page.

You can see my fully working example at https://soccerscanner.net/filters/examples/

**Comment by mistic100** [comment]
So this is a problem with Bootstrap Selectpicker, NOT QueryBuilder.

I suspect the problem is you initialize the Selectpicker on an element that is not visible, so it cannot get it's position and resize correctly.

I recommend you initialize the builders only when switching between the tabs, not all at once.
