### ISSUE TITLE
uppercase input filter

### ISSUE THREAD

**Issue by ittaskeu** [mistic100/jQuery-QueryBuilder#900]
Is it possible to change the case of searched string to uppercase ? 
![image](https://user-images.githubusercontent.com/23516846/107138206-ca0fd200-691b-11eb-8518-86286aa404a4.png)

**Comment by mistic100** [comment]
this could be done by applying a jQuery plugin to the filter  
https://querybuilder.js.org/#filters (plugin option)

I don't know such plugin but it's probably not hard to create (intercept keydown events to replace by the upercase value)
