### ISSUE TITLE
Custom Naming Operators Per Filter

### ISSUE THREAD

**Issue by chalamministries** [mistic100/jQuery-QueryBuilder#902]
So I know how to override the language wording for operators as a whole. But is there a way to do it per filter? For example, I have a Lead Score (A-F) and technically "A" would be "greater than" an "F" but the way this sorts, "F" is greater than "A". So the query would be the same, but I just want my user to say "Give me leads with a lead score higher than F" 

Make sense?

**Comment by mistic100** [comment]
the only possibility is to define another operator, let's say "reverse_equal" and use it instead of "equal" on your filter

https://querybuilder.js.org/#operators
