### ISSUE TITLE
ARRAY contains ARRAY with SQL 

### ISSUE THREAD

**Issue by Z-alexZ** [mistic100/jQuery-QueryBuilder#903]
Hey all,

is it somehow possible to get the sql command for this filter? I'am trying to search for possibility to filter down an array_column.

For example: colA = [1,2,4], Value = [2 or 3] -> true

**Comment by mistic100** [comment]
you can add your own own operators https://querybuilder.js.org/index.html#operators  

and configure them for the sql plugin https://querybuilder.js.org/plugins.html#sql-support => Operators section  
just define `sqlOperators` in your conf to add the new operators  
each sql operator must have an "op" property using "?" has placeholder and an optional "sep" to join multiple values

specific operators can be attached to each filter https://querybuilder.js.org/index.html#filters => operators option
