### ISSUE TITLE
setting toValue and toDisplay for Bootstrap datepicker

### ISSUE THREAD

**Issue by DSBhogal** [mistic100/jQuery-QueryBuilder#913]
I've noticed on the Boostrap Datepicker documentation that you can[ set the display and value date format to be different](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#format). I'm having trouble configuring this as I create my filters and store them in a model and pass them to my JS file: 

![image](https://user-images.githubusercontent.com/33750091/118939692-de666080-b947-11eb-9e5a-7ce9b064e41b.png)

![image](https://user-images.githubusercontent.com/33750091/118939782-f8a03e80-b947-11eb-95f2-4d4d1d2c50a1.png)

Any idea of how to configure this?

**Comment by mistic100** [comment]
Please show your `_filters` otherwise how could I help ?

**Comment by mistic100** [comment]
Options of jQuery plugins are specified with the `plugin_config` property on the filter https://querybuilder.js.org/#filters

**Comment by DSBhogal** [comment]
_filters is a list of the following model:

![image](https://user-images.githubusercontent.com/33750091/118957459-73715580-b958-11eb-82c8-e28b03410835.png)

This is how I populate the list: 
![image](https://user-images.githubusercontent.com/33750091/118957967-e4187200-b958-11eb-8aa3-0c5e876ab5c7.png)


I understand you place your plugin options in the plugin_config property but the toValue and toDisplay options are functions unless I'm mistaken?

![image](https://user-images.githubusercontent.com/33750091/118957878-cea34800-b958-11eb-9cbf-925f95e75437.png)

**Comment by mistic100** [comment]
Show the final value of filters, I don't know how your backend works. 
Yes they are functions, this is how Bootstrap Datepicker works. You will have to find a way to populate functions in your config.

I close this issue because it does not concern Query Builder, all that goes into `plugin_config` is the responsibility of said plugin.
