### ISSUE TITLE
Is there any plugins for Filters search option ?

### ISSUE THREAD

**Issue by godofblack** [mistic100/jQuery-QueryBuilder#915]
Hey there.,
Is there any filter search options becoz, i have 100 above data's in filter dropdown 

If it's there Kindl y give me some example, i tried bt-selectpicker but it's affect my design and not working

**Comment by mistic100** [comment]
https://querybuilder.js.org/plugins.html#bt-selectpicker

by enabling the search https://developer.snapappointments.com/bootstrap-select/examples/#live-search

**Comment by godofblack** [comment]
Hi @mistic100 
How to enable that search option in my filters ?
any special keyword is there ?

**Comment by godofblack** [comment]
I do all the changes and import that plugin but, select box search design not displayed why ? i missed anything ?!

**Comment by mistic100** [comment]
Did you click on the second link ? did you added "liveSearch: true" to the config of the plugin ?

**Show your code !**

**Comment by nankris** [comment]
https://jsfiddle.net/HariKrishna_N/oyepzw6u/1/ (I added this if someone is struggling to get the search in filter and operator dropdown)
