### ISSUE TITLE
How to provide user settings for plugins?

### ISSUE THREAD

**Issue by t34rus** [mistic100/jQuery-QueryBuilder#916]
Hi

I use one custom *smart* control with plugin selectize to display dufferent data for rules and want to use custom settings in it.
```javascript
controls.push({
        id: 'control_select',
        type: 'string',
        operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null', 'contains', 'not_contains'],
        plugin: 'selectize',
        plugin_config: {
            valueField: 'id',
            labelField: 'name',
            searchField: ['name', 'id'],
            load: function (query, callback) {
                $.ajax({
                    url: '/search',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        q: query,
                        type: rule.data.settings.url ?!?!??!?!??!?
                    },
                    success: function (res) {
                        callback(res);
                    }
                });
            }
        },
 ```

and use rule like this
```javascript
            var rule = Object.assign({}, ctrl);
            rule.id = attr.id;
            rule.data = {
                settings: {url:"user-data"}
            };
            rule.label = attr.title;
            rule.optgroup = attr.groupTitle ;
            rule.description = attr.description;
            rule.datajs = attr.data;
            return rule;
```

How to pass settings from data (rule.data.settings.url) to plugin ?

Thanks

**Comment by mistic100** [comment]
This is not possible, the plugin configuration on the filter cannot depends on the rules.
The rules are created by using filters, not the other way arround.

Further more, rules created by the user by clicking the "new rule" button have no associated data.

You will have to re-think your need of find another way.

**Comment by t34rus** [comment]
> This is not possible, the plugin configuration on the filter cannot depends on the rules.
> The rules are created by using filters, not the other way arround.
> 
> Further more, rules created by the user by clicking the "new rule" button have no associated data.
> 
> You will have to re-think your need of find another way.

But what about another method? I have access to rule that associated with filter
I need the same option for load method (((

for example 
'''
       valueSetter: function (rule, value) {
            var url = rule.data.settings.url;
 
'''

**Comment by mistic100** [comment]
because valueSetter and valueGetter are specifically designed to update the existing filter for a rule. it is not the same thing as configuring the plugin which is only called on creation of the filter.

As you might have seen there is not such much developement on this plugin, it is not on my priorities.  
What you want to do is not possible.

**Comment by t34rus** [comment]
Is it possible to access filter settings in plugin ?

Is able to store my custom setting in filter

**Comment by mistic100** [comment]
there is no point in "storing" a setting in the filter, just declare it alongside, or create a generator function


```js
function buildFilter(url) {
  return {
        id: 'control_select',
        type: 'string',
        operators: ['equal', 'not_equal', 'in', 'not_in', 'is_null', 'is_not_null', 'contains', 'not_contains'],
        plugin: 'selectize',
        plugin_config: {
            valueField: 'id',
            labelField: 'name',
            searchField: ['name', 'id'],
            load: function (query, callback) {
                $.ajax({
                    url: '/search',
                    type: 'GET',
                    dataType: 'json',
                    data: {
                        q: query,
                        type: url
                    },
                    success: function (res) {
                        callback(res);
                    }
                });
            }
        }
    };
}

controls.push(buildFilter('some url')):
```

**Comment by mistic100** [comment]
I will also add this : the `load` function is not managed nor called by Query Builder, so there is **no way** it could access any data from Query Builder. It is function from selectize, which can also do things with selectize data.

**Comment by t34rus** [comment]
Yes i see it
But i hope to use this way 
```javascript
filter.settings = {url:'some_url'}
```

and than get access in any place i want
