### ISSUE TITLE
comma separated column search

### ISSUE THREAD

**Issue by halatef** [mistic100/jQuery-QueryBuilder#918]
how can i search within comma separated column, what type of field uses find_in_set() to search?

**Comment by mistic100** [comment]
you can add your own own operators https://querybuilder.js.org/index.html#operators  

and configure them for the sql plugin https://querybuilder.js.org/plugins.html#sql-support => Operators section  
just define `sqlOperators` in your conf to add the new operators  
each sql operator must have an "op" property using "?" has placeholder and an optional "sep" to join multiple values

specific operators can be attached to each filter https://querybuilder.js.org/index.html#filters => operators option

**Comment by halatef** [comment]
> 
> 
> you can add your ownoperators https://querybuilder.js.org/index.html#operators
> 
> and configure them for the sql plugin https://querybuilder.js.org/plugins.html#sql-support => Operators section
> just define `sqlOperators` in your conf to add the new operators
> each sql operator must have an "op" property using "?" has placeholder and an optional "sep" to join multiple values
> 
> specific operators can be attached to each filter https://querybuilder.js.org/index.html#filters => operators option

thanks for ur replay, i could make the customer type and i displayed it in the builder, but i can not find the file in which i will add the custom function to make the operator find_in_set

could u plz help me

**Comment by mistic100** [comment]
I don't understand what you want.

**Comment by halatef** [comment]
here's an example 
 { type: 'geo', optgroup: 'custom', nb_inputs: 3, multiple: false, apply_to: ['number'] }

 in which file  i will add "geo" and make it return find_in_set() sql function

**Comment by mistic100** [comment]
None, you don't modify the source code of the lib. Everything is configurable. That's why I said above
> just define `sqlOperators` in your conf to add the new operators

example https://github.com/mistic100/jQuery-QueryBuilder/issues/920#issuecomment-868427246
