### ISSUE TITLE
Either of the filter selection

### ISSUE THREAD

**Issue by manoj123patil** [mistic100/jQuery-QueryBuilder#919]
Hi
I am using the Query Builder tool for custom rule creation in our project.
I am struggling with one scenario where I want to disable the filter based on another filter.
Eg. I have 4 filters defined.
1) partTitle1
2) partTitle2
3) price
4) Identifier
Now when the user selects partTitle1 filter, the partTitle2 filter should be disabled just like the unique plugin and vice versa so that in one group either partTitle1 or partTitle2 rule will exist.

Is there any way to do this?

```
$('#builder-basic').queryBuilder({
  filters: [{
    id: 'partTitle1',
    label: 'partTitle1',
    type: 'string',
    input: 'select',
    values: {
      101: 'Books',
      102: 'Movies',
      103: 'Music'
    },
    operators: ['equal']
  }, {
    id: 'partTitle2',
    label: 'partTitle2',
    type: 'string',
    input: 'select',
    values: {
      201: 'Books',
      202: 'Movies',
      203: 'Music'
    },
    operators: ['equal']
  }, {
    id: 'price',
    label: 'Price',
    type: 'double',
    validation: {
      min: 0,
      step: 0.01
    }
  }, {
    id: 'id',
    label: 'Identifier',
    type: 'string',
    placeholder: '____-____-____',
    operators: ['equal', 'not_equal'],
    validation: {
      format: /^.{4}-.{4}-.{4}$/
    }
  }]
});
```

**Comment by mistic100** [comment]
Why don't you use the unique plugin then ?

**Comment by mistic100** [comment]
There is no built-in option to do that. You can create your own plugin with "unique-filter" as a starting point.

https://querybuilder.js.org/dev/plugins.html
