### ISSUE TITLE
Correct way to store per-filter metadata on a rule?

### ISSUE THREAD

**Issue by bentayloruk** [mistic100/jQuery-QueryBuilder#92]
Hi,

Is there a "correct" way to store per-filter metadata on a rule?  I want to do something like below, where `werhooImAllCustomAndStuff` is a custom property on the rule.  I would want this set when a new rule is created (presumably based on the filter or an event when the rule is created?).

I guess I could use options `onAfterAddRule`.  However, the data I have is specific to the filter, so I was hoping that I could pass some custom data from the filter to the rule.  Am I missing something that would make this possible?  For example, is it possible to set properties on the rule from `onAfterCreateRuleInput` (I'm not sure if I can get the rule from the`$rule` `<li>` somehow).

``` json
{
      "id": "price",
      "field": "price",
      "type": "double",
      "input": "text",
      "operator": "less",
      "value": "10.25",
      "werhooImAllCustomAndStuff": "someData"
}
```

So far I'm really enjoying using jQuery QueryBuilder.  Thanks for building it!

Ben

**Comment by mistic100** [comment]
Really... I didn't understand anything...
I should explain what you want to achieve, what is the purpose if these data, how it is used

---

the `<li>` IS the rule, no data are stored anywhere else (this will change in version 2)
so `$rule.data('werhooImAllCustomAndStuff', 'someData')` is the jQuery way to store data

**Comment by bentayloruk** [comment]
*Apologies, I am mainly a server-side dev and am not yet fully familiar with the jQuery way of storing data.*

I am mapping rules on the server-side, in and out of another system.  I need to store some additional information in each rule, in order to do this mapping.  When I send the rules from the server, I need to include an additional property in each rule and then I need that sent back to me (i.e. when I call `getRules` I'd like this custom property to still be there).  When I create a new rule on the client, I need that property to be set with a value that is decided based on the filter.

Thanks for your suggestion.  I have tried it, but it does not work for me.  When I call `getRules` the rules do not have the custom property on them.

There are other ways for me to do this that don't need JQQB, but I wondered if it was possible with JQQB.

**Comment by mistic100** [comment]
ok understood

the fast is that `getRules` construct brand new objects, thus without any additional data

your best solution so far is to store somewhere else (client-side) your additional data, and inject it in the result of `getRules`

I'll think about a way to store additional data, kept but not used by QueryBuilder

**Comment by bentayloruk** [comment]
OK.  Thanks for the confirmation.

**Comment by bentayloruk** [comment]
Perfect.  Thanks Damien.
