### ISSUE TITLE
Is there a plan to remove jQuery as dependency?

### ISSUE THREAD

**Issue by CrestApps** [mistic100/jQuery-QueryBuilder#921]
With bootstrap 5.1 out and less projects depending on jQuery. Is there a plan to upgrade this amazing plugin and removing the jQuery dependency?

**Comment by mistic100** [comment]
Yes I would like to https://github.com/mistic100/jQuery-QueryBuilder/issues/432#issuecomment-856490252

But as you might have seen, the developement is stopped
