### ISSUE TITLE
how to evaluate rules in javascript ( apply them)

### ISSUE THREAD

**Issue by dimo2008** [mistic100/jQuery-QueryBuilder#922]
i am asking how to apply rules set on on javascript.
as i tried to apply them ( using .Net parser) it doesn't work with dynamic lists

**Comment by mistic100** [comment]
Sorry this is not in the scope of this library. The plugin provides the JSON representation fo the rules, up to you to use it as you want.

Example of library which does this kind of filtering : https://www.npmjs.com/package/json-rules-engine (there are many)
