### ISSUE TITLE
I am updating the value of the textfield through jquery but when i run queryBuilder('getRules') it is empty. May i know if there are still some functions that need to trigger for the rules to be not empty?

### ISSUE THREAD

**Issue by pixobit** [mistic100/jQuery-QueryBuilder#925]
I am updating the value of the textfield through jquery but when i run queryBuilder('getRules') it is empty. May i know if there are still some functions that need to trigger for the rules to be not empty?

_Originally posted by @PIlepRusel in https://github.com/mistic100/jQuery-QueryBuilder/issues/581#issuecomment-640490138_

I noticed the exact same issue... I think the queryBuilder isn't binding the events to these generated input elements

**Comment by mistic100** [comment]
try to trigger an "change" event on the textfield, this way the builder will be notified of the changed value

**Comment by mistic100** [comment]
Otherwise please provide a demo as explicitely requested in the issue template.

**Comment by pixobit** [comment]
what do you mean trigger a change event? I'm using the inputs as   
input: function(){  
 return '\<input id="asd" type="text" />';  
}  
(The above is just a dummy example, it's not the actual input, but serves the purpose)  
  
These already have html specific change event, it's just not getting picked up by the queryBuilder. So if I trigger a change event, that's the same as the native event, but that won't get picked up by the queryBuilder

**Comment by mistic100** [comment]
I cannot help you if you don't show a whole working code.

**Comment by pixobit** [comment]
The whole would be impossible, and hard to understand, but I'm going to try to create a simplified codepen example

**Comment by pixobit** [comment]
Sorry, I actually realized that I was overwriting the value field's outerHTML on operator change. Would it be possible to add the required events to the input field at this point?

For example creating the value input element on "afterUpdateRuleOperator.queryBuilder", replacing the element in the DOM (need to do this because the value field changes based on the operator), and attaching the required events manually.

**Comment by pixobit** [comment]
```
// Solved it by attaching the event listener like this... (Also made sure the input has the name attribute set to the auto generated one for ex. queryBuilder0_rule_7_value_0)
var qryBuilder = document.getElementById(id).closest('.query-builder').queryBuilder;
$('#' + id).on('change', function () {
	if (!rule._updating_input) {
		rule._updating_value = true;
		rule.value = qryBuilder.getRuleInputValue(rule);
		rule._updating_value = false;
	}
});
```

**Comment by mistic100** [comment]
I suppose you are trying to change the input based in the operator, which is not supported (there is an issue for that).  
Of course if you manually overwrite the inputs it will destroy the existing listeners and nothing will update.

Your solution is correct I guess.

If it works please close this issue, the input/operator feature will be tracked in #284
