### ISSUE TITLE
onAfterSetValue example correctness

### ISSUE THREAD

**Issue by dpnishant** [mistic100/jQuery-QueryBuilder#926]
Is this example event handler correct: https://github.com/mistic100/jQuery-QueryBuilder/blob/dev/examples/index.html#L417-L421 

With the debugger I'm not "breaking into" this function, even if I edited the HTML with a JSON that includes this rule filter with a value.

**Comment by mistic100** [comment]
That's some outdated code.  
The correct way is to use `valueSetter` filter property and/or `afterUpdateRuleValue` event

**Comment by dpnishant** [comment]
@mistic100  So if I understand correctly currently it is not supported to declaratively define event handlers on a per-filter basis. Is that correct?

**Comment by mistic100** [comment]
I *was* possible and will never be again. It's not a problem though `afterUpdateRuleValue` is called with a rule object and you can test the filter applied.

**Comment by dpnishant** [comment]
Got it. Thanks for the confirmation.
