### ISSUE TITLE
Can't display errors using "bt-tooltip-errors" plugin

### ISSUE THREAD

**Issue by abeer93** [mistic100/jQuery-QueryBuilder#942]
I'm using the source of [Widgets](https://querybuilder.js.org/demo.html#widgets).
to implement this UI to be able to take key-value representation for each filter.
![Screenshot from 2022-01-28 01-26-22](https://user-images.githubusercontent.com/16510751/151460648-23fd39a7-00b7-454a-bb2c-f8446f644e0a.png)
After implementing the UI I need to display the errors and I used "bt-tooltip-errors" plugin.
But it doesn't work and there is an error displayed in the console
![Screenshot from 2022-01-27 23-58-51](https://user-images.githubusercontent.com/16510751/151460770-cf539010-a1a1-407a-a5b8-1b346dcb59db.png)
I'm using Laravel and I already loaded bootstrap js and CSS in webpack.mix.
this is my query-builder js file
![Screenshot from 2022-01-28 01-35-45](https://user-images.githubusercontent.com/16510751/151461205-3849b5f3-9392-4c02-ae73-1ce080d323dd.png)
Any Help?

**Comment by mistic100** [comment]
Are you using bootstrap 4 ? It does not work with v5

Sent from MailDroid

-----Original Message-----
From: Abeer Elhout ***@***.***>
To: mistic100/jQuery-QueryBuilder ***@***.***>
Cc: Subscribed ***@***.***>
Sent: ven., 28 janv. 2022 0:38
Subject: [mistic100/jQuery-QueryBuilder] Can't display errors using "bt-tooltip-errors" plugin (Issue #942)

I'm using the source of [Widgets](https://querybuilder.js.org/demo.html#widgets).
to implement this UI to be able to take key-value representation for each filter.
![Screenshot from 2022-01-28 01-26-22](https://user-images.githubusercontent.com/16510751/151460648-23fd39a7-00b7-454a-bb2c-f8446f644e0a.png)
After implementing the UI I need to display the errors and I used "bt-tooltip-errors" plugin.
But it doesn't work and there is an error displayed in the console
![Screenshot from 2022-01-27 23-58-51](https://user-images.githubusercontent.com/16510751/151460770-cf539010-a1a1-407a-a5b8-1b346dcb59db.png)
I'm using Laravel and I already loaded bootstrap js and CSS in webpack.mix.
this is my query-builder js file
![Screenshot from 2022-01-28 01-35-45](https://user-images.githubusercontent.com/16510751/151461205-3849b5f3-9392-4c02-ae73-1ce080d323dd.png)
Any Help?


-- 
Reply to this email directly or view it on GitHub:
https://github.com/mistic100/jQuery-QueryBuilder/issues/942

**Comment by mistic100** [comment]
erratum, it only works with BT 3

**Comment by MaruanBO** [comment]
@abeer93 You can use No Bootstrap (https://querybuilder.js.org/dev/no-bootstrap.html).

**Comment by mistic100** [comment]
I don't see how this is a solution as OP wants to use a Bootstrap plugin....

**Comment by MaruanBO** [comment]
> I don't see how this is a solution as OP wants to use a Bootstrap plugin....

I just give a one solution cause she only say "i wanna display errors" for this u don't need any bootstrap.

**Comment by abeer93** [comment]
yes, I'm using `"bootstrap": "^5.0.2",`. @mistic100 
in there any other plugins to display errors?

**Comment by mistic100** [comment]
No, but as @MaruanBO you don't need a plugin to display errors, it will just use native browser tooltips.
