### ISSUE TITLE
getRules is better to return {empty: true} for empty rules

### ISSUE THREAD

**Issue by tlyau62** [mistic100/jQuery-QueryBuilder#944]
For the getRules api, the returned rules array may be better to have the empty rule like the following

```js
{
  "empty": true
}
```

instead of the null values object to prevent ambiguity.

```js
{
  "id": null,
  "filter": null,
  "value": null
  // ...
}
```

So, may we have an option like this which also support for backward compatibility?

```js
builder.getRules({
  "emptyRule": true
})
```

**Comment by mistic100** [comment]
if filter is null then then rule is empty, and the rule is only considered empty if the filter is null

you can also already ignore empty rules with `skip_empty` option

no need for change
