### ISSUE TITLE
Class attribute to radio inputs

### ISSUE THREAD

**Issue by umneeq** [mistic100/jQuery-QueryBuilder#95]
Can you add ability for adding class attributes to radio inputs? This feature would be very helpful. For exmaple, I have iCheck plugin that converts my radio and checkbox inputs to pretty look, but it adds a parent div to inputs and after that buttons "AND" and "OR" become inoperative. If I would have an ability to add class for this inputs I can turn off iCheck plugin (and maybe other plugins) to operate with them specifying the desired class.
Sorry for my English.
Thank you.

**Comment by mistic100** [comment]
`input[type=radio]:not(.query-builder .group-conditions input)`
no need for extra class
demo: https://jsfiddle.net/j455zq6y/1/

(seriously, stop apologies for english, not one cares on such international website ;-) )

**Comment by umneeq** [comment]
Not working for me.

**Comment by mistic100** [comment]
No example, no help, that's how I work

**Comment by mistic100** [comment]
don't expect any help if you don't show what you did

I added this at the end of the example page and it works
```
$('input:not(.query-builder input)').iCheck({
  checkboxClass: 'icheckbox_minimal',
  radioClass: 'iradio_minimal'
});
```

**Comment by mistic100** [comment]
feedback ?

if you really need to add classes you can overwrite the template method

```js
$().queryBuilder({
  template: {
    group: myGroup
  }
});
```

where myGroup is a modified version of https://github.com/mistic100/jQuery-QueryBuilder/blob/1.4.2/src/query-builder.js#L1388-L1426
