### ISSUE TITLE
Beware of which package you install, "jQuery-QueryBuilder" is NOT a malware

### ISSUE THREAD

**Issue by Prophecy35363** [mistic100/jQuery-QueryBuilder#952]
Received a github [advisory](https://github.com/advisories/GHSA-fw55-8gwc-gf65)  stating that this library is malware but I can't find any evidence as to why. Do people think there is any truth to this?

**Comment by Cashewz** [comment]
A malicious package with the same name (written in lowercase) exists, that causes this issue.

see https://github.com/github/advisory-database/issues/419#issuecomment-1160928395

**Comment by mistic100** [comment]
Thank you both for the report, I pinned the issue.
