### ISSUE TITLE
Adding one input box to the Group

### ISSUE THREAD

**Issue by crookedcircle** [mistic100/jQuery-QueryBuilder#958]
Hello Mistic,

I have added one field in the group and it is being displayed nicely. But i am unable to get the value of that field in the JSON. Can you please tell me how do i get this field in the JSON output.
builder_group_0_remarks
builder_group_1_remarks

While adding the groups the field name is also getting updated. But i am unable to get the value in JSON output
![FieldAdded](https://user-images.githubusercontent.com/9528201/204100771-bed28adf-7527-4695-ad86-08abc0516354.jpg)

Can you guide me how do get the field added to the group node. 

**Issues guidelines**

- Please search in the [documentation](http://querybuilder.js.org) before asking.
- Any issue without enough details won't get any answer and will be closed.
- Help requests must be exhaustive, precise and come with some code explaining the need (use Markdown code highlight).
- Bug reports must come with a simple test case, preferably on jsFiddle, Plunker, etc. (QueryBuilder is available on [jsDelivr](https://cdn.jsdelivr.net/npm/jQuery-QueryBuilder/dist/) and [unpkg](https://unpkg.com/jQuery-QueryBuilder/dist/) to be used on such platforms).

**Comment by crookedcircle** [comment]
Please ignore. this issue is resolved.

**Comment by dgw2jr** [comment]
> Please ignore. this issue is resolved.

So how did you resolve this issue?
