### ISSUE TITLE
The value I entered as 123417006008284650 is strangely mapping to the model as 123417006008284660

### ISSUE THREAD

**Issue by mustafaerdogmus** [mistic100/jQuery-QueryBuilder#959]
I am getting a strange error when using query builder. 
The value I entered as 123417006008284650 is strangely mapping to the model as 123417006008284660

I thought that the problem was caused by the backend, but when I printed the console as $('#jquery-query-builder').queryBuilder('getRules') I saw that the value changed without ever going to the backend.

In the picture below you can see that different number values are coming. The value I entered and the console output are different.
thank you for your help

![querybuidler question 2](https://user-images.githubusercontent.com/8672979/211535799-6c506f9f-10f9-4b23-a77f-6c39b01efb51.png)

**Comment by mistic100** [comment]
This is a JS issue, probably because the value is above `Number.MAX_SAFE_INTEGER`. You can test this outside QB by declaring a variable with this value, it will have the same issue.

Switch your filter to type string, that's the only solution.
