### ISSUE TITLE
SQL plugin support allows only one condition

### ISSUE THREAD

**Issue by Yoniffer10** [mistic100/jQuery-QueryBuilder#96]
Hi all, can you check SQL support functionality please?, I was testing and I saw that when you add new group you have the possibility to select condition again (AND / OR), however if you check line 120 on SQL plugin.

               return parts.join(' '+ data.condition + nl);

you have join method, but always replace with the first condition and does not respect the second group condition.

Same case if you have more the one group, does not matter what you choose always take first condition.

![screenshot](https://cloud.githubusercontent.com/assets/11580027/6762956/af6610ee-cf30-11e4-8160-ebe91285ffc1.png)

Thanks for your support and your excellent job.
Br.

**Comment by mistic100** [comment]
There is something you didn't understand : the group conditions applies for rules INSIDE this group, and your "OR" group has only one rule

**Comment by mistic100** [comment]
QueryBuilder will always surround group rules by parenthesis, so you will never get "AND" and "OR" in the same set of parenthesis

this is impossible : `a AND b OR c`
it's either `a AND (b OR c)` or `(a AND b) OR c`

**Comment by Yoniffer10** [comment]
You're right, Now I understand, Sorry I was confused. 
Thanks a lot.

**Comment by shahbikash** [comment]
Hi,
i am trying to achieve this query 
(SC = '6F' OR SC='7F') AND ( OpportunityName LIKE('%Global Incentives%') OR OpportunityName LIKE('%Global  Incentives%') )  
would this be possible, coz what i see is condition applied on rules is also the condition applied on the next group, is it not possible apply different conditions on rules and groups

I am consuming the library in Angular 4 application

![capture](https://user-images.githubusercontent.com/29737163/32312664-fac951ae-bfc4-11e7-9237-a3d6c5e6f5d1.PNG)

Thanks

**Comment by mistic100** [comment]
Make the main condition AND and create another group for the SC fields

**Comment by mistic100** [comment]
The condition is always applied INSIDE the group, not toward it's siblings

**Comment by shahbikash** [comment]
i am trying to achieve 
(SC = '6F' OR SC='7F') AND ( OpportunityName LIKE('%Global Incentives%') OR OpportunityName LIKE('%Global  Incentives%') )  

which means my main condition must be OR so that i achieve (SC = '6F' OR SC='7F') and in the second group my condition must be OR to achieve ( OpportunityName LIKE('%Global Incentives%') OR OpportunityName LIKE('%Global  Incentives%') )  now my question is how do i get AND in between these two groups,
and thanks a lot for that super quick reply:)

**Comment by mistic100** [comment]
No your main condition is AND. Or you don't understand how parenthesis work in SQL

**Comment by mistic100** [comment]
You need two subgroups for each parenthesis with a OR

**Comment by shahbikash** [comment]
![capture1](https://user-images.githubusercontent.com/29737163/32312971-8ab69b2c-bfc6-11e7-9d58-8637fd63d33c.PNG)

**Comment by shahbikash** [comment]
if i give AND in main condition then the query would become (SC = '6F' AND SC='7F') and not (SC = '6F' OR SC='7F')

**Comment by mistic100** [comment]
CREATE ANOTHER SUBGROUP FOR "SC" FIELDS

**Comment by shahbikash** [comment]
Thank you, i got it.
![capture2](https://user-images.githubusercontent.com/29737163/32313181-8980b408-bfc7-11e7-933d-d9a7cd10c17e.PNG)

**Comment by shahbikash** [comment]
thanks a lot buddy, have a good day
