### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by JellyFilledStudios** [mistic100/jQuery-QueryBuilder#961]
Is there any plan to support Bootstrap 5?

jQuery-QueryBuilder with plugins only works with old versions of Bootstrap.  With Bootstrap 5, the following errors occur trying to use different plugins:

Uncaught MissingLibraryError: Bootstrap Popover is required to use "filter-description" using Bootstrap 5
Uncaught MissingLibraryError: Bootstrap Tooltip is required to use "bt-tooltip-errors" using Bootstrap 5

bt-checkbox doesn't generate an error. But, it doesn't work with Bootstrap 5
sortable doesn't generate an error. But, it doesn't work with Bootstrap 5

**Comment by liamkeily** [comment]
Bootstrap 5 now supported https://github.com/mistic100/jQuery-QueryBuilder/releases/tag/3.0.0

**Comment by liamkeily** [comment]
I've created a new issue for looking at getting this new version docuemnted https://github.com/mistic100/jQuery-QueryBuilder/issues/995
