### ISSUE TITLE
Unable to find plugin "not-group"

### ISSUE THREAD

**Issue by priyamsharma2704** [mistic100/jQuery-QueryBuilder#964]
I am trying to add a plugin(not-group). But it is not able to find it. These are the scripts that I have in my html page. What else do I need to add?

    <script src='../../ThirdParty/JQuery-UI/scripts/jquery-ui.min.js'></script>
    <script src='../../ThirdParty/JQuery QueryBuilder_2.3.3/main.js'></script>
    <script src='../../ThirdParty/JQuery QueryBuilder_2.3.3/utils.js'></script>
    <script src='../../ThirdParty/JQuery QueryBuilder_2.3.3/model.js'></script>
    <script src='../../ThirdParty/JQuery QueryBuilder_2.3.3/plugins.js'></script>
    <script src='../../ThirdParty/JQuery QueryBuilder_2.3.3/defaults.js'></script>
    <script src='../../ThirdParty/JQuery QueryBuilder_2.3.3/plugin.js'></script>
    <script src='../../ThirdParty/JQuery QueryBuilder_2.3.3/query-builder.standalone.min.js'></script>
    <script src="Scripts/queryEditor.js"></script>

This is my code snippet:

        $('#builder').queryBuilder({
        plugins: ['not-group'],  
        filters: [
            {
                "id": "name",
                "label": "Name",
                "type": "string"
            }, 
            {
            "id": "''category''",
            "label": "Category",
            "type": "integer",
            "input": "select",
            "values": {
                "1": "Books",
                "2": "Movies",
                "3": "Music",
                "4": "Tools",
                "5": "Goodies",
                "6": "Clothes"
                },
            "operators": ["equal", "not_equal", "in", "not_in", "is_null", "is_not_null"]
            }, 
            {
            "id": "''in_stock''",
            "label": "In stock",
            "type": "integer",
            "input": "radio",
            "values": {
                "1": "Yes",
                "0": "No"
                },
            "operators": ["equal","in"]
            }, 
            {
            "id": "''price''",
            "label": "Price",
            "type": "double",
            "validation": {
                "min": 0,
                "step": 0.01
                }
            }, 
        ],
        rules: rules_widgets
    });

This is the error that i am getting:

    query-builder.standalone.min.js:8 Uncaught ConfigError: Unable to find plugin "not-group"
    at l.error (query-builder.standalone.min.js:8:7543)
    at g.<anonymous> (query-builder.standalone.min.js:7:6775)
    at Array.forEach (<anonymous>)
    at g.initPlugins (query-builder.standalone.min.js:7:6623)
    at g.init (query-builder.standalone.min.js:7:11902)
    at new g (query-builder.standalone.min.js:7:5569)
    at $.fn.queryBuilder (query-builder.standalone.min.js:8:8755)
    at queryEditor.js:30:21

**Comment by mistic100** [comment]
This plugin does not exist in version 2.3.3, use the latest version.
