### ISSUE TITLE
validation.min and validation.max not casting string numbers to int

### ISSUE THREAD

**Issue by smailliwnosaj** [mistic100/jQuery-QueryBuilder#97]
I am using the standalone version of query-builder.js from March 18, 2015.   I am serializing a C# model of Filter Definitions.  In order to get both regex validation and min/max validation to work, I use a Dictionary<string,string> instead of Dictionary<string,int>.  

new QueryBuilderFilter
{
    id = "RandomPercent",
    label = "Random Percentage of Calls",
    type = "integer",
    input = "text",
    optgroup = "Other",
    validation = new Dictionary<string, string>{{"min", "1"}, {"max", "100"}},
    operators = new string[1] {"equal"}
},
new QueryBuilderFilter
{
    id = "LowDuration",
    label = "Low Duration",
    type = "string",
    optgroup = "Date / Time",
    placeholder = "00:00:00",
    validation = new Dictionary<string, string>{{"format", "^[0-9]{2}:[0-5]{1}[0-9]{1}:[0-5]{1}[0-9]{1}$"}},
    operators = new string[1] {"equal"} 
}

The Regex validation works great in my UI.  However, the min and max value validation treats the numbers as strings instead of integers and seems to be validating on their alphabetical value rather than their numeric value.  To fix it, I had to make a change to Query Builder and wrap my textbox values in parseInt().

    // From line 1382 of the standalone query-builder.js
    if (validation.min !== undefined) {
        if (parseInt(value[i]) < parseInt(validation.min)) {
            result = ['number_exceed_min', validation.min];
            break;
        }
    }
    if (validation.max !== undefined) {
        if (parseInt(value[i]) > parseInt(validation.max)) {
            result = ['number_exceed_max', validation.max];
            break;
        }
    }

**Comment by mistic100** [comment]
Why don't you declare the bounds as int ?

and you will have a similar problem with `validation.format` as QueryBuilder assumes to have a RegExp object and here you have a String (the necessary cast should be done in `checkFilters` internal method)

just wondering, I will make this changes (or preferably you could do a Pull Request)

**Comment by zachawilson** [comment]
@smailliwnosaj is there any chance that you could be compelled to make the serializing of C# jQuery-QueryBuilder models available on github? I am about to start the same thing and it would be great to avoid duplicating each other's work. I will contribute if you do get yours up and I can expand on it.

**Comment by smailliwnosaj** [comment]
No prob.  Here is a repo with my basic models.  I quickly stripped out code related to my implementation of it.  So, what I am sharing is bare bones.

https://github.com/smailliwnosaj/Integrating-C-Sharp-with-jQuery-QueryBuilder
