### ISSUE TITLE
Minified styles missing in version 2.7.0

### ISSUE THREAD

**Issue by marekdedic** [mistic100/jQuery-QueryBuilder#976]
Hi,
with the upgrade to 2.7.0, the minified styles (`dist/css/query-builder.default.min.css`) are missing. See https://github.com/skaut/skautis-integration/pull/556

The release notes don't mention this, so I assume it's a bug?

**Comment by mistic100** [comment]
Sorry for not mentionning it. I removed the minified files on purpose as it is globally discouraged to publish minified code and let the end user integrates it he wants.
