### ISSUE TITLE
validation.format should accept a String

### ISSUE THREAD

**Issue by smailliwnosaj** [mistic100/jQuery-QueryBuilder#98]
Using the March 18, 2015 standalone version of query-builder.js with bootstrap 3.3.1 throws a javascript error when using validation.format and a regex expression.

To get around it, I had to comment out the block on line 1357 of the standalone query-builder.js file and replace it with the following:

    if (validation.format) {
        if (value[i] != value[i].match(validation.format)) {
            result = ['string_invalid_format', validation.format];
            break;
        } 
    }

**Comment by mistic100** [comment]
as said in #97 the format must be a RegExp, not a String

**Comment by smailliwnosaj** [comment]
Thanks, Damien.  I just gotta say, jQuery-QueryBuilder is awesome.  You've really set the bar high.  Now that these issues are resolved, the framework is doing exactly what I need out of the box without any hackery.  Thank you for the time you've devoted to this.
