### ISSUE TITLE
Build instructions needed

### ISSUE THREAD

**Issue by robstant** [mistic100/jQuery-QueryBuilder#986]
Hi,

I would like to modify this for my purposes. Namely to allow expressions built from math functions and field names. I have followed the following instructions as well as several variations. 
1. npm install jQuery-QueryBuilder
2. npm install
3. npm run build

after 3. I get the following error
(function (exports, require, module, __filename, __dirname) { import fs from 'fs';
Unexpected token import

I would be grateful if you could post a set of instructions which would produce a build. The default query-builder.standalone.min.js is working on my system.
Regards
Rob

**Comment by mistic100** [comment]
what is your nodejs version ? you need at least node 16

**Comment by robstant** [comment]
Thanks a lot for your help. The version of node was too low. I now seem to have built some working output.

Regards
Rob
