### ISSUE TITLE
Modify filters depending on group level

### ISSUE THREAD

**Issue by yakamuki** [mistic100/jQuery-QueryBuilder#987]
Sorry if this is answered before, but i couldn't find any solution yet.

I'm building a queryBuilder where the allowed group levels are 2. I've set the filters option when initializing the queryBuilder, but i want to remove some options from the dd when the group level is > 1.

eg. in the picture below i want the option Num of days to be removed from the dd when the group level is > 1. How can i achieve that?

thanks in advance

![image](https://github.com/mistic100/jQuery-QueryBuilder/assets/20537620/f852b743-5c36-4f93-b905-75aa2d82f670)

**Comment by mistic100** [comment]
Try something like this (I didn't test it, you will have to explore a bit)

```js
$('#builder').on('getRuleFilters.queryBuilder.filter', (e, filters, rule) => {
  if (rule.level > 0) {
    e.value = filters.filter(/* filter which filters are available  */);
  }
});
```

**Comment by yakamuki** [comment]
Ok thanks, that worked well with a workaround.

this code should do the job

           
```
 $('#builder'').on('getRuleFilters.queryBuilder.filter', (filters, rule) => {
                if (rule.level > 1) {
                    filters.value = filters.value.filter(function( obj ) {
                        return obj.id !== 'time';
                    });
                }
            });
```
