### ISSUE TITLE
Move Flags.css into Repo

### ISSUE THREAD

**Issue by liamkeily** [mistic100/jQuery-QueryBuilder#991]
I noticed that the demo relies on a flag.css file which appears to be hosted externally on Github

https://github.com/mistic100/jQuery-QueryBuilder/blob/2a1404c7cc154fc6ecc0d66b34ee42191845253b/examples/index.html#L17

It might be nice to bring this file and its related image into the repo

**Comment by mistic100** [comment]
It's in the gh-pages branch https://github.com/mistic100/jQuery-QueryBuilder/tree/gh-pages/assets/flags
